### ISSUE TITLE
The admin team should see all pipelines, volumes, containers, and workers across all teams

### ISSUE THREAD

**Issue by rfliam** [concourse/concourse#1012]
# Feature Request

## What challenge are you facing?

I administer a fairly large cluster for several teams (10+). These cluster sometimes has issues which cross teams. Troubleshooting this is _very_ difficult, as even listing containers is namespaced. Worse these teams are authed based on github team groups, which I try not to maintain membership in unless necessary. 

## A Modest Proposal

The main team should be able to see into _all_ namespaces. As an administrator the ability to troubleshoot and inspect multiple team pipelines is critical to workflows. Particularly when auth is broken out such that the admins are not necessarily a member of all sub teams.

**Comment by pms1969** [comment]
I'll second that.  It would be handy to see all pipelines (as if an expose-pipeline had been applied to all pipelines in all teams) when logged into "main" as well. (not sure it that was included in the request, just wanted to explicitly state it.)

**Comment by joshzarrabi** [comment]
We are looking into this, you can follow our progress here: https://www.pivotaltracker.com/story/show/143692391

**Comment by pivotal-topher-bullock** [comment]
In lieu of allowing the `main` team to see all pipelines (due to security risks) we're working on a proposal to give teams the ability to temporarily expose information to another team #1209 . Feel free to discuss your needs, use cases, and opinions around sharing pipeline access in a multi-tenant Concourse in that issue.

**Comment by x6j8x** [comment]
While I'm not sure about such broad rights for the admin team, as we're also running a big multi-tenant concourse cluster (>50 teams), we're facing similar issues. 

The most pressing thing for us at the moment would be the ability to simply see for how many containers on our workers a team is responsible for. We're hitting the "max container" limit from time to time (mostly due to misconfigurations in individual pipelines), but not knowing which teams is responsible for it, makes running such a large concourse cluster challenging to say the least.

**Comment by evanchaoli** [comment]
Any update on this issue?

**Comment by vito** [comment]
@evanchaoli Nope - we haven't planned out operator-specific roles yet.
