### ISSUE TITLE
Absolute paths are treated as relative

### ISSUE THREAD

**Issue by jadekler** [concourse/concourse#1022]
```
inputs:
  - name: whatever
    path: /foo/bar
```

ends up in `/tmp/build/80754af9/foo/bar`

Concourse version: `2.7.3`

**Comment by vito** [comment]
This is intentional, but yeah, a bit unintuitive and undocumented. The idea is that tasks are locked down to a workspace, because from an abstraction perspective we don't know if you're using a Garden backend that has an entire filesystem to itself (i.e. Linux), or one that is limited by the capabilities of its platform (Darwin, Windows). There's also a general line in the sand drawn that tries to prevent tasks from being too coupled to their rootfs.

**Comment by jama-pivotal** [comment]
Added some notes in our documentation around absolute paths in our Tasks docs http://concourse.ci/running-tasks.html#path
