### ISSUE TITLE
Concourse should retry when reaching Postgres server-side connection limit

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1032]
# Feature Request

## What challenge are you facing?

GCP's Postgres offering has a connection limit of 100, which is kind of low. With more than one ATC (say, 2), it can be pretty easy to hit, as both set a limit of `64`. This number is unconfigurable as it's meant to be more of a safeguard than anything else.

When hitting the server-side limit, we saw this error:

```
pq: remaining connection slots are reserved for non-replication superuser connections
```

This bubbled up to builds and caused them to error.

## A Modest Proposal

We should catch this error, treat it as a "failed to connect", and have some sort of retry logic. Note that there may be different forms of this error with different wording. At a quick glance I don't see anything in `github.com/lib/pq` that we can check for, so if it's a string match, that'll be fun.

ref. https://github.com/concourse/wings.concourse.ci/issues/5

**Comment by lnhrdt** [comment]
Hey @vito! I have a v6.3.0 Concourse cluster deployed to GCP (via [concourse-chart](https://github.com/concourse/concourse-chart)), backed with a Google Cloud SQL Postgres database (100 connections max), and 3 ATC instances. I'm getting frequent `pq: remaining connection slots are reserved for non-replication superuser connections` errors, most often from resource checks.

While this issue is 3 years old, I thought I'd inquire here because it seems like I'm encountering the same issue you described. Should the retry logic you implemented (referenced above) have prevented these errors? Is there any configuration or action you'd recommend to resolve my issue?

**Comment by vito** [comment]
@lnhrdt You're probably seeing that error because the retry logic eventually gave up. A 100 connection limit is a bit low for 3 ATCs. I'm not sure if GCP lets you configure the server-side limit higher, but if not you could try configuring lower pool sizes on the `web` nodes (see the [connection pooling docs](https://concourse-ci.org/concourse-web.html#web-connection-pooling)) or and/or scaling down the number of ATCs (if possible).

Hope this helps!

**Comment by lnhrdt** [comment]
@vito that does help! Thanks for explaining what's probably happening and laying out the options.

Heads up to anyone else encountering this issue, GCP does let you [configure a higher concurrent connection maximum](https://cloud.google.com/sql/docs/quotas#postgresql).
