### ISSUE TITLE
reference deployment manifest

### ISSUE THREAD

**Issue by evanfarrar** [concourse/concourse#1034]
# Feature Request

## What challenge are you facing?

I work on a team that writes BOSH Bootloader (BBL). It can prepare an IaaS for use by BOSH, creates load balancers and cloud configs to support the two most common BOSH deployments needed by Cloud Foundry core developers: Concourse and Cloud Foundry.

Now that BOSH supports factoring out IaaS and deployment specific details into vars and cloud-config, Cloud Foundry maintains an executable reference deployment manifest, cf-deployment. This has made it possible for BBL to put details about the networks, security groups and load balancers into a cloud-config on the BOSH director, allowing users to deploy cf-deployment with only a few ops files to make IaaS specific changes.

This is great, because it makes our documented commands for deploying Cloud Foundry static and copy-pastable.

For Concourse however, our documentation must explain in detail how to edit the YAML included in concourse documentation to incorporate the CIDR blocks allotted to your VPC into the manifest. On AWS, the ELB cannot terminate SSL so that is a further operation the user must make, to add a cert into the file. In cf-deployment, any certs used internally are generated by BOSH using the vars system and CIDR blocks are automatically corresponded to BBL generated BOSH azs by an agreed upon name zoning scheme.

## A Modest Proposal

I would like Concourse to maintain a reference manifest, concourse-deployment, that continuously test on multiple IaaSes, similar to bosh-deployment or cf-deployment. This would make it possible to create IaaS infrastructure and provide a place to make suggestions about IaaS specific ops-files (ops/gcp.yml runs in http and LB terminates, ops/aws.yml runs in https and supplies the certs etc). BBL could then provide all of the VM types, networks, and VM extensions needed on multiple IaaS to abstract new users away from some of these details when they just want to try out Concourse itself.

**Comment by vito** [comment]
I think there may be a need for this but I don't want it to be on us to fix it, because I don't want this to be what every BOSH release author has to do.

Part of the point of BOSH is that release authors can write a release and not have to test it on every single IaaS (BOSH is supposed to cover that layer of abstraction). It's not perfect today, but it'll never get better if every release author keeps shielding BOSH from the pain.

I also think that manifests should be simple enough to be portable across IaaSes. The introduction of `cloud-config` made this possible, or was supposed to.

Manifests should also be simple enough to maintain without needing a complicated series of templates. We put a lot of effort into making the various properties well-documented and with example values for each. We also make sure to have reasonable defaults for just about everything, so things can "just work" out of the box, and the operator can easily discover what they need/want to change as they go along.

The example in our docs is intentionally not placed in a repo of its own, as I don't want to get into maintaining a `.yml` file that a bunch of people unbeknownst to us are performing YAML surgery on for their production deployments. We haven't changed our example in about a year, and simply edit entire deployment manifests for each of our own Concourse deployments. It's much lower cognitive overhead than a chain of ops-files.

If there are difficulties here, we should surface them, but with the goal of feeding that back into BOSH. This is a burden that should not be placed on every release author.

**Comment by evanfarrar** [comment]
I can understand the desire to avoid maintaining snippets of YAML and testing them against IaaSes continuously. In that case could the manifest published in documentation utilize variables, director-uuid, vm_types, dynamic IP assignment and a vm_extension for the load balancer?

This would make things a little less error prone, and for users on BOSH Bootloader they could let bbl make the cloud-config for them, then let BOSH decide what their passwords and IP addresses will be.

Right now we verbally patch your manifest in our docs with these details pulled from BBL commands, and when you compare that to 100 yaml files being spiffed together I don't really know which is worse.  I'd pull request, but I usually give up before I finish reading about the third transpiler required to make the docs.

**Comment by vito** [comment]
> Right now we verbally patch your manifest in our docs with these details pulled from BBL commands, and when you compare that to 100 yaml files being spiffed together I don't really know which is worse.

To what end? Why not just start with a manifest that makes sense for `bbl`? As I said previously, we do not want people templatizing our manifest, which is why it's not available in a more convenient form. Our manifest has been stable ever since 2.0. If you've got CI for your concourse `bbl`ing it would catch any backwards incompatible changes, and they'd also be documented in our release notes. 

And for building the docs without chasing a dependency chain, see https://github.com/concourse/concourse/blob/master/docs/README.md#with-fly. I would not want to change the manifest in any way that makes it harder for human consumption though. Copy/paste and hand editing is a lot easier than templating.
