### ISSUE TITLE
Feature Request: SAML authentication support

### ISSUE THREAD

**Issue by pavelnikolov** [concourse/concourse#1036]
Hi there!

# Feature Request: SAML authentication for Concourse

All the application that my team uses support SAML authentication and we manage permissions through our active directory. This allows us to have a single password and based on AD roles, users have access to different apps. We want to create a `Concourse` role and people in this role to be able to access concourse without requiring another set of credentials.

I have used [crewjam/saml](https://github.com/crewjam/saml) to add support for SAML in other Go projects. 

I would be happy to help with this.

* Concourse version: v2.6.0

**Comment by joshzarrabi** [comment]
Hi, we probably won't find time as a team to get this done, but feel free to submit a pr if you feel up to it.
Starting with concourse 2.7.1 we added a fairly simple interface to follow in order to add any authentication flow you want. You're provider has to satisfy the `AuthConfig` interface seen here: https://github.com/concourse/atc/blob/master/auth/provider/provider.go#L40 

See the GenericOauth https://github.com/concourse/atc/tree/master/auth/genericoauth implementation for a fairly basic and easy to follow example. 

It would be awesome if you could do this :) Feel free to ask for more help here or in slack if you need anything.
