### ISSUE TITLE
Have a failed trigger, like passed trigger

### ISSUE THREAD

**Issue by groenborg** [concourse/concourse#1043]
Hi there!

# Feature Request
I would like to be able to trigger jobs on failed like `passed`, so you could write 
``` 
failed: [some-job] 
trigger: true
```
It could also be nice if you could have a trigger acting like an `or` gate, so whatever jobs passes, they can trigger the next job.
 
## What challenge are you facing?
We have an advanced hardware test setup, and we would like to be able to trigger an entire new set of task when one of our tests fail. The `failed` state should not determine the termination of the process, but rather which branch of execution it should start next. To be more specific, failed test sets, trigger storage of output and executes a different test-set which has other outputs.  

## The idea
The idea behind this is, that concourse is great at visualizing your success path, but we have extensive tasks to run on failed. So if we adjust the mindset of success or failed in pipelines from start or stopping execution, it can in stead also function as a way of arbitrarily execute a graph of tasks. 

Thanks for a great product and keep up the good work

**Comment by vito** [comment]
I think this is a reasonable request but I've got a few questions to try and peel back the layers a bit and get to something more basic:

1. In your use case, would you want the pipeline to stay red? That is, is the original failure an actual failure (i.e. test failure) that requires cleanup, or are you trying to just express "if-then-else" in your pipeline to handle various states?

2. We definitely shouldn't visualize this in the same way that we visualize normal pipelines, i.e. chaining on success only. It may even be that jobs aren't the way these should be expressed. Which makes me wonder what the simplest thing is that you'd need out of this - is it just better pipeline visibility into which part of the sequence failed?

**Comment by jama-pivotal** [comment]
See @vito response above. Closing

**Comment by r-chris** [comment]
Is this similar to what `on_failure` provides?

https://concourse.ci/on-failure-step.html

```
plan:
- get: foo
- task: unit
  file: foo/unit.yml
  on_failure:
    task: alert
    file: foo/alert.yml
```

**Comment by shannoncurnew** [comment]
How do I update (put) a resource and run a task as part of the `on_failure` hook?

**Comment by viccuad** [comment]
I share the need for a 
```
failed: [some-job] 
trigger: true
```

Our usecase: we deploy a k8s cluster and then several helm charts. Then, we run a list of testsuites that test the deployment, chained one after another because of dependencies (some testsuites are destructible, and you can't run several testsuites at once because of cluster resources).
The setup of the clusters and deployment of helm charts is expensive in time, so it would be nice to run all testsuites (and report state to github on them, collect artfifacts, timings, etc) even if 1 of them fails. This is useful for pre-release pipelines. On release pipelines, we would not proceed from testsuite to testsuite if there's a failed job in the middle.
