### ISSUE TITLE
limit user access to specific pipeline

### ISSUE THREAD

**Issue by cppforlife** [concourse/concourse#106]
We have a CI (https://main.bosh-ci.cf-app.com/) that has multiple pipelines and would like to limit specific users to specific pipelines. I hear long term plan is to integrate with UAA but for a short term solution it would be nice to set basic auth creds per pipeline when deploying atc.

**Comment by vito** [comment]
Rather than deploy-time, I'm thinking this should be done via `fly`. That would also make the Vagrant-built boxes more useful; right now they have no auth making the AWS box pretty useless. You'd also have to keep it in sync with your pipelines (and what if you configure the pipeline first, etc. etc.).

It also shouldn't go in the pipeline template, since those should be reusable and generic. So maybe something like:

```sh
fly set-pipeline-auth \
  -p foo \
  --basic-auth-username foo \
  --basic-auth-password bar \
  --github-auth-client-id abcdef \
  --github-auth-client-secret 324867jkherj \
  --github-auth-user vito
```

...Which you'd then just stow away in a script somewhere safe for keeping it up to date.

There are other details to think about, i.e. what's the default for new pipelines. Maybe the flags are required as part of `set-pipeline` if it's a new one? Hmm.

**Comment by vito** [comment]
Thinking about this a bit more, I suspect we'll need two tiers of auth:

1. Superuser auth: today's auth - global to the instance, authorizes everything.
2. Team auth: auth config defined by a superuser for a given team.

```sh
fly set-team \
  -n my-team \
  --basic-auth-username foo \
  --basic-auth-password bar
```

I've inverted it from before because I think teams should be able to create their own pipelines, and having the auth defined on the pipeline itself makes that awkward. (Configuring a new pipeline would have to carry over the auth in some way, but from which pipeline?) This makes it so that if you're authorized in team X and you configure a new pipeline, it's automatically added to that team's set of pipelines.

Teams would also be able to change their own credentials. This would make it easier to manage leaked credentials without relying on a superuser. It also makes the out-of-the-box experience a bit more intuitive; there'd be a default team and you can change its credentials.

The delta from today:

* `fly set-team` would be added for reconfiguring an existing team. Superusers can run this command (which will create the team if it doesn't exist), and members of the specified team can run it to update the credentials.
* The AWS vagrant box would come with a `default` team, whose authorized tokens would be superusers, so that you can configure its credentials.
* Each pipeline would be owned by one team. Newly created pipelines would be owned by the current team. 
* `publicly_viewable` would be moved to a per-pipeline basis.
* If a pipeline is not `publicly_viewable`, it will only show up in the sidebar if you're logged in.
* We'll need to make the login button more prominent (and exist at all), and probably to show you who you're logged in as (i.e. github user / basic auth username) to prevent confusion ("where'd my pipeline go?").
* Pipelines would become namespaced under their team, and grouped in the sidebar. The current team would show up up top.

**Comment by nicorikken** [comment]
+1

**Comment by wendorf** [comment]
My use case around this is that I have multiple teams with low resource needs. I'd like to be able to provision a Concourse with medium/high resource levels and give individual teams access to their pipelines. Assuming that those with access are acting responsibly, they should be able to share an ATC and many workers without resource contention, but should only be able to modify the pipelines for their team.

Ultimately, I'd like to be in the position where someone in my circle of trust can say "I wish I had Concourse, but deploying it is too hard", and I can say "I know your GitHub team is foo/bar. I've given you a foo-bar pipeline. Have fun."

**Comment by vito** [comment]
BAM

**Comment by xoebus** [comment]
DANG. WHAT'S UP WITH ALL THESE STORIES.

**Comment by drnic** [comment]
Awesome work! 






On Thu, Aug 25, 2016 at 3:08 PM +1000, "Christopher Brown" <notifications@github.com> wrote:












DANG. WHAT'S UP WITH ALL THESE STORIES.
