### ISSUE TITLE
hijacking should search harder for a shell

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1073]
It seems to be that in the absence of a command, hijacking works by starting /bin/bash in the victim container. Some containers don't have a /bin/bash - for example, the Git resource. In this case, such a hijacking attempt fails.

One can explicitly specify /bin/sh as a command to get a shell. It would be a minor boon if the hijacking process did this automatically if there was no /bin/bash.

---
Moved from concourse/fly#73
/cc @tomwhoiscontrary

**Comment by DRuggeri** [comment]
+1
Similarly, those using a minimal docker image such as alpine don't have /bin/bash

**Comment by emcniece** [comment]
At the very least, it would be nice to have some sort of visible error indicating that `fly hijack` can't find the executable. Right now, failing hijacks print a 200 response with the `--verbose` flag and exit cleanly when the attempt fails. We had to inspect ATC logs to discover `runc exec: exit status 1: exec failed... executable file not found in $PATH`.

**Comment by wagdav** [comment]
@emcniece  this is documented in #833

**Comment by DRuggeri** [comment]
Well, I still think it is relevant, Mr. bot...

**Comment by tomwhoiscontrary** [comment]
It's no longer important to me, because i've stopped using Concourse.  Maybe it's still important to some other people here, though.

**Comment by tomwhoiscontrary** [comment]
I feel like if a bug has been open for two years, and nothing's been done about it, the thing to do isn't to ~~exterminate~~ close it (oh, you cards!), it's to promote it to some sort of Hall of Fame.

**Comment by tomwhoiscontrary** [comment]
The most sensible way i can see to do this would be to change `atc.HijackProcessSpec` so that `Path` is an array, whose elements are alternatives, in preference order. If there is an explicit command given to hijack, make it a single-element array. Otherwise, make it `["/bin/bash", "/bin/sh"]`.

Then, in `Server::hijack`, put the [`request.Container.Run`](https://github.com/concourse/concourse/blob/1d71ab91a3be61214250efdfa4ceda31fe53efef/atc/api/containerserver/hijack.go#L217), call in a loop, trying each alternative in turn, and stopping as soon as one succeeds. Better than that would be to only try the next alternative if the error is specifically that the command isn't found. I don't know what that error type is, though, so i don't know if it's possible to tell that.

This is not exactly a beautiful change, but it is fairly contained. One field and two bits of code need changing.

A variation would be to put both path and args into an array. That would let you express things like "either run /usr/bin/lsb_release -a, or if that's not available, cat /etc/redhat-release". That feels like it could be useful, but i'm clutching at straws here.

Another approach would be to introduce some magic sentinel value which means "any shell", pass that as the path, and then have `Server::hijack` detect that and do some special handling and tries various shells in turn. That would involve baking shell paths into the server code, though, which you might not want to do.

**Comment by tremblaysimon** [comment]
I think it's always an issue. It should search for `sh` like it does for `bash`.

**Comment by rexfordnana** [comment]
Can we pass a flag to `fly hijack` ? say `fly hijack -D bin/sh` to specify which shell to use ?

**Comment by jamieklassen** [comment]
@rexfordnana `fly hijack` already takes the command to run via positional arguments!

```
$ fly hijack --help
Usage:
  fly [OPTIONS] hijack [hijack-OPTIONS] [command...]

...

[hijack command arguments]
  command:                          The command to run in the container (default: bash)
```
