### ISSUE TITLE
Feature Request: Ability to clean up failed builds via the UI

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1140]
As described in concourse/bin#24, There are cases where large artefacts can be left around when builds fail.  In my case, this caused subsequent builds to fail due to lack of disk apace.  A method of cleaning up old builds manually between runs would be great so that disk space can be freed up.

---
Moved from concourse/bin#26
/cc @sybrandy

**Comment by chendrix** [comment]
When the filesystem used by the worker gets filled-up, we appear to get into an unrecoverable state with concourse itself throwing out errors that will make no sense to the uninitiated. e.g.:

* from a resource: `hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"mkdir /mnt/concourse/depot/8a0229e1-c899-44c0-5575-b01fbe314e9c/processes/d76dfcfc-548e-47b2-585c-dc1a2e54dac0: no space left on device","Handle":""}`
* from a job: `connection: process error: the exitcode file is empty`
* from another job: `mkdir /mnt/concourse/depot/37d776c6-4933-4187-5e4d-e95dfbc5ba99: no space left on device`
* from another job: `command not found`

It seems like we should go further than allowing users to manually clean-up failed builds via the UI.  It seems like concourse should be able to determine when the filesystem used by the worker is full and start removing artifacts from old failed builds - probably starting with the oldest.

This gives a better user experience by concourse cleaning up after itself above & beyond the normal cleanup that occurs after a successful build.

---

from @billimek

**Comment by mattdodge** [comment]
I think I'm running into this now. Build failed because of no disk space. I expanded my cloud VM's disk, now `df` shows I have plenty of room, but the build is still failing. My guess is that the volume that was created originally for the resource didn't get enough space allocated and now it never will? Definitely just a guess.

Regardless:
1. I think this may still need to be open...
2. Even if I can't do it from the UI, how do I clean up old builds/volumes?

**Comment by Yacine-A** [comment]
Any updates on that?
