### ISSUE TITLE
Volume size stats no longer being collected

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1163]
This used to happen as part of heartbeating, but we no longer heartbeat as of v3.0.0. It was pretty expensive to do it all the time anyway; maybe we can just call it once when the volume is initialized?

**Comment by mariash** [comment]
Is this story blocked on btrfs exploration? https://github.com/concourse/concourse/issues/1045

**Comment by mariash** [comment]
Isn't the size going to change while volume is used?

**Comment by mariash** [comment]
needs concourse/concourse#1045

**Comment by clarafu** [comment]
I don't think this'll need #1045 actually.

There should be some time where the volume isn't being written to anymore. Maybe this can be done at the end of `get`, `put`, and `task`?

**Comment by mariash** [comment]
In the new theme of our refactoring of get/put/task steps into actions that can be an action, e.g. GetVolumeSizeAction that we run as part of those steps.

**Comment by jtarchie** [comment]
We tried to dive into this morning. We'd like some clarification on this story.

Since volumes no longer report their size, after the *great refactoring*, do we want them back?

1. No other user has reported an issue or added to this issue
1. It is not clear what volumes need to be queried for their sizes, for example, in this [comment](https://github.com/concourse/concourse/issues/1163#issuecomment-304074959) it mentions getting the volumes from a `get`/`put`/`task`, please clarify which volumes should be gathered.
1. We could just remove it from `fly volumes`. Does anyone need it?

**Comment by vito** [comment]
@jtarchie I think we can just remove it for now. As far as I can tell no one's complained that it's gone, only that `fly` has an always-empty "size" column.

**Comment by jtarchie** [comment]
Alright, we are going to remove everything associated with it:

* the column from fly
* the value from the API response
* the database column, maybe?

![all the things](https://i.imgflip.com/1tw9hg.jpg)
