### ISSUE TITLE
Generic version-filter on resources

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1176]
# Feature Request

## What challenge are you facing?

concourse/github-release-resource#45
concourse/bosh-io-release-resource#12
concourse/github-release-resource#38

As seen in at least the three stories above, there sometimes exists the need/desire to only want versions that match some kind of filter to continue along in your pipeline.

## A Modest Proposal

We should introduce a generic version filter on resources that's applicable to all resources. This filter could either determines whether a version:

- gets counted as a new version
- triggers a get

My preference is for the latter.

**Comment by chendrix** [comment]
Also concourse/datadog-event-resource#1

**Comment by bcampoli** [comment]
Any updates on this? My use case involves checking versions of a docker image on docker hub but ignoring the "latest" tag and just using the latest "pinned" version.

**Comment by vito** [comment]
Another one: https://github.com/concourse/github-release-resource/pull/68

**Comment by vito** [comment]
Closing this for now. At the moment it seems like version filters might just be a reasonable thing for resources to implement, since the mechanism by which it filters can be pretty different from resource type to resource type.

The generic aspect of this may also be accomplished by spaces, which allows jobs to selectively run against spaces matching some pattern.
