### ISSUE TITLE
Feature request: "on_abort" hook 

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#120]
When a task acquires an env and uses on_failure to release the env, it doesn't fire on abort.
This makes it difficult to manage env resources that are passed between a series of jobs.

Could we add an `on_abort` hook or allow `on_failure` to also fire on aborting a job?

The former seems like the right thing to do.
Another idea would be to have a pipeline level `ensure`. 

Regards,
Ergin & Sameer

**Comment by spikymonkey** [comment]
Hi Concourse,

This would definitely be useful for us too. We have on_failure cleanups which aren't being automatically run whenever a user manually aborts a task. If the user forgets to run the cleanups manually then this causes us issues the next time the job runs. Ideally the user wouldn't have to remember to trigger the cleanups manually since the act of aborting the job in concourse would run them automatically.

Cheers,
Gareth

**Comment by JamesClonk** [comment]
Yes, this would be immensely useful for some of our pipelines. (dealing with github PRs / gitlab merge-requests)

**Comment by timrchavez** [comment]
This is finally happening folks :)
