### ISSUE TITLE
Proposal: being able to temporarily expose information to another team

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1209]
# Feature Request

## What challenge are you facing?

When operating in a multi-tenant environment, there are times when one team with a private pipeline/job/etc. may want to request help from another team. A couple examples of this are:

1. I want to expose it to the admin team (`main`), to request support from the operators of the Concourse deployment, because my build completed in an interesting way (error, failure, false green).
2. I pulled in a dependency produced by another team, and it broke my pipeline, and I'd like them to help me investigate.

## A Modest Proposal

For the first case it's tempting to reach for a "god view" (#1012), however this would mean that if anyone admin team has their auth compromised, or simply forgets to log out, it'd result in mass credential leakage.

If we more tightly scope the exposing of information, i.e. on a case-by-case basis for the amount of time that it's actually needed, this risk is mitigated. We're thinking this may also be all that's needed for the second case.

So, our initial idea is to have a way for a user to temporarily expose something in the web UI (e.g. a build) to another team, for a certain amount of time (e.g. 24 hours). A "flare gun" icon seems appropriate. This will be read-only, though we're considering allowing use of `intercept` as well, as that's often the next step in debugging something.

**Comment by chendrix** [comment]
Oftentimes people are trying to expose information about a *failing build*, so they can get help with debugging their current issue. To the person supporting them, though, this often requires them to know information about the rest of the pipeline that feeds into that failing build. So there's a potential use case for exposing a build and exposing a pipeline. 

We did some initial research using mocks and found interesting information. However, we'd also like to start deploying beta features to our internal research-focused multi-tenant environment (**Wings**) and gathering real user feedback, which can drive our product decisions. Due to both of these  we are going to try the simplest approach and do:

- [] Expose a read-only view of a single build to the main team, indefinitely  

This matches our most likely Wings use case, so we are going to attempt to do this, gather user feedback, and use that to determine the next steps for this feature.

**Comment by rfliam** [comment]
I believe this lacks a major feature set (and really the thrust of my issue behind #1012):
## Feature's an Admin Need's

1. I, an admin,  need to be able to identify "bad actors" (generally not intentional) who are using excessive resources. For example one of my teams had a script go awry that attempted to create 1,000's of check containers over the course of a week. This brought down the environment for everyone. Identifying who was "leaking" these containers resulted in me simply joining every team so I could look and see what was going on. Metrics is often insufficient here (and would have been in this case). 

2. I, an admin, need to be able to troubleshoot issues that cross the concourse environment. For example if I see a container that appears to be stuck, hung, or consuming inordinate resources I need to be able to find _who_ created that container. I can do this by inspecting the database today (painful) or trying to dig through logs (painful), but it's often very difficult. I have had a container which was consuming 100% of a workers IO capacity on accident. Identifying that required again, joining every team, and using fly to list out the containers.

The idea behind #1012 was to enable admins to _operate the system_ while this feature enables admins _to help users_. Both are good, but the former is more important IMO as it affects all users rather than a subset.

## Regarding Security:
As an admin I (the main team) can modify the login methodology for all teams and list all teams. So it is trivial for an attacker who has compromised admin credentials to add himself to all teams and dump there credentials. In many (if not most) cases if an admins credentials are compromised so are the credentials to access the database. In addition troubleshooting a team particular issue often requires physical access to the node anyways. Which again makes the secrets inherently accessible. Strong security models will have multi-factor authentication for admin credentials. Blocking the power of someone who inherently already has complete access makes little sense.

The way to prevent the leakage of secrets is instead to encrypt them, with a key, outside the control or access of the admin. If a team has secrets they are concerned about an admin (or a adversary who has gained admin access) seeing a proper pattern might look something like this:

1. A resource is placed in the pipeline that requests a token from a store (like vault)
2. When that pipeline is triggered a request is made for that token
3. Before issuing the token authorization is requested from a user along with a second factor of authentication. For example vault might use a [Duo Push](https://www.vaultproject.io/docs/auth/mfa.html)
3. That token is issued to the pipeline and it proceeds to use it.
4. Down-streams verify the token with the the store to authorize access.

In this model the admin only has access to the secrets of a given team with _explicit permission_. In today's Concourse the admin has access to secrets stored in any team regardless, as they can simply add a manual login to the teams. _Most_ admins will also have physical access to the un-encrypted database.

**Comment by jama-pivotal** [comment]
Closing this in preference to doing #769  instead
