### ISSUE TITLE
Add Documentation for params in the resources under Resources section

### ISSUE THREAD

**Issue by TiraO** [concourse/concourse#121]
We looked at the git resource and wanted to add the depth parameter to our build. We weren't sure where to add that based on the git resource readme, so we looked at the documentation for Resources. (http://concourse.ci/resources.html)

It would have been good to have something there that mentioned that params for Resources get configured in the Jobs where they get pulled in. It wasn't clear that we should look under Build Plans for documentation on how to configure Resources.

**Comment by vito** [comment]
I've updated the Git resource's [README](https://github.com/concourse/git-resource#example) to include more useful examples. Generally the place to go is the resource's own README; we decentralize the docs since we don't want to give our own resources special treatment (besides being there by default). I've added a few links from the section you landed on as well.
