### ISSUE TITLE
Prevent "illegal" changes to resources

### ISSUE THREAD

**Issue by evanshort73** [concourse/concourse#126]
Related to concourse/s3-resource#7

The idea of "changing the regex for your s3-resource" seems reasonable, but in reality this is a *new* resource that needs to be managed separately.

However, a `fly configure` still lets you do this and then breaks your resource. For better end-user experience, this should be prevented during the `fly configure` stage.

cc @chendrix

**Comment by vito** [comment]
I don't think this can really be done practically. Generally resources should be durable to the state of their `source` configuration changing. The s3 resource should now behave correctly in this case (by starting over from what the current source can identify rather than the previous version).

The features that I think would replace this:

* having versions correlated with their `source` at the time they were detected. (which you don't always want actually, so we haven't done it.)
* being able to purge or mass-invalidate a resource's versions
