### ISSUE TITLE
Concourse release blobs should be versioned

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1264]
# Feature Request

## What challenge are you facing?

The team at Pivotal needs to scan the concourse repository for potential conflicts in the open source licenses for dependant libraries. A part of the process relies on `config/blobs.yml` and detecting changes to the libraries listed within it. According to our teams, we need to version the specific names of the blobs so that the tool knows when a change to the blob has been made. 

## A Modest Proposal

The tool we are using is currently not sophisticated enough to actually scan for the `sha` field in the `blobs.yml` to detect the change. Our proposal is to add the github `sha` to the blob's name in `blobs.yml`

**Comment by chendrix** [comment]
Change the tool you're using 😄

**Comment by vito** [comment]
What even is it going to look for in those blobs? They're all rootfses built in-house, containing either binaries or packaged code distributed verbatim. What happens if we *don't* do this? How exactly does the security scanner tie those to any license? Does it just look in the entire image for license files?

I ask because the only reason this would be beneficial to us is if we can put the ref of the git repo in the filename. Then we can now the commit that the blob traces back to, which we've wanted before. But that's not enough to truly determine whether the blob has changed; what you'd really need there is the digest of the image itself, as it could be the same commit of the resource but built from a newer base image. But at that point the license scanning tool might as well just use the sha from `config/blobs.yml`, which is a better source of truth.

What does it do with the version in the filename? Does it map that to the source in some way?

/cc @xtreme-gavin-enns

**Comment by xtreme-gavin-enns** [comment]
@Manifaust or @ryanmattcollins could chime in for more specifics, but if I understand correctly it's mostly a problem of knowing when to scan the source repos of dependencies so that legal can review any license changes. Like, they detect the change in the version of the blob and then scan the source. This works best when we can link the blob name to a git ref via a regex, usually by version number but a commit hash works just as well.

I hadn't thought about the problem of docker base images that resources are built on. That sounds like a hard problem.

**Comment by Manifaust** [comment]
A docker base image is challenging problem. But lets just deal with source code for now. If you append a ref to the blob name, and help point us to the repo, then our tooling can know whenever you update your blobs and scan the source code for dependencies (and other stuff).
