### ISSUE TITLE
Document v1 API

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1278]
# Feature Request

## What challenge are you facing?

I am facing having to read go-lang code which is a language  Iam not very familiar with to understand how to connect to golang in a pragmatic manor.

## A Modest Proposal

Document the methods under 

https://github.com/concourse/atc/blob/master/routes.go

and write a brief example using curl

**Comment by elgohr** [comment]
Just a tip, have a look at the API calls done by the browser. This doesn't replace a real documentation but helped me to reverse it. It's not that complicated.

**Comment by DRuggeri** [comment]
+1 - at the least, patch the docs to point people to this go code

**Comment by chendrix** [comment]
There is a reason we have not documented the API and that's because it's not meant for public consumption.

Thanks for bringing this up to us but it's unlikely we will do this ourselves, as it then ties us to what we publicly expose and document.

Any usage of the API by clients other than our own `fly` are fully in *Here Be Dragons* territory.

**Comment by DRuggeri** [comment]
So.... Concourse, being a modern CD platform in the year 2017, offers no supported way to programatically interact with it other than invoking a thick client and scraping the thick client's output?

... just want to make sure I understand the direction because that seems to be in conflict with what I see elsewhere in the industry.

**Comment by chendrix** [comment]
I'd like to remind everyone involved that the API still exists, and you can certainly attempt to use it for programmatic interaction. And if someone would like to make a PR documenting it, we'd more than likely accept it, but for such a small development team (8 engineers for the entirety of concourse), I will repeat that creating it and keeping it up to date is an engineering burden we do not feel comfortable with.

We are certainly interested in the ways people would like to programatically interact with Concourse, but we do not necessarily believe that documenting an API that was never meant for public consumption is the appropriate way to *deliver* on the underlying desire of *programmatic interaction with Concourse*. The *direction* of Concourse certainly involves figuring out a way to solve that desire, but hopefully in a way the 8 person team feels confident and comfortable with.

I'd also please ask for a bit more empathy @DRuggeri. Our team provides a large, complicated piece of open source software (for free), and we provide support for it (also for free), and snarky posts do nothing but demoralize.

**Comment by drahnr** [comment]
@chendrix where would you like this to be documented? I am up for it, I am digging into it anyways. Cheers

**Comment by chendrix** [comment]
@drahnr all of our docs also live in the `concourse/concourse` repo, here at [concourse/docs](https://github.com/concourse/concourse/tree/master/docs)

You can see how the [index page](https://github.com/concourse/concourse/blob/master/docs/index.any) is done, and I think the best place for it would be a separate section called API. It's not very well documented as a documentation language but the other pages provide lots of example documentation.

**Comment by DRuggeri** [comment]
I think you are misinterpreting my reply, @chendrix.

After having reread your first response a few times, the message I am able to take away is that you only endorse the use of fly and a browser to interact with concourse and that there is no current desire or plan to expand on that. I'm happy to hear (in your second reply) that this isn't the architectural direction concourse is going and that there _is_ desire to support something else. It would have been great to get that information in the first reply since it came across as a simple "shut down" of the conversation (which could be my own misinterpretation).

I'm even happy to assist you and @drahnr in documenting the API for the components I reverse engineer if that is where the concourse team chooses to go. I'll stand down on that, though, since your replies indicate that the API server does not represent an intentional contract and would rather volunteer my cycles on something that has a higher chance of sticking around.

P.S.
Please don't immediately assume malice and snarkiness on the part of your community when questions are raised about the product based on the sparse information shared. Aggressive replies only serve to ensure your small team stays that way by pushing away potential contributors.
I, for one, am one of a handful of active _volunteer_ developers on [the world's most widely deployed http server](https://projects.apache.org/committee.html?httpd) - and take exception to the statement that I lack kindness and empathy for a small project.
