### ISSUE TITLE
Build plans should not be indefinitely stored in the database with credentials

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#1303]
In #1050 we encrypted pipeline configs and team auth, but missed one spot: build plans, which are currently stored on the `builds` table with credentials in plaintext, and never removed. This is pretty awful for security and also takes up a ton of space over time.

**Comment by vito** [comment]
We still need the plan after the build completes so that the web UI can render the structure of the build. However we should no longer need the credentials.

Let's start by encrypting the data, as we'll still need it while the build is running. This can be kept in a separate table/column, and preserve the plan as needed for the web UI (the public plan) unencrypted. The encrypted plan information can be removed when the build is done.
