### ISSUE TITLE
Discussion; Fine-grained / Role-based Access Control

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#1317]
# What challenge is the Concourse community facing?

There is a clear, cross-cutting thematic need for fine grained access controls or role-based access control for the actions a user is able to perform within a team. This observation comes from many issues opened over the history of Concourse, each expressing the need for this level of access control granularity in different ways:

## Multi-tenancy
*As a multi-tenant (MT) admin,* I want to manage many teams and their auth : 
concourse/concourse#1167 
*As a MT admin,* I want to scope out a tenant team's pipeline :
concourse/concourse#1209
*As a MT user,* I want to scope out another team's pipeline :
concourse/concourse#970

## Operability
*As an operator of a MT Concourse,* I want to find and resolve problem container / volume on a worker
concourse/concourse#1012 

## Security
*As a user,* I want to limit who can see my secrets:
concourse/concourse#1059
*As a user,* I want to show a pipeline, but restrict who can trigger builds:
concourse/concourse#769
*As a @Amit-PivotalLabs* I suggested this years ago:
concourse/concourse#194

# A Modest Proposal

As a Community, we should discuss this need, and how it might be met by Concourse. A solution similar [Cloud Foundry's role-based access control](https://docs.cloudfoundry.org/concepts/roles.html) might meet our needs, as we could solve most of the above issues by providing a hierarchy to teams and roles within them. I'm curious how the community at large feels about this level of access control, and how it might address these issues. 

Discuss! 🛩

**Comment by OwenGr** [comment]
Please forgive my ignorance. I'm relatively new to Concourse (since March)...but it seems a lot easier (and preferable from a best-practice point of view) to spin up a single instance of Concourse per team. This eliminates the headaches of trying to maintain all the needs of multiple teams in one instance and is relatively easy to script and deploy for each individual team.

Benefits of a single instance per team:
- Entire server is deployable via an IAC tool (I used Terraform/AWS for this), including the team configuration. In my use-case, teams can spin up their own instance using an approved Terraform script.
- No cross-team rights issues.
- A bad pipeline from one team doesn't kill other teams' pipelines (this happens often).
- Teams can vary Concourse version based on when they're ready for the move. For example, the new interpolation syntax caused some migration issues.
- You know who your problem children are based on their resource usage.
- For most teams and deployments, it's easier/cheaper to scale up then out.
- No licensing fees to worry about, at least as far as Concourse goes.

Downsides:
- May need more boxes than a shared instance, though I generally find one agent per team is about the right scaling unit. Using AWS EC2 boxes is relatively cheap and easy to acquire, but premise-based hardware will be more of a pain. YMMV.

**Comment by brittag** [comment]
As a person who supports the security standards compliance of a system that uses Concourse in a regulated environment, role-based access control similar to Cloud Foundry would help our team because we are required to give information to auditors and to carefully apply the principle of least privilege to our work.

My use cases are similar to https://github.com/concourse/concourse/issues/769 - for example:
* During routine audits of our system, we could give the auditors read-only access to everything, so that they can review the system more quickly (instead of us needing to screen-share with them or send lots of screenshots).
* We have a team of people with full privileges and a team of people with fewer privileges that builds components that interact with the first team's work. The team with fewer privileges should have write access on their own components, and they should have read-only access to the first team's work (to better understand the status of relevant parts of the first team's work).

**Comment by pivotal-topher-bullock** [comment]
@OwenGr 
The issues you describe with operating a multi-tenant ( 1 > team ) Concourse deployment are all issues we are looking to solve in the platform. Concourse should be able to scale to multiple teams and allow operators of the deployment to horizontally scale workers based on resource demands. We're planning additional features around supporting these use cases to address the problems you're solving by having teams "own" their Concourse deployment. Currently the multi-tenancy support is pretty lose, and you've identified a lot of the key problems with the current state of things. ( some issues related to your needs #1284, #1012, #1209) . Some users also have operational, security, or organizational requirements that make it easier to manage and scale a large concourse instance with many teams, rather than deploy many Concourse instances.

@brittag Glad to hear where Concourse could help you in your role! Audibility and compliance are definitely a driving factor behind adding this level of RBAC as well. I agree; enabling compliance and security auditing for users in regulated environments would be serviced greatly by having an "auditor" role similar to CF.

Here are some existing issues which I identified as benefiting from this level of access control / defining roles and users. #194 #1294

**Comment by Rukenshia** [comment]
Hi @vito et al, wondering if this is actively being worked on or will be sometime soon. The current setup is not compliant with company policies so we might need to switch tools which we want to avoid

**Comment by jama22** [comment]
Closing, because we did it
