### ISSUE TITLE
Feature Request: Document how to prepare postgres for a standalone binary installation

### ISSUE THREAD

**Issue by zgagnon** [concourse/concourse#1323]
My team has faced some challenges in following the installation directions for the standalone binary install. One of those challenges is that none of us are very familiar with postgresdb. It would be helpful if the standalone binary install documentation included the steps to prepare a postgres database for concourse, as well as to clean up after it so we could try again.

Thanks!

**Comment by pgporada** [comment]
This would be useful for my org as well. I just started investigating concourse as a standalone install.

**Comment by chendrix** [comment]
Unfortunately, this falls into our anti-pattern of [Duplicate Effort](https://github.com/concourse/concourse/wiki/Anti-Patterns#duplicate-effort).

Because documenting external dependencies then becomes a monumental task in keeping that up to date, we try to minimize it as much as possible.

Thanks for letting us know this is has been an issue of yours, though.
