### ISSUE TITLE
Inconsistent behavior when not authenticated

### ISSUE THREAD

**Issue by chendrix** [concourse/concourse#1331]
# Feature Request

## What challenge are you facing?

would expect all commands that require authentication to show an error and a nonzero exit code when not authenticated. Some commands behave as expected, but some show an empty table and exit with 0.

> fly -t ci volumes
not authorized. run the following to log in:
    fly -t ci login
> fly -t ci workers
not authorized. run the following to log in:
    fly -t ci login
> fly -t ci pipelines
name  paused  public
> fly -t ci builds
id  pipeline/job  build  status  start  end  duration

--

moved from concourse/fly#177
cc @jmcarp

**Comment by chendrix** [comment]
Also concourse/concourse#1071

**Comment by jama-pivotal** [comment]
Update from 2018 with Concourse 4.2.1

It still makes sense that `volumes` and `workers` require you to login since there is no world where you can access that information unauthenticated

```
fly -t ci volumes
not authorized. run the following to log in:

fly -t ci workers
not authorized. run the following to log in:
```

However, commands like `pipelines` and `builds` could potentially show information about the system when you are unauthenticated because of [exposed pipelines](https://concourse-ci.org/managing-pipelines.html#fly-expose-pipeline) and [public jobs](https://concourse-ci.org/jobs.html#job-public). 

As an unauthenticated user, `pipelines` will give you empty output, but `pipelines` with the `-a` option will include exposed pipeliens as well:
```
fly -t wings pipelines
name  paused  public

fly -t wings pipelines -a
name                                 team                        paused  public
strabo                               cf-tools                    no      yes   
booklit                              vito                        no      yes   
atomy                                vito                        yes     yes   
```

Surprisingly, I would have expected `build` to do the same, but it doesnt, which is concerning

**Comment by xtreme-conor-nosal** [comment]
@jama22 Another scenario where this leads to misleading output is when the session token expires. If I login and run `fly pipelines` I see the list I expect. If I wait 24 hours and run `fly pipelines` again, I see an empty list instead of a prompt to re-authenticate.

If `fly pipelines` (and other commands) can't automatically redirect to the token renewal flow because of the exposed pipeline use case, can the output be explicit that only exposed data is being returned so I know I need to reauthenticate and that my pipelines didn't disappear?

Alternatively, could fly conditionally redirect/provide different output when an invalid token is present vs when no token is present? (If I was logged in before I probably want to reauthenticate)
