### ISSUE TITLE
oAuth behind proxy fails on callback 

### ISSUE THREAD

**Issue by richarddowner** [concourse/concourse#1337]
It seems that when you need to use a proxy with concourse, by supplying env variables http_proxy etc, the github oAuth callback fails.

I believe either concourse web OR the golang oauth package is not honoring the http_proxy, https_proxy and no_proxy environment variables. 

I managed to get the oAuth working in AWS by adding a transparent proxy between our corporate proxy and the concourse instance. This transparent proxy adds a default route 0.0.0.0/0 to the subnet route table so ALL traffic is routed to the transparent proxy and then on to corporate proxy. The oAuth now works. 

Here are some of my findings:

**Error within concourse atc:**
```
atc.oauth-callback.callback.failed-to-exchange-token, errror: post https://github.mycompany.com/login/oauth/access_token: dial tcp xx.xx.xx.xx:443: getsockopt: connection timed out
```

**The call within concourse throwing the error:**
https://github.com/concourse/atc/blob/176c130dc78f77eb0350b42c8b40312a3cbf3547/auth/oauth_callback_handler.go#L147

**The library that concourse calls for oauth exchange:**
https://github.com/golang/oauth2/blob/4464e7848382e6f39db55097f70e1460bdf944b3/oauth2.go#L178

I cannot confirm, but it seems like, either concourse atc or the golang oauth2 module is not honoring the proxy environment variables.

**Comment by bkeyser** [comment]
We are experiencing the same symptoms that @richarddowner has identified.  While he used a transparent proxy to identify this issue, we monitored the proxy logs as well as inspected the packets from the ATC host with tcpdump.  There were no proxy log entries and the tcpdump clearly showed that the ATC was attempting to make a direct connection to the GitHub instance rather than the proxy.

**Comment by xtremerui** [comment]
Already done.
