### ISSUE TITLE
Trouble getting fly to build

### ISSUE THREAD

**Issue by jkunzelman** [concourse/concourse#1373]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Bug Report
installed concourse with vagrant worked with out a hitch.

cloned concourse repo to begin to follow instructions to build fly.

used brew install go
tried to do go build
failed with dependancies

Bug reports are pretty free-form; just replace this with whatever. If applicable, though, please include steps to reproduce. Help us help you!

The following can also be handy:

* Concourse version:
Adding box 'concourse/lite' (v3.2.1) for provider: virtualbox
* Deployment type (BOSH/Docker/binary):
vagrant

* Infrastructure/IaaS:
mac osx sierra
* Browser (if applicable):
safari
* Did this used to work?
not for me, but i'm sure does for others.

**Comment by chendrix** [comment]
@jkunzelman I'd also ask if you are attempting to build fly from scratch because you're trying to work on fly or were you just trying to get a binary of fly so you can interact with your Concourse vagrant box?

If the latter, you should be aware that you can download the fly binary via the little windows/osx/linux icons in the bottom right corner of the Web UI of your running Concourse

**Comment by jkunzelman** [comment]
I had a problem with direnv so it was not seeing the local libraries. Thanks for your quick responses. I hadn't had a chance to come back an close this yet.
