### ISSUE TITLE
Docs: Build on pull request is now possible

### ISSUE THREAD

**Issue by j0hnsmith** [concourse/concourse#1384]
The docs https://concourse.ci/concourse-vs.html#travis-ci-and-other-hosted-offerings say `[Travis CI]  It also has great support for building your GitHub pull requests. This is something that Concourse cannot yet do but we have plans to allow the same workflow in the future.`

This is a big deal for many potential users (including me, been waiting for this before I try concourse), since https://github.com/concourse/atc/pull/163 it _is_ possible to do this (assumed).

**Comment by SHyx0rmZ** [comment]
It is not yet possible to have Concourse build multiple branches without setting up quite a bit of plumbing. To do this today, you have to detect changes in the available branches and then dynamically set new pipelines (or modify existing ones). I'm guessing the excerpt from the documentation has something easier in mind (as have many people discussing this). Web hooks are not really part of the problem because the current polling behavior already enables you to build on new commits. I would therefore advocate not updating the documentation at the current point in time.

**Comment by j0hnsmith** [comment]
Fair enough.
