### ISSUE TITLE
Bring back Search bar in docs

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1387]
Hi there!

# Feature Request

## What challenge are you facing?
Bring back the search function in the docs page http://concourse.ci/introduction.html ! Its missing and @ebabani uses it a lot, it also makes him sad that its gone

## A Modest Proposal
Bring it back to what it once was

**Comment by andrewedstrom** [comment]
@chendrix and I spent a day trying to port the old search bar code over to booklit and were able to get the search bar to render but could not actually make it search for anything.

In order to perform the search, we need to populate a [`SEARCH_TAGS`](https://github.com/vito/anatomy/blob/0ac8cb647791b8aabb91801567013139cc67ca42/lib/anatomy/renderers/js/search.js#L13) variable that is iterated over in the javascript. This appears to be a data structure containing fields `content`, `name`, and `url` that was populated by some atomy code, but we were not able to make sense of that code or figure out the correct way to port it over to booklit.

We're setting this down and going to make @vito do it, since he's the one who wrote all these things.

**Comment by jama-pivotal** [comment]
ITS BACK!
