### ISSUE TITLE
Resource checking fails with hijack backend error

### ISSUE THREAD

**Issue by ercollin** [concourse/concourse#1395]
This report is filed per request from @andrewedstrom.

Running concourse 3.1.0 on Linux and Windows workers.

Today all of my pipelines got into a state where the resource checkers are saying:
hijack: Backend error: Exit status: 500, message: {"Type":"","Message":"unable to find user root: no matching entries in passwd file","Handle":""}

I tried restarting the Linux worker and the web. I tried rebooting the VM both run on. I tried destroying and re-creating some pipelines. 

Not sure what logs would be helpful here but I can provide them if needed. 

Attaching the 2 screenshots requested by @andrewedstrom 
![screenshot from 2017-07-18 13-50-40](https://user-images.githubusercontent.com/3660837/28342267-4094452e-6bcc-11e7-999e-a29eb6b71cb6.png)
![screenshot from 2017-07-18 13-50-55](https://user-images.githubusercontent.com/3660837/28342272-4355b0cc-6bcc-11e7-9235-777ea5ed9145.png)

**Comment by chendrix** [comment]
Can we see what your configuration of those resources is?

Are they custom resource types?

**Comment by ercollin** [comment]
[java-core-libs.txt](https://github.com/concourse/concourse/files/1157454/java-core-libs.txt)

**Comment by andrewedstrom** [comment]
+1

@mhuangpivotal and I observed a slightly different error on a resource in the web ui that also started with `hijack: Backend error: Exit status: 500`. In our case weirdly this error message disappeared before we were able to copy it and was replaced by an error indicating the container could not be found. After we refreshed the page the error message disappeared entirely. Strange voodoo is afoot.

This happened on an s3 resource (`final-release` in our own ci publish pipeline), and @ercollin's issue happened on git resources, so this is probably an atc issue rather than an issue with any particular resource.

I'm a confused/disturbed about why we are seeing errors in the web ui that begin with `hijack:`.

**Comment by chendrix** [comment]
Note that @ercollin is also seeing

```
{"timestamp":"1500404761.373156548","source":"atc","message":"atc.syncer.dispatch-sla:radar.scan-resource.interval-runner.tick.find-worker.worker-for-container.garden-connection.retryable-http-client.retrying","log_level":1,"data":{"error":"dial tcp 127.0.0.1:45449: getsockopt: connection refused","failed-attempts":1,"pipeline-scoped-name":"dispatch-sla:resource:dispatch-installer","ran-for":"540.224µs","session":"16.59.26.1.3.1.1.1.1"}}
```

and

```
{"timestamp":"1500404741.701813221","source":"guardian","message":"guardian.create.containerizer-create.runtime-create-failed","log_level":2,"data":{"error":"runc create: exit status 1: container_linux.go:264: starting container process caused \"process_linux.go:339: container init caused \\\"rootfs_linux.go:57: mounting \\\\\\\"/tmp/concourse/worker/3.3.1/assets/bin/init\\\\\\\" to rootfs \\\\\\\"/tmp/concourse/worker/volumes/live/97013041-9eb3-4c1a-42de-aa8b2c384356/volume\\\\\\\" at \\\\\\\"/tmp/garden-init\\\\\\\" caused \\\\\\\"stat /tmp/concourse/worker/3.3.1/assets/bin/init: no such file or directory\\\\\\\"\\\"\"\n","handle":"24e0571a-a976-4927-5cef-d90fed8f97c5","session":"419629.2"}}
```

and is running on Centos 7 `Linux client-build 4.12.0-1.el7.elrepo.x86_64`

**Comment by ercollin** [comment]
Attaching logs in case they come in handy. I blew away everything and started from scratch and things are working again.
[messages.zip](https://github.com/concourse/concourse/files/1157627/messages.zip)

**Comment by topherbullock** [comment]
Looks like a #1413 related issue. 

Containers getting reaped while creating causes all kinds of weird stuff to go down.
1. Garden container's rootFS gets pulled out from underneath it
1. Garden is still like "um excuse me I'm trying to make a container here" and various problems occur: 
   - Wot, the user I'm trying to do things as no longer exists? 
   - Whoa where'd that file go that I just created in order to initialize some part of the container?
   - Why am I suddenly not able to use the network?
