### ISSUE TITLE
Web Server Dashboard

### ISSUE THREAD

**Issue by iswix-llc** [concourse/concourse#1399]
# Feature Request

## What challenge are you facing?

When I log into the web ui I have to click on all of my pipelines to know what their status is.

## A Modest Proposal

I wish there was an option to sort the pipeline names alphabetically.  I wish the alignment was left to right instead of right to left as  it makes it easy to differentiate similar pipeline names (something-dev, something-master)  and I wish their was a some visual indication of whether a job is in progress and/or what the previous execution result was.  Bonus points for a heatmap.

**Comment by iswix-llc** [comment]
It would also be nice to not have to click the button every single time I visit the site to see my list of pipelines.

**Comment by jtarchie** [comment]
There's a lot of requests in here:
* modify alignment of text
* sort pipelines by alpha-numeric order
* visual indication of pipeline
* previous execution result
* heatmap (which has not explanation of what should be heated)
* not click a button to see a list of pipelines

Can we narrow this down to what solves the original problem statement? Otherwise it is hard to determine what the deliverable and issue are trying to solve.

**Comment by iswix-llc** [comment]
They are all related to solving the problem.  The instructions said to not stifle my creativity.  No worry, I'll close this issue.

**Comment by chendrix** [comment]
It also looks like this is related to (or maybe even solved by?) a bunch of other issues already captured in web-ui

https://github.com/concourse/concourse/issues/531
https://github.com/concourse/concourse/issues/1259
