### ISSUE TITLE
Feature request: Allow token to be passed as parameter at login

### ISSUE THREAD

**Issue by pranaysharmadelhi** [concourse/concourse#1402]
It would be useful if we could pass token for UAA auth similar to how we pass --username for basic auth. 
This would help scripts used by operations to do housekeeping or scheduled tasks.

**Comment by Chumper** [comment]
I have actually implemented the token part for the atc side here: https://github.com/concourse/atc/pull/169
I will open a PR shortly that adds the token feature to fly.

**Comment by pranaysharmadelhi** [comment]
Great. So, what is the parameter you pass to the login command to provide token?

**Comment by Chumper** [comment]
There is no parameter yet as this is a two step process. 
fly talks to the atc to authorize a user and what I implemented ist that the atc *can* accept a token instead of using the oauth flow.
However, the functionality still needs to be implemented in fly. That is the second part that I am currently working on.

**Comment by xtremerui** [comment]
The UAA auth is fundamentally changed to use the [cloudfoundry connector by dex](https://github.com/concourse/dex/blob/master/connector/cloudfoundry/cloudfoundry.go)
