### ISSUE TITLE
fly sync does not recognize the -c flag

### ISSUE THREAD

**Issue by sjolicoeur** [concourse/concourse#1452]
# Bug Report

Fly sync rejects the `-c` flag, preventing users from syncing to targets that they have not yet logged into before.

```
$ fly -t apps-manager login -c https://wings.concourse.ci  
logging in to team 'main'

WARNING:

fly version (3.3.5) is out of sync with the target (3.3.2). to sync up, run the following:

    fly -t apps-manager sync

navigate to the following URL in your browser:

    https://wings.concourse.ci/auth/github?team_name=main&fly_local_port=65462

or enter one of the following token types:
    - Personal access token (e.g. '1234567890')
    - Bearer token (e.g. 'Bearer 1234567890')

Token: ^C

$ fly  sync                                                             
no target specified. specify the target with -t or log in like so:

    fly -t (alias) login -c (concourse url)

$ fly  sync -c https://wings.concourse.ci -t apps-manager        
error: unknown flag `c'
```
Also this is a new install on a new computer. ( there is no `~/.flyrc` file )

It's worth noting that if we add a `~/.flyrc` without a token, like this:

```
targets:
  apps-manager:
    api: https://wings.concourse.ci
    team: main
#end of file
```

then the `-c` still doesn't work but the `fly sync` will.

```
$ fly sync -c https://wings.concourse.ci -t apps-manager
error: unknown flag `c'
$ fly sync -t apps-manager                                                 
downloading fly from https://wings.concourse.ci...
 14.89 MB / 14.89 MB [================================================================================================================================================] 100.00% 35s
successfully updated from 3.3.5 to 3.3.2
```

* Concourse version: 3.3.5
* Did this used to work? Unknown

**Comment by sjolicoeur** [comment]
I was pairing with @andrewedstrom on this

**Comment by SHyx0rmZ** [comment]
Doesn't the login work even if it the wrong version?

**Comment by topherbullock** [comment]
`3.3.5` isn't a released version. You don't need to be logged in to download the fly binaries, or to sync. Fly will complain about version numbers that are off by a few points, and suggest sync-ing, but you'll always be able to download right fly binary from the web ui. The `sync` command doesn't take a `-c` flag, and you're already targeting that instance, so you just need to `sync` with a target.

This isn't a bug, but points to a documentation gap on this flow.

**Comment by sjolicoeur** [comment]
@topherbullock 
That was the issue, we couldn't target that machine. And we could not login.

The only time we were able to do so with the 3.3.5 was when we created the .flyrc file. Once we had filled in the info like the above we were able to use fly login and got the version that was in line with wings with fly sync.

To reproduce i would recommend deleting your ~/.flyrc file and connecting to wings and testing 3.3.5

**Comment by drennalls** [comment]
@topherbullock this might not be a bug but it's a pretty confusing/odd workflow if you're already using `fly` with some existing targets and then need switch to a new concourse server (like I just had to do). OR if you have a pipeline job that talks to concourse using `fly`. When you run into this..
* You can't `fly sync` without there  being a target for the server i.e. it's in `.flyrc`
* You can't `fly login` to create the target using `fly login  --target new-concourse -c https://new.concourse.server/` because it fails and tells you to `sync`.. 
..catch-22

So as a user you then either have to (A) hand-edit `.flyrc` or create one or (B) Go launch a browser just to find out the download URL `https://new.concourse.server/api/v1/cli?arch=X&platform=Y` or use `wget` etc..

`fly sync` would just "work" if I could use `-c` as @sjolicoeur suggested. We've had to workaround this issue in a pipeline by using `wget` and the expected download URL (which could change at some point) so fly is the right version to start with. The job uses `fly` to login and do a `set-pipeline` etc.. but since the job container is "fresh" each time, there's no `~/.flyrc` etc. So yes they're workarounds but it would alot simpler + intuitive to allow for `fly sync -c` or maybe have `fly login` allow for auto-syncing when a mismatch is detected instead of advising the user to do it when they can't

**Comment by Firebladee** [comment]
Is this being looked into as I got into this catch-22 today?

**Comment by topherbullock** [comment]
Looking at this again after seeing #2944; I 100% disagree with past @topherbullock

Sorry for closing this so quickly; it is a weird part of the flow that should definitely be addressed.
