### ISSUE TITLE
When starting container ,  garden can't connect docker registry

### ISSUE THREAD

**Issue by aminotsukasa** [concourse/concourse#1454]
# Bug Report

When executing task . garden can't connect docker registry
$ fly -t lite execute -c hello.yml
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
run:
  path: echo
  args: ["Hello", "World"] 

initializing
resource script '/opt/resource/check []' failed: exit status 1
* ping https: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
* ping http: Get http://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
occured.

Web and worker are working on same host.
this is a worker daemon command line 
/usr/local/concourse/concourse worker --work-dir /usr/local/concourse/work --tsa-host localhost --tsa-public-key /usr/local/concourse/host_key.pub  --tsa-worker-private-key /usr/local/concourse/worker_key 

The following can also be handy:

* Concourse version: 3.3.4
* Deployment type (binary):
* Infrastructure/IaaS: aws t2.medium Ubuntu 16.04
* Browser (if applicable): Chrome
* Did this used to work? yes

After I restart this host and prune worker.but It's not worked.
internet is connected .wget and docker pull is working on this host .
what a reason?

**Comment by panpan0000** [comment]
try to ```iptables -I FORWARD -j ACCEPT``` in your worker machine.
I was suffered from this for 1 day with deploy worker from bintray ...

**Comment by aminotsukasa** [comment]
thank you panpan0000
It worked!

**Comment by jtarchie** [comment]
Thanks @panpan0000. @aminotsukasa, I'm closing this as your issue seems resolved.

**Comment by atbentley** [comment]
@panpan000 @jtarchie Why exactly is `iptables -I FORWARD -j ACCEPT` required?

Would I be correct in assuming that the concourse containers are using a different network interface (a virtual one?), so we have to tell the host to forward the traffic from our workers to the internet?

And this is not required when running concourse in docker because docker has taken care of all the networking bits and pieces for us?

Would it make sense to add this to the Setup and Operations section of the docs, possible around the inbound and outbound traffic: https://concourse-ci.org/topology.html
