### ISSUE TITLE
Add `on_error` attribute to allow outside sources to be notified of CI failure 

### ISSUE THREAD

**Issue by AdamDorwart** [concourse/concourse#1460]
# Feature Request

## What challenge are you facing?
When jobs fail that use a github PR resource, they get stuck with the last build badge that they were set with. To the user on Github, they see their job 'pending' forever. It would be nice to try to put a error badge on the build. `ensure` doesn't quite work because what badge should be put is different based on the outcome of the build.

Also another easy way to see the disconnect:
Concourse Job Events : Github Build Status
task -> pending
on_success -> success
on_failure -> failure
? -> error

## A Modest Proposal
Add an `on_error` attribute so jobs that have an error can be properly communicated to external services.

**Comment by jtarchie** [comment]
This might be difficult in some cases. Sometimes the error state is because containers cannot be reached/created. If that error occurs, we have to watch out for the infinite loop.

**Comment by vito** [comment]
This is hopefully something you'd only want for notifications. I don't think we should add an `on_error` - this probably points to more exploration needing to be done around the many UX problems resulting from using resources for notifications.

**Comment by shinmyung0** [comment]
I also noticed this, when I am using something like the `pool` resource to manage cloud foundry spaces, sometimes my jobs will `error` due to mysterious `failed to create volume` messages. This results in the job not triggering the `on_failure` step that I have put to release the space's lock. 

Could we just have errors maybe triggering these `on_failure` events? Not sure what the proper way to do this currently is.

**Comment by akamalov** [comment]
@vito is it possible to get an ETA on ```on_error``` attribute making it to Concourse release? Currently, one of our pipelines errors (not fails) on S3 upload. Since it does not fit to category ```on_failure```, there is no way we can notify the team that object upload has never taken place. We could definitely use this attribute in our production.

**Comment by vito** [comment]
@akamalov There is no ETA - see https://github.com/concourse/concourse/issues/1460#issuecomment-333652366. The current plan is to improve support for notifications so that you don't need to attach all these hooks everywhere in the first place. We did some planning in concourse/rfcs#1 but later cut scope, so we'll probably tackle support for notifications as a new interface (and RFC) later on.

**Comment by marco-m** [comment]
@vito, to be sure you considered this, I would like to restate what @shinmyung0 mentioned, this goes beyond notification and is more serious: if I use the Concourse pool resource to take a lock in a previous job and a subsequent job errors out, there is no way to release the lock.

**Comment by vito** [comment]
resolved by https://github.com/concourse/concourse/pull/3652 :+1: this will be in 5.1

**Comment by marco-m** [comment]
This is nice, thanks!
