### ISSUE TITLE
Take a worker out of service

### ISSUE THREAD

**Issue by william-tran** [concourse/concourse#1461]
Sometimes I want to take a worker out of service gracefully so I can do some maintenance to its VM, e.g. you're using T2 burst EC2 instances and you're running low on CPU credits, so you want to bring up another instance (or in k8s, schedule the worker onto another node). It would be nice to be able to 
```
fly drain-worker -w worker-1 
```
which would allow running containers to complete but no new jobs would run on it. 

It would also be nice to forcefully "prune" a worker to force concourse to view a particular worker as a new worker when it calls back again, rather than some existing one where the process is actually new, and the volumes are all mixed up. E.g. 

```
fly prune-worker -w worker-1 -f
```

This would simplify this procedure: https://github.com/kubernetes/charts/tree/master/stable/concourse#restarting-workers

**Comment by topherbullock** [comment]
The `concourse` binaries have the commands you're looking for to manage worker lifecycle;
```
  land-worker    Safely drain a worker's assignments for temporary downtime.
  retire-worker  Safely remove a worker from the cluster permanently.
```
`concourse land-worker` tells the ATC to stop scheduling new work on that worker and eventually put the worker into the `landed` state. This allows operators to account for scenarios where they know a worker will be removed from the pool. Similar to your proposal.

BOSH deployments do this automatically via drain scripts, but other deployment setups are left up to operators to handle, there's a story to capture this work #1457

Would love to hear your thoughts there.

**Comment by william-tran** [comment]
Thanks @topherbullock I was about to say I should have read the manual because I thought I had seen docs for that... but I think that was my memory not serving me right and I only saw that output when I was poking around the concourse container. Next time I need to recycle workers I'll try those commands and update the helm chart docs if I can simplify that process.

**Comment by ashishgoel-ps** [comment]
@topherbullock I am using concourse containers and have been trying to find a way to gracefully shutdown the concourse worker containers. One of the way was to stop the concourse worker and prune it when it stalls but is a lengthy process and not the best one I believe. 

**two questions:**
**1.** does **concourse land-worker** will also stop the concourse worker container? or the worker will be running but will not be assigned any job?
**2.** how can **concourse land-worker** be used with _concourse containers_? the setup is like concourse web & concourse worker containers are on same vm and concourse worker containers are named like concourse_worker_1, concourse_worker_2 & so on.
I am asking this because I tried to land-worker from inside the concourse web container but it did not work.
