### ISSUE TITLE
Rewrite UI with a more common js framework

### ISSUE THREAD

**Issue by airtonix** [concourse/concourse#1488]
## A Modest Proposal

Rewrite ATC/ui in VueJs/ReactJs

Having the feeling that concourse is CI/CD done right, I can't be the only one who has that wtf moment when we realised the UI was written in something called `Elm`

- I've never heard of it?
- where is the documentation?
- most people now use es6 with ReactJS or VueJs or Jquery

I guess in the end the real question is "Do you intend for concourse/atc to be open for public contributions"?

**Comment by SHyx0rmZ** [comment]
I very deeply believe Elm is the right choice, but I haven't been able to put it into the right words in the last 15 minutes, so let me just link you to the website at http://elm-lang.org/. The documentation can be found at http://elm-lang.org/docs. Packages and their documentations can be found at http://package.elm-lang.org/.

In my humble opinion Elm does many things right and is quite easy to pick up in two to three days. My believe is that every front-end developer (which I am not, so I don't know too much about React or Vue.js) should try Elm for a few days, because even if they don't like the language the concepts are really important and translate well to other languages.

Personally, I would not write front-ends in anything else than Elm anymore, because it just feels as if it is making iterating faster and avoiding bugs easier.

**Comment by vito** [comment]
Nope!

We used ReactJS and vanilla JS before and the constant mental overhead of working in such a hostile environment (JavaScript and its mutability, scoping quirks, terrible stdlib, ...) is much higher than the initial hump it takes to learn Elm.

We always felt paralyzed and slowed down when implementing UI features until we switched to Elm. The mental model is intuitive and well-documented, and while it's still new and prone to change, we're still able to implement features much more quickly even when we have to play catch-up with Elm itself.

We've brought people on to our team with 0 Elm experience going in, and even the skeptics were able to get up to speed surprisingly quickly, and the whole team grew to love it.

I'm in agreement with @SHyx0rmZ - after using Elm I don't think I'd use JavaScript ever again. I distinctly recall it being the first time that frontend development felt "right."

**Comment by topherbullock** [comment]
Former Elm skeptic @vito was talking about reporting in!

I used to be a huge JS fan... I hated on CoffeeScript so hard for being an abstraction between mean and vanilla JS, and wondered why anyone would ever use it over plain ol' JS. Since using Elm, my mind has been changed entirely.  

I definitely get the desire to have something with adoption in the JS community, but after a while I've grown to understand what makes Elm a great candidate for front-end dev; a lot of the common problems with (painfully janky) solutions in all of the front-end frameworks I've used (Backbone, Ember, Angular, React) are ironed out by a type system and functional programming.
