### ISSUE TITLE
Provide sensitive variables from command line prompt when setting pipeline

### ISSUE THREAD

**Issue by xtreme-peter-iskandar** [concourse/concourse#1504]
# Feature Request

## What challenge are you facing?

When setting a pipeline, we usually provide a credentials.yml which is not committed to the repo but maintained locally. Sometimes the credentials file can contain some sensitive information (e.g. passwords). This is fine when you are developing by yourself, however, when pair programming, you run the risk of exposing personal passwords to another person.

It would be useful that when you run the following command:

`fly -t lite set-pipeline -p my-pipeline -c pipeline.yml -l credentials.yml`

that anything not populated, or somehow denoted as sensitive will prompt user to enter the variable manually in the command line.

**Comment by jtarchie** [comment]
@xtreme-peter-iskandar this is why we've started expanding the credential management with `vault` and (rumour has it) `credhub` (in Toronto). These will be much better at storing sensitive variables than having to retype them each time.

As for this feature request, it would only make sense with one-two password top, otherwise, I guarantee, someone will automate it because remember all the password is hard. Then we'd have another feature request to resolve that.... and then cycle continues. 😄

**Comment by marco-m** [comment]
@xtreme-peter-iskandar I think that now the answer is: "put secrets in a credentials manager", and as such this ticket can be closed. Or am I missing something ? @jama22
