### ISSUE TITLE
Control over display of pipeline in the web UI

### ISSUE THREAD

**Issue by yacovmalen** [concourse/concourse#1513]
# Feature Request

## What challenge are you facing?

When there are jobs that have no dependencies the will appear in line with other jobs that can occur at the same time. The best example of this with versioning: 
![image](https://user-images.githubusercontent.com/16318802/29570854-551bedb2-8760-11e7-8bcf-eccc5941023b.png)

This can cause some confusion as to the order/placement of these steps in the pipeline. There are no conditional jobs in concourse, meaning (in the example above) that I cannot place the shipit depenedent on the major/minor build steps because it would require that the both jobs be complete successfully (this is not always the case).  

## A Modest Proposal

A few possible solutions:

1. Conditional jobs. Added an option of passed_one: [major, minor] and then the next job would take the most recent completed job.
2. Serial jobs should appear serially in the pipeline. If they can run in parallel, the don't need to appear in parallel. They don't need dependencies (maybe the connecting line should be dots rather than dashes to show no dependencies in the job - only that they are serial)
3. Control over display order of pipeline in webUI - Add a new option of group_order with a hierarchical list of jobs to group jobs that appear in a line and the order the jobs appear in.
     * This option can allow people to show non-connected regions of the pipeline (like the version) in the more appropriate place in the pipeline without needing to connect it. For example: version happens in the step after the Shipit, it should appear above the job that occurs after Shipit.

**Comment by jtarchie** [comment]
@yacovmalen, it seems like you have a couple of thoughts running through here. I am not following the issue/problem you are having.

The example you give above shows a job three jobs -- `minor`, `major`, and `shipit`. They are rendered this way because this is how the grouping has limited the rendering of the pipeline. If you view the pipeline as a [whole](https://ci.concourse.ci/teams/main/pipelines/main?groups=develop&groups=publish&groups=workers&groups=dependencies) (shift select all the groups), it renders in priority. Since groups are limited a rendering, the graph algorithm renders as so.

1. There is already an issue (concourse/concourse#313) for this.
2. This seems like it would take a lot of real estate. Just having a single serial job taking its own row.
3. I don't like the idea of groups, as it limits the overall view of how things affect each other, which is your issue. And having a way to control the order of groups seems like a smell.

**Comment by jama-pivotal** [comment]
Hi @yacovmalen , not sure if you've had a chance to read @jtarchie response to your proposal. I would tend to agree with him on all 3 points. Closing this issue for now, but feel free to re-open if you feel like we've mis-represented or mis-understood the issue
