### ISSUE TITLE
Building Github Pull Requests directly

### ISSUE THREAD

**Issue by ns-phennessy** [concourse/concourse#1520]
Hi there!

# Feature Request

## What challenge are you facing?

The number one thing preventing us from switching from Jenkins to something like Concourse is the ability to automatically run a build off of a Github / Gitlab pull request. The overwhelming majority of our builds will be coming from this type of thing. 

I've done some digging and can't seem to find anything that provides this functionality, and even the docs say that Concourse does not have this functionality. I have found a handful of tickets mentioning this; but it is unclear as to the current state of this in Concourse.
https://github.com/concourse/concourse/issues/1384
https://github.com/concourse/concourse/issues/239
https://github.com/jtarchie/pullrequest-resource

To make this work; I image there would have to be some kind of middleware service kick off a pipeline while listening for webhooks outgoing from Github?

It does appear to be possible; i see that Fly is using some kind of PR builder? https://ci.concourse.ci/teams/main/pipelines/prs/jobs/fly

Thanks!

**Comment by jtarchie** [comment]
@ns-phennessy:

In short, there is no native pull request support. Some of users use Gitlab, Bitbucket, etc, which have a different model for pull requests.

Most PRs are created because of a git-flow practice. There is issue documenting this more generic usage -- concourse/concourse#1172.

I created the [pull-request resource](https://github.com/jtarchie/pullrequest-resource) to aid in this issue though. Have you tried it? This is what `fly` uses to test PRs.

I'd ask you to use the resource and if that doesn't fit your workflow. Let's discuss the missing feature set.

Cheers!

**Comment by vineela-gampa** [comment]
@jtarchie  can you please send in a sample pipeline yaml file i could look into to use your pull-request resource  ?

**Comment by jtarchie** [comment]
@vineela-gampa, please follow the link to the resource to see the README. There are few example listed there.
