### ISSUE TITLE
build page loading is very slow

### ISSUE THREAD

**Issue by kkallday** [concourse/concourse#1543]
# Bug Report

We recently upgraded to v3.4.0 and noticed that web UI is slow to load builds (ie: https://example.com/teams/main/pipelines/some-pipeline/jobs/some-job/builds/999).

It is slow regardless if they are passing or failed. We've also noticed that while the build is loading and when you click the "hamburger" icon, there is a 4-5s lag to close the menu. Some builds take about 45s to load. The specific build that has the most trouble has a task that has a lot of build output.

* Concourse version: v3.4.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome
* Did this used to work? It became slow when we upgraded to v3.4.0.

cc @rizwanreza

**Comment by jtarchie** [comment]
Related: https://github.com/concourse/concourse/issues/1009 https://github.com/concourse/concourse/issues/644

@kkallday, can you try in Firefox or Safari, do you have the same slowness?

**Comment by Gerg** [comment]
We have also noticed severe performance issues using Chrome for certain jobs. One of our jobs doesn't produce much output, but takes multiple minutes to load in Chrome (if it ever loads). In Safari/FF, it loads in a few seconds.

**Comment by jtarchie** [comment]
@greg the other issues also reference this is a rendering issue with chrome, which we are not able to resolve. ☹️

**Comment by Gerg** [comment]
Is there an open issue against chrome that I can track? Can concourse modify its UI to render better in chrome?

**Comment by matiasanaya** [comment]
I'm running `3.4.1` and the build logs are very slow (~1min) to load for every build (running / passed / failed). It's not browser dependent in my case, and even `fly -t team watch --job pipeline/job --build 1` takes equally long.

**Comment by tcdowney** [comment]
Not sure if this is related, but we noticed today that it was even causing Firefox to hang and we had to tell the browser to "wait" for it to continue rendering again.  It wasn't as severe as it is in Chrome, but still seems indicative of some underlying issue.

![screen shot 2017-09-08 at 2 08 04 pm](https://user-images.githubusercontent.com/2096955/30231336-482032e8-949f-11e7-9eaa-6b85e3f12465.png)

**Comment by joshzarrabi** [comment]
It seems the cause for this is a massively inflated set of build events. A call to the events api of a slow build consists of about 10,000 events, which mostly look like this:
```
id: 10581
event: event
data: {"data":{"origin":{"id":"59b07b20","source":"stdout"},"payload":"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "},"event":"log","version":"5.0"}
```. 
A fast build has about 300 events, none of which are empty.

**Comment by jtarchie** [comment]
@joshzarrabi that is the best lead we've had. Thanks! This is something to investigate.

For your clarification, that build event is not a no-op. At some point your build output had that many " " (space) printed to, we need to emulate it in the build output.

Perhaps there is a way to flatten the output. Either as one large build event? We have to worry about the ANSI support, which can have problems of deleting a previous character is outputted.

Anyways. Thanks! We are going to tinker.

Out of curiosity, would you be able to share the build events with us, so we can replicated appropriately?

**Comment by joshzarrabi** [comment]
@jtarchie We believe this is caused by the bosh2 cli, as it prints out stderr and stdout next to eachother, I don't totally understand it but I can get back to you with more info on Monday. We think more people are seeing it now because they are migrating to the bosh2 cli. cc @kkallday

**Comment by z4ce** [comment]
I think this is the same issue we are seeing at a client. I can see that concourse is hitting the `events` endpoint and that messages are all sent across but concourse continues to display `loading` until the events stream is actually closed...

**Comment by z4ce** [comment]
We ran some performance tests using the chrome dev tools, it looks like it is a "work" function that is running 1000s of times and taking about a second each time and it kills the browser:
![image pasted at 2017-9-28 11-35](https://user-images.githubusercontent.com/4860914/30976508-f8e39f36-a442-11e7-81a9-896c5cc6b5dd.png)

**Comment by z4ce** [comment]
@jtarchie @vito I did some testing and came up with a pipeline that will replicate this issue. 

Here is the repo:
https://github.com/z4ce/break-concourse-ui

Notice the pipeline has a "sleep" between writing each line. It turns out that if you slam the log output quickly concourse is smart enough to "condense" the lines into one event. When it does this, there is no performance issue in the UI. If you do it more slowly it doesn't condense the events and the performance suffers. On my laptop (i7 mac with 16gb of ram) the page takes about 50 seconds to load, on the customers laptop takes ~5min.

**Comment by jtarchie** [comment]
We found it!

This turns out to be an issue with Google Chrome with large arrays. We've created an [issue](https://github.com/elm-lang/core/issues/916) with `elm` to resolve the issue. We'll investigate if there is a soft-patch that we can apply.

**Comment by tahaozket** [comment]
Any updates on this or any soft-patch to apply?

**Comment by ashishgoel-ps** [comment]
we are facing similar issue with the newer version 3.6.0
Concourse build page is loading very slowly and the builds are taking almost 25 mins for which it took 5 mins on the other concourse environment. 
is there a fix to this yet or a patch to apply?

**Comment by william-tran** [comment]
On 3.8.0, build/BUILD_ID/events seems to take up way more time than in previous versions, but I don't have two side by side to give exact differences in timing. Using curl on that endpoint gives me everything in a second, but it takes 16 seconds in Chrome and a little less than that in Safari.

**Comment by EugenMayer** [comment]
If you clear the logs, things will load very fast again. Its simply that:

`delete from build_events where type='log'`

This will though delete _all_ logs of all pipelines. We do that regulary right now, because concourse becomes unusable very very fast.

**Comment by timrchavez** [comment]
In our case the `/events` endpoint starts returning a 504 and viewing build logs becomes impossible. Restarting the web process (we use the binaries), resolves the problem temporarily. I'll start collecting more debugging data on this when it happens again. We're on v3.8.0

**Comment by EugenMayer** [comment]
@timrchavez those are exactly the ones i mentioned. We are talking about the build-log events, so AFAICS a even per line, serialised. So should be about 1.000.000 in no time.

**Comment by timrchavez** [comment]
Not sure if I'm conflating issues here or not, but I really think that the binaries need a `--build-logs-to-retain` setting that applies across the board. It could then be overridden by `https://concourse.ci/single-page.html#job-build-logs-to-retain`. We have something like 32m log events, but there doesn't seem to be a way to selectively delete, say, the "builds older than 30 days"

**Comment by william-tran** [comment]
@EugenMayer I think this is more of a browser efficiency issue than a DB one, at least in my case:
>Using curl on that endpoint gives me everything in a second, but it takes 16 seconds in Chrome and a little less than that in Safari.

**Comment by timrchavez** [comment]
Streaming build events only seems important as the build is happening. How do people feel about rendering the complete log after a build finishes and serving that?

Writing build logs to `.txt` files after a build complete and then serving those seems like it'd get complicated with multiple ATCs. 

Rendering the build log server side on _every_ request eliminates the problem of storing and finding files, but very large logs could conceivably cause the request to time out (or not?). You're also still having to compute the build log in the context of a request which will still probably have some amount of latency.

Rendering the build log server side after a build completes and storing in a new DB table (e.g. `build_logs`) could eliminate the storing and finding files problem and the latency problem when rendering in the context of a web request, but could have a negative impact on DB performance.

Any other ideas?

**Comment by jama-pivotal** [comment]
In lieu of no longer waiting for the Elm change to come in, we want to apply some optimizations to this page _today_.

We have a few options

1. Have the logs collapsed by default on all build states, this would just defer the loading of big logs to when folks click in
2. Keep the design the same but only load the most recent 100 lines. We could add a button to let users "click to load more" or even just "Download"
3. Display events in reverse chronological order with some of the optimizations from suggestion (2) so that folks don't have to scroll all the way down every time anyways. 

Implementation Details:
- flatten events as build steps complete
- check before and after performance 
- re-assess

**Comment by hfinucane** [comment]
I have some jobs where 'collapsed by default' would be a huge win, but some where it wouldn't, because there's just one long log. Even if everyone else has just one long log, I'd still support the change, people see the blank page with the spinner and say "concourse doesn't work".

The most recent 100 lines seems pretty reasonable, since I'm often looking at logs to discover an error, which tends to be near the bottom.

**Comment by pivotal-jamie-klassen** [comment]
# What we did
## Batching Events
The most significant change we made is that now the `EventStream.LowLevel.onEvent` function has type `Array.Array Event -> Task Never ()` rather than `Event -> Task Never ()`. Now, instead of pushing a single event onto the Elm work queue for every single server-sent event, we batch them up and just drop whatever is in the buffer onto the workQueue as a single event every 200ms. This reduces the size of the workQueue by about 3 orders of magnitude. Because `Array.shift` has `O(n)` complexity in Google Chrome, we get an increase in efficiency both by limiting the number of calls to `Array.shift` and by reducing the cost of each individual call (two consequences of keeping `n` small).

This change bubbles up through the system where various locations that have to handle `EventSource.LowLevel.Event`s or `EventSource.Msg`s or `BuildEvent`s now handle arrays of the respective types, but it felt worth it for the performance boost.

## Json Decoding

Our Json decoding functions were a bit funny, wrapping and unwrapping `Result`s instead of using the built in `success` and `failure` functions in the `Json.Decode.Decoder` module.

# Next steps

It's still not wicked fast, even though for sizeable (~3MB) logs we got ~6.5x speed improvements. At this point, looking at the Performance pane in Chrome shows that a lot of time is still spent on two things:
* parsing/rendering calls in the [vito/elm-ansi](https://github.com/vito/elm-ansi) library, so maybe those parsers could be optimized (I see there are some calls to `++` and, not knowing how the elm compiler really works, I suspect that string concatenation is always low-hanging performance-optimization fruit)
* Rendering the transformations to the DOM. It's not obvious to me how much of that is unavoidable cost of using a browser, or how we can help Chrome/Elm to make the transformations cheaper. Maybe it's a question of CSS? Honestly I'm a bit out of my depth on this topic.

**Comment by topherbullock** [comment]
Lets call this done for now and address the 'Next Steps' in a future issue.

**Comment by jama-pivotal** [comment]
Just deployed internally on Wings. We observed similar improvements on the page load time. Accepting this for now and like @topherbullock said, we'll address 'Next Steps' in the future 😎 

![untitled drawing](https://user-images.githubusercontent.com/19274230/41924102-1c508352-7937-11e8-889c-cf09bff5d562.jpg)
