### ISSUE TITLE
[Multi-Pipeline View] Pipeline ordering by status

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1553]
This is an extension to the story #1491 

After ordering red pipelines first we realized that it makes more sense to commit to a more structured ordering of all the other states, instead of leaving them mixed in. 

The order of pipelines within teams should be:

1) Red (failing)
2) Yellow (Errored)
3) Brown (Aborted)
4) Green (Succeeeded)
5) Grey (Pending)
6) Blue (Paused)

Furthermore, internally within each state we should push the running state to the top of the list to highlight their state

**Comment by andrewedstrom** [comment]
Is there any possibility of having a mode to keep the pipelines in a fixed location rather than reordering them when the status changes? We are feeling pain around this; we would like to be able to have the pipeline stay in place on the dashboard so we know where to glance when we want to check on it.

We don't particularly feel a need for pipelines to be grouped together based on status.

**Comment by mhuangpivotal** [comment]
👋 @andrewedstrom 

We assumed people would look at the shape of the pipelines once the thumbnail preview is implemented (#1462). Do you think you will still prefer the pipelines in fixed locations?

**Comment by robdimsdale** [comment]
@mhuangpivotal I have seen more than one team with multiple pipelines of the same topology, so I'd advocate for keeping the pipelines in fixed locations. I think it's reasonable to reorder when pipelines are created/destroyed.

**Comment by jama-pivotal** [comment]
Pipelines are actually now in fixed positions! Closing
