### ISSUE TITLE
How to test `semver` resource

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1603]
When it comes to contributing to Concourse resources, our projects have a "testability" gap. While the community is more than open to making changes and tweaks to Concourse resources, it is very difficult to write tests for them. This story is an effort to 

1) make the `semver` resource more test-able
2) provide any resource-specific instructions (if applicable) to run and write tests

**Comment by jmelchio** [comment]
With this and #1601, we have to find a way to mock an s3 bucket, so users don't require active s3 integration.

**Comment by vito** [comment]
As far as I can tell this is actually done.

We ended up making an `approved-for-ci` label on the semver resource's repo, and having the pipeline integrate against real services. The pipeline then only runs PRs labeled 'approved-for-ci', so that we can make sure it's not going to do anything nefarious with our credentials or service.
