### ISSUE TITLE
insufficient subnets remaining in the pool

### ISSUE THREAD

**Issue by iswix-llc** [concourse/concourse#1620]
# Bug Report

I have a Concourse environment with 1 linux worker and 1 windows worker.  I have 36 pipelines.  I start with all of the pipelines paused and then I gradually unpause and run each of the jobs.  The first 14 pipelines succeed and then they start failing with the error message 'insufficient subnets remaining in the pool'.  

fly workers shows the windows worker has 3 containers and the linux worker has 256 containers.   fly containers shows hundreds of  check type containers with "none" for pipeline, job, build #, and build id.
There are also 15 task, get and put containers with valid pipeline, job, build # and build id data.

At this point no more pipelines will execute.

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary):  docker
* Infrastructure/IaaS:  vm running docker
* Did this used to work? yes - didn't use to see these.

**Comment by jtarchie** [comment]
@iswix-llc, it is not clear what bug you are reporting. The title of the message report an error message, but the contents seems to indicate you ran out of containers.

If you ran out of containers, which at 256 containers it looks like you have, you can increase the max containers on a garden worker.

```
--garden-max-containers=                           Maximum number of containers that can be created. (default: 0) [$CONCOURSE_GARDEN_MAX_CONTAINERS]
```

If you are running out of subnets, they are limited by CIDR range, so that garden workers can have limited access to the host IP range. You need to override to be able to allocate more.

```
--garden-network-pool=                             Network range to use for dynamically allocated container subnets. (default: 10.254.0.0/22)
                                                             [$CONCOURSE_GARDEN_NETWORK_POOL]
``` 

All the options above are available on the `concourse worker`.

I would recommend that you don't increase your worker to any more that ~250 containers. Linux just starts having a bad time handling and scheduling that many containers. You might have reached the point that adding another worker would best suit your needs.

If you are concerned with the number of check containers that are being reported and resolved [here](https://github.com/concourse/concourse/issues/1510). We believe that we have a resolution for it that will be released in the next version.

Thanks for reporting the issue. At this moment, I believe there is enough information above to resolve your issue.

**Comment by iswix-llc** [comment]
Closing this issue didn't help me at all.  Part of your advice says I can increase the number of containers but then another part of the advice says you wouldn't recommend it.     I can add another container but I have a feeling it'll just max out at 256 X 2 and fail again.    I only ran a dozen jobs and none are running right now because none of them will start.   I don't see how adding more workers is the solution.  My problem is I have all these seemingly orphaned containers gumming up the system and I don't know how to fix it.    

I restarted the linux worker and it's container count went back down to zero.  But I still see hundreds of containers when I run the containers command.  Now my builds are failing with the resource check reporting 'unknown handle: 09c92ccb-a19c-4e8a-743c-67509197cbad' and so on.

**Comment by jtarchie** [comment]
@iswix-llc,  it was not clear the issue you were experiencing. I tried to give as much general information I could to help solve any of the unclear issues. I closed the issue because of those reasons.

Please provide more clear, concise, and actionable errors. This makes it more useful for us and the community. Show don't tell.

* Your title was an error message, which appears [many times through out issues](https://github.com/concourse/concourse/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22insufficient%20subnets%20remaining%20in%20the%20pool%22), made it seem like a duplicate.
* Your point of a single linux worker made it appear that you've reached max containers on garden worker.
* Your point about all the check containers made it sound it was related to the bug #1510.

And please, we are providing support for free to the community. If we helped resolved an issue with the provided, we'll close that issue to help close our backlog. That's been our policy, you're free to comment on it, but the perceived tone of your response above hurts me (and maybe others) in motivation to help more.

I ask for understanding, courtesy, and empathy. Thanks.

As for you comments above:

* It sounds like you are experiencing issues with #1510. We hope to have that fix out soon. Adding another linux worker is meant to alleviate this error till then, please give it a try.
* The error messages `unknown handle` is related to what the `atc`/`web` thinks the current state of the world is. It should eventually catch up to the actual state. This can happen when a worker is restarted.

**Comment by iswix-llc** [comment]
I would appreciate a bit of empathy on your part also.  I'm not sure how you expect me to react when you close an issue without even inquiring if my problem was resolved. It certainly hurts my motivation to bother submitting issues and asking for help.

As for the issue, I can only report what I did and what the result was.  I've created another linux worker and I hope to see 1510 released soon so I can try it out.    I work in a company where we are required to have ephemeral servers. As such I frequently have to rebuild my stack and repopulate the pipelines.  These  transient errors that eventually go away cause lots of issues as I'd like to see all of my pipelines go  green in one attempt.  Not bang on them repeatedly until they do.

**Comment by jama-pivotal** [comment]
@iswix-llc  I'm going to close this issue again since it doesn't quite qualify as a bug report regarding a specific piece of Concourse functionality and/or one of its subcomponents. In general, we try to keep our Issues backlog specific to actionable bugs and feature requests; we don't want it to be a filled with Stack Overflow Q&A posts (we actually have a place for those here: https://stackoverflow.com/questions/tagged/concourse)

You're having trouble running Concourse in your particular setup and we recognize that. I'd like to take this opportunity to invite you into our Slack channel where the team here & the Concourse community can work through some of those issues with you _collaboratively_ . If, through that process, we find a new issue with Concourse I'd be more than happy to review and prioritize it in our backlog.
