### ISSUE TITLE
Display "pending" on pipelines where pipelines are paused or has pending runs

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1622]
Display "pending" on pipelines where pipelines are paused or has pending runs for multipipeline view. This is to be consistent with the timer thats on pipelines for other states. 

![dashboard_legend_01](https://user-images.githubusercontent.com/27746614/30719743-b2ae894a-9ef2-11e7-821e-31c5ad6863e1.png)

Update icon to new svg. 
[pending_ic.svg.zip](https://github.com/concourse/concourse/files/1322782/pending_ic.svg.zip)

**Comment by vito** [comment]
@jama-pivotal I think this is kind of confusing. I would expect the `bosh:borg` pipeline above should be *green* with the animation, not grey. It seems weird that the flow is now:

```
grey ->
grey and running ->
green ->
grey and running ->
green
```

instead of:

```
grey ->
grey and running ->
green ->
green and running ->
green
```

I would expect that a job progressing from left -> right on its first run would be additive; there may be parts of a pipeline that don't run for an extended period of time (i.e. `shipit` and jobs thereafter), and having it go "backwards" to grey is surprising.
