### ISSUE TITLE
Target should not be deleted when logging out

### ISSUE THREAD

**Issue by timrchavez** [concourse/concourse#1672]
# Bug Report
Logging out of a target, deletes the target, which seems like unexpected behavior. Instead, it should simply clear out the token and leave the target intact.

```
timrchavez@zombiekitten:~$ fly -t main logout
logged out of target: main
timrchavez@zombiekitten:~$ fly -t main login
error: unknown target: main
```

* Concourse version: 3.4.1
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: DigitalOcean
* Browser (if applicable): N/A
* Did this used to work? No idea. I suspect not.

**Comment by xtremerui** [comment]
This is currently blocked by lacking way of ATC JWT token expiration. Thus Fly has to delete the target entry in .flyrc to force Fly cli to re-login by given ATC url. Noticed that, only delete token in .flyrc won't actually logout since token is still alive on ATC. It will expires after configured time only (24 hrs by default).

**Comment by jama-pivotal** [comment]
@xtremerui can you please try again by leaving the target in place but removing the token?
