### ISSUE TITLE
Add aws parameter store secret backend

### ISSUE THREAD

**Issue by jmcarp** [concourse/concourse#1676]
# Feature Request

It would be useful for aws users to add a secret backend for [aws parameter store](http://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-paramstore.html). We're interested in using parameter store so that we don't have to operate and maintain our own secret store, like vault or credhub. As usual, the cloud.gov team would be happy to send a patch for the feature if you're open to it.

cc @sharms

**Comment by willejs** [comment]
This would be great. Running and operating vault is quite a large overhead when you are only using a few secrets!
However, the aws backend in vault will be useful to solve sts credentials in pipelines, otherwise someone needs to create an iam/sts secret backend for concourse.

**Comment by mogul** [comment]
@jtarchie @chendrix @vito have you had any chance to think about this? We're ready to start making some decisions about how we handle secrets, but the Concourse direction/receptivity here is a blocker for us.

**Comment by itsdalmo** [comment]
This would be a very nice addition to Concourse, and is something I've been waiting for myself.

**Comment by jtarchie** [comment]
@jmcarp and @mogul since this is security related, we all have to concerned about its implications. The concourse team doesn't have experience with the aws parameter store, which is why we've be cautious in approaching this.

When it has come to other backends (credhub and vault), we've paired on it and written *hopefully* [exhaustive](https://github.com/concourse/topgun/blob/master/credhub_test.go) [tests](https://github.com/concourse/topgun/blob/master/vault_test.go) to ensure that we understand them. We'd feel more comfortable if we can replicate this experience.

**Comment by itsdalmo** [comment]
Disclaimer: I haven't used SSM Parameter store myself either (only want/need it for CI/CD), just skimmed the documentation to figure out what it might look like for Concourse.

In comparison to Vault, the ATC won't need a token to gain access to the Parameter store since we should use an instance profile instead - So we

On launching the ATC it could have the equivalent of  `--vault-path-prefix` for SSM, where the prefix for both parameters and kms keys could be set according to the policy on the instance profile. The policy can restrict access by both parameter name and KMS key id or alias:

```json
{
   "Version":"2012-10-17",
   "Statement":[
      {
         "Effect":"Allow",
         "Action":[
            "ssm:GetParameters"
         ],
         "Resource":[
            "arn:aws:ssm:region:account-id:parameter/concourse*"
         ]
      },
      {
         "Effect":"Allow",
         "Action":[
            "kms:Decrypt"
         ],
         "Resource":[
            "arn:aws:kms:region:account-id:key/concourse*"
         ]
      }
   ]
}
```
source: [AWS SSM Documentation](http://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html)

Teams could be isolated by following the pattern used for Vault, i.e. limiting teams to only being able to use parameters with `/concourse/<team>/<pipeline>/<param>` and `/concourse/<team>/<param>` as parameter names, in which case the pipeline definition would request `((<param>))` and the ATC would look up either a team or pipeline parameter.

I don't know much Go, but it seems like the missing code for SSM Parameter support would be a new module [here](https://github.com/concourse/atc/blob/master/creds), which would only be responsible for only getting a parameter after being provided with the name/team/pipeline. If a SSM Parameter implementation just followed whats done for Vault in terms of using paths for parameters, it seems like most of the code and tests could just be copy/pasted?

Vault is great, but it basically requires 2x the effort to set up and Concourse w/Vault as it does without. And managing Concourse requires 2x the effort as well; if you want to create a new team, you have to write a policy for Vault and onboard the team (e.g. add a role to AWS auth in Vault). 

I really think SSM Parameters would be awesome for Concourse, and I'd be happy to help out in any way I know (or I could attempt to learn some Go) ;)

**Comment by pms1969** [comment]
I'm very interested in this as well.  Not that I don't like vault, but until I have a clear use-case for it over and above what ParameterStore has, I see no reason to add it.  So at the moment, we have to ship parameter files around for everyone updating pipelines, which I'm not so happy with either.

@itsdalmo 's approach here seems sound, and doesn't look like it's too different to the approach taken with Vault.  I've been hoping to get time to code this up, and submit since the credential store was first introduced, I just haven't been able to find the time - other business priorities keep me extremely occupied.
