### ISSUE TITLE
[Search] Search by pipeline status

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1703]
As a concourse user, I'd like to be able to filter the dashboard by pipelines with a specific status.

**Given** that I am on the multi-pipeline dashboard
**When** I enter `status:succeeded`
**Then**  I should only see pipelines that are green and succeeded

The allowed search parameters should be:
`status:succeeded`
`status:errored`
`status:aborted`
`status:paused`
`status:failed`
`status:pending`
`status:started`

**Comment by vito** [comment]
Looks good but noticed two confusing aspects:

* `pending` includes running pipelines whose builds have actually started. We think this is less of the query being wrong, and more our notion of 'pending' being wrong - a pipeline with a build that's *running* should be distinct from a pipeline whose builds are all *pending* (or has no builds). Let's change this so that pipelines with builds that are actually running, with no prior build state, show 'running' instead of 'pending', and are not included in the 'pending' search. (captured as #1746) 
* `started` confusingly includes `aborted` pipelines. We're also thinking `running` makes more sense since that's what shows in the legend, and more intuitively should not include aborted builds (which, arguably, are started because they never finished).
