### ISSUE TITLE
Per-team worker base resource type volumes outlive their team

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1708]
# Bug Report

The WATs create a fresh team for every test and then destroy it at the end. It looks like the volumes for the base resource types never go away, even when the `team_id` column is `NULL`.

If `team_id` is ever `NULL`, I think we should GC the volume. We don't share any type of volume across teams, even resource caches, so there's no case where we'd want to keep it.

**Comment by vito** [comment]
@topherbullock It's been a while, so do you know if this is still the case? I think this would be low-hanging fruit to fix, so if we've got the bandwidth for it it'd be nice to clean up this tech debt.

**Comment by topherbullock** [comment]
@vito ![george costanza shrugging](https://media.giphy.com/media/RIS1sypJ2Vfwc/giphy.gif)
No idea. We should validate whether this is still the case.. dragging it up the backlog.

**Comment by topherbullock** [comment]
Ran through creating a team with a pipeline which uses base resources, and they do get GC'd eventually.
I did observe a lot of `"volume cannot be destroyed as children are present"` messages relating to the base resource type volume, so this might be a place to improve. We could potentially do some ordering of the volumes (and containers) to delete, so that we remove the deepest children first.

**Comment by vito** [comment]
I think this may have actually been fixed by https://github.com/concourse/atc/commit/25cac08a1231469559f84ff945a99b5554fc77c9 as part of https://github.com/concourse/concourse/issues/2168.
