### ISSUE TITLE
Come up with a breadth of pipeline use cases to explore how spaces may be used

### ISSUE THREAD

**Issue by vito** [concourse/concourse#1766]
Epic: https://github.com/concourse/concourse/issues/1707

There are a few decisions we're having a hard time making without understanding the impact they would have:

* The notion of a "default space" - once resources become space-aware, how do existing pipelines change?
* Fan-in syntax in `passed` - is `passed: [foo: all]` enough to express existing fan-in flows? Are there other syntaxes to explore?

These pipelines should vary in size and complexity - we want the story for "0 -> hello world" to feel just as intuitive as a pipeline maintained by a large team doing real-world stuff.

Things to keep in mind:

* It's not necessarily bad to have spaces be something a user thinks about early on. Learning 1% early helps for when they need the other 99% later.
* We want to minimize the breadth of change required to a pipeline as user interacts with spaces.

Here are some use cases:

1. * I have a small Ruby project with a `test` stage and a `ship` stage.
   * I initially only test against the master branch with Ruby v2.0.x.
   * Later I want to test against Ruby v2.1.x, and ship only if both pass. 
     * What does this change look like?
   * Later I want to run tests against all branches, and against all versions of Ruby, but only ship if 
  it's the master branch.
     * What does this change look like?

2. * I have a reasonably large pipeline (say, [ours](https://ci.concourse.ci/teams/main/pipelines/main)) with a `shipit` job that has super conservative `passed` constraints.
   * I have a job in the middle of the pipeline, which produces an artifact that feeds into `shipit`.
   * One year later, I want to have that job run against multiple spaces (e.g. `bosh-deploy` against multiple IaaSes).
     * What does this change look like?
     * As part of the change, was there an increased risk of `shipit` not being as conservative as it should be? (Did the job require a config change?)

3. * I have a resource in my pipeline that truly doesn't have a "default space". Let's say pull requests, where each space is a different PR.
   * What does it look like to interact with this resource?
   * What kinds of configurations would be "invalid" or at least misleading?

**Comment by vito** [comment]
Additional concern: what does "spaces" mean for anonymous resources like `resource_types` and `image_resource`?

**Comment by highb** [comment]
Hi there! I'm very interested in the spaces feature and I figured it might be helpful if I shared a use case that comes to mind:

1. I have multiple releases of my application that I must maintain. Each release has its own git branch. Let's call them `1.0.x`, `1.1.x`, and `2.0.x`. `1.1.x` was branched off `1.0.x` when we started work on that version, likewise with `2.0.x`.
2. We must continue to maintain all of these version branches in parallel. That means pulling from Git when there are new changes, running unit and acceptance tests, as well as shipping built packages for each of them. It would also be ideal if we could force all tests to run nightly or on-demand, regardless of whether any new code has shipped.

**Comment by flavorjones** [comment]
Ahoy, answering your call for use cases from the Medium post. I'm not sure anything I'm doing is edge-case-y or novel, but here goes, anyway:

-----

I have a [popular Ruby project](https://ci.nokogiri.org/teams/nokogiri-core/pipelines/nokogiri?groups=master) that only runs tests today (i.e., doesn't shipit (yet))

I test master with a large matrix:

* dimension 1: Ruby [MRI 2.{1,2,3,4,5}, Rubinius, Jruby {1.7,9.1}]
* dimension 2: OS [Linux, Windows]
* dimension 3: origin of C libraries [system, vendored]
* dimension 4: without and with Valgrind
* dimension 5: without and with the `libxml` gem loaded

Some intersections in the matrix are not tested, i.e.

* only MRI is tested on Windows
* only MRI+Linux is tested in dimension 3 (with system libraries)
* only MRI+Linux is tested in dimension 4 (with Valgrind)
* only MRI+Linux is tested in dimension 5 (with `libxml`)

I'll add `shipit` soon, and that will fan in from _all_ of the above jobs.

__Pull Requests__ are run through a leaner pipeline, primarily because Windows containerization isn't safe for running untrusted PRs:

* dimension 2: __flattened to just Linux__ (no Windows coverage)

but again, for PRs, fan-in is from _all_ of the above jobs. (Note that any untrusted branches must also be limited to only Linux for now.)

-----

I have a second, [less-popular Ruby project](https://ci.nokogiri.org/teams/nokogiri-core/pipelines/loofah) that does some of what's done above, but has a variation, which is that there are jobs that are ["allowed to fail"](https://ci.nokogiri.org/teams/nokogiri-core/pipelines/loofah?groups=allow-failure), meaning that fan-in on `master` and on PRs should be limited to an enumerated set of jobs, somehow.

**Comment by vito** [comment]
@flavorjones Thanks!

Can you describe how you configure dimensions 3-5? Are they with e.g. task params or are they using different Docker images?

I ask because so far our design for spaces is resource-centric, and so it would want every dimension to be somehow backed by a resource, with a space for each thing you want to fan-out by. For example, a Docker image with tags (which correspond to spaces) for with/without `libxml`.

OS is slightly different since that's presumably the `platform` config in the task .yml, which I guess could come from a resource but it seems more likely that you've currently just got two jobs that point at different task files?

**Comment by flavorjones** [comment]
@vito All three of those dimensions are configured via `params`:

* C libraries: https://github.com/sparklemotion/nokogiri/blob/master/concourse/nokogiri.yml#L89
* Valgrind: https://github.com/sparklemotion/nokogiri/blob/master/concourse/nokogiri.yml#L129
* libxml ruby gem: https://github.com/sparklemotion/nokogiri/blob/master/concourse/nokogiri.yml#L152

You can see in that pipeline config that I'm doing some gymnastics with erb using Ruby version metadata (present in `RUBIES`) to help build these spaces. It was annoying to set up, but honestly isn't too bad to maintain now. (The Ruby version metadata is pulled from the [concourse gem](https://github.com/flavorjones/concourse-gem#templating-and-rubies).)

**Comment by jchesterpivotal** [comment]
## Project Riff

Project Riff has pipelines built using [nested loops in an ERb template](https://github.com/projectriff/ci/blob/master/pipelines/riff.yml). Right now it can be configured to test a matrix of Kubernetes runtimes across individual components of the system. Because of the difficulty of wrangling that main pipeline, we are currently only testing against GKE.

This becomes incredibly brittle when we try to add [a PR pipeline](https://github.com/projectriff/ci/blob/master/pipelines/riff-pr.yml) that looks like the `master`-branches pipeline. To the point where the PR pipeline is often broken and ignored. The Project Riff team is following a multi-repo, PR-based workflow. This means that PRs are not being tested in the way the team would like -- where CI enters an opinion _before_ a commit hits master.

I expect this will become more intensive over time, as we add more k8s targets (eg. AKS, EKS, reintroducing CFCR).

## Load & Performance Testing

In future we intend to incrementally build out a performance suite for Riff. This potentially has many dimensions. For example:

* Workloads / Scenarios
    - Few functions installed vs many functions installed
    - Requests per second
    - Function sleep time
    - Few functions triggered by events vs many different functions triggered by events
* Configurations
    - Scaling algorithms
    - Virtual machines -- CPUs, RAM, disk performance
    - Size of kubernetes cluster
    - Size of kafka cluster (within kubernetes)
    - Configuration of kafka
        - Buffers, disk sizes, number of disks
        - Replication policies
        - Number of topics, partitions, brokers

We might later want to apply some subset of these to non-riff targets. For example, to maintain comparative statistics vs Lamba, Fn and so on. Plus it may be that we would run these tests against the k8s environments -- GKE, CFCR etc. Already we're into a very large number of dimensions which, most likely, would require a monte carlo-based technique to explore efficiently.

I am not actually sure whether this would work best as spaces, or as a single config file fed to a group of tasks that know what to do with it.

**Comment by jchesterpivotal** [comment]
Another conceptual dimension is dependency versions. `Gemfile`s, `project.json`s, `pom.xml`s etc tend to provide exact versions or version ranges. Keeping those versions up to date is typically time-consuming, because the pace of upstream releases is very quick and grows approximately linearly with each dependency I add to my project. 

I can of course run something like `bundler update`, but that upgrades everything at once. When everything explodes, as it inevitably will, I have a tedious process of bisecting ahead of me. Many teams, faced with this hassle, simply do not upgrade dependencies, except by whim or warnings. Which is how "dependencies with known vulnerabilities" winds up in the OWASP Top 10.

Now: suppose I had a Concourse resource that can emit versions for entries in a `Gemfile` (by consulting some service, say). Then I want my regular pipeline to run for that new version, and commit the upgrade if it passes.

This is very much like a PR: a change is contributed from outside master. The dimension is *defined* but not *static*. So if I get a space per-version, per-dependency, then I am on my way to bragging in a blog post about having hard-pinned dependencies without getting pins & needles.

**Comment by ringods** [comment]
@jchesterpivotal I'm building a product that does that exactly! Feel free to reach out to me. My Twitter handle is the same as my Github handle. ;-)

**Comment by jchesterpivotal** [comment]
Happy to learn more -- best way to reach me is email (see my profile).

**Comment by vito** [comment]
I'm going to close this out for now - I believe the new RFC process would be a better way to go about exploratory discussions like this. I'm thinking about opening one for "Spaces" after 5.x is out - tangentially related to concourse/rfcs#1 but more focused on the pipeline design aspect.
