### ISSUE TITLE
Error not descriptive enough for when a task cannot be found at the path you've provided

### ISSUE THREAD

**Issue by timrchavez** [concourse/concourse#1775]
# Bug Report
You will get an error like "unknown artifact source: ci" if you specify a relative path to a task yaml file but forget a path component. Can we maybe get a more descriptive error like "could not find task at path: <path>"?

The following can also be handy:

* Concourse version: 3.5
* Deployment type (BOSH/Docker/binary): N/A
* Infrastructure/IaaS: VMs
* Browser (if applicable): Chrome
* Did this used to work? N/A

**Comment by Aid19801** [comment]
Thanks for flagging, Tim. I'm very new to CI/setup and this error left me clueless. It was only because you mentioned task path's that i decided to try messing with the `./` i had at the beginning of my path. Now it works.

**Comment by connormckelvey** [comment]
Im still lost at what to do here. What do you mean a path component @timrchavez?

**Comment by ddadlani** [comment]
For anyone that searches for this error in the future, `unknown artifact source` refers to the resource containing the task config file. The task config file path should be prefixed with the resource name as the source path so that Concourse can locate the task config file. As of now, we have edited the error message to say `unknown artifact source: <source> in task config file path <given_path>` to make the error clearer to the user.

This error only occurs if the source path is invalid. If the source path is not present, or if the task config path is incorrect, other errors are surfaced (see https://github.com/concourse/concourse/blob/bfa45ef7eb9d7b09a47acd67f0254910c2559341/atc/exec/task_config_source.go#L94 for more info)

**Comment by daniellavoie** [comment]
I also want to share an experience that might help others in the future who encounter this error.

I've been scratching my head for two hours trying to understand why I had an `unknown artifact source`. Turns out my task was declared in an `aggregate` by mistake and collocated with the resource that it needed. Joys of yml indentation :)
