### ISSUE TITLE
Clean up noisy 'failed-to-transition' log during volume GC

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#1780]
# Bug Report

```
Nov 03 20:09:38 somewhere.io docker[3779]: {"timestamp":"1509739778.442883492","source":"atc","message":"atc.volume-collector.run.orphaned-volumes.mark-created-as-destroying.failed-to-transition","log_level":2,"data":{"error":"volume cannot be destroyed as children are present","session":"26.14766.1.3","volume":"480df3bf-97f8-4b3b-6b15-464eea436eb5","worker":"primaryworker"}}
```

The work dir is btrfs based.

The following can also be handy:

* Concourse version: 3.6.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work? yes

**Comment by william-tran** [comment]
Also seeing this on our 3.8.0 k8s deployment 
```
{"timestamp":"1513025322.749217510","source":"atc","message":"atc.volume-collector.run.orphaned-volumes.mark-created-as-destroying.failed-to-transition","log_level":2,"data":{"error":"volume cannot be destroyed as children are present","session":"64.436.1.27","volume":"0d000b92-4edf-488e-67c6-c58f6d3dd6c3","worker":"concourse-worker-2"}}
```

**Comment by pn-santos** [comment]
We're seeing several of these logs on a constant basis... is this something we should be worried about?

All the volumes show up with type `unknown` and `n/a` identifier when listed with `fly volumes`

Could this be a consequence of running docker inside a concourse task?

**Comment by jorymorrison** [comment]
@pn-santos We are experiencing this issue as well. 1 of 2 concourse web instances is in a  persistently failing state. We also have several unknown and n/a volumes. We are thinking of manually deleting volumes and re-deploying concourse with the desired number of web instances.

**Comment by xtremerui** [comment]
@william-tran @pn-santos what version of concourse are you guys running on right now? If concourse have updated are you still seeing the same log? Since it is been a while just want to make sure. Thank you!

**Comment by william-tran** [comment]
@xtremerui we're on 3.9 and get log messages like https://github.com/concourse/concourse/issues/1780#issuecomment-350853575 every 30 seconds. Let you know once we upgrade.

**Comment by pn-santos** [comment]
@xtremerui we are running 3.12.0 and still getting a bunch of these messages every 30s too.

**Comment by pn-santos** [comment]
Any update on this? These logs make the `error` level log very noisy... (still seeing it with 3.14.1)

**Comment by vito** [comment]
We could probably silence the logs or make the GC smarter to avoid trying to delete these volumes in the first place; even if we silence our log, people will still complain about/notice Postgres logging failed queries.

@topherbullock I'm gonna toss this in to Runtime instead of Operations.

**Comment by iuriaranda** [comment]
We're also seeing this. We didn't notice it until yesterday, when one of the workers ran out of disk space. We're running 4 workers at the moment, and we're seeing a lot of `"volume cannot be destroyed as children are present"` errors in the logs referencing all of them.

We've tried stopping the worker process on one of the nodes and removing all the volumes manually, but we got this:
```
/opt/concourse/volume/live
rm -rf 04eeb3d5-562a-4e2c-7440-b1b2c1182f4c
rm: cannot remove '04eeb3d5-562a-4e2c-7440-b1b2c1182f4c/volume': Operation not permitted
```
Not sure if that's expected or not, although it looks odd. So we ended up recycling that node. The problem is that all the workers are slowly and consistently getting out of free disk space over the time.

Also worth mentioning, although not sure if it's related or not, the database server is also getting out of disk space over the time. And it only started happening since around one week ago. Here's the graph for the `Free storage space` metric in RDS:

![capture](https://user-images.githubusercontent.com/510809/45078950-8c2a7600-b0f1-11e8-9cdc-0897f6c12b3e.PNG)

Some more info that can be useful:

- Running Concourse version 3.14.1
- Workers are standalone EC2 instances (`c5.large`)
- Each worker has a 100GB `gp2` EBS disk for the Concourse working directory, formatted with `btrfs`
- The `web` node is running in a container in ECS

**Comment by vito** [comment]
@au-hao The issue here is just noisy logs, it should have no impact on actual scheduling. We could fix it ourselves but it's pretty low priority - a PR would be very welcome! 🙂

**Comment by vito** [comment]
@au-hao As far as I can tell that sounds normal - there should be a 1:1 correlation to the logs, and whenever the thing keeping them alive (i.e. a build) finishes they should be GCed and the logs will also cease (for that handle anyway).

**Comment by vito** [comment]
@ddadlani @kcmannem Dragging this to top of the backlog as it keeps misleading people and causing noise in actual bug reports.
