### ISSUE TITLE
Make web UI show task duration

### ISSUE THREAD

**Issue by JohannesRudolph** [concourse/concourse#1788]
# Feature Request

## What challenge are you facing?

Build performance is an important goal for us to keep developer productivity high. We'd like to track build performance to identify slow jobs / tasks in our pipeline. We're already using timeouts to discipline the team to maintain fast builds.

Jobs already have start/end times and duration displayed in the web ui, we'd like to have the same for tasks. 

## A Modest Proposal

Make the UI display task duration for finished tasks in the web ui. Without special support from the backend, the UI could just use the first and last event timestamp to calculate this data. Proper backend support may be more helpful though. 

(originally mentioned in https://github.com/concourse/atc/pull/219#issuecomment-342239963)

**Comment by marco-m** [comment]
I think this is a very needed feature. Not only for the reasons pointed out by @JohannesRudolph, also to help troubleshooting when something is going bizarrely slow.

**Comment by Lindsayauchin** [comment]
We could add it inline with the green chackmark on the task. 

Like so:
![Screen Shot 2019-03-08 at 3 16 45 PM](https://user-images.githubusercontent.com/27746614/54053427-36747a80-41b5-11e9-82ee-002298249278.png)

![Screen Shot 2019-03-08 at 3 16 41 PM](https://user-images.githubusercontent.com/27746614/54053434-396f6b00-41b5-11e9-8268-47bc11a0ac3d.png)

**Comment by marco-m** [comment]
Another possibility would be to make it ever shorter, something like:

                                                                          [1m 06s]

Why ? because also resources are containers, and can take a lot of time to complete (for various reasons). If we follow this reasoning, then each "item" in the web page above, no matter if task or resource, could have on the right its duration.

If we follow this reasoning, then maybe from an implementation point of view it is simpler to do it incrementally, first with the tasks and in a second moment with the resources.

**Comment by pivotal-jamie-klassen** [comment]
Fixed by #3579
