### ISSUE TITLE
cache UI assets

### ISSUE THREAD

**Issue by aybabtme** [concourse/concourse#1807]
# Feature Request

## What challenge are you facing?

A lot of time is spent, when opening a page on Concourse, pulling down the same assets again and again (say `elm.min.js`). The assets aren't served from a CDN, so everything ends up being pulled from the application server.

## A Modest Proposal

Use `Content-MD5` headers to avoid pulling down the same asset if their MD5 checksum hasn't changed (server will respond with `HTTP 304 Not Modified`).

* Concourse version: v3.5.0
* Browser (if applicable): Chrome Version 62.0.3202.89 (Official Build) (64-bit)

**Comment by jama-pivotal** [comment]
Sounds like something we can tackle. I'm going to schedule this in our UX backlog. Thanks for the suggestion @aybabtme

**Comment by mhuangpivotal** [comment]
According to https://tools.ietf.org/html/rfc7231#page-92,

>  The Content-MD5 header field has been removed because it was
>  inconsistently implemented with respect to partial responses.

Unless I'm misunderstanding the problem, currently ATC sets `Cache-Control: max-age=31536000` (one year) for all public assets, so the browser should not be pulling down the same assets again and again.

We are going to make some performance tweaks in #1729.

**Comment by jtarchie** [comment]
I see the the assets being cached effectively from Chrome. It shows that they are being loaded from memory cache, because of the `Cache-Control` header.

<img width="1171" alt="screen shot 2017-11-17 at 4 16 50 pm" src="https://user-images.githubusercontent.com/75184/32973071-cd4abaa2-cbb2-11e7-9c89-04d21f8676fa.png">

As for the `Content-MD5`, I believe it has been replaced in favor of `E-Tag`, right?

@aybabtme, are you able to show where the cache miss is occurring?
