### ISSUE TITLE
Fly errors when trying to destroy a specific pipeline

### ISSUE THREAD

**Issue by ljfranklin** [concourse/concourse#182]
Fly is unable to delete one of our pipelines, although other pipelines can be destroyed successfully. Output from fly:
```
fly -t concourse destroy-pipeline bad-pipeline
!!! this will remove all data for pipeline `bad-pipeline`

are you sure? (y/n): y
2015/10/24 13:13:20 failed to get config: EOF <nil>
```

Just looking for a workaround (e.g. run this SQL query) to get rid of this pipeline. Thanks!

**Comment by vito** [comment]
Assuming you were eventually able to get rid of this; this is due to a slow synchronous delete, which should at least finish in the background, as long as the pipeline's paused while you're deleting it.

I've tagged this with a story we have to fix the root cause (either async delete or soft delete or make it faster somehow).
