### ISSUE TITLE
Keyboard shortcut to bring up help doesn't work if build has no history

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1824]
The keyboard shortcut to bring up the help tips on the build page does not trigger if the job has no build history.

![screen shot 2017-11-20 at 11 05 05 am](https://user-images.githubusercontent.com/19274230/33028023-b0fb34a8-cde2-11e7-95f0-a97e8b05c39e.png)

**Steps to Reproduce**
1. Set a fresh pipeline
2. Click on a job
3. Don't trigger anything
4. Type `?` to bring up the keyboard help

**Expected**
Should bring up the help  menu with all the keyboard shortcuts

**Actual**
Nothing happens

Repro'ed on Chrome, so its not related to #1759

**Comment by mhuangpivotal** [comment]
@jama-pivotal The keyboard short doesn't work here because it is the `builds` page (/teams/:team_name/pipelines/:pipeline_name/jobs/:job_name), which normally looks like this:

<img width="1280" alt="screen shot 2017-11-22 at 1 53 10 pm" src="https://user-images.githubusercontent.com/1919762/33144879-8f612720-cf8c-11e7-89d8-da638c2136c4.png">

Do you want to port the build page shortcuts to this page? The `previous/next build` shortcuts probably don't make sense here.

**Comment by jama-pivotal** [comment]
Cowardly avoiding it then. The issue here is that when tehre is no build history we go to the builds page. Since it doesnt make sense to have the shortcuts on there anyways, this is a non-issue brought up by me mis-understanding the page that I landed on
