### ISSUE TITLE
Downloads Page Should Include Preferred PostgreSQL BOSH Release Version

### ISSUE THREAD

**Issue by nebhale** [concourse/concourse#1860]
Currently the [downloads page](https://concourse.ci/downloads.html) includes the preferred (supported?) versions of the BOSH releases for Concourse and Garden runC.  It should also include the version of the PostgreSQL BOSH release since it's now a required dependency.

**Comment by vito** [comment]
This is something I'm monitoring. I'm not sure if we'll do it.

Where Garden-runC is definitely an integration point, Postgres is more of an assumption. There's not really release-to-release compatibility, and we've only changed the minimum version of Postgres we require once since the beginning of the project. We should just be sure to document that somewhere (we currently do on the binaries page, but not BOSH).

I don't necessarily think we need to dictate use of a particular version of a particular release. In fact, I'd rather leave that decision up to the user. If a user doesn't care about CVEs there's no real point in having them continuously upgrade their postgres. That's all our CI would be doing. The upstream release has pretty [well-documented upgrade process](https://github.com/cloudfoundry/postgres-release#upgrading) that should probably be considered each time.

**Comment by vito** [comment]
In fact, as we move more towards concourse-deployment, we might just start leaving it all up to that repo. The Garden-runC version even only matters to those using BOSH.

**Comment by nebhale** [comment]
Good enough for me.  I'd just prefer it to be consistent and automated.  As it stands now between this and #1861, it's unclear what version of Postgres you've tested against and would constitute valid bug reports.

**Comment by vito** [comment]
Sounds good. #1861 is done now, so I'm going to close this.

Thanks!
