### ISSUE TITLE
Slash in job name only allows job to be run once. Ever.

### ISSUE THREAD

**Issue by track0x1** [concourse/concourse#1892]
# Bug Report

If you have a slash `/` in a job name, it will break concourse. The job will only be able to be triggered manually once. After it runs, you will have to destroy the pipeline and recreate it if you want it to run again. The fix is to not put a slash in the job name.

Possible solution? if a slash is present, it should be encoded so the URL to the build reads `http://concourse.../pipelines/pipelineName/jobs/build%2fship/builds/1` instead of `http://concourse.../pipelines/pipelineName/jobs/build/ship/builds/1`

**Comment by mhuangpivotal** [comment]
When a job name contains `/`, this is what the build API returns:

```json
···
"job_name":"some/job",
"url":"/teams/main/pipelines/test/jobs/some%2Fjob/builds/1",
···
```

 Note the job name is in decoded form and the URL is in encoded form.

The web uses the job name as the job's display name and the URL as the link. This works in most cases, but it fails when it constructs URLs from the job name (e.g. the job url will be constructed as `/teams/main/pipelines/test/jobs/some/job`).

Potential fixes:
- Return `job_name` in encoded form. This will make URL constructions work, but we'll need to decode the name everywhere we display it
- Encode the job name everywhere we construct URLs

**Comment by aeijdenberg** [comment]
One thing I learned recently, is that unlike parameters which can always be safely escaped in a query string, path elements, as far as I can tell, cannot (at least not reliably).

For example, at first glance one might think that escaping with `some%2Fjob` would do the trick (and it certainly would, when using within a query string value), however when used in a path, reverse proxies may undo this for you, e.g. `gorouter` certainly does, I believe that behavior stems from the behavior of [`net/url` line 617](https://golang.org/src/net/url/url.go).

Apache by default also undoes this for you:
<https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes>

I believe nginx also does by default as part of normalization, although I'm unable to confirm:
<https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass>

There's more interesting discussion here: <https://stackoverflow.com/questions/1957115/is-a-slash-equivalent-to-an-encoded-slash-2f-in-the-path-portion-of-a>

(It somewhat rocked my world to learn this, by the way, as it means that in general any automation that passes values to a REST API needs to whitelist, rather than simply escape, values sent to them, consider for example a value such as `../../../some/other/rest/api/call` as a value, which some reverse proxies will normalize before making the proxy call to the app)

I'm unable to find a clear answer in RFCs as to what the correct behaviour should be - in any case - it seems dangerous to rely on this behavior working - I suspect many Concourses live behind various reverse proxies, which often are used to terminate TLS.

Not exactly sure what the best path forward in this particular case - I don't think returning `job_name` in encoded form is a good option - the API can't know in what context it will be used and thus can't be sure to correctly encode it.

Could we consider any of the following?

- steer away from using user generated IDs as path elements in API calls (e.g. switch to params in query string instead)
- allow a smaller set of allowed characters in job names (and any other IDs affected in the same way)
- use a different encoding mechanism (e.g. hex-encode) that might look ugly, but remove the problem

**Comment by aeijdenberg** [comment]
Related: #1877 and #1906.

**Comment by vito** [comment]
Folding into https://github.com/concourse/concourse/issues/1906
