### ISSUE TITLE
Compacting teams on the dashboard for better space utilization

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1899]
Based on some of the feedback we gotten, we realize that for multi-tenant installations we waste a lot of space with teams that only have one or two pipelines: 

![screen shot 2017-12-13 at 4 05 09 pm](https://user-images.githubusercontent.com/19274230/33962451-942b1254-e01f-11e7-88e0-fea0bb1287cc.png)

We should visually group pipelines by teams and "compact" them so we can better utilize the empty space

P.S. this might break sticky header...oh well?

/cc @Lindsayauchin

**Comment by sampeinado** [comment]
# Feature Request

## What challenge are you facing?

Many Concourse users choose to display their pipelines and pipeline dashboards on large TV monitors. It is important that such an "information radiator" be able to show as many pipelines as possible since a user will likely be unable to scroll through their pipelines if they are on a monitor. The goal is for the user to be able to glance at the TV monitor and know immediately if there is an issue with any of their pipelines. 

## A Modest Proposal

Lindsay and I have created the below "presentation mode" view that will display 130+ pipelines in a single 1920x1080 viewport. Pipelines are represented by rectangular cards with a strip of color on the left side that shows the current status. To avoid the need to scroll, the cards are small and contain less detail than cards in the existing beta dashboard view. The cards of pipelines which are failing will be entirely red and will radiate a lower opacity red as well. Font size has been enlarged for reading at a distance.

![high density proposal](https://user-images.githubusercontent.com/35495560/35520908-6377f44c-04e6-11e8-9e8d-c886d4c3536f.png)

We arrived at this solution by considering various layouts that would allow us to increase information density. After several rounds of feedback from Concourse users inside Pivotal, we came to the conclusion that rearranging the view in this way would not be too confusing and might make life easier for operators and engineers who monitor multiple teams' pipelines.

**Comment by astrieanna** [comment]
Is the old beta dashboard going to just be dropped entirely? It's really great for single-team CI displays, and I'd be sad to lose being able to see what part of the pipeline is broken at a glance.

**Comment by jama-pivotal** [comment]
@astrieanna NOPE. This is our "high density view" improvement of the existing dashboard. If you look in the status bar right beside the "pending" hint you'll see a toggle for "High Density". The idea would be to show the current dashboard by default, and if you flip the switch you get dumped into this new view for high density TV view-age.  Hope that makes sense

**Comment by jama-pivotal** [comment]
We've implemented the first pass of the designs, which you can check out here: https://ci.concourse.ci/beta/dashboard/hd  I'm going to close the issue for now, but we definitely want to keep tweaking it. As usual, this feature is gonna be rolled under beta. We'll be keeping an eye out for:

- how the column wrapping performs with different team sizes and pipelines
- does the team label look weird to you?
- legibility of team names, pipeline names and pipeline status
