### ISSUE TITLE
Concourse should have a resource marketplace. It should be called "duty free"

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#191]
A place to discover and publish concourse resources, perhaps located at `resources.concourse.ci`

**Comment by zachgersh** [comment]
This is a great name.

**Comment by jchesterpivotal** [comment]
I see this was tagged "who-cares" in Tracker.

Let the record show:

Me. I care.

**Comment by timlombardo** [comment]
+1

**Comment by vito** [comment]
@jchesterpivotal probably from when i bulk labelled all of rob's stories as "who-cares". fixed. ;)

I'd like to do this without needing people to sign up for an account, similar to how Elm's package management works.

* Entrants to the marketplace are just done via PR to a canonical repo. If we go with this, be careful about the structure; we don't want merge conflicts if two people submit independent resources. Maybe each resource gets its own subdirectory?
* We should think about explicit versioning of resources, and how people are expected to consume them in a stable way. Maybe the metadata to store in the subdirectory is a docker URI string pointing at a fixed digest for each version?
* Related, we should think about how our core resources fit into this scheme, and whether we should change our ways to provide for a better model for external contributors.
* As much information as possible should be drawn from the upstream repo. This way we're not constantly managing PRs to our central repo.

Open questions:

* This is pretty coupled to GitHub, but I think that's a reasonable tradeoff.
* How to manage versions being published? What kind of auditing should be in place?
* How easy would it be for a mischievous contributor to sneak a resource into someone's CI that does bad things with their credentials? Related to auditing, but also just how autonomous is this once a resource is registered with the marketplace, and what kind of information is exposed to individual resources. Thankfully, not much (only the resource's individual config).

**Comment by xoebus** [comment]
@vito To make sure that the contents of the resource image match what is claimed we need to see the source that generated the resource image. I wonder if there's some way that we could accept PRs of `task.yml`s and Dockerfiles to allow us to build their resource image.

**Comment by thewoolleyman** [comment]
+1

**Comment by thewoolleyman** [comment]
What about reusable Jobs, in addition to resources?  We have implemented support for automatically building arbitrary branches, which is implemented as both a reusable resource and a reusable job:

https://github.com/pivotaltracker/git-branches-resource
https://github.com/pivotaltracker/concourse-branch-manager

**Comment by xoebus** [comment]
@thewoolleyman We've thought about that before and it's something that we would like to have (along with having a full search to find these things). Instead of sharing at the job level we would allow the sharing of reusable pipelines. Task parameters and the rudimentary templating in Fly allow for simple generic pipelines to be shared. We have [a few generic pipelines of our own][redeploy-pipeline] that we would like to share.

[redeploy-pipeline]: https://github.com/concourse/concourse/blob/master/ci/pipelines/concourse-redeploy.yml

@vito I had a look at how the Elm packaging works. I like how lightweight it is. I think they can get away with such a small amount of infrastructure because you consume the source code of Elm libraries directly. This let's them just download the source code from the releases section once a commit is tagged. Unfortunately we need a Docker image and even though resource images can be small they're still 2 orders of magnitude too big to commit into Git.

As far as I can see there are two things we could do in order to have a repository of Docker images.

1. We store the registry, name, and digest which lets us fetch the exact image that the resource maintainer intended.

2. We store the Docker image itself. We could make an organization on DockerHub that we would hand out credentials for to resource creators. I think we can use the built in [Teams and Organizations][docker-teams] for DockerHub to allow this. Each resource owner would only be allowed to push to their own image. If we didn't want to give out credentials then we would need to build the images ourself. The resource maintainer would give us a `task.yml` for building their resource and we would then watch their repository for a new Git tag. When a new tag is published we would build their image and push it under the name of the tag.

[docker-teams]: https://docs.docker.com/docker-hub/orgs/

I think I prefer option 1 as it doesn't tie us to Docker. If another image format takes over then all we need to do is add `type: docker` to the package files and then allow different types. Option 2 is really tightly bound to Docker.

Something else that I'm very worried about is image integrity. A popular resource is a great attack vector into a lot of CI systems. I'm struggling to come up with a good way to mitigate this. I think having the changes to the resource repository require signing with a GPG key might be a good way to go. RubyGems and Git support this so if we went with the Git backed model or a service backed model then we have an example for both. This does add another barrier of entry to publishing a resource but I think it's really important that people can trust these images.

**Comment by xoebus** [comment]
Also, :+1: on having the documentation be grabbed from a standard format in the README.

**Comment by zachgersh** [comment]
Really glad the discussion has picked up on this issue!

I think the metadata / install script hosting model has worked well for a
lot of package managers, didn't know elm was doing this but homebrew has
worked this way for a long time. It probably is the most viable solution -
as long as a decent specification is provided for what the metadata parts
look like.

But...advocating for the docker solution - wouldn't a private registry that
is just for concourse resources get you 90% of the way there? Auth would be
one of the questions you would need to answer but at least you can use the
images as they are currently shipped. As much as we "don't want to tie
ourselves to docker" it doesn't seem like it will be going anywhere for
awhile and we can host most of the tooling ourselves.

**Comment by xoebus** [comment]
I don't want to have to maintain and keep up a Docker registry that more than just the Concourse team uses.

**Comment by vito** [comment]
@xoebus I'm leaning towards option 1, with the addition that we should consume them as GItHub releases. That seems like it could be a good way to delegate all the release authoring and publishing to an external source (plus changelogs, etc).

The artifacts in the releases could either be tarballs or metadata pointing to Docker images.

I'm not sure how this affects the image signing thoughts, aside from wondering whether GitHub releases fall under enough security scrutiny for something as critical as these images.

**Comment by thewoolleyman** [comment]
Signing is a tricky issue.  It's complex, and places a burden on contributors and Concourse itself.

There's also a need to recognize different classes of users.  Some casual users or contributors don't care about the overhead of signed package security (eg Business User, Concerned Developer, and Casual Developer from the last link below).  You can choose to care about accommodating the less concerned user, or not, but this will affect the ease of contributions.

Here's some relevant links from the RubyGems case:

* http://guides.rubygems.org/security/
* https://github.com/rubygems-trust/rubygems.org/wiki/_pages
* https://github.com/rubygems-trust/rubygems.org/wiki/Getting-up-to-speed

I like RubyGems' model of different trust levels.  If you built that support in from the beginning, then the initial minimal viable implementation could only support "no trust policy" (forcing users to be explicit about this so they are clear they are taking a risk), with a placeholder to add support for higher trust policies in future iterations.

**Comment by drnic** [comment]
The entire lifecycle of creating and testing, then publishing and sharing resources is super important. It is a huge success factor for Jenkins imo

**Comment by vito** [comment]
Making a 180 on what I said earlier; the more I think about it the less I like the idea of people publishing tarballs or Docker image strings. There's no way to prove that it came from trusted source code and doesn't do something malicious.

So, thinking about option 2 a bit more now. A bit concerned that Docker changing their pricing scheme to anything but "unlimited free public images" could screw us over but maybe that's just being paranoid. Also ideally if we do end up building and publishing the images ourselves, the images would still clearly owned by the original author. It'd suck if everything had to fall under the `concourse/` namespace. OTOH it would kind of force a flattening of resource implementations (only one `git-resource` could exist), which could be better in the grand scheme of things.

Haven't looked at the Rubygems stuff yet. Will once I get the chance.

**Comment by zachgersh** [comment]
@vito - Isn't that concerns over pricing solved by just hosting our own registry? Maybe I am discounting how much maintenance time would be required to keep the registry rolling along? I also am uncertain how third party authentication would go.

**Comment by xoebus** [comment]
Hosting our own would probably cost a similar amount and then also incur the cost of having to run and support it.

**Comment by xoebus** [comment]
I don't want to be carrying a pager.

**Comment by thewoolleyman** [comment]
> It'd suck if everything had to fall under the concourse/ namespace. OTOH it would kind of force a flattening of resource implementations (only one git-resource could exist), which could be better in the grand scheme of things.

"awesome-git-resource" in 3... 2... 1...

But seriously, innovation is good.  Bazaar, not Cathedral.

-- Chad

**Comment by jchesterpivotal** [comment]
Also worth talking to the buildpacks team, including @jtarchie. Buildpacks have some familarity with a range of different packaging systems and can probably comment on what rules (bundler) and what drools (npm).

For myself, my preference is that I can bring in a resource (or job, per @thewoolleyman's suggestion) in with a version tag in my `pipeline.yml`. I am not firmly decided on whether I want it to be downloaded from dockerhub or github. The former would definitely require some independent way to check a hash or signature.

For me the goal is that I require the dependency and then give it no further thought, including during reproduced builds. If I check out an old version of my code, referring to a previous version of a resource, that historical version is checked out and used.

**Comment by thewoolleyman** [comment]
Also, on the topic of versioning, you also have to consider dependencies.  E.g. if there's dependencies of a given version of a job on a given version of a resource's get/put interface.

[Semantic versioning](http://semver.org/)?

[Schema Versioning](http://snowplowanalytics.com/blog/2014/05/13/introducing-schemaver-for-semantic-versioning-of-schemas/)?

As @jchesterpivotal indicated, we definitely don't want to repeat the mistakes of others like NPM: https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-dependency-hell

**Comment by jadekler** [comment]
+1 for this type of thing

**Comment by muv** [comment]
Please call it **repository** and not **marketplace**.

If I assume correctly, the goal of this issue is to introduce **package management** and not a platform to _sell_ addons.

The words "marketplace" and "store" are used extensively by big companies (perhaps intentionally?) to establish an assotiation with physical store and prepare the user on the sub-conscious level to pay money.

Please do not join that tradition.

**Comment by topherbullock** [comment]
This issue hasn't been updated in a while and seems to have gone stale. Also @vito opened a new issue to collect some thoughts here: https://github.com/concourse/design-notes/issues/1

Closing this, but lets keep "duty free" in our back-pockets as a name 😄
