### ISSUE TITLE
Lengthy task output renders extremely slowly

### ISSUE THREAD

**Issue by loktar** [concourse/concourse#1912]
We've noticed that viewing the output for tasks with a lot of logging has become extremely slow. We have a task that outputs ~25k lines and it takes almost 2 minutes to render the logs on a pretty decent machine. This appears to be mostly time spent on the frontend rendering the text.

For comparison, a build with ~2.5k lines takes 2 seconds to render.

It's not so great to have to wait for 2 minutes to see why your build failed, all the while hoping and praying that your browser tab doesn't crash.

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Browser (if applicable): Chrome, macOS
* Did this used to work? Not 100% sure, but in nearly 2 years of using Concourse this is the first time I've noticed this big of a delay in rendering task output.

**Comment by pivotal-mike** [comment]
@jama-pivotal  Seeing this as well with the GPDB deployments after upgrading to 3.8.  May have something to do the large job output + timestamping

**Comment by elasticdog** [comment]
I can't link to the Slack conversation I had due to how old it was, but I do believe this issue was confirmed to be caused by the timestamping feature when rendering large build output. Some improvements were expected with some upstream Elm changes as well, but I don't know the current status of things.

**Comment by jtarchie** [comment]
Unfortunately, upstream `elm` happens slowly. I did look into a patch, but had a hard time proving I had something *faster/better*. I'll see if I can revisit it.

I don't know if that fix would help the timestamp issue though. At some point there could just be too much going on in browser window, right?

**Comment by elasticdog** [comment]
If the performance can't be fixed directly, maybe a boolean flag could be added so the timestamps could be disabled on a per-job basis (or just the anchor link generation on the timestamps, if that's the real culprit)?

**Comment by hsyuan** [comment]
Agree with @elasticdog

**Comment by kdvolder** [comment]
@jtarchie I figured you might say that. Perhaps consider disabling the timestamps by default then, if you can't implement it to work reliably with timestamps. So, people with 'small builds' can opt in to timestamps. That way it at least works consistently and reliably for everyone without fiddling with special flags.

**Comment by kdvolder** [comment]
Maybe another option could be to have a button or checkbox in the web UI that allows enabling timestamps display. Have it disabled by default. (And maybe store the choice in a cooky).

**Comment by vito** [comment]
Let's not start with just removing/toggling the feature; we haven't even investigated the source of the slowdown yet, and it may be something really simple. If we make it a toggle so quickly that'll just paper over the root of the problem.

When we tackle this, let's make sure to have a concrete example to target (e.g. 10k lines should take X seconds to render). Otherwise this'll be a continuous wild goose chase. We should have a test in our UI suite ensuring this doesn't regress again.

**Comment by metatype** [comment]
Any updates on this issue?  One of our teams is unable to view the build logs at all due to the slow down (115k lines of output will do that).

**Comment by jama-pivotal** [comment]
@metatype team picked up this issue to investigate this week!

**Comment by jmelchio** [comment]
@mhuangpivotal and I made some changes to make the data load faster but for rendering we've not found much in the way of improvements.

For the load we tested 100K log lines in a step;  before the the changes this takes 27s and 2s after the changes on our machine.

**Comment by metatype** [comment]
Sounds like a great improvement!  As a data point, our render times for 115k lines of build output are on the order of minutes.

**Comment by kdvolder** [comment]
>  but for rendering we've not found much in the way of improvements.

Perhaps you don't need to render all of the lines? 100K lines certainly do not fit onto my screen so I can't possibly see them all at once, which means a lot of work is being done for no benefit. Maybe you could think in the direction of limiting what is rendered to an interesting subset which is only rendered 'on demand'. I.e. start by show the end of the log which is visible on the screen only. Render additional lines if/when a user scrolls to other areas in the log.

**Comment by jmelchio** [comment]
@kdvolder the current behavior is that the rendering only happens when you 'click' on the step in question. Once you do, all lines in the step will render and this is where the time is spent. The rendering performance is pretty linear in this case and for most people 100K lines of log in one step will not be the rule and performance will be fine. 
I'm not sure how easy it will be to determine which part of the log within a step is interesting but this is something we can keep in mind if the current improvement is insufficient.

**Comment by kdvolder** [comment]
> I'm not sure how easy it will be to determine which part of the log within a step is interesting

Maybe you misunderstand. I don't mean you implement something 'smart' that tries to guess which part of the log I want to see (bamboo does that and I do not find that very useful as its guess is usually wrong).

What I mean by 'interesting' is merely 'the part of the log visible on the user's screen'. I assume you'd automatically place the scrollbar so that the end of the log is visible and let user scroll up and down using the scrollbar. As I'm scrolling you only really should need to render the part of the log that I can actually see on the screen. This should be only a fraction of the entire log if the log is 100K lines or more. Even a large screen can't display more than a few 100 lines of log. In other words more than 99% of the rendered lines are not visible and really shouldn't need to have been rendered.

I understand... this kind of 'on demand' rendering is probably a bit tricky to implement, compared to just rendering all 100K lines in one go. But, if you don't want to frustrate users with big logs into switching to bamboo or not even bringing their build to concourse in the first place... (I know I won't be bringing my big bamboo builds to concourse precisely for this reason) then maybe you have to byte that bullet.

**Comment by kdvolder** [comment]
> 100K lines of log in one step will not be the rule and performance will be fine.

You may wish it were so, but the number of people participating in this thread belies that point. 

One of the strenghts of concourse is the diversity of workloads it can accomodate elegantly, please don't start making these kinds of assumptions on your users behalf.

**Comment by jmelchio** [comment]
@kdvolder you're right I should not assume things on our users behalf. We can certainly take a look at an option where we limit rendering of logs to what is visible on screen.

**Comment by elasticdog** [comment]
Many Gradle projects have ridiculous amounts of output. For reference, I'm working on a bunch of projects that typically output around ~50,000 lines, and the rendering speed has made viewing builds in the UI completely unusable.

**Comment by elasticdog** [comment]
Was this closed because it is considered resolved?! Isn't the load speed only a portion of the issue, where rendering speed is still the larger problem?

**Comment by jama-pivotal** [comment]
@elasticdog sorry it might look a bit mysterious since I don't think you can see all the labels and projects that we apply on things. We made a small fix to make the page render faster without turning off the timestamps. This should be rolling out in an upcoming release (tentatively 3.9.1). Issue #1543 is still open though, and that's something we'll still be looking into

**Comment by elasticdog** [comment]
@jama-pivotal thanks for the clarification. I'll subscribe to that issue and will report back once the fixes are in (if we're still experiencing slowness).

**Comment by chaoyangnz** [comment]
this issue has been fixed? every time i wait a long time to see the lengthy logs. when the logs are shown, I found I am able to grab the scroll bar and scroll to the bottom. I have to scroll several lines each time. doesn't anyone complain this?!
