### ISSUE TITLE
resource check_every: 10s causes runaway DB load

### ISSUE THREAD

**Issue by william-tran** [concourse/concourse#1928]
# Bug Report

Here's our CPU utilization of an RDS m4.xlarge with the spike and steady increase in load caused by setting `check_every: 10s` on our triggering git resources, about 150 resources in total. We're going to move these all to use webhooks instead, but the increase might be showing an issue with connection cleanup.

We use 3 concourse-webs via k8s helm chart on concourse 3.8.0.

![image](https://user-images.githubusercontent.com/1084441/34487753-b4ef75a0-efa3-11e7-971e-2825fabccd0c.png)

![image](https://user-images.githubusercontent.com/1084441/34487820-f68e4bd0-efa3-11e7-92d9-e28e29bf953b.png)

**Comment by EugenMayer** [comment]
def had the same exp. here, we used the easier way of using far more longer check intervals

**Comment by vito** [comment]
I don't suspect there's much to go on here, to be honest. CPU and db connection sampling are very fuzzy metrics and can be subject to sampling intervals and internal postgres mechanics that could resolve over time.

I'd have to see some concrete evidence on the ATC's side to make this seem like anything more than "more load when requested". :) That's not to say there's nothing to optimize, but I don't see this and think there's a bug involved, and don't know how easy this will be to reproduce.

**Comment by vito** [comment]
Linking to #3678 - I think we'll probably change how `check_every` is implemented. Instead of having that number directly determine the interval that checks are queued, we'll keep the 1 minute interval but instead use `check_every` to determine "has it been `check_every` since the last check?" That way users can't configure overly aggressive durations that hammer the database and workers.

**Comment by xtremerui** [comment]
closing stale issue.
