### ISSUE TITLE
proposal:  $FLY_TARGET environment variable

### ISSUE THREAD

**Issue by tsaleh** [concourse/concourse#1933]
# Feature Request

## What challenge are you facing?

Typing `fly -t aliasname` is tiresome.  Also, I generally separate my work by directories, so it'd be convenient to be able to configure `fly` to target different environments based on where it's run.

## A Modest Proposal

A couple different solutions come to mind:

### Local `.flyrc`:

Have `fly` search upwards from the current directory for the `.flyrc` file, instead of just using `~/.flyrc`. 

If we did that, I could imagine we'd soon find that we need to load _all_ of the `.flyrc` files in between `$PWD` and `/`, combining the results (or some variation of that).  Complicated :-/

Also, this doesn't _quite_ solve my problem...  we'd need to also be able to specify a default target.

### Environment variables for CLI options

Allow environment variables to specify defaults for the CLI flags (`-t` being the most important, here), and leave it as [an exercise for the reader](https://direnv.net/) as to how to manage those variables per directory.

The precedence would be (1) CLI flags, (2) env variables, (3) values in the `~/.flyrc` file.  ie: Specifying a flag would trump any set environment variables, which in turn would trump any values in the `~.flyrc`

### Atom Bomb ☢️ 

Rewrite the flags and config code to use [viper](https://github.com/spf13/viper) so it supports configuration files, flags, and environment variables consistently and seamlessly.

### Which one?

Either solution would help me out.  I lean toward the second, only because it grants more flexibility to the end user.  It's also a tad more idiomatic with current CLI tools.

**Comment by EugenMayer** [comment]
why not just implement the ENV var and then use a dotenv integration? less code and much more could be done?

**Comment by tsaleh** [comment]
Sure, that's option number 2 above.

**Comment by tsaleh** [comment]
Ah, sorry - I misread "dotenv" as "direnv" (https://direnv.net/).  I'm not sure I'd suggest that fly implement dotenv conventions.  I'd personally rather simply see fly support a `FLY_TARGET` environment variable, and leave it to us to set that variable however we see fit.  Personally, I'm more of a fan of direnv than dotenv, simply because direnv doesn't require software to support it - it just works through bash.

**Comment by EugenMayer** [comment]
`bash` is a software, what if your service is started in `sh` because its a alpine based resource or rather more realistic, in `zsh` on a OSX/Linux cli? I think both ways have there dependencies - i see that dotenv is very often adopted, not seeing direnv a lot. 

But well, thats part of a discussion i guess. If i would be in need to set the env var myself, that whole option would become useless to me, typing 

`export FLY_TARGET=mytarget` compared to `fly -t <target>` just does not make it, IMHO

**Comment by marco-m** [comment]
I don't think this proposal is a good idea for the following reason:

the Concourse documentation at http://concourse.ci/fly-login.html states:
```
The -t flag is intentionally stateless and must be explicitly added to each command.
This reduces the risk of accidentally running a command against the wrong environment
when you have multiple targets defined.
```
And I agree with this Concourse philosophy. Explicit is better than implicit and reduces errors.

**Comment by EugenMayer** [comment]
So considering i have a repo `projectA` with a folder `projectA/ci` where all my pipelines are.

Now i have a `projectA/ci/.env` with `FLY_TARGET=projectA` since it is its own team. When i enter projectA/ci to deploy my pipeline and it type

`fly sp configure -c pipeline.yml`

So contextually, i have the right target, always. Even if i am the new in the team, the new devop guy, i cannot screw up.

---

In your case it depends on the devop guy, on the docs, on whoever intructed him and on the home of humans not making mistakes.

And to be honest, the reason why humans make so many mistakes we have automation, which is part of the reason CI tools exist.

**Comment by vito** [comment]
Sorry, but I'm afraid we won't be implementing this. See https://github.com/concourse/fly/pull/157 for prior discussion.

CLIs that change their behavior based on pwd, env, and other invisible things are the bane of my existence. It will cause you to do something disastrous eventually, I guarantee it. The old BOSH CLI had this problem, and I know of at least one occasion where a production deployment was destroyed by an *experienced engineer* because their target was set incorrectly, and all the CLI prompts in the world are powerless against an engineer's muscle memory. The new BOSH CLI is a lot more like `fly`, but still allows you to set `$BOSH_ENVIRONMENT`, which has already bitten me despite it not even being the encouraged way to use it.

New members of the team will have no idea why a command works in one place but not another, or won't realize they've been running against the wrong target. This can result in all kinds of bad things: with `set-pipeline` you could accidentally end up with two prod pipelines running on different targets/teams (hopefully you remember where you ran that command so you can find and kill it when you realize). Or you could accidentally delete prod rather than your local version. Or you could be running `fly execute` all day and not know why it's way slower than usual (if you typically run it against a local Concourse).

The `cf` CLI has a similar problem, and as a result every single command was changed at some point to fully print "you are in space X, organization Y, target Z". Better read it and Ctrl+C quick if it's wrong!

For people new to Concourse, this feature delays a fuller understanding of how things work. For everyone, even experienced users, it points a loaded gun at their feet. Keeping it stateless is simpler, means your shell history is always relevant and fully-specified, and doesn't introduce yet another thing for engineers to worry about. This issue comes up now and then but there's never been a very compelling reason to change it. Lots of people find the statelessness to be a feature, not a bug.

**Comment by chrishiestand** [comment]
I'm in the middle here. I think @vito has a lot of sage wisdom here, but I do appreciate convenience of less typing when my risk profile is small. And I personally only have environment variables/settings change behavior if I'm in a virtual shell environment with my `$PS1` automatically explicitly labelled.

In any case, if you want to give yourself a minor convenience you can always put this in your e.g. `.bashrc` or virtualenvwrapper's `bin/postactivate`:
```bash
alias flyprod='fly -t production'
```

If using a virtual env you should then run this on deactivate:
```bash
unalias flyprod
```

Note that `flyprod` is still an explicit shortcut for the named target, so it is less of a footgun than `fly` would be.
