### ISSUE TITLE
Link hint on cursor for jobs and resources on the pipeline view has stopped working

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#1978]
This is happening in our current dev branch. Previously, on the main pipeline view when you hover your mouse over a resource or build box, the cursor changes from the arrow to the link hand.

Right now in our dev branch that's broken and the cursor actually turns into the "I" text cursor.

**Comment by JohannesRudolph** [comment]
This may well be the cause of the issue we are seeing (unable to click jobs to open link to build page).

**Comment by vito** [comment]
@JohannesRudolph I don't think so; this issue is just a UI thing, shouldn't reflect on any behavior.

@xtremerui Looks like it's a bit *too* indicative now. :) The cursor changes to a pointer pretty far outside the bounds of the actual clickable target, because jobs have padding around them for the running animation. Clicking in this area has no effect, so it shouldn't have the pointer cursor.
