### ISSUE TITLE
binary worker failing to ssh handshake with concourse web

### ISSUE THREAD

**Issue by ashishgoel-ps** [concourse/concourse#2004]
I am using a binary worker on a vm and a remote concourse web & db. Web has SSL configured and ports 443 & 2222 are exposed.

Now, when the worker is started to register itself with the web using the command below:

> **concourse worker --work-dir /opt/concourse/worker --tsa-worker-private-key /opt/keys/worker/worker_key --tsa-public-key /opt/keys/worker/tsa_host_key.pub --tsa-host 1.xxx.xxx.4**

It throws the error below:
> **{"timestamp":"1517803666.098464727","source":"worker","message":"worker.beacon.restarting","log_level":2,"data":{"error":"failed to dial: failed to construct client connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain","session":"4"}}**

This works if SSL is disabled on web. not sure whats missing when ssl is enabled.

**Comment by shashwathi** [comment]
@ashishgoel-ps : Can you provide the version of Concourse ?

**Comment by ashishgoel-ps** [comment]
i got it working. its just the right pair of keys you need on the worker to establish connection to tsa. I am using concourse v3.8.0

**Comment by bencao** [comment]
I got a similar error message, and it turned out to be connectivity issues between worker and web.

I ran web as a container and forgot to expose the 2222 port from the container to the docker host, which resulted in the above handshake failed error.

Please double check those connectivity setups if you encounter similar issues in the future.
