### ISSUE TITLE
cannot find package "github.com/concourse/atc/atccmd"

### ISSUE THREAD

**Issue by alcnsahin** [concourse/concourse#2005]
Hello,

I cloned atc and trying to build but I'm getting following error.

cannot find package "github.com/concourse/atc/atccmd" in any of...

Thank you for your helps.

**Comment by jama-pivotal** [comment]
@alcnsahin do you want tot specifically JUST build the ATC or the concourse project as a whole? Normally we refer folks to our Contributing guide for more details: https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md 

Under **Running Concourse locally** you can use the dev scripts to run only certain components.

Give that a shot and see if that helps. Closing this issue for now since its more of a "help" style issue. Feel free to jump into our OSS slack to ask us questions http://concourse.ci/community.html
