### ISSUE TITLE
`version: every` misses some versions

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#2028]
# Bug Report

`version: every` misses some versions. I have a github-pullrequest-resource that emits the correct versions but every now and then a build is not scheduled for some versions. Newer versions may appear and have tests run for them but some old versions remain buildless.

Disabling the newer versions for which builds have run then causes a build to be immediately scheduled for the version that was previously missed.

* Concourse version: 3.8.0
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP
* Did this used to work? Maybe?

**Comment by vito** [comment]
This is caused by the PR resource re-ordering version history as things like comments are left on pull requests. `version: every` will never go backwards; if there is a more recent version that builds have been scheduled for, that's the new starting point.

The current work-around is to leave comments on PRs to "bump" them. The long-term fix is to have a new spaces-aware (#1707) flow for pull requests. The current implementation hacks around resource version emitting in an attempt to achieve spatial versioning, and this is one of the big pitfalls.
