### ISSUE TITLE
Is there a way to prevent parallel jobs from getting triggered if they are dependent on the same resource

### ISSUE THREAD

**Issue by SaurabhQA** [concourse/concourse#2071]
Hi there!

JobA and JobB are parallel jobs in the pipeline which get triggered when there is a change in some resource. Other jobs in the pipeline are dependent on previous jobs. I donot want my pipeline to get triggered if any job in pipeline is in-progress. For that I am using pool lock which is working fine except for the parallel jobs. I wanted Job2 to be triggered only when Job1 starts running. 

Is there a way to pause the resource check from the pipeline? Fly supports the pause resource similar functionality can we do inside the pipeline.

Below is the sample pipeline.

resources:
- name: flight-school
  type: pool
  source:
    uri: https://github.com/SaurabhQA/flight-school
    branch: master
    pool: lock
    username: <username>
    password: <password>
- name: runOnConcourse
  type: git
  source:
    uri: https://github.com/SaurabhQA/runOnConcourse
    branch: master
jobs:
- name: job-A 
  plan:
  - get: flight-school
  - get: runOnConcourse 
    trigger: true
  - put: flight-school
    params: {acquire: true}
  - task: tests
    file: flight-school/buildTest.yml
- name: job-B 
  plan:
  - get: flight-school
  - get: runOnConcourse
    trigger: true
  - task: tests
    file: flight-school/buildTest.yml

- name: job-C 
  plan:
  - get: flight-school
  - get: runOnConcourse
    passed: 
    - job-A
    - job-B
    trigger: true
  - task: tests
    file: flight-school/buildTest.yml
- name: job-D 
  plan:
  - get: flight-school
  - get: runOnConcourse
    trigger: true
    passed: [job-C]
  - task: sleep
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sleep
        args: ["60"]
  - put: flight-school
    params: {release: flight-school}

**Comment by shashwathi** [comment]
>  I saw that when Job-C was is progress A and B was not triggered however once Job-C completed again Job-A and Job-B was triggered

It is possible that Job A and Job B are triggered because of new commit to `flight-school` resource. Job A and Job B have `trigger: true` set only on that resource.

> I expected Job-D to be triggered after Job-C completed. 

If there is a new commit on flight school which has passed `Job C` then `Job D` will be triggered. It is possible that the following sequence of events might have occured
- Job A and Job B pass with commit 1234
- Job C is triggered with flight school resource 1234
- New commit is made to flight school with commit sha 1235
- Job A and Job B is queued up(not running cuz of serial group)
- Job A and Job B get triggered before Job D.

> How can I prevent triggering of pipeline when previous Jobs are expected to run?

Consider merging Job C and Job D and use [`on-success`](https://concourse-ci.org/single-page.html#job-on-success) to trigger task of Job D. Looks like you really want Job D to be triggered after C so merge them into one job definition and have 2nd task trigger only if previous one succeeds.

Hope this helps

**Comment by SaurabhQA** [comment]
Thanks! It works 👍
