### ISSUE TITLE
Initial database migration is not atomic in 3.9.1 and can become wedged if interrupted

### ISSUE THREAD

**Issue by hfinucane** [concourse/concourse#2074]
# Bug Report

* Concourse version: 3.9.1 
* Deployment type (BOSH/Docker/binary): binary

This appears to be a regression of #722. As a refresher, my Chef deployment of Concourse is also a torture test of initial migration safety, because it runs 'concourse web', and then pretty rapidly restarts that process. I'm seeing this in my 'integration tests' on fresh systems with a fresh db. On the Concourse side, I get

```
failed to migrate database: Dirty database version 1510262030. Fix and force version.
```

With verbose postgres logs, the problem seems like a straightforward repeat of #722- there are two separate transactions, one to update the schema_migrations table, one to apply the schema migrations, and if the second transaction is interrupted, the database is in an indeterminate state.

```
LOG:  execute <unnamed>: SELECT pg_try_advisory_lock($1)
DETAIL:  parameters: $1 = '6'
LOG:  statement: SELECT version FROM migration_version
ERROR:  relation "migration_version" does not exist at character 21
STATEMENT:  SELECT version FROM migration_version
LOG:  statement: SELECT CURRENT_DATABASE()
LOG:  execute <unnamed>: SELECT COUNT(1) FROM information_schema.tables WHERE table_name = $1 AND table_schema = (SELECT current_schema()) LIMIT 1
DETAIL:  parameters: $1 = 'schema_migrations'
LOG:  statement: CREATE TABLE "schema_migrations" (version bigint not null primary key, dirty boolean not null)
LOG:  execute <unnamed>: SELECT pg_try_advisory_lock($1)
DETAIL:  parameters: $1 = '2019668375'
LOG:  statement: SELECT version, dirty FROM "schema_migrations" LIMIT 1
LOG:  statement: BEGIN
LOG:  statement: TRUNCATE "schema_migrations"
LOG:  execute <unnamed>: INSERT INTO "schema_migrations" (version, dirty) VALUES ($1, $2)
DETAIL:  parameters: $1 = '1510262030', $2 = 't'
LOG:  statement: COMMIT
LOG:  statement: BEGIN;

    CREATE TYPE build_status AS ENUM (
          'pending',
        'started',
        'aborted',

... (omit the concourse schema)

          ALTER TABLE ONLY workers
              ADD CONSTRAINT workers_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;


        COMMIT;

LOG:  could not receive data from client: Connection reset by peer
LOG:  could not receive data from client: Connection reset by peer
LOG:  execute <unnamed>: SELECT pg_try_advisory_lock($1)
DETAIL:  parameters: $1 = '6'
LOG:  statement: SELECT version FROM migration_version
ERROR:  relation "migration_version" does not exist at character 21
STATEMENT:  SELECT version FROM migration_version
LOG:  statement: SELECT CURRENT_DATABASE()
LOG:  execute <unnamed>: SELECT COUNT(1) FROM information_schema.tables WHERE table_name = $1 AND table_schema = (SELECT current_schema()) LIMIT 1
DETAIL:  parameters: $1 = 'schema_migrations'
LOG:  execute <unnamed>: SELECT pg_try_advisory_lock($1)
DETAIL:  parameters: $1 = '2019668375'
LOG:  statement: SELECT version, dirty FROM "schema_migrations" LIMIT 1
LOG:  execute <unnamed>: SELECT pg_advisory_unlock($1)
DETAIL:  parameters: $1 = '2019668375'
LOG:  execute <unnamed>: SELECT pg_advisory_unlock($1)
DETAIL:  parameters: $1 = '6'
LOG:  could not receive data from client: Connection reset by peer
```

**Comment by topherbullock** [comment]
@hfinucane This issue is related to the [migration library we're using](https://github.com/mattes/migrate), and the inability to safely recover from a state where the migrations it is trying to run for us never succeeded. As you observed, there's 3 steps it uses to run each migration. Here's the flow it follows for running migrations:

1. - Set the `schema_migrations` `version` to `<desired-version>` and `dirty` to `true`
2. - Run the contents of the up migration for `<desired-version>`
3. - Set the `schema_migrations` `version` to `<desired-version>` and `dirty` to `false`
4. - Repeat steps 1-3 for each `up` migration to run
5. ???
6. Profit

Our initial thought was "Let's just change it to run 1-3 in a transaction", but there are [reasons for not wanting every migration to run in a transaction](https://github.com/mattes/migrate/issues/13). Since we don't really know whether step 2 (running the migration) or 3 (marking the migration table as clean) failed, the ATC isn't really able to determine what to do about the state being dirty.

One thing which may help you is the ability to upgrade the db to a desired version once, and exit. `concourse web` supports a `--migrate-db-to-version` flag which does just that. You could potentially use that in conjunction with `--supported-db-version` like so : 
`concourse web --migrate-db-to-version $(concourse web --supported-db-version)` 

If you run this once before the aggressive stopping and starting of the `concourse web` service (maybe in the db setup after the initial db is created?), then it will be more resilient to restarts going forward.

**Comment by nbrys** [comment]
We are currently having the same issue after trying an upgrade from 3.9.2 to 3.13.0. We get the following errors in the log: failed to migrate database: Dirty database version 1522178770. Fix and force version.

Any help to get our concourse installation working again is appreciated.

**Comment by ywei2017** [comment]
Any updates on the 3.9.2 to 3.13.0 upgrade. I just got into the exact same error, and am totally at a loss.

**Comment by DRuggeri** [comment]
FWIW, I was able to work past the issue by...
* Adding the postgres release to the ATC box
* Use `psql` and concourse credentials to log into the DB
* Manually run the commands in [migrations](https://github.com/concourse/atc/tree/master/db/migration/migrations)
* Run `UPDATE schema_migrations SET dirty=false`

YMMV, but that's how I recovered from this half state.

**Comment by ddadlani** [comment]
We have moved to a new migration library (#2452) which should provide more information when migrations fail, so we are closing this issue. 

If anyone runs into issues with migrations in the future (from Concourse v4.0.1 onward), please look at the `migrations_history` table for more information on what failed. Please also feel free to open a new issue to discuss the migration failure. Thanks!

**Comment by vito** [comment]
Accepting this! I opened a separate issue for extracting it to a separate library (repo) and some odds and ends: https://github.com/concourse/concourse/issues/2516
