### ISSUE TITLE
Wait for incoming resources earlier in the pipeline before triggering a job [feature request]

### ISSUE THREAD

**Issue by dumbbell** [concourse/concourse#2076]
# Feature Request

## What challenge are you facing?

We have a [pipeline to test all components of RabbitMQ](https://ci.rabbitmq.com/teams/main/pipelines/server-release:v3.8.x?groups=qa%3Abroker). Those components are split into two groups:
* the core components
* the plugins

The first group (`qa:broker`) contains jobs triggered by any core components. When we commit a change to one of them, the new resource enters the pipeline at the very first job in that group.

The second group (`qa:plugins`) contains jobs triggered by any core components, once they passed the first group, or by any plugin. In the case of a new core components, all plugins-related jobs are triggered. In the case of a plugin change, only the job related to that plugin is triggered.

Sometimes, we need to commit a change to all core components and plugins (e.g. when we update `erlang.mk`, the build tool we use). When this happens, this causes a "build storm" because all plugins jobs are started always twice: once for the commit in the plugin, once for the commits in the core components. Many times, they are executed, three or four times, either because changes to multiple core components were detected separately, triggering two runs of the core components jobs, or because a plugin depends on another plugin.

On top of that, we currently have three "copies" of this pipeline: one for our `master` branch, one for each release branch. And sometimes we need to commit a change to all release branches + `master` of all components.

This always cause the infrastructure to fall part because we reach the max number of containers or volumes, or both. We have 6 workers with 250 containers max each. Most of the time, we use about half of that capacity.

The current workaround is to:
1. Pause all three pipelines and all plugin jobs and plugin resources in those pipelines.
2. Publish the commits.
3. Unpause one pipeline: the core components jobs run.
4. Wait for all core components to finish.
5. Gradually unpause plugin resources and jobs.
6. Jobs are still triggered twice, so go over all builds and cancel them.
7. Wait for the second set of builds to finish.
8. Go back to step 5 to unpause more plugins.
9. When the pipeline is running again, go back to step 3 for the next pipeline.

## A Modest Proposal

Instead of limiting the number of parallel builds globally (i.e. accross multiple pipelines), I believe a better solution for us would be to not trigger a particular job if there another resource "earlier" in the pipeline which may retrigger the job.

Here is an example:

```
R1 --> [J1] --> R1 --> [J2] --> R1 --> [J3]
                                R3 --> [  ]
```

If there are new versions of `R1` and `R3`, both `J1` and `J3` will be triggered. Then `J3` will be triggered again after `J1` and `J2` pass. It would be nice to delay the build of `J3` until `R1` goes through `J1` and `J2` or one of them fails. Likewise if `R1` had to go through parallel paths before reaching `J3`.

In the pipeline configuration, this could be a parameter at the job level to indicate if we want that job to run everytime an immediate resource is updated (default) or if we prefer to delay in case there is a incoming new version of an immediate resource somewhere upstream.

* Concourse version: 3.9.1
* Deployment type (BOSH/Docker/binary): BOSH
* Infrastructure/IaaS: GCP

**Comment by dcarwin-pivotal** [comment]
Thanks for filing. Heads up this would be a game-changer for us in release productivity.

**Comment by topherbullock** [comment]
While you've done a good job explaining what you'd like the build scheduler to do in order to satisfy your needs, there are some tricky details missing about how this would work in practice. This is a pretty major change from a build scheduler standpoint, so we'd need to make sure we're making choices which don't break existing behaviour, and don't introduce performance issues.

Two concerns :
**UX** 
How would one expect to specify this in a pipeline? Not all pipelines will have the same "cost" of executing a job with many resource updates. The current behaviour is to schedule a new build when a new version of a resource `passed` with the `trigger` flag set to `true` (https://concourse-ci.org/get-step.html#get-step-trigger) is discovered, so many users will still want this behaviour. The trigger flag could be extended to accept a value of "most-recent" (or something similar), which will wait for pending jobs upstream to finish. One downside of this could be: if the upstream job keeps triggering, the downstream job would take a long time to ever actually get the "latest" version which will eventually satisfy the passed constraints. Also, the current behaviour could still occur, depending on when the check for new versions occurs, so its a synchronization problem if a new version triggers a job upstream _just_ after the downstream job triggers.

**Perfomance** 
This adds a lot more complexity to the version semantics, and how new builds are auto-triggered by passed constraints. Currently a job only cares about direct inputs from its `passed` constraints, but this change would mean the scheduler has to look back at the entire tree structure of the pipeline upstream to see if any running or pending builds are using that resource and have newer versions. A large pipeline with many jobs specifying different "modes" of `trigger` would be exponentially (at best) more expensive than the current query to determine when a build should be scheduled.

**Comment by dumbbell** [comment]
Hi!

About the configuration, I was thinking of a separate attribute because, for the job to be triggered (if that new attribute is set), all input resources should be considered together: "if one of the input resources has a new version incoming, currently 3 jobs away earlier in the pipeline, this job should wait, even if another input resource could also trigger it". That's why I was suggesting a parameter at the job level, not at the input resource level.

The name could be something like `wait_for_new_inputs_from_upstream` or `wait_for_upstream_inputs`. I couldn't come up with something shorter for now :-)

About synchronization, I wouldn't expect Concourse to wait for one of those upstream inputs just in case a new version shows up. If I take my example above, when a new version of `R3` was detected and is about to trigger `J3`, either there is already a new version of `R1` previously detected and the scheduler waits, or `J3` is triggered.

About the performance impact, it's difficult for me to comment on this. I agree this adds complexity but I don't know the current design and I don't know how far away such a feature would be from it. To me, the most difficult part seems to be the handling of a failure upstream: if `J1` or `J2` fail in my example, what to do about `J3` and the new `R3` resource? Perhaps one wants `J3` to be triggered because `R1` won't reach it. In our specific case (the RabbitMQ pipeline) I don't know what I would prefer so I suppose both ways would be fine :-)

**Comment by sbkg0002** [comment]
Is there any news on this? Any workarounds maybe?

**Comment by vito** [comment]
The typical work-around is to just 'snapshot' all the inputs to your pipeline in one place so all the versions pass through together.

This would mean threading resources through jobs via `passed` constraints, so you'd end up with this:

```
R1 --> [J1] --> R1 --> [J2] --> R1 --> [J3]
R3 --> [  ] --> R3 --> [  ] --> R3 --> [  ]
```

The upside is this has pretty intuitive semantics from a pipeline scheduling standpoint. The downside is it means adding resources to jobs that don't really need them.
