### ISSUE TITLE
Adding jitter to resource intervals

### ISSUE THREAD

**Issue by Freakin** [concourse/concourse#2112]
# Feature Request

Add jitter to intervals so they don't execute at the same time

## What challenge are you facing?

I have a set of ~450 pipelines which have git resources with a 12h `check_every` interval to trigger a job on changes (also using webhooks for immediate trigger).  All of these resources check at the ~exact same time, which creates a lot of load on both concourse as well as the internal git server they are calling.

It would be great if the resources with interval based execution had some amount of jitter so they didn't go off at the same time.  If it were percentage based jitter on the interval (in seconds) it would spread things out fairly well.

**Comment by prein** [comment]
I am suffering from the same problem. We have self-hosted docker registry and self hosted git server and the team maintaining both blames the concourse for performance impact on the registry and git. I have reduced the check_every from default 1 min to 15 min but it won't help since all the resource checks load is created at once.

It would be very useful if the check interval was randomized. I think I found corresponding code, in case it helps to link it https://github.com/concourse/concourse/blob/0f5bd8f7b9561d2f57a08f85cbdaabca805b3d04/atc/radar/resource_scanner.go#L403
