### ISSUE TITLE
Error  : docker: error pulling image configuration:

### ISSUE THREAD

**Issue by tiendzbk** [concourse/concourse#2143]
Hi,  sudo docker run --rm -v $(pwd):/app composer/composer install on terminal, and Error : 
Unable to find image 'composer/composer:latest' locally
latest: Pulling from composer/composer
51f5c6a04d83: Pulling fs layer 
3234e782e15b: Pulling fs layer 
6450a2e3df13: Pulling fs layer 
a42226649bd8: Waiting 
d949d6fac6b4: Waiting 
239f4c7193af: Waiting 
b4901d6b46ce: Waiting 
4c58095fbe14: Waiting 
7f4085ad855d: Waiting 
3641c1a77089: Waiting 
6f5a87555c0c: Waiting 
f10483f071cb: Waiting 
6417f8c8cb63: Waiting 
f51e86361b1b: Waiting 
docker: error pulling image configuration: Get https://registry-1.docker.io/v2/composer/composer/blobs/sha256:5afb0951f2a407ce67c32ed7c6fa41f8287f3a35eb85947557fe8de14f1e0343: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: read udp 127.0.0.1:55758->127.0.1.1:53: i/o timeout.
See 'docker run --help'.
What s a pity. Can anybody help me??? thank you very much!

**Comment by marco-m** [comment]
hello, could you please shorten the title and format the contents ? Thanks!

**Comment by jama-pivotal** [comment]
@tiendzbk we're trying to move all "needs-help" or "support" style questions to our forums or our chat application. I'd like to suggest that you cross-post your question to our forums under the Support tag here: https://discuss.concourse-ci.org/c/support

Also, in order to help you better I'd like to suggest that you give a few more details about your problem:

* What version of Concourse are you trying to run?
* What is the system OS that you're running this command on
* What have  you tried to debug the issue?
* Does the computer you're running this on have access to the docker registry (e.g. https://hub.docker.com/explore/) 

Closing this issue for now, looking forward to hearing your response on our forums!
