### ISSUE TITLE
Release notes links are broke

### ISSUE THREAD

**Issue by GaryPWhite** [concourse/concourse#2159]
Still running 3.5, and on my way to upgrade, I clicked in the notes for 3.6, but it says "404 not found" from concourse.org...

seems to me like the links like this:

https://concourse-ci.org/downloads.html#v3.6.0

ought to be like this:

https://concourse-ci.org/download.html#v360

with no "s" on downloads and the "." being eliminated.

Small issue, figured it out with little to no problem. Sorry if this is the wrong forum for this :)

**Comment by jama-pivotal** [comment]
Thanks for reporting @GaryPWhite . That's a good point...with our changeover our downloads page changed and we don't have redirects set up since the Concourse site is a relatively simple static site.

I'm going to go ahead and close this issue and in return I've opened up two issues on our Docs repo:

https://github.com/concourse/docs/issues/50
and
https://github.com/concourse/docs/issues/51
