### ISSUE TITLE
Garden-Windows Worker Support

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2175]
# Feature Request
Moving the drain and registration to `go` binaries should make cross-compilation of the worker job for a windows job a lot easier. Currently [concourse-windows-worker-release](https://github.com/pivotal-cf-experimental/concourse-windows-worker-release) is what we use for Windows workers, which runs `concourse.exe worker` and uses Houdini to allow containerization-less Garden on the worker.

## Challenges
Its probably easiest to support this in BOSH first and add support to the binaries later, so lets just focus on the challenges there.

- We'll need to confirm `Attach`/`Exec` support in Garden Windows; Concourse needs this to be able to run builds and hijack . 
- Baggageclaim support; Baggageclaim is colocated with Garden, and the `worker` job registers the Baggageclaim and Garden servers as a Concourse Worker.  We'll need a Windows job to run Baggageclaim.
- All of the base resources are currently built as Linux container images, so we'll need to think about resource support. Users currently need at least one Linux worker to support the base resource types. Does the same "written in go so we can cross compile" plan work for the base resources?

## A Modest Proposal
A good first step would be to create a `windows-worker` job which can run on Windows instances, basically a copy of [`beacon_ctl.erb`](https://github.com/concourse/concourse/blob/master/jobs/worker/templates/beacon_ctl.erb#L115:54) logic which calls `worker.exe`.  Same goes for [`baggageclaim_ctl`](https://github.com/concourse/concourse/blob/master/jobs/baggageclaim/templates/baggageclaim_ctl.erb), once Baggageclaim supports Windows. 

I think this would be a good start, and implementing resources will still be something to chew on.. It would be less than ideal if we need to create windows containers for every base resource type to support them. 

CC + Thanks to @natalieparellano

**Comment by vito** [comment]
Closing this, but we haven't ported any resources to Windows or really have any idea what that'll look like yet. Let's carve that out as a separate issue in the future.

**Comment by awmartin** [comment]
@vito Is there a new issue tracking a worker based on winc and the new garden stack?

**Comment by vito** [comment]
@awmartin Nope - we don't really have the bandwidth for that but would be really interested to see if it already works to some extent. Theoretically it would just be a matter of using the other BOSH release instead of our houdini job.

**Comment by awmartin** [comment]
@vito Well, the Garden Windows team did its part to fulfill the Garden API contract in particular for this feature, so it'd be a shame to see that work fall to the wayside. Pivotal also sees customer demand for this, particularly for building .NET apps. And I'd love to see if this works already, too. What would need to be true to move this forward at least a little bit? cc: @jama-pivotal

**Comment by vito** [comment]
@awmartin I've been wanting this for months myself, it's just difficult to justify prioritizing it over all the other things that are sorely needed by our users, Pivotal customers included. :( Right now we have pretty big fish to fry (spaces, large-scale operability, RBAC, Kubernetes runtime).

Honestly we're pretty reliant on the community (which includes Pivotal teams) to contribute to the areas they feel passionate about in any way they can. The scope of this project is huge compared to the size of our team - we can't do everything ourselves. I'm happy to provide guidance there.

The first step would be to take `concourse-bosh-deployment`'s manifests and use an ops file like [this](https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/windows-worker.yml) but with the Garden Windows release's job instead of our Houdini job. And then see what happens. It might "just work", or it might take a bit more effort.

I'll ping @topherbullock too and see where this could fit in the Runtime backlog (I mainly stick to Core - see https://project.concourse-ci.org/), but I can't promise anything. It'd be faster to just try it out yourself and open an issue/PR for any changes needed. :)

**Comment by sneal** [comment]
@vito It looks like the strategy you mentioned needs to change as Houdini is directly consumed as part of the Concourse binary now. Concourse also shells out to `gdn` which I'm not sure supports Windows, or at the very least isn't available on the GitHub releases for Windows.

I think the approach would be to have `gdn` support Windows and package that along with the Concourse Windows zip and then modify the Concourse source to use `gdn` for Windows instead of Houdini. Does that sound correct?
