### ISSUE TITLE
Proposal: Change the pan behavior on the pipeline view to be triggered with a keyboard combination

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2192]
# Context
In the early days of concourse, you can click around freely on the pipeline view to pan around the pipeline. We noticed that if you start your click on a click-able object (like a resource or job) then when you release the mouse it would register as a click into the item vs just a pan. This was captured in #947 and we "fixed it" so that if you start a click in a job but move the mouse, you don't get transported in.

Fast forward a few months later and we start seeing reports of unclickable items #1996. At first we found a Chromium issue and fixed that, but we still saw a bunch of problems. We think it has to do with the issue of folks doing mini-mouse movements while clicking which is incredibly annoying and makes it hard to use Concourse naturally

# Proposal
We should change the "pan" behavior so that the user can only engage it while depressing a specific key. This will specifically move the UI into "pan" mode and let us remove the pesky logic of preventing clickthroughs while moving around

Proposal is to require the user to hold down the ~`Spacebar`~ `ctrl` button in order to force the user into Pan mode.

**Comment by xtremerui** [comment]
@jama-pivotal based on the way we implement dragging, the available keys during the `mousedown` event are meta, ctrl, alt and shift refer to [mourse events](https://www.w3schools.com/jsref/obj_mouseevent.asp).

Considering the browser behaviour when pressing above keys and left clicking mouse on a clickable node (job and resource node in our case) listed below, I would suggest using `ctrl` key as the leading key for dragging.

ctrl + click ----> as mouse right click (would become the new dragging combo)
alt + click -----> save as link
meta + click ---> open link in a new tab
shift + click ----> open link in a new window

Comments please?

**Comment by jama-pivotal** [comment]
Let's try using `ctrl` !

**Comment by xtremerui** [comment]
Updated: seems click+ctrl is a tough one to play with as in our code we already stop the listener for this combo. That makes `alt` the next option. Will try `alt` + click for dragging combo.

**Comment by jama-pivotal** [comment]
This has been deployed to our prod environment now and here are some thoughts:

* There's no UI affordance for users to know to even use the `alt` key to pan and zoom around. If we push through with this we would need to do some UI improvements to increase awareness of this change
* `alt` turns out is a crappy key too because it activates the Toolbar hint (File, Edit, Tools, etc.) in Firefox
* @vito has rightly pointed out that since our new Spaces UI will eventually take over, this change might not be that necessary

Suggestion is to revert this change for now @xtremerui so we don't roll this into the next release
