### ISSUE TITLE
communication with container via network from remote host

### ISSUE THREAD

**Issue by ezraroi** [concourse/concourse#2203]
Hi,
we have a use that one of the steps in our pipeline is starting distributed application on remote host via REST API. after this, we run a tests inside the container started by concourse. The problem is that during the test, a component running on the remote host needs to connect to an open port on the container host. 

Looks like this is not possible in the current way concourse is starting the containers.

Is it possible? Any other idea?

**Comment by jama-pivotal** [comment]
@ezraroi not sure if you've already tried, but you might get more of a response if you tried asking in our Discord chat or forums. You can find both links on our community page here: https://concourse-ci.org/community.html 

Closing for now due to staleness. Feel free to re-open if you feel I've made a mistake!
