### ISSUE TITLE
OxygenMask pipelines should be removed after they finish in the "Create and Run New Pipeline" test

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2252]
OxygenMask pipelines should be removed after they finish in the "Create and Run New Pipeline" test.

**Comment by pivotal-nader-ziada** [comment]
This is already being done. This issue was probably inspired by the fact that https://wings.pivotal.io/teams/monitoring/pipelines/monitoring contains a few jobs with many builds (which run every 30 seconds). We further presumed that this would bloat the length of the `builds` table and cause the slow `REFRESH MATERIALIZED VIEW` referenced in #2253. However, there are two problems with this:
1. We cannot verify that the length of the `builds` table was the only factor influencing the running time of that query -- it very well may have to do with the `check_order` index thing we fixed.
1. Even if having too many builds was the problem, the monitoring pipeline needs to be long-lived because it is used for the "run existing job" SLI.
