### ISSUE TITLE
Epic : Multi-tenant runtime scalability

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2271]
This aggregate issue covers the scope of a few loosely tied threads in the `Runtime` backlog:
- Better distribution of jobs across workers #675
- Limit resource usage and runtime of tasks for a specific team #1284
- Concourse should support imposing limits on container resources #787
- Make things safe for running untrusted code #366

The common theme here is: Operators need some support from the Runtime in order to be confident that their cluster is scalable and secure when running many pipelines in untrusted multi-tenancy scenarios. This covers the Runtime's limiting of resources for teams and individual tasks, pipelines' usage of resources across workers, and other details around running untrusted code.

**Comment by topherbullock** [comment]
A related issue which will make this benefit more obvious to operators is: 
**Proposal: Metrics / Tools for Operators running large-scale Concourse #2249**

**Comment by jchesterpivotal** [comment]
A note here: the ATC has a number of distinct roles which don't need to remain centralised. One such role is managing workers, placing jobs, managing resources and whatnot. That's the remit of this epic.

Another role is keeping history, managing auth, serving the web UI and so on.

My point is: these could be separated. I would be able to have one scheduler and worker pool shared by multiple history/auth/UI servers. Whether this is achieved by having two processes, or whether we expand the worker API to allow a single magically beefy "worker", isn't immediately obvious to me.

The reason is that often I want _workload_ consolidation but not _workspace_ consolidation. Workload consolidation reduces variance, making capacity planning and autoscaling more tractable. The worker pool can be run at higher utilisation without adding to risk. But often I want my pipelines, versions, logs etc to be completely separate from anyone else's.

**Comment by KevinJCross** [comment]
There is a case you may wish to consider where you might need extra resources allocated and properly provisioned so that the performance is stable. I.e. an integrated stress test or a single container/box performance test.
We are currently finding that our test is failing due to over-provisioning the containers in a multi-tenancy arrangement. This is normally the correct thing to do but occasionally for a specific step/task the provisioning might be essential otherwise the pipeline becomes unstable without any mechanism to fix it.
In the above example we found that we are occasionally getting 10s+ local loopback response times  1/10 runs (depending on what is happening in concourse) where normally this has a mean of 12ms and 99 percentile of 150ms. The only thing we have been able to pin it down to is over-provisioning within concourse.

**Comment by ddadlani** [comment]
related to discussion in #3695
