### ISSUE TITLE
Dashboard as  Home aka `/`

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2282]
With the Concourse Dashboard leaving beta in 3.10.0 (ish), I think its time we wrapped up some loose ends and made Dashboard the top-level item on `/` of Concourse

But first, some polish items:
- [x]  Need to be able to LOGOUT from dashboard #1663 
- [x] Need a "No Pipelines set" hint for when a user views the dashboard. This would be equivalent in function to the existing "no pipelines set" view that we have when a user first installs Concourse and there are no pipelines set

- [x] Need an icon on the normal pipeline view so folks who are viewing the pipeline can get back to the dashboard. This would be an icon on the breadcrumb.

~~- [ ] Pause on dashboard~~ #2365  

~~- [ ] Re-ordering pipelines on dashboard~~ #2364 

...and finally
- [x] Change the `/` route to load the dashboard as well

cc @Lindsayauchin for designs on some of these subtasks

**Comment by Lindsayauchin** [comment]
"No Pipelines set" 

![screen shot 2018-06-18 at 11 01 19 am](https://user-images.githubusercontent.com/27746614/41544577-186b3e54-72e7-11e8-8041-efe3494b6e1f.png)


Font: #9B9B9B, 28 px
[dashboard_ic.svg.zip](https://github.com/concourse/concourse/files/2111721/dashboard_ic.svg.zip)

**Comment by xtremerui** [comment]
Also need to make dashboard top bar and non-dashboard top bar look the same etc. font, height, background colour, user profile menu.

**Comment by jama-pivotal** [comment]
For draggable items, @vito made a handy dandy module in Elm https://github.com/vito/cadet/blob/master/src/Drag.elm

**Comment by pivotal-jamie-klassen** [comment]
As I watch this story creep, I will write some of the acceptance cases here:
- [ ] pipeline/build/resource page top bar matches dashboard top bar
- [ ] dashboard button appears on pipeline/build/resource pages
- [ ] hover state for 'logout' button
- [ ] darker top bar, lighter groups bar
- [ ] hamburger button appears on dashboard/hd pages
- [ ] border styling?
- [ ] hamburger button expands sidebar on dashboard/hd pages
- [ ] 'X' instead of clicking again on hamburger to dismiss sidebar

**Comment by Lindsayauchin** [comment]
[baseline-close-ic.svg.zip](https://github.com/concourse/concourse/files/2167086/baseline-close-ic.svg.zip)
