### ISSUE TITLE
High CPU usage as a result of constant to CredHub client construction

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2300]
A number of users have reported high CPU usage with v3.14.1. This seems to be coming from the lazy CredHub client construction, which was introduced to fix https://github.com/concourse/concourse/issues/2154 but seems to be unintentionally creating a CredHub client repeatedly rather than just once (on first use).

I think this is happening because this doesn't return a pointer: https://github.com/concourse/atc/blob/master/creds/credhub/manager.go#L98 ... and so the client is always assigned on a copy.

We should also make sure this is safe for concurrent use. I believe the current code won't be happy with `-race` once we make it a pointer. This may be a good time to use `*sync.Once`: https://golang.org/pkg/sync/#Once

* Concourse version: v3.14.1
* Deployment type (BOSH/Docker/binary): any that use CredHub
* Infrastructure/IaaS: any
* Browser (if applicable): n/a
* Did this used to work? yes

**Comment by jmcarp** [comment]
😱

**Comment by kgrodzicki** [comment]
Hi, I am getting "too many open files" because credhub is going crazy :) 

Had increased limits in /etc/security/limits.conf with
`
*         hard    nofile      500000
*         soft    nofile      500000
root      soft    nofile      500000
root      hard    nofile      500000
vcap      hard    nofile      500000
vcap      soft    nofile      500000
`

but vcap (credhub process) user does not seem to be affected:

`
cat /proc/2094/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             128591               128591               processes 
Max open files            1024                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       128591               128591               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us 
`
do you have any suggestions ? We have large installation and it stops the whole team atm. Thanks in advance !

**Comment by engrun** [comment]
We have stumbled upon this issue (see [discuss](https://discuss.concourse-ci.org/t/downgrade-possible-from-3-14-1-to-3-13-0/322) .  Does anyone have an estimated date for a fix?

**Comment by jama-pivotal** [comment]
Update for ya'll, our fix moved through the pipeline so it should be coming in the next release

**Comment by iferunsewe** [comment]
We don't think the proposed fix works after having investigated with a profiler. More details are in this PR: https://github.com/concourse/atc/pull/291

**Comment by vito** [comment]
Yep, we've merged https://github.com/concourse/atc/pull/291 now which should actually fix it. Thanks again @iferunsewe!
