### ISSUE TITLE
Allow hijacking successful builds

### ISSUE THREAD

**Issue by krishicks** [concourse/concourse#2328]
## What challenge are you facing?

When debugging a build that is successful but not working properly it's sometimes hard to hijack the build while it's running.

This is because of two things:

* It's not possible to initiate a hijack until some non-obvious point in the scheduling/running of the containers; hijacking too early returns an error.
* Attempting to hijack the build once it has completed is not possible; hijacking too late returns a different error

If the build is quick this makes hijacking almost impossible, and also results in unnecessary builds having to be run.

## A Modest Proposal

I would like to configure the duration that containers for successful jobs are kept around. It would be nice if this were a pipeline-configurable setting that I could turn on and off on a per-job (or per-task!) basis, but a Concourse-deployment-configurable setting would be fine also.

The former would be similar to how CircleCI allows you to "rerun with SSH"; I don't always need to keep the containers around but I'd like to be able to reconfigure the job such that it keeps the containers around when I'm debugging.

**Comment by vito** [comment]
I just added a bunch of info to a similar issue for hijacking one-off builds: https://github.com/concourse/concourse/issues/2289#issuecomment-401134173

The query to change will be very similar, but I think the approach for configuring this should be a bit different so I haven't consolidated the two issues. I like the idea of having the config for this be scoped to a pipeline/job/task(?) rather than a global config, since you should only really want this in isolated scenarios.
