### ISSUE TITLE
BBR mitigation and testing

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2332]
A few versions ago we shipped a PR where @rkoster kindly implemented the BBR interface for Concourse. Unfortunately, during testing @vito was able to easily break it and cause some strangeness (see https://github.com/concourse/concourse/pull/1975#issuecomment-380583374)

Given the increasing popularity of BBR and increasing requests for it, I think its time that we took this seriously and do some testing for ourselves to:

1. identify weird behaviour and edge cases
2. develop mitigations for (1)
3. write documentation on our BBR integration and un-mitigated edge cases

<br />

---

*[@cirocosta's updates]*

 <br />

**Progress**

- [x] Add BBR tests to our pipeline for backing up concourse and restoring data.
  - https://github.com/concourse/concourse/pull/3908
  - https://github.com/concourse/concourse/pull/3815 
- [x] Retrieve properties from ATC configuration when using links
  - https://github.com/concourse/concourse-bosh-release/pull/35
- [x] Write documentation on our BBR capabilities (see [doc][bbr-doc])
- [x] Ensure BBR team is unblocked to work on the `single-transaction` story ([see in pivotaltracker](https://www.pivotaltracker.com/n/projects/1662777/stories/163252225))
- [x] Validate the backup/restore [doc][bbr-doc]
- [x] Validate we have necessary test coverage for BBR
  - [x] Remove hardcoded Postgres' 9.6 version
    - https://github.com/concourse/concourse/issues/3750
- [x] Reach out to Docs team to work with team to write / review documentation.
- [ ] Backup & Restore experiments on Prod - https://github.com/pivotal/concourse-ops/issues/66

[bbr-doc]: https://github.com/concourse/concourse/issues/2332#issuecomment-454556158

**Comment by Pivotal-Christopher-Wong** [comment]
I'd also like to add an additional action:
☐ Reach out to Docs team to work with team to write / review documentation.

A story has already been logged in the PCF Docs Services Tracker here: #144535081

**Comment by cirocosta** [comment]
Hey,

Thinking about some possible scenarios to test, we could start with the case mentioned by Alex (https://github.com/concourse/concourse/pull/1975#issuecomment-380583374) there to check the removal, and another that's more close to what [the BBR guide proposes](https://docs.cloudfoundry.org/bbr/bbr-devguide.html#testing).

i.e., have the following:

- [ ] Restoration when there are additions:
  - deploy concourse; take backup; create pipeline ; restore backup
- [ ] Restoration where there are removals:
  - deploy concourse; create pipeline; take backup; delete pipeline; restore backup

Please let me know if you have any other possible scenarios that would be interesting to have tested.

Thanks!

**Comment by cirocosta** [comment]
Hey,

As we continued testing BBR with Topgun, here's a list of issues we found:

- [ ] https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/issues/14

Thx!

**Comment by cirocosta** [comment]
Hey,

@Youssb and I noticed that problems arise when:

1. there's a mismatch between the tables that are in the backup
  and the current database state.
  1.1 because Concourse creates tables on-the-fly (`team_build_events_$ID`
      and `pipeline_build_events_$ID`)
  1.2 because the database is completely empty (has no tables)

To make it work, we can go with few approaches:

1. updating "bosh backup restore sdk" to make `--clean` configurable
  1.1 update `atcdb-bbr` script to drop the tables before starting the
      recover process

2. eventually perform some diffs? (going to elaborate this later)

Thanks!

**Comment by YoussB** [comment]
Hi, 
I was able to do a workaround that works.

1. added a user that had superuser permissions
2. took a bbr backup of the db
3. using the admin user, dropped the `public` schema `DROP SCHEMA public CASCADE`
4. re-created the schema and assigned to the atc user
5. restored the backup.
6. it worked!! 😁 

how to use this solution:
* update the current `bbr-atcdb` restore script to drop the public schema and make sure to create it and assign it to the atc user (will need to pass a superuser role to the script as well as the name of the role used by atc).

how about that?

**Comment by xtreme-sameer-vohra** [comment]
Update from @YoussB & myself;

# Tested Scenarios and current state:
- [working] backup, re deploy, restore 
- [not working, messes with the db and leaves it in a potentially inconsistent state] backup, add a team or pipeline
	We are talking to the bbr team to fix this scenario by adding transactions
- [working] backup, remove pipelines, restore 
- [working] backup, create new build, restore
- [working - running builds get into forever running state - they need to be cleaned up manually & some build history is lost] backup while a pipeline is running, re deploy, restore 

# Action Items:
- [in progress] Discuss adding the `single transaction` field to the restore scripts [Ref](https://www.postgresql.org/docs/9.6/app-pgrestore.html) - `--single-transaction`

- [Enhancement] - add check to ensure db restoration is happening on same version of Concourse release
- [Enhancement] - stalled worker cleanup after a successfull restore
- [Enhancement] - flag to bail out if a build is running - for backup

	
### Appendix
Issues
- cannot drop tables that dont exist while restore - this results in silent errors ( as in the process continues ). this is an issue for a dynamically created table such as team build events. We dont know what the exit code is we dont know why this doesnt work although the --if-exists and --clean flags are set ( we suspect this might be due to issues with fk relations - TBC)
- cannot drop tables that have fk relationships - this results in silent errors ( as in the process continues ). this is an issue for a table such as build events, where fk relationship is dynamic - a new pipeline or team is added. we dont know what the exit code is

**Comment by YoussB** [comment]
first draft for documenting using bbr with concourse that @xtreme-sameer-vohra & me are thinking about adding to concourse.
# Steps for using BBR:

## Setup
- Deploy Concourse with the following config
   Add some releases

   Add some jobs to existing instance groups
   bbr-atcdb job
   backup-restore-sdk job

- Refer to (bbr)[https://docs.cloudfoundry.org/bbr/installing.html] docs to setup/install bbr cli

## Backing up data
BBR backs up the DB used by Concourse
- Follow BBR instructions to backup a deployment
- Store the backup artifacts in a secure and durable location

## Restoring data
BBR restore the DB used by Concourse
- Setup a new Concourse deployment using the same release versions as the backed up deployment
- If the current state of Concourse is desired, Follow steps to backup the data prior to proceeding
- Follow BBR instructions to restore the deployment to its original state



## Gotchas
- If restore is performed on deployment where new pipelines or teams have been added, the restore will `fail`. In this scenario, we recommend backing up the current deployment (before running any restores) and running restore on a new deployment.
- Since workers' ids differ from a deployment to another, when restoring a backup you might see some stalled workers (these are coming from the backup, and it is safe to prune them).
- it is preferable to make sure no jobs are `running` while performing a backup. If not, when restoring from a backup the running job(s) will be resotred in a running state but won't continue to run as their containers will be lost. You will need to abort and rerun it.


@scottietremendous @jama-pivotal @Pivotal-Christopher-Wong 

Please tell us what do you think?

**Comment by xtreme-sameer-vohra** [comment]
# Next Steps
- validate the backup/restore doc posted above
- validate we have test coverage for BBR
- ensure BBR team is unblocked to work on the story linked above

**Comment by xtreme-sameer-vohra** [comment]
Noticed issues during restore in one scenario with `pg_stat_statements` where the restore failed. 

It appeared that the backup was taken with `pg_stat_statements` enabled on the atc schema, however, we didnt have the historical context to confirm if that was the case or not.

To resolve the issue, the bosh deployment had to be re-run with [DB Stats](https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/db-stats.yml) and the restore user needed to have the appropriate permissions as well to successfully restore.

**Comment by aclevername** [comment]
> Noticed issues during restore in one scenario with `pg_stat_statements` where the restore failed.
> 
> It appeared that the backup was taken with `pg_stat_statements` enabled on the atc schema, however, we didnt have the historical context to confirm if that was the case or not.
> 
> To resolve the issue, the bosh deployment had to be re-run with [DB Stats](https://github.com/concourse/concourse-bosh-deployment/blob/master/cluster/operations/db-stats.yml) and the restore user needed to have the appropriate permissions as well to successfully restore.

Versions we noticed this on:

```
Name         Release(s)                     Stemcell(s)                                    Team(s)
concourse    backup-and-restore-sdk/1.14.0  bosh-google-kvm-ubuntu-xenial-go_agent/250.25  -
             concourse/4.2.2
             garden-runc/1.16.3
             postgres/30
```

**Comment by xtreme-sameer-vohra** [comment]
There is a new version of [BBR](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release/releases/tag/v1.15.0) with the `--single-transaction` flag

**Comment by pivotal-bin-ju** [comment]
**Dev Note**
Done:
- Done the backup and restore test on both concourse 4.2.3 and 5.1.0.
- Reviewed the coverage of top-gun test cases for bbr, and added a new test case.

In progress:
- Testing the pipeline with  forever running job, observing the behavior when we do BBR.

To Do:
- Talked about whether we are going to fix the recover issue (setup new pipeline and after backup, then do recover)
- Talked about the best way of testing inconsistent state after backup-and-restore-sdk
/1.15.0 has `single-transaction` flag by default.

**Comment by mhuangpivotal** [comment]
Tasks for using bbr to backup atc database on prod:

- [ ] Write an ops file to add bbr release and jobs
- [ ] Update prod-deploy to use the ops file
- [ ] Add a new job that periodically runs bbr backup, and uploads the backup to GCS
