### ISSUE TITLE
Operators should be able to configure login tokens to auto-renew

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2343]
Currently the login token is set to auto-expire after a set amount of time. It would be really  nice if we could auto-renew the token based on some user interaction. It would also let folks who put up a CI monitor not have to constantly re-login

**Comment by jama-pivotal** [comment]
We can do it so that we refresh the web ui token every hour so long as the window is open. But this raises a potential problem with users who are de-provisioned from a team and should really be kicked out. So at the expiry interval (default 24 hours) we should check with the provider that this user is still valid

**Comment by xtremerui** [comment]
Currently there is no implementation of refresh token on concourse thus the only way to 

> we should check with the provider that this user is still valid

is inevitably to go through the auth code grant login, which requires manual user authentication that goes against the "auto-renew" part in this feature request.
