### ISSUE TITLE
Equivalent resources defined across pipelines and teams should only correspond to a single version history

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2386]
## What challenge are you facing?

Today, pipeline resource versions are collected in to a `versioned_resources` table. This table was predated the "life" epic (#629). It contains the following schema:

```
atc=# \d versioned_resources
                               Table "public.versioned_resources"
   Column    |  Type   | Collation | Nullable |                     Default                     
-------------+---------+-----------+----------+-------------------------------------------------
 id          | integer |           | not null | nextval('versioned_resources_id_seq'::regclass)
 version     | text    |           | not null | 
 metadata    | text    |           | not null | 
 type        | text    |           | not null | 
 enabled     | boolean |           | not null | true
 resource_id | integer |           |          | 
 check_order | integer |           | not null | 0
```

It points to `resource_id`, making this per-pipeline-resource. This means that multiple pipelines with the same resource configs will be redundantly collecting the same version/metadata information.

## A Modest Proposal

To be honest, this isn't a *huge* deal right now, aside from wasted database space and redundant checking. However if we make the relationship between a pipeline's resources and the abstract version history a bit tighter, there are actually a few benefits:

* We can reduce the amount of `check`ing required across pipelines for equivalent resources.
* We can reduce the amount of data recorded for equivalent resources.
* When a user changes their pipeline resource's configuration, the history will be "re-set" (ref. #145) to the new config, and should always be correct.
* There may be some as-yet-unknown improvements we can make to the database model by having a cleaner representation.
* As part of concourse/rfcs#1, we're going to start collecting *all* versions, not just starting from pipeline configuration time. There'll be a lot more data to record, so sharing it between duplicated resources will make things a lot more efficient.

### Enabling/Disabling versions

Enabling/disabling versions should remain scoped to pipeline resources, obviously. This can be done via a join table (`pipeline_resource_config_versions` or some such).

### Distinct check intervals

Now that we only check once per resource config, there's a little gotcha. Different pipelines can have varying `check_every` settings.

Here's one idea: record `last_checked` on the resource config, and have each pipeline's radar component just check if the `last_checked` is >= their interval. So, we'll check at the fastest defined frequency. Pipelines with longer `check_intervals` will have versions show up more quickly than expected, but that really shouldn't matter.

### Pausing pipeline resources

Currently, users pause pipeline resources with the intended effect that no new versions are collected and used for later builds. This is really awkward when other pipelines result in checking the config anyway.

We could still support today's behavior by "faking it" and having pausing a resource really just 'pin' it to whatever the version was at the time. But actually, that sounds a *lot* like #1288. Maybe we should just implement that instead, and remove the resource pausing functionality?

**Comment by krishicks** [comment]
I really like this. Reducing the redundant check containers for a single resource would make me feel like a better netizen.

> Pipelines with longer check_intervals will have versions show up more quickly than expected, but that really shouldn't matter.

Is the idea here that even though new versions would show up, the check_interval would be respected for triggering new builds? I can see someone using different check_intervals across pipelines to create varying pipeline behaviours, and that would be silently lost here.

One thing I was thinking of recently, and which I discussed with @xoebus in the past, is separating resource config from pipeline config. If multiple pipelines share the same config, why do I have to copy the configuration? This can become a chore when managing the same resource across many pipelines.

It would be great if I could just configure resources kind of like a cloud_config and then just refer to them in jobs in pipelines by name. Then a check_every would only be specified once for a particular configuration, and there'd be no surprise about which is the canonical resource definition.

**Comment by vito** [comment]
Hmm, one scary thing about this approach is that `check` containers can be hijacked. If we're not careful that could allow a malicious user to hijack "their" `check` container and influence it in such a way that the version detecting is affected, thereby affecting all teams.

Similarly, who should own the `check` container? It'd be nice if we could just have one `check` container per resource config, but then which team does it belong to? That would really limit who would be able to hijack it and debug it, if it's failing.

Here's one approach: we could make the containers global, and then take the container out of commission once it's hijacked. This would still allow anyone to debug a failing `check` and keep them from influencing its behavior. We should be careful to not allow hijacking of a container with an in-flight `check` call, too. Locking may be all we need there.

**Comment by vito** [comment]
Oof. This is actually really difficult with credential rotation (especially with automated rotation via credential managers).

If someone rotates their password to Docker Hub or their private key for their Git repo, that shouldn't reset the entire history of the resource. But with versions tied directly to a resource config, it'll be a different resource config any time the credentials change.

At the same time, we need the resource config to be fully resolved, because there should be some sort of authentication check before we share all the versions and especially the cached bits (which are also identified in part by resource config).

Should we separate credentials from config? What would that look like? Would it require a change to the resource interface? I'm thinking a simple 'check access' call - maybe this could also be for validation prior to use?

Back to the drawing board...

**Comment by vito** [comment]
Yet another concern: `time` resources configured with intervals like `1m`, `5m`, etc. will all find new versions at the same time when they're all tied to the same history. That would basically mean stampedes of periodic builds across the workers. (The same is technically true for any resource that many pipelines point to, but `time` resource usage would be especially severe by nature.)

Maybe sharing the version history globally just isn't worth it. :/ The initial concern was regarding database storage now that `check`s will be returning the entire history, but to be honest the disk usage will probably be nothing compared to the build events table.

I still think there are good things that can come out of this, but perhaps they can be prioritized differently:

* Splitting out auth config from source config will be hugely beneficial to anyone with frequent automated credential rotation. It would enable cache reuse throughout, and this could also determine how we implement config validation in resources (something we initially wanted in concourse/rfcs#1 but didn't find the motivation to include as the scope was already large).
* Tying pipeline resource history to its resource config makes sense for achieving #145. (Purging wouldn't be necessary, as the history would always be 'correct'.)  This would also benefit from splitting auth config out, so that the version history doesn't reset every time the credentials change.

**Comment by krishicks** [comment]
What about having a single "real" check container that does the checking on the minimum configured interval. Then there are "fake" check containers that have their actual check_interval configured, and which are the containers you can hijack. They ask the real check container (which itself speaks "check") for new versions. Think of the "real" one as being Concourse's internal bookkeeping.

**Comment by vito** [comment]
@krishicks Yeah, that'd help make hijacking safer. (Though I'm not sure how the 'fake' container would delegate to the 'real' one).

We could also do something like provision a fresh 'check' container when they try to hijack it. We could even run a one-off `check` call or write the JSON payload that we would be calling `check` with to a temporary file, so the user can manually run the `check` themselves. At that point it'd be less of "hijack" and more of "provision me a debugging container".

**Comment by vito** [comment]
To balance out some of the pessimism in my recent comments, there's one big benefit to consolidating version history which I neglected to mention: this could *dramatically* reduce the load on external services caused by constant `check`s. It would be amazing if we could reduce things down to one check interval at a time per Concourse installation for e.g. a git repo or custom resource type. That'd make GitHub Enterprise and private Docker registry operators much happier.

**Comment by vito** [comment]
One way to mitigate the concerns with the `time` resource could be to just have "shared history" be an optional feature, as determined by the resource type (not the user).

Looking at the list of supported resource types, we'd benefit from shared history for the following:

* `git`
* `hg`
* `s3`
* `docker-image`
* `github-release`
* `bosh-io-stemcell`
* `bosh-io-release`
* `semver` (less so)
* `pool` (less so)

The following resource types however wouldn't really benefit much from it at all, for different reasons:

* `time`
* `cf`
* `tracker` (which is still there apparently)
* `bosh-deployment`

So, maybe it could be an opt-in behavior via the `info` call we'll be adding in concourse/rfcs#1, and default to `false`?

All other behavior would be the same (i.e. however we handle `hijack`), they just wouldn't share their history.

**Comment by snegivulcan** [comment]
We are also very much interested in effectively reducing the number of times resource check ( docker_image in our case ) is performed. In our case we are running out of GCR (Google Cloud Repository ) new version check API quota, which is 3 per second per IP. We have a concourse cluster with 3 worker nodes, with a total of 24 pipelines. Each pipeline polls for 6 docker_image resources on avg and we have about 2 dozens docker_image resources in total.

**Comment by clarafu** [comment]
Brief notes on some initial changes we need to make during the spike.

Migrations
- new resource-config-versions (resource-config-id, version, metadata)
- new join table pipeline-disabled-resource-config-versions (pipeline-id, resource-config-version-id)
- edit resource-configs (add last-checked)

(later)
- edit resources (remove last-checked, paused later)
- edit resource-types (remove last-checked, version, type?)

Radar
- check for last checked on resource configs (instead of resources)
- if last checked is less than the check every interval, then we check

note.: two resources that reference the same resource_config might have different check_every intervals - we need to either pick the lower or the bigger

**Comment by clarafu** [comment]
Side refactor:

During the spike, we realized that the "UsedResourceConfig" object needs to have a connection and a lockFactory on it for us to do locking around the resource config. This made us revisit the whole structure around creating resource configs and the purpose behind these used resource configs and we have decided to do a refactor to make more clean abstractions between these old "ResourceConfigs" and "UsedResourceConfigs". "ResourceConfigs" objects are being used to construct a resource config in the database, which means that it really isn't a resource config itself but more of fields we need in order to construct one. This will be renamed to "ResourceConfigDescriptor". "UsedResourceConfigs" are used for when there is a "use" for a resource config in the database but it only really made sense when we still had the resource config uses table (which was removed). This will be renamed to "ResourceConfig". We will also make use of our ResourceConfigFactory (which was before only being used for 'fly check-resource') in order to ensure that every resource config object is being created with a connection and lockFactory.

**Comment by jchesterpivotal** [comment]
I've been thinking about this from a different direction. If we introduce some kind of versions API, then `check` can be split out from the ATC into 1-n standalone services, which manage their own containers. 

It also means that polling containers doesn't need to be the way Concourse learns about new versions -- instead efficient multitenant gateways can be built for very high-value resources like github, GCR etc.

The latter is important for very large installations (pinging @ImJasonH) and is already a pattern that [has appeared in the wild](https://github.com/sapcc/webhook-broadcaster) (h/t @databus23).

Both v1 and v2 resources would still work as-is under this model. What we'd be providing is a high-cost/high-payoff alternative for special cases and platform operators.

**Comment by vito** [comment]
@jchesterpivotal Yeah, that'd be pretty cool. We'd have to figure out what the trust model is for that API, of course. Definitely not something we'll dig in to today but we've already started to think about general resource APIs as a result of this story. So far they've all been read-only, though. The idea has been to bridge the gap between resource functionality and resource type functionality (which is basically nonexistant atm) by having an API that directly goes to their underlying abstract resource config.

**Comment by clarafu** [comment]
Build_resource_config_version_inputs/outputs will now use a resource id and version in order to determine the version of the resource config to use. The behaviour before was to have these tables use the resource config version id but that proved to be a problem in the case that a custom resource type gets a new version. This will result in all resources that point to that custom resource type to get assigned a new resource config id (since the resource cache of the custom resource type depends on a specific version of it's resource config) and this will basically invalidate all the build inputs/outputs that point to a resource config version of the "old" resource config. By having the build inputs/outputs use a resource id and version, it will allow for them to be resilient to a change in resource config as long as the versions for the resource is the same.

**Comment by clarafu** [comment]
Due to a failure in the resource versions check testflight test, we realized there will be a problem with the current architecture when a resource that uses a custom resource type gets a new version of the custom type. This problem is similar to the case in the previous comment, where the resource config will get updated and the resource will point to this new resource config, which as a result will invalidate all the versions associated to the old resource config. This case caused problems with the "get" step, where the version that is passed into it will be a valid version, but the resource config version that is associated to that version will be outdated. 

As a solution, we will do an upsert for saving the resource config version in the "get" and "put" step. It will find or create a resource config version (since we trust that the version passed into the "get" or "put" step is valid) and if the version is not found, it will create a new resource config version but with a check order of 0. Anything that looks at the resource config versions table should ignore any version that has a check order of 0 (during the scanning of resource config versions and at LoadVersionsDB). Only at the check should the check orders be overwritten and given a proper check order.

**Comment by clarafu** [comment]
Other migration code:

```
  CREATE TABLE versioned_resources (
      id integer NOT NULL,
      version text NOT NULL,
      metadata text NOT NULL,
      type text NOT NULL,
      enabled boolean DEFAULT true NOT NULL,
      resource_id integer,
      check_order integer DEFAULT 0 NOT NULL
  );

  CREATE SEQUENCE versioned_resources_id_seq
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;

  ALTER SEQUENCE versioned_resources_id_seq OWNED BY versioned_resources.id;

  ALTER TABLE ONLY versioned_resources ALTER COLUMN id SET DEFAULT nextval('versioned_resources_id_seq'::regclass);

  ALTER TABLE ONLY versioned_resources
    ADD CONSTRAINT versioned_resources_pkey PRIMARY KEY (id);

  CREATE INDEX versioned_resources_resource_id_idx ON versioned_resources USING btree (resource_id);

  CREATE UNIQUE INDEX versioned_resources_resource_id_type_version ON versioned_resources USING btree (resource_id, type, md5(version));

  ALTER TABLE ONLY versioned_resources
    ADD CONSTRAINT fkey_resource_id FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE CASCADE;
```

**Comment by clarafu** [comment]
**Refactor idea**

Resource caches currently refer to a version of a resource config using it's version column (which is the literal version json). This means that it does a join on the version instead of using the version_md5 column on the resource config versions table. We can refactor this so that a resource cache refers to a resource config version id instead of a version string.

**Comment by jchesterpivotal** [comment]
>  We can refactor this so that a resource cache refers to a resource config version id instead of a version string.

Is it an actual string, or is it a `jsonb` type? (Joining on ID will be much faster either way, but I am curious)

**Comment by jchesterpivotal** [comment]
> API changes :
> BuildResources endpoint will not include type, resource, metadata anymore

Why would this go away? I am actually relying on this exact behaviour right now for [my build resource](https://github.com/jchesterpivotal/concourse-build-resource).

**Comment by vito** [comment]
@jchesterpivotal It's a `jsonb` type.

The API endpoint was simplified because we only ever use the name and version in the UI, and the rest of the information is no longer immediately available from a schema standpoint. Builds now only keep a reference to an input name and version as their inputs and outputs. What values do you actually need from that endpoint?

I'm sure you know this but I'm gonna say it anyway - our API is currently unsupported and documented and prone to change at the whims of our engineers. We're ramping up an API track, though, so this will hopefully change in the future.

**Comment by vito** [comment]
IT WORKS! :confetti_ball:

**Comment by marco-m** [comment]
This is great news, it will help a lot people being throttled by credential managers like SSM when looking up the git key to do a check :-)

**Comment by vito** [comment]
@marco-m Hmm I don't think this will actually help that case at all. Credential resolution is done prior to even determining whether to run the `check` or not, since we have to resolve the credentials to determine the resource config to check in the first place.
