### ISSUE TITLE
Set global default resource limits for tasks

### ISSUE THREAD

**Issue by YoussB** [concourse/concourse#2431]
## What challenge are you facing?

As an operator, I would like to control worker resource usage in at least a coarse way.

## A Modest Proposal

Since we already implemented #787, it seems reasonable that I could start my atc with command-line flags like
```
concourse web --default-task-cpu-limit 256 --default-task-memory-limit 200mb
```
(or equivalent environment variables or bosh configuration, etc)

and have every task implicitly be configured with
```
container_limits:
  cpu: 256
  memory: 200mb
```

This could be overridden by actually setting different `container_limits` in your task yaml. This feels like incremental work towards something more like #1284.

**Comment by marco-m** [comment]
I like the idea of enforcing limits on the worker command-line.

On the other hand, regarding:

> This could be overridden by actually setting different container_limits in your task yaml. 

the override would go against the whole idea of enforcing global limits on the worker, so personally I disagree with that part. I think that the overriding behaviour of a task should be like the Unix limits model: a task should be able to only reduce the global limits set on the worker, never increase them.

I was also thinking that using limits in general needs the scheduling on the ATC to be aware of them. For example, if a task says `memory 1000mb` and some workers enforce lower limits, it means that the scheduler must know the limits of each worker and schedule that task on a worker that will accept it.

**Comment by YoussB** [comment]
@marco-m I see your comment as suggesting some possible extensions to the feature described here:

1. Instead of just setting "default limits" per task that can be overridden, what if these were actual "maximum limits" that _enforced_ (rather than merely suggesting) a particular pattern of resource usage?
2. Instead of having the default (or max) limits set globally across your whole cluster, wouldn't it make more sense to have it set granularly per-worker, as each of your workers might have different capacities?

I think these are both great ideas; the idea of this story is about establishing a slightly blunter instrument: Suppose you're an operator and your teams are running such expensive tasks that they actually crash your worker. What's the smallest incremental value we can add to help remedy this? Our idea was that you can get slightly earlier/less costly feedback about these expensive tasks -- You can set limits across the board, causing expensive tasks to fail, instead of allowing them to overwhelm your worker. Following this line of thinking, we realized enforcing static global limits might be draconian; it makes sense to allow your teams to have more expensive tasks, they just have to explicitly declare their resource demands.

Everything you have said here, and further improvements/configuration options as described in #1284, are all desirable features still to come in the backlog.

Do you have a specific use-case in mind? When trying to imagine the per-worker resource constraints we envisioned a setup like this: I have one big worker and one small one, and when it comes time to schedule an expensive task, the ATC should be able to figure out that it must run on the bigger worker. However, as it stands right now we already have the option of tagging the task so that it only can run on the bigger worker. I guess your proposed features would allow the ATC to be smart enough to make this decision without being explicitly told to.

**Comment by marco-m** [comment]
@YoussB, I went too fast reading the part of the command-line, somehow I though it was per-worker, while clearly it is on the ATC :-). I take back that part, setting on the ATC is good enough in my opinion, even better because simpler, there would be no need to make the ATC smarter knowing about the workers (and as you mention, there is still the tag approach).

The use case I have in mind is the same you mention: as a Concourse operator I want to protect my beloved workers from pipelines that would devour all resources. (This is exacerbated by the fact that currently there is no job queuing in the ATC, everything that is triggered is scheduled immediately).

As such, I think the limit should either be a maximum, or, if we want to have a default, then there should also be a maximum.

If I look at the existing `web` command-line options, it seems that the pattern I am suggesting is already there. Let's look at two examples:

I think that this one sets the maximum (pipeline cannot have a faster interval):
```
--resource-checking-interval=
```

Here another example, in this case there is a default, but there is also a maximum:
```
--default-build-logs-to-retain=                               Default build logs to retain, 0 means all [$CONCOURSE_DEFAULT_BUILD_LOGS_TO_RETAIN]
--max-build-logs-to-retain=                                   Maximum build logs to retain, 0 means not specified. Will override values configured in jobs [$CONCOURSE_MAX_BUILD_LOGS_TO_RETAIN]
```

So I guess, if we want to look at it from an incremental delivery point of view, since the keys here have `default-` as prefix, this is a good first iteration :-) On the other hand, please really consider adding a `--max-` version of these two tunables.

Thanks for Concourse!
