### ISSUE TITLE
Dashboard with no exposed pipelines should not confuse newcomers

### ISSUE THREAD

**Issue by aequitas** [concourse/concourse#2432]
# Feature Request

* Concourse version: 4.0.0

## What challenge are you facing?

When viewing the dashboard as an unauthenticated user it shows "no pipelines configured" with the client download options and the text "first, download the CLI tools:" and "then, use `fly set-pipeline` to set up your new pipeline". 

This can be very confusing for (newcomer) users that don't necessarily need to create/maintain pipelines but just need to view them occasionally.

## A Modest Proposal

When on pipelines are exposed and a user is unauthenticated, tell them they should log in first instead of showing instructions for pipeline configuration.

Also the search field is shown and makes no sense if there are no exposed pipelines, maybe adding a little more confusion.

**Comment by jama-pivotal** [comment]
Good point! We should change our default `no pipelines configured` to also suggest `or login`

cc @Lindsayauchin

**Comment by ZKjellberg** [comment]
I encountered this Issue today and its good to see its been documented.

This really confused me as I accessed Concourse CI to see "No pipelines configured.", thinking somehow my pipelines got nuked, until I realized I was unauthenticated.

**Comment by Lindsayauchin** [comment]
Adding in messaging before the empty state pipeline: 
"first download the CLI tools: 
then, use ‘fly-set pipeline’ to set up your new pipeline
or login"

![screen shot 2018-12-06 at 10 31 53 am](https://user-images.githubusercontent.com/27746614/49593710-33fa4e80-f942-11e8-83d3-ca45165f241f.png)

**Comment by ZKjellberg** [comment]
@Lindsayauchin Wouldn't it be more intuitive to word this similar to:
`Please login to view your private pipelines. Otherwise, download the CLI tool to set up new pipelines using the command 'fly-set pipeline'`

Additionally, changing the wording for the non-logged in dashboard to state `no public pipelines set`?

**Comment by Lindsayauchin** [comment]
@jama-pivotal 
![screen shot 2018-12-06 at 10 47 44 am](https://user-images.githubusercontent.com/27746614/49594683-6c9b2780-f944-11e8-9d16-efb9d450771b.png)

**Comment by aequitas** [comment]
@Lindsayauchin thanks for looking into this. New screen looks great. I also like @ZKjellberg's suggestion to add the 'public' word.

**Comment by pivotal-jamie-klassen** [comment]
To be clear, based on what the API exposes, there are two mutually exclusive possibilities:
1. You are not logged in, and there are no public pipelines on ANY team. At the moment, you see a welcome message and no cards (not even ones with 'no pipelines set'), as there's no reason (from the API's perspective) for you to know of the existence of any teams at all:
![screen shot 2019-03-01 at 11 05 17 am](https://user-images.githubusercontent.com/22056320/53650227-0ad01e00-3c12-11e9-8487-b7ab24efcb41.png)
My understanding of the discussion here is that this unauthenticated no-pipelines view should  perhaps mention the possibility of hidden pipelines, by showing copy more like this (I actually prefer 'hidden' over 'private' for consistency with `fly hide-pipeline`):
![screen shot 2019-03-01 at 11 13 03 am](https://user-images.githubusercontent.com/22056320/53650691-1839d800-3c13-11e9-9c5c-d091082d8f7e.png)


1. You are logged in and a team is visible to you, but none of its pipelines (if there are any) are visible to you. At this point, given our RBAC model, the only way this can happen is if you are an admin user (i.e. have the `owner` role on an team, i.e. `main`). In this case, we show a 'no pipelines set' card for every team:
![screen shot 2019-03-01 at 11 22 15 am](https://user-images.githubusercontent.com/22056320/53651308-600d2f00-3c14-11e9-82a2-cb4199f3c9bf.png)
@ZKjellberg's comment suggests that the copy in this case should also hint at the fact that there might be pipelines, you just can't see them:
![screen shot 2019-03-01 at 11 18 23 am](https://user-images.githubusercontent.com/22056320/53651031-d5c4cb00-3c13-11e9-9ceb-5ff22a0e6979.png)
This feels a bit like an edge-case, though as our RBAC model becomes more sophisticated it might become more relevant.

@aequitas @jama22 @Lindsayauchin @ZKjellberg @vito is this a fair assessment? Based on what we have already, the only difference here is mentioning to unauthenticated users that they might need to log in when the cluster has no public pipelines. I'd vote against making the second change above because it's an exceedingly rare edge case and seems unlikely to make an interesting difference to cluster admins.

**Comment by vito** [comment]
What if we cleared up the ambiguity by having different messaging based on whether you're logged in or not? Logging in is a pretty basic step that a new user will need to do anyway (even after downloading the CLI and configuring a pipeline), so having them just do that first in order to make the messaging clearer seems like it'd pay off.

i.e.

If there are no pipelines and the user is not logged in, just show:

```
welcome to concourse!

[ log in ]
```

...I couldn't really think of a clear message here, since saying anything like 'there are no pipelines' or 'to get started' would scare existing users into thinking all their pipelines disappeared. Maybe it's better to just say nothing and have a prominent 'log in' button?

Then, if you're logged in and there are *still* no pipelines, we can say something like the following with more confidence:

```
welcome to concourse!

it looks like you don't have any pipelines - to get started, download the fly cli:

[download buttons]

pipelines are created by the `fly set-pipeline` command.

for more information, check out the [concourse docs](...).
```

I'm not particular on the messaging in this case. Maybe we could show a basic "hello world" pipeline instead of just giving them the command name?
