### ISSUE TITLE
Dashboard header doesn't stick on mobile resolution

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2434]
This occurs when viewing the Dashboard at mobile resolutions. The black header bar with search should remain sticky

![screen shot 2018-07-30 at 10 07 43 am](https://user-images.githubusercontent.com/27746614/43402300-6ebef0ec-93e0-11e8-8bf1-5efe09034c05.png)

**Comment by pivotal-jamie-klassen** [comment]
there could be some interplay with the "sticky header" technology we are using here. More specifically, we have an elm port that enables a jQuery plugin that sets the vertical offset of the sticky team headers to a hardcoded value. I'm going to spike a bit on using elm-css to see if we can get a more type-safe implementation (and maybe reduce our dependence on ports and external javascript while we're at it)

**Comment by Lindsayauchin** [comment]
Capturing the conversation @pivotal-jamie-klassen and I had about a more elegant solution. 

Because the top navigation bar is increasing in height this is causing problems downstream. If we can better arrange the elements in the top nav to better accommodate the search input and log out/in button.  

## Proposed solution:
 - [ ] keep the top navigation bar the same height at all breakpoints
 - [ ] move the icon beside the concourse logo button
 - [ ] remove the search input box outline 
 

![search_mobile_dashboard](https://user-images.githubusercontent.com/27746614/46356659-2cac8100-c631-11e8-9ce6-7a91cf997efe.png)

 - [ ] search input outlined box will appear on the selection of the icon and cover the username/ logout button (similar to https://concourse-ci.org/)


![search_mobile_dashboard_expanded](https://user-images.githubusercontent.com/27746614/46356658-2cac8100-c631-11e8-9603-8a28ad89f884.png)

**Comment by pivotal-jamie-klassen** [comment]
@Lindsayauchin the only edge case I have not covered (and it is a somewhat exotic one) is this:

when you are in the mobile view and the search bar is collapsed (the first screenshot above), the keyboard shortcut for search (`/`) does nothing. You might have expected it to expand and focus the search bar.

I consider this exotic because you are generally not relying on keyboard shortcuts at the mobile view. @jama-pivotal does this strike you as reasonable?

Either way, if this feature is desirable, let's maybe put it in a different story? I've added a ton of tests as part of this work and it's going to help with some [single source of truth](https://gist.github.com/pivotal-jamie-klassen/b90592320124d00098a8de9979be6a97#architecture) refactors down the line. once the `NewTopBar` and `Dashboard` models get unified as part of this, testing and implementing the keyboard shortcut feature will be easier.
