### ISSUE TITLE
Unexpected Metric Attributes

### ISSUE THREAD

**Issue by nursejason** [concourse/concourse#2468]
# Bug Report
Probably less of a bug and more of a bad user.

* Concourse version: 3.14.1
* Deployment type (BOSH/Docker/binary): docker (kube)
* Infrastructure/IaaS: Openstack
* Browser (if applicable): N/A
* Did this used to work? No

## Problem
I've enabled emitting of Prometheus metrics VIA Helm chart. Based on documentation, I would expect to see `pipeline`, `job`, `build_name`, `build_id`, and `build_status` on the `build finished` metric.

What I actually see is a bit different: 
`concourse_builds_finished{pipeline="autorun-thing",status="failed",team="tarot"} 2`

In fact, searching the entire series of exported metrics for `job` just shows me HTTP request durations.
`concourse_http_responses_duration_seconds_bucket{method="GET",route="GetJob",le="0.005"} 0`

**Comment by mattburgess** [comment]
What version of Concourse are you using? I see the following on a 3.14.1 instance:

`concourse_builds_finished{instance="concourse01.local",job="concourse",pipeline="mypipeline",status="failed",team="main"}`

So, it looks at first sight as if `build_name` and `build_id` and `duration`.  However, I'm not sure they should be there due to the way that Prometheus works.

I think there are actually a number of bugs here:

1. Documentation bug: I think the page at https://concourse-ci.org/metrics.html lists the **metric events** that are emitted for metrics emitters to then consume; presumably given the different nature of the metrics implementations (prometheus, datadog, etc.) each one may decide to expose different metrics (aggregates, counts, histograms, etc. rather than the raw events that Concourse emitted).  If my understanding is correct, I think it'd be useful to have sections for each emitter to show which metrics they expose.
2. The `concourse_builds_finished` Prometheus metric only ever has the `job` label set to `concourse` in all of my metrics, which I don't think is right. I was expecting that to be the name of the job in the pipeline that was built.  In the example above, that should be `job="myjob"`
3. The `concourse_builds_duration_seconds_count` metric has the same problem with the `job` label as above.

**Comment by pms1969** [comment]
I'm seeing similar behaviour on a v4.0.0 release deployed on kubernetes.

```
concourse_builds_finished{app="concourse-web",chart="concourse-2.0.0",heritage="Tiller",instance="10.2.1.79:9391",job="concourse-web",kubernetes_namespace="dev-tools",pipeline="test",release="concourse",status="errored",team="main"}
```

although the `job` is there, instead of reading `grn` it has `concourse-web`.  Very strange.

**Comment by renbeynolds** [comment]
We are seeing the same behavior on our BOSH deployment of Concourse version 4.2.1. 

<img width="774" alt="screen shot 2019-01-24 at 3 54 50 pm" src="https://user-images.githubusercontent.com/8278063/51707918-73632400-1ff0-11e9-804d-99ed72fb48e4.png">

**Comment by vito** [comment]
Possibly relevant: https://github.com/concourse/concourse/issues/2896

In general our metrics situation is a bit of a mess, partly because are too many ways to do things and each metrics backend is slightly different.

Centralizing the metrics on one stack would make it easier to document and set expectations. And would make it harder to accidentally do bad things like emit metrics with unbounded cardinality.

**Comment by chrisfarms** [comment]
Possibly relevant: https://github.com/concourse/concourse/pull/4976

**Comment by xtremerui** [comment]
closing stale issue.
