### ISSUE TITLE
Investigate : Auto-magically generating K8s helm chart parameters

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#2472]
Currently the process for adding new parameters to the Concourse helm chart is to manually add them to the chart yml.

Is there a way to automagically generate this yml? 
OR is there at least a way to detect when there are new parameters to configure in the helm chart?

Let's look at using the struct fields parsed by `go-flags` to determine what settings should be configurable (a-la https://github.com/vito/twentythousandtonnesofcrudeoil)

**Comment by pivotal-jamie-klassen** [comment]
As it stands, the `values.yaml` file in the Concourse helm chart contains both Concourse-specific values as well as Kubernetes configuration values. We toyed with the idea of splitting out the two, thereby allowing us to generate the Concourse-specific values into one `values.yaml` file and keeping the Kubernetes specific values in another file, to allow for ease of modification and open source contribution.

However, there is no current way to split this out because the `values.yaml` file provides default values, and there can only be one default value file.

Our next investigation was to look into using templating for the Concourse-specific parameters, however, there is support for templating values (https://github.com/helm/helm/issues/2492) but not the parameters themselves. 

The best solution at this point would be to have a job that checks for the existence of Concourse parameters and corresponding Helm chart values, and to error out if there is a discrepancy. This would require manual intervention to fix but the job would provide us with an easy reminder to update the Helm chart with changes in Concourse.

**Comment by jama-pivotal** [comment]
@ddadlani says, maybe we could somehow detect these new parameters and automagically enter new issues for us to triage and work on manually?

**Comment by xtremerui** [comment]
We have pushed all our changes in concourse/charts and submitted the PR to [helm/charts](https://github.com/helm/charts/pull/7804).

In prod CI there is a job `check-helm-chart-params` that making sure all concourse binary env vars are sync with the chart.

**Comment by topherbullock** [comment]
Closing this since https://github.com/helm/charts/pull/7804 is merged and we have the jobs in the pipeline
