### ISSUE TITLE
Proposal: Heat Map of pipelines with jobs scaled to the amount of time it takes to finish

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#2497]
# Feature Request

It would be interesting to take the visualization of the pipeline thumbnail, but re-size the jobs according to the total amount of time it takes for each job to complete. This would help teams quickly identify where to focus their efforts (big box = long time = make it faster!) The design would be similar to the file size maps like this: https://www.novell.com/communities/coolsolutions/feature-focus-file-reporter-tree-map/

Questions:
- [ ] where to put it
- [ ] ??

**Comment by dlresende** [comment]
@Lindsayauchin thanks for considering the suggestion :)

**Comment by marco-m** [comment]
I am confused. The amount of time of a given build is greatly influenced by the load on the worker. I understand a graph of the trends or rendering a running average of the last N builds (but then this is Jenkins, Concourse doesn't have this approach). This looks to me eye candy, I am sure I am missing something ?

**Comment by dlresende** [comment]
This is actually a proposal to solve the following problem: if I need to optmise my pipeline, where should I focus/start?

Pipelines can be very complext. Sometimes we're biased by misperceptions and might end up spending a lot of energy optimising based assumptions, mainly by lack of measures. AFAIK, today we cannot easily extract from Concourse metrics like avarage time spent by (last N passing?!) jobs, tasks, etc. If I could easily spot jobs comsuming most part of the time, I would know where I should focus my efforts.

Maybe there's a better solution to this problem. Although, even if I agree that the build time can depend on the load on the worker, I've observed time tends to stabilise on many of the pipelines I work with, so I'd argue the avarage would still make sense here.

**Comment by marco-m** [comment]
@dlresende ah I understand. My 2 cents opinion (I am an user like you :-) is that Concourse should provide average load per pipeline and export it as a metric, so that decisions like yours can be made.

The proposal in this ticket, to me, goes under the "quick fix" Concourse antipattern (https://github.com/concourse/concourse/wiki/Anti-Patterns).

**Comment by dlresende** [comment]
I disagree :)

I'd like my dashboards to radiate as much info as possible and still remain simple and focused. The proposal discussed here is very close to what Concourse already provides, at least from a UI perspective.

I don't see any problems in having both approaches: dashboard + exported metrics. From my experience, teams running Concourse rarely monitor Concourse via metrics, let alone configure the plumbing required to build dashboards from those metrics. That's why I believe what we propose here is still simple and could have a huge impact on teams, since they already have a dashboard available just there. It's like coming with batteries included to me.

I see this as an experiment: we build, we measure and we assess. If it makes sense, we improve it. Otherwise, we remove it and move on.
