### ISSUE TITLE
Pull out migration package into separate library

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2516]
* Handle dirty state in new table (short-circuit without trying to migrate again)
* Add a connector or something to support migrating from mattes/migrate (and possibly others?)
* Add a CLI command to run the migrations standalone
* Anything else?

**Comment by ddadlani** [comment]
Things to do:
- [ ] Decouple migration `source` from our own migrations
- [ ] Support migrating up from/down to a previously used migration library
- [ ] Add extended CLI options to run migrations (currently only generates migration files)
- [ ] Support other databases/types of migrations?
- [ ] (In parallel) move code over to the new migration repo

**Comment by ddadlani** [comment]
Update on progress: WIP code is currently at https://github.com/ddadlani/voyager .
Migration changes for Concourse are on the `extract_migration_library` branch in this repo.

A bunch of work has been done so far to decouple the migration logic from Concourse code. Any Concourse-specific logic has been moved to the `OpenHelper`.

Currently working on supporting migrations to/from a previously used migration library. So far, we are experimenting with a `SchemaAdapter` which takes 2 functions, `migrateFromOldSchema` and `migrateToOldSchema` which can optionally be run before an `up` migration / after a `down` migration. This should allow users to port between their old schema and the new `migrations_history` schema however they choose.

**Comment by ddadlani** [comment]
Another update: Library now supports passing metadata in the form of an `[]interface{}` to Go migrations.

Tests were refactored for easier reading

**Comment by ddadlani** [comment]
The ability to pass arguments as metadata to your Go migrations was removed. This is because:

1. This ability was added because we wanted the ability to pass in metadata for encryption to certain migrations. However, passing metadata in as arguments to the Go migration meant that the same arguments had to be passed in to every Go migration, which seems unnecessary.
2. There was some overhead in accepting string arguments from the command line for the CLI, parsing them into a slice of type `[]interface` , which would then be parsed in the Go migration itself. It was not an ideal implementation.
3. Since the `runner.MigrationsRunner` is an interface and not a specific type, the user needs to provide an implementation anyway. The type that implements `MigrationsRunner` [e.g.](https://github.com/ddadlani/voyager/blob/master/migrations/migrations.go) could simply have more fields which could be used as metadata to the migration [e.g.](https://github.com/ddadlani/voyager/blob/master/migrations/4000_go_migration.up.go).

**Comment by ddadlani** [comment]
The migration library is currently Unix-specific (checks file permissions for Unix), etc. We may need to change this to support ATCs running on other platforms.

**Comment by xtreme-sameer-vohra** [comment]
What is remaining
- [ ] Implementing Schema Adapter within Concourse


Tests to be done
- [ ] Use Voyager to migrate from 0 to latest schema migration
- [ ] User Voyager to migrate an existing Concourse Deployment at version ( v5 ) -> Latest ( Assuming there are some migrations to run within that time frame )
