### ISSUE TITLE
The "errored current" colour and "started" colour are very similar

### ISSUE THREAD

**Issue by ryanmattcollins** [concourse/concourse#2520]
# Feature Request

## What challenge are you facing?

When looking at builds, it can be unclear at times whether a job is `errored` or if it is `started`. Particularly if you are on an `errored` build:

![screen shot 2018-08-22 at 11 09 16 am](https://user-images.githubusercontent.com/4941777/44472497-499a7100-a5fc-11e8-9fc6-48f4cd4c642e.png)

This is particularly more noticeable on crappier monitors.

## A Modest Proposal

Make the `started` state have a different/more contrasty colour. Maybe have a way to indicate the build you've currently selected?

**Comment by Lindsayauchin** [comment]
## A Modest Proposal

Adding the running state to the background of the area where the job name lives to provide contrast to the amber errored. 

![screen shot 2018-08-27 at 1 59 02 pm](https://user-images.githubusercontent.com/27746614/44678718-0a5a8e80-aa07-11e8-813e-09ef1ed66589.png)

**Comment by ryanmattcollins** [comment]
What would this look like if your currently selected tab isn't the running build, but the errored build? Does this change apply to the running tab as well?

**Comment by jama-pivotal** [comment]
1. MVP is not animated
2. bonus points for animating it

**Comment by pivotal-jamie-klassen** [comment]
Since the 'running stripes' animation is implemented via CSS animation, there could be some trouble synchronizing the animation on the whole banner with the animation on the build number in the list below. If we don't address this in the implementation (either by doing some synchronization tricks to make sure CSS gets applied at the same time or using a slightly richer animation tool than css animations), we could get screens like this:

<img width="522" alt="screen shot 2019-02-21 at 10 01 30 am" src="https://user-images.githubusercontent.com/22056320/53180181-1a70b680-35c3-11e9-80a5-6209a3fee18e.png">

@jama22 @Lindsayauchin 'MVP'-wise I see two options:

1. no animation, but a guarantee that the stripes line up
1. animation, with the possibility of unsynchronized stripes

any preference? In the meantime I'll spike a bit on a more synchronizable animation technique to see if it's actually a moot point.

**Comment by Lindsayauchin** [comment]
Can we try with the possibility of unsynchronized stripes?
 I think a spike on an alternative way of rendering the animation would be helpful to this [issue](https://github.com/concourse/concourse/issues/2410 ) as well. This issue highlights the noticeable jagged edge to the stripe that we couldn't quite get rid of on the dashboard.

We can look at different widths of the stripes, angle, and spacing of the stripes if that helps in the rendering of the animation across these different applications.

**Comment by Lindsayauchin** [comment]
talking to @pivotal-jamie-klassen and @xtreme-james-cooper we concluded to leave the animation polish for another issue and go ahead with what we have now as an MVP on the feature that we will continue to iterate on.
