### ISSUE TITLE
Worker on busy concourse deployment has high disk usage 95% and it appears as though volumes under "dead" are not being cleaned up.

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#2529]
This was on Concourse 4.x.x

Observed:
df -lh
```
/dev/loop0      956G  904G   49G  95% /var/vcap/data/baggageclaim/volumes
/dev/loop1      966G 1018M  965G   1% /var/vcap/data/grootfs/store/unprivileged
/dev/loop2      966G 1018M  965G   1% /var/vcap/data/grootfs/store/privileged
```
```
worker/ab5584ea-363d-4600-8149-84aa949647b3:/var/vcap/data/baggageclaim/volumes# ls -lh dead/ | wc -l
2453
```
All the volumes were created ~1 wk ago and don't seem to be cleaned up.

**Comment by ddadlani** [comment]
So it appears that there are two related issues at play here. 

1) The `baggageclaim` process hits the error `too many open files`(a lot of tcp connections), which is because the max open files ulimit for the worker is set to 1024 by default. This is probably too low and should be increased.

2) Volumes under `dead` are not being cleaned up. We believe this is happening because of issues with the `btrfs` driver, which locks up, causing Deletes to error out and volumes to stick around.

The issue with `btrfs` probably causes the issue with `baggageclaim` due to increased load causing connections to the baggageclaim client to hang. When the connections hang, the atc's `baggageclaim.Client` issues retries for the connections which leads to `too many open files`. The only fix here would be to switch to `overlayfs` which is pending because of another issue.

For now the fix is to increase the `max open file` ulimit on the worker, which should reduce the occurrence of these issues.

**Comment by kcmannem** [comment]
We wanted to use the os-conf release to set open file limits but it sets limits by adding a file to `/etc/security/limits.d/`. These are read during bootup and applied. During an initial deploy the prestart script populates `limits.d/` after bootup so limits don't get applied until a vm restart occurs which isn't really a thing with bosh. We decided to use the ulimit-release (https://github.com/pivotal-cf/ulimit-release) which uses `prlimit` to set the limit on monit during the prestart lifecycle stage so when monit forks off jobs, the limits are passed on. This avoids the need for a reboot.

**Comment by ddadlani** [comment]
We set the `ulimit` for the worker daemon to 64K in the concourse bosh-release to reduce/prevent the occurrence of the `max open files` error. This may need to be done manually for other deployment methods in the future.

**Comment by DimitarVoynov** [comment]
Hi @ddadlani, 

can you please share how exactly you set the `ulimit` for the worker daemon in the concourse bosh-release to reduce/prevent the occurrence of the `max open files` error? I am facing the same error and would like to do the same thing, but I am not sure how. 

Thanks!
Dimitar
