### ISSUE TITLE
Emit more ATC metrics

### ISSUE THREAD

**Issue by colmtuohy** [concourse/concourse#2594]
Hi there!

# Feature Request: Emit more metrics from the ATC emitter 

## What challenge are you facing?
Currently using Grafana/influx for monitoring concourse health. Using 3 (or 4) data sources: ATC, telegraf, concourse postgres DB. Key metrics we use to monitor, based on experience so far, include number of containers/worker (to watch for those hitting 250 limit), worker disk space, pending builds (time series), previous 3, 6, 12, 24 hour build stats, ATC http response time. 

To obtain these, have home cooked various recepies to obtain them, such as for pending builds, have used grafana to query the ATC DB for numbers of pending builds, and insert these into influx, for grafana to plot over time. 

To switch to a different metrics reader (datadog) make us to have to redo this work again to suit. Should the atc emitter send these meteics (and others) by default?

If so, we can compile a comprehensive list of metrics we think should be included. 

Also, it appears that some metrics that are emitted to influx, and not being emitted to datadog (container count/worker, for example) 

## A Modest Proposal

If you think we should improve the atc emitter, we can derive a list of metrics we think wouls be useful, something we can then use to auto trigger tasks to resolve issues (such as recreate a worker with excessive containers) 

The following can also be handy:

* Concourse version: 3.13.0
* Deployment type (BOSH/Docker/binary):bosh
* Infrastructure/IaaS: openstack
* Browser (if applicable):
* Did this used to work?

**Comment by colmtuohy** [comment]
Note for the pending builds plot, that should rwad we use telegraf to query the atc db, which inserts timeseries rwadings into influx

**Comment by cirocosta** [comment]
Hey @colmtuohy,

Thanks for bringing that to attention!

> Also, it appears that some metrics that are emitted to influx, and not being emitted to datadog (container count/worker, for example)

That's indeed a problem - right now we end up having to write emitter-specific code for certain emitters. Recognizing that, we're aiming at moving towards a model where we can have a single source of metrics and that can be scraped by whatever consumer of those metrics end up being by going - see https://github.com/concourse/concourse/issues/2896 (your input there would be very appreciated!)

> If so, we can compile a comprehensive list of metrics we think should be included.

That'd be awesome! Internally, the team has a track of work (proactive support), so that's some line of work that we'd like to get some more input from the community too! Would you mind sharing some of those metrics you've been keeping track of that are not currently supplied by concourse?

Thanks!

**Comment by handytom** [comment]
Hi @cirocosta,

We will put together a list of the metrics we are currently generating via custom DB queries.

In the mean time can you confirm that the atc.worker_containers metrics value can be considered an accurate metrics to track average container counts across all workers in a deployment.

Cheers
Tom

**Comment by WxFang** [comment]
Resource types would be very useful cause then we can create a table for checked git resources.

**Comment by xtremerui** [comment]
closing stale issue.
