### ISSUE TITLE
Pause/Play button for job should always be visible

### ISSUE THREAD

**Issue by loewenstein** [concourse/concourse#263]
Steps:
- click on a job which has builds
- notice there is no play/pause button
- click on the job title to get the job overview (now the button is there)

Having to click twice is rather unintuitive.

**Comment by xoebus** [comment]
Yeah, this is a little unintuitive at the moment.

When you click on a job that has builds we redirect you to the page for the latest *build* because that's probably what you want to see most of the time. Clicking on the job title takes you to the page for the *job*. Since the pause action is on jobs and not builds the play/pause button only shows up there.

We're looking into ways to make this better at the moment.

/cc @kimeberz

**Comment by benmoss** [comment]
This github thread is serving as the documentation for this feature right now. Definitely agree it's unintuitive.

**Comment by xoebus** [comment]
@vito Bad close

**Comment by jama-pivotal** [comment]
Linking to #1915 which is the same feature request but has more fully fleshed conversation and designs. Closing this issue to funnel conversations to that issue instead...and really to avoid any people clicking into that old tracker. Anyways, feel free to re-open if you feel that i have misunderstood
