### ISSUE TITLE
Feature Request: Provide a quick way to filter dashboard pipelines to favorites

### ISSUE THREAD

**Issue by philwebb** [concourse/concourse#2647]
## What challenge are you facing?

I'm a member of a GitHub team that has lots of CI pipelines, but not all of them are relevant to me. I would like a way of viewing a dashboard that only includes pipelines that I've bookmarked.

## What would make this better?

I would like a way to "star" or "favorite" a pipeline to indicate that it is one I often need to look at. I would then like an option on the dashboard to "only show stared pipelines".

**Comment by marco-m** [comment]
I think that you can obtain the same with Concourse 4.x, the dashboard and a web browser bookmark or bookmarks, because with 4.x the search query in the dashboard can be passed as an URL.

For example, `http://127.0.0.1:8080/?search=foo` will match all pipelines containing `foo` in their name.

If you play with the search field, you will see also "selectors", for example `http://127.0.0.1:8080/?search=team%3A%20main` shows only pipelines belonging to the `main` team.

**Comment by jama-pivotal** [comment]
Interesting! We've also played around with the idea of "pinning" pipelines in the past, so a user can pin pipelines to the top of their dashboard. Especially useful in multi-tenant environments where folks expose pipelines willy nilly.

**Comment by marco-m** [comment]
@jama-pivotal If I understand correctly, I think you mean `team: foo OR team: bar`.

**Comment by philwebb** [comment]
I'd still like this feature. I use a similar thing in Artifactory all the time.

**Comment by vito** [comment]
I don't think we have bandwidth for this on our own roadmap, but it seems like a good feature. We'd probably need to figure out where the state is actually stored. Would client-side local storage be sufficient? I don't think we store any per-user data right now.

**Comment by philwebb** [comment]
Client-side local storage would work fine for my needs since I rarely change computers. 

For reference, Artifactory initially shows a full list of repositories:

![Screen Shot 2019-08-16 at 4 57 34 PM](https://user-images.githubusercontent.com/519772/63203831-0922d700-c047-11e9-9442-4b1a280dc221.png)

You can "star" a repository in the details pain on the right to mark it as a favorite. Once you've marked the ones you're interested you can click the star icon in the tree view to show only favorites:

![Screen Shot 2019-08-16 at 4 57 43 PM](https://user-images.githubusercontent.com/519772/63203866-4be4af00-c047-11e9-9bf8-0a14bc9d398d.png)

I imagine Concourse could work in a similar way with icons next to the pipelines to mark and a filter option in the hamburger menu.

**Comment by pivotal-jamie-klassen** [comment]
@jomsie and I, who work full-time on Concourse, are pair-programming and splitting our time between the UX roadmap and [release engineering](https://github.com/orgs/concourse/projects/36) tasks. This means we're able to work on at most one issue at a time, and not full time. At this point we have some roadmap items that involve large wide-ranging changes and a fair amount of tech debt/refactoring that will require our full attention and expertise: [Build Rendering Performance](https://github.com/concourse/concourse/projects/37) and [Rewriting the pipeline page in pure Elm](https://github.com/concourse/concourse/projects/33). So at this point I'm predicting that this issue won't get our attention in the immediate future.

Instead I'm going to try to give some general guidelines about how I might approach solving the problem. Hopefully this eases the way for another contributor.

## Interacting with localStorage

Presently there are two use-cases that interact with the browser's localStorage:
* CSRF tokens - this includes [acquiring a CSRF token on app startup](https://github.com/concourse/concourse/blob/master/web/elm/src/Application/Application.elm#L88-L92) and [storing a CSRF token](https://github.com/concourse/concourse/blob/master/web/elm/src/Application/Application.elm#L94-L97) on [login](https://github.com/concourse/concourse/blob/master/web/public/index.html#L84) (when there is a [token in the redirected URL](https://github.com/concourse/concourse/blob/master/web/indexhandler/handler.go#L52)).
* Sidebar expanded state - gets [loaded](https://github.com/concourse/concourse/blob/master/web/elm/src/SideBar/SideBar.elm#L145-L146) on [app startup](https://github.com/concourse/concourse/blob/master/web/elm/src/Application/Application.elm#L100) and [saved when the hamburger menu is clicked](https://github.com/concourse/concourse/blob/master/web/elm/src/SideBar/SideBar.elm#L50-L53).

In the Elm code, writing to localStorage takes the form of [`Effect`s](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Effects.elm#L169-L170), which, when [run](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Effects.elm#L435-L439) invoke [ports](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Effects.elm#L85-L88) which invoke pretty [thin wrappers around the localStorage API](https://github.com/concourse/concourse/blob/master/web/public/elm-setup.js#L90-L110). Reading from localStorage happens in a similar way, but instead of `Effect`s we make use of the [`Subscription`](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Subscription.elm#L34) type which hooks up to an [inbound port](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Subscription.elm#L34) and when [run](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Subscription.elm#L139-L140) also hits the localStorage API in a similar fashion.

The reason we use these thin wrappers (`Effect` wraps a port which returns `Cmd`s which invoke a thin piece of Javascript as a side effect) because it makes for [easier testing](https://github.com/concourse/concourse/blob/master/web/elm/tests/SideBarFeature.elm#L1776-L1778) and brings as much business logic as possible into the Elm code, keeping it out of `Cmd` callbacks (which are harder to test) or Javascript (which I generally consider less fun to maintain).

### A better localStorage interface

I think it probably makes sense to standardize the ways that we access localStorage so it feels a bit more like talking to the API -- maybe it's understood that we JSON-encode stuff to save there and JSON-decode the strings we read from it. This is more of an architecture idea to help make similar changes cheaper in the future

### Saving favourites

Probably we could save an array of strings at a key like `"favorite_pipelines"`. If we don't get a solid JSON-encoding approach established, we could just have an Effect like `SaveFavoritePipelines (Set Concourse.PipelineIdentifier)` and a Subscription `LoadFavoritePipelines`. Whatever happens, I think it's a good idea to keep the ports thin, though.

## Design

Anything that comes through a PR is probably gonna get some feedback from @Lindsayauchin and/or @matthewpereira. I'll take a stab here and invite them to comment further if I'm way off base.

### Setting Favorites

I think there could be some kind of widget on the pipeline cards on the dashboard (like a [star icon](https://material.io/resources/icons/?search=star&icon=star_border&style=baseline) to the left of the pipeline name in the card header) that you can click to toggle favorite/non-favorite, similar to how the show/hide eyeball icon works now. However, if the pipeline cards feel too busy, this could be hidden behind another click (like a little [more icon](https://material.io/resources/icons/?icon=more_vert&style=baseline) you can click to expand to show more icons on the card) as it's not likely to be accessed super often. I can imagine the eyeball and star living together in this menu... we could go back and forth on the details, but you probably get the picture.

In terms of implementation, these kinds of client-side state changes are pretty well-established in the sidebar and its tests. You could show some loading spinners while the calls to localStorage are happening, but they're probably gonna be nearly instantaneous for the cases I can think of off the top of my head.

### Filtering for Favorites

This is kinda up in the air as far as I'm concerned.

* I can imagine having a star button in the top bar that lets you toggle favorites on (only show faves) or off (show all). This state should probably be persisted in the URL, like `http://my.concourse.url?favorites=true`.
* Another choice would be to add another type of top-level [`GroupFilter`](https://github.com/concourse/concourse/blob/master/web/elm/src/Dashboard/Filter.elm#L109-L111) so that including `+favorites` in your search string would change the current filter to only include favorites. Fortunately, we're already persisting the search string in the URL, so you could get that part for free here. I guess this approach would mean no favorites on the high-density view, since it doesn't have a search bar.

### Favorites section

An alternative to filtering would be to just always show favorites at the top of the dashboard. Presumably you could have favorites from multiple different teams, so this way you could make more efficient use of the vertical space and show them as though they were all in one "virtual" team.

**Comment by matthewpereira** [comment]
Just to update everyone on this thread: the Concourse team has put a new epic into our backlog to describe an MVP feature for Favorite Pipelines, and it should be picked up by an engineer sometime late this week or next week. https://github.com/concourse/concourse/issues/5434

We can keep this issue around for discussion/feedback so that it's all in one place, if that works best for everyone.

**Comment by matthewpereira** [comment]
Updating and closing this thread: Favorite Pipelines shipped with v6.5.0, and is available for evaluation.

If anyone has feedback or further requests in this respect, please direct them to https://github.com/concourse/concourse/discussions/6028 

We have further work we'd love to complete in this area of the app, and getting your input is crucial to make sure we make our efforts as effective as possible. 🙇
