### ISSUE TITLE
Update cf dex connector to use the `authorization_endpoint`

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#2649]
Issue to track:
https://github.com/concourse/dex/issues/4

**Comment by gobeila** [comment]
Has a version been targeted for the correction of this? 

This issue prevents us from updating our Concourse instances to 4 since we use CF authentication on an external SSO provider (SAML). The token_endpoint points to the internal UAA of CF while the authorization_endpoint points to the authentication provider.

This seems to be already fixed in dex: https://github.com/concourse/dex/commit/0d46e2edee94a71203408bd46691d02a16020bfb

**Comment by jama22** [comment]
This is actually fixed and targeted for Concourse 5.0 release https://github.com/concourse/dex/commit/0d46e2edee94a71203408bd46691d02a16020bfb

**Comment by vito** [comment]
Quick note: this ended up being backported to v4.2.3 - updated the milestone accordingly.

**Comment by gaigaslab-operations** [comment]
@vito I see that 4.2.3 has been released.  Is there any ETA on updating the BOSH release which we use to deploy?

**Comment by vito** [comment]
@gaigaslab-operations known issue, we're working on it!: https://github.com/concourse/concourse-bosh-release/issues/13
