### ISSUE TITLE
Consume resources v2 interface & merge "spaces" branch in ATC

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#2651]
Convert spaces branch in the old atc repository to the new global-resources branch in the one big concourse repository. There will be a lot of differences since we have to move it over to the new database schema with the global resource versions.

Another part of this issue is to implement the resources v2 interface along with the merge. We want to implement it as part of this story because the spaces branch had to hack out radar since the resources v2 interface was not mapped out at the time. Now that we have a good idea of what the interface should look like, we can start from the beginning (radar) and work from there in order to make sure the structure of our implementations are correct. Our strategy is to implement radar with the v2 interface, then use the spaces branch to pull in the implementation of scheduler and then api.

A few notes to take into consideration:
- The migration will rely on the fact that the global resources migration will blow away all resource version history

To do :
- [ ] All the previous builds will be referring to a "default" space that is created in the migration, **this will be something we have to continue to think about** since it might be weird for users to always have this default space which holds all their previous builds after they migrate

**IMPORTANT**: The source of truth for the implementation of the v2 interface is outlined in the [rfc](https://github.com/concourse/rfcs/pull/1). This issue is for developer comments which can be outdated at any time.

**Comment by clarafu** [comment]
Things to do:

- [ ] Add a migration to master to remove the materialized views
```
  -- DROP MATERIALIZED VIEW transition_builds_per_job;
  -- DROP MATERIALIZED VIEW next_builds_per_job;
  -- DROP MATERIALIZED VIEW latest_completed_builds_per_job;
```

**Comment by clarafu** [comment]
Along with this issue, we will refactor to use the name `resource versions` instead of `resource config versions`. Technically the name should be `resource config space versions` but a long and precise name does not make it easier for people to understand what it does or might even confuse even more (such as pen-pineapple-apple-pen). Therefore we will shorten to the naming of versions to `resource versions` as this is clear enough to understand the purpose of this object/table.

**Comment by clarafu** [comment]
We just finished a discussion about how put steps will work with spaces. The following are the steps laid out for both the v1 and v2 flows for a put step: 

v1 Put Step
1.  Run put script (returns one version)
2. Save resource version
3. Save output
4. Run `get` for new version

v2 Put Step
   1. Run put artifact (returns multiple versions from multiple spaces)
   2. Save resource versions for all spaces
   3. Save outputs for all versions
   4. Run `check` to reorder the versions
   5. Run `get`?

We decided that the `check` after the put within v2 will run the check **from the current version**. This means that if the put step created any versions before the current version, it will not be checked. We ran through three different versioning situations to make sure that this rule makes sense:
  - Git versioning: commits made before current version by force pushing will result in new commit hashes for the current version
  - Semver versioning (ex. S3): creating a previous version is an unlikely scenario semantically
  - Single state versioning (ex. docker): ordering of versions does not matter because new versions always replace old versions

Another thing we discussed is the `get` that happens with the `put`. This does not make much sense if we are deleting a version within the `put` so we decided that having the `get` be opt in might be a better idea. It would look something like this in the pipeline config:
```
- put: some-resource
  get: latest
```
This then introduces the problem of which space `latest` grabs from since a put step can create multiple versions within multiple spaces. After coming up with a couple of solutions that would involve lots of backwards incompatibility, we decided to go with having the `put` step only be able to make changes/create a single space. This would mean that `latest` would grab from the latest version within that space. This still make it backwards incompatible but it is necessary if we are going to add the ability to delete versions using a `put`.

**Comment by clarafu** [comment]
With the `put` artifact only affecting one space, there will be changes to the response.
```
{"space": "sample-space"}
{"type": "created", "version": {"ref": "v1"}}
{"type": "deleted", "version": {"ref": "v2"}}
```

Streaming this response is actually not necessary because we will not be parsing/saving each version individually due to implications with the put step implementation. Even though returning a simple JSON would be sufficient for the `put` response, we decided to stream because consistency with the `check` interface and so that implementing the event streaming in the future will be easier.

**Comment by mhuangpivotal** [comment]
The way we determine if a resource is v1/v2 is by running the `/info` script. If there are no errors, then it's a v2 resource; if the script does not exist, then it is a v1 resource.

To check if the resource is v1, we are checking that the error string contains "/info: no such file or directory" (system error ENOENT). This works on Linux workers, but may not work on other systems (if they are supported in the future).

We needed to do a string comparison because the error type came from Guardian which includes either file not existing error or file not executable error (https://github.com/cloudfoundry/guardian/blob/80d2d6ab6f4b7ed489401eefcf2ef3b2fdc86482/rundmc/execrunner/dadoo/execrunner.go#L172).

**Comment by mhuangpivotal** [comment]
While we were working on the new behaviour for the v2 interface check, we noticed that there is a saveGiven boolean that is used for whether or not we will save the given `from` version. The reasoning behind it is that we want to save the given version if the check came from a `fly check-resource` but we do not want to save the given version if it came from a radar interval check because we know that the given version already exists.

Instead of creating this behaviour within the new v2 interface, we decided to change the response from the resource entirely. In this new response, we would not return any versions if the only version returned by the check is the given version. This way we won't have that difference in behaviour for `fly check-resource` and radar scans. This also results in us needing a different way of telling atc which spaces still exist or need to be deleted. All these questions led us to the solution of using event messaging with the following structure in this [gist](https://gist.github.com/vito/326acf50ee6bf43605b56a6f0a050ac3).

**Comment by mhuangpivotal** [comment]
While implementing the `put` step, we wanted to perform a `check` after to validate the new versions returned and to fetch the metadata, but this was difficult/inefficient to do as it required keeping track of all versions in memory.

Instead, we are thinking to change versions the `put` response to include metadata and to be ordered chronologically. This makes the `put` response more symmetrical to the `check` response. The put step will now be responsible to run the put artifact, then use the latest version returned by the put for the implicit get. Along with this change, we will be making the implicit get after the put optional. It will look something like
```
- put: some-resource
    get: true
```

**Comment by clarafu** [comment]
Merging the current master which has resource config scopes with the current spaces branch caused some complications. One major decision that came out from the merge was that the flow will be similar to this:

    Resource Configs -> Resource Config Scopes -> Spaces -> Versions

Since spaces are returned by checks and each check happens depending on what scope the resource uses, it made more sense for spaces to belong to each scope.

There were a few more changes to the implementation that came about from this merge.
- [ ] Add back saving metadata on resource cache and that metadata is emitted to the event stream on cache hit. 
- [ ] Get and Put interface will return metadata and emit to the event stream
- [ ] Get and Put saves metadata (only if the version exists) in both v1 and v2 and does not insert unchecked version

**Comment by vito** [comment]
Closing this as we've taken a step back regarding the approach to spaces - the New Beginning is here: https://github.com/concourse/rfcs/pull/24
