### ISSUE TITLE
Adding delete/edit target to fly

### ISSUE THREAD

**Issue by YoussB** [concourse/concourse#2659]
## What challenge are you facing?

Sometimes, operators would need to edit a target or remove old targets. This is currently only possible only from the `.flyrc` file. better to have commands for that.

## What would make this better?

implementing new `fly delete-target` and/or `fly edit-target`

**Comment by pivotal-kahin-ng** [comment]
@YoussB  In the ideal scenario, how would `fly delete-target` look like? 

Theses are just a few ideas I had in mind:
1.    `fly -t target delete-target` which deletes the current target?
2. `fly -t target delete-target --to-delete targetName` which deletes the specified target?
3. `fly delete-target --to-delete targetName` which also deletes the specified target?
4.   `fly delete-target --all` which will delete all the targets? 

I'm leaning towards option 3 and 4? What are your thoughts?

**Comment by aegershman** [comment]
Unsolicited opinion: I think 3 or 4 would be ideal. Here's why:

- it appears to be keeping in step with [how the bosh-cli does things](https://github.com/cloudfoundry/bosh-cli/pull/409)
- doing `fly -t target delete-target` feels like I'm about to accidentally destroy my pipelines.
- in my opinion, when you use a "target flag" it feels like you're going to be acting on something external. A target flag feels like you're signaling "I want to go act upon the external world; do <some action> to <a specific target>". But if you have `fly <command-without-target>` it feels more like you're acting on your "local" context.

Also, sidenote, instead of `delete-target` you might consider `unset-target`. It sounds less... destructive?

**Comment by taylorsilva** [comment]
Closing because https://github.com/concourse/concourse/pull/2893 was merged.
