### ISSUE TITLE
pinning/unpinning a resource version from fly

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#2702]
It seems appropriate, if we are going to be able to pin resource versions from the web UI (#2508) then we should also be able to do it from fly. I suspect the basic syntax might be

```
fly -t <target> pin-resource -r <pipeline-name>/<resource-name> -v <version>
fly -t <target> unpin-resource -r <pipeline-name>/<resource-name>
```

A potential problem here is that resource versions could be arbitrary JSON? I suspect it would be a bit unwieldy to say something like

```
fly -t dev pin-resource -r booklit/booklit -v {"ref": "723f16754b8939a486fcdd35d569a0686ff9ceec"}
```

so maybe it would make more sense to provide some kind of jsonpath/regex expression for `<version>`.

**Comment by xtremerui** [comment]
In order to pin a resource, one must know the version first. 

For now in Fly there is no command for listing resources https://github.com/concourse/concourse/issues/869 or resource versions. The resource versions are only shown on web UI or fetched from api endpoint `/api/v1/teams/:team_name/pipelines/:pipeline_name/resources/:resource_name/versions`, whose example response for team `main` pipeline `concourse` resource `mock-resource` is

```
{
	id: 740908,
	type: "github-release",
	metadata: [{
			name: "name",
			value: "v0.5.1"
		},
		{
			name: "url",
			value: "https://github.com/concourse/mock-resource/releases/tag/v0.5.1"
		},
		{
			name: "body",
			value: ""
		},
		{
			name: "tag",
			value: "v0.5.1"
		},
		{
			name: "commit_sha",
			value: "70b8b0efe61d2eeb877f1f30720d972fdeecf0cd"
		}
	],
	resource: "mock-resource",
	version: {
		tag: "v0.5.1"
	},
	enabled: true
}
```
one would need to parse the version out programmatically.

**Comment by chenbh** [comment]
Started working on this with @cirocosta, I believe we are going with 
```
fly -t <target> pin-resource -r <pipeline-name>/<resource-name> -i <version-id>
fly -t <target> unpin-resource -r <pipeline-name>/<resource-name>
```
Where you can get the `version-id` by calling
```
$ fly -t <target> resource-versions --resource=<pipeline-name>/<resource-name>

id      version                                       enabled
148973  ref:6e6da90ca9cef2b293482545ed0ac2fb5ca568bc  yes
148972  ref:921e968df19a06272f9571b9cc7aa4d96c91cfdc  yes
148971  ref:bb518ed06a5d973d76318ca83d62522c0b4ea8d7  yes
148969  ref:6cd995c0b36fa36d99e8e527339ace5270da0282  yes
```

This is so that we don't have to worry about adding custom support for every resource type and keep it pretty agnostic.  

Does anyone have any suggestions?

**Comment by vito** [comment]
(I don't think this is in-flight anymore but replying for posterity...)

That sounds fine to me, though it's not very pretty UX-wise as finding the ID seems cumbersome. But I see why it's done that way - referencing versions is somewhat difficult since they're a key-value map and there's no easy lookup from that to the ID in the API. (Maybe that should be added at some point?)

**Comment by cirocosta** [comment]
Hey,

Just a reminder that now we're unblocked regarding the version retrieval 😁  https://github.com/concourse/concourse/issues/3932
