### ISSUE TITLE
Is there a way to set ldap as default auth method at login page?

### ISSUE THREAD

**Issue by drduker** [concourse/concourse#2708]
Concourse 4.2.1

I'm just wanting to know if there is a way that the ldap auth url can be set to default "auth/ldap?"

Not go to "/auth?access_type=offline" or "auth/local?"

Since most of our users use ldap it would make sense if they didn't always have to click on the ldap button first.

Any assistance appreciated!!!

**Comment by jama-pivotal** [comment]
Oh that's interesting. So to make it more generic, maybe if there's only one auth connector configured we should always default it to that path, instead of making folks click on that button. The same could be said if folks only configured GitHub auth to their instance; its a bit silly to have to click on GitHub every time

**Comment by pivotal-jwinters** [comment]
@jama-pivotal @drduker if LDAP (or local auth) is the only connector configured you will automatically be redirected to the username/password screen to login.

**Comment by drduker** [comment]
Local auth has to be available in case ldap goes down.  But ldap is the desired default screen.  Good to know thoug.

**Comment by xtremerui** [comment]
So maybe other then local auth we can default to the only auth provider, if configured
