### ISSUE TITLE
Remove "allow all users" ability

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2721]
## What challenge are you facing?

It's currently possible to configure `--main-team-allow-all-users` (and `--allow-all-users` on `set-team`), which will do what it says on the tin: allow literally everyone that can log in to be a member of the team. This is almost certainly a bad idea in production scenarios, and we really don't have a strong need for it during development either, since we can just list the `test` user.

## What would make this better?

Let's just remove it. It broke with https://github.com/concourse/concourse/issues/2670 anyway.

## Are you interested in implementing this yourself?

Nah, y'all do it.

**Comment by xtremerui** [comment]
We need to consider migration of `teams` table since if someone config a team with `--allow-all-users`, the `auth` would be
`{"owner":{"groups":[],"users":[]}}` after the migration ran as in https://github.com/concourse/concourse/blob/a08dce30f205088b20c02dd3692c2fd4775ea4d3/atc/db/migration/migrations/1537196857_add_team_roles.up.sql#L1-L3


With this change, it is impossible to config a team to allow all users access anymore. Then this value would be invalid.

Solutions could be:
1. Copy the auth config from main team so admin users in main team could have access to this specific team at least. But problem is, if main team was configured with `--allow-all-users`, the auth would be also invalid.
2. Fail the migration by forcing user to reconfigure the team to has auth config without `--allow-all-users`

**Comment by vito** [comment]
@xtremerui maybe we should just permit existing configurations to work as they did before (but still prohibit configuring it), and fix the behavior which was broken with #2670?
