### ISSUE TITLE
Problem upgrade from 3.x to 4.x - Migration Failure

### ISSUE THREAD

**Issue by ghost** [concourse/concourse#2724]
## Bug Report

I'm attempting to upgrade to 3.13 to 4.2.1 and I ran into an issue with migrations.

```
failed to migrate database: 1 error occurred:

* Migration '1510262030_initial_schema.up.sql' failed: 2 errors occurred:

* Transaction CREATE TYPE build_status AS ENUM (
        'pending',
      'started',
      'aborted',
      'succeeded',
      'failed',
      'errored'
  ) failed, rolled back the migration
* pq: type "build_status" already exists
```

## Steps to Reproduce

I'm not entirely sure how to reproduce this. But I can't delete this `TYPE` because it's being referenced by a table.

This might be because I accidentally ran multiple web nodes at the same time on the new version. Each of which attempted to migrate, and one of them ultimately failed.

## Expected Results

Migrations are idempotent

## Actual Results

A migration most likely started, got interrupted, and I cannot continue the migration.

## Additional Context

I checked out this page:
https://github.com/concourse/concourse/issues/2074

```
SELECT * FROM public.schema_migrations
ORDER BY version ASC 

"1524079655"	false
```

## Version Info

* Concourse version: 4.2.1
* Deployment type (BOSH/Docker/binary): Kubernetes/docker
* Infrastructure/IaaS: Kubernetes
* Browser (if applicable): N/A
* Did this used to work? First time trying to upgrade to 4.2.1

**Comment by wesm-outreach** [comment]
I've updated the schema_migrations table by adding the migration that failed but didn't, and it seems to be ignoring it.

![image](https://user-images.githubusercontent.com/22123857/47397911-5c0d5580-d6e6-11e8-93b2-df7b01da523a.png)

still seeing the same error. I'm not sure how to get it to skip the migration.

**Comment by wesm-outreach** [comment]
`migrations_history` table

```
1510262030	2018-10-23 22:02:06.585918+00	up	failed	f
1510262030	2018-10-23 22:02:09.280937+00	up	failed	f
1510262030	2018-10-23 22:02:27.597743+00	up	failed	f
1510262030	2018-10-23 22:03:01.731454+00	up	failed	f
1510262030	2018-10-23 22:03:43.557971+00	up	failed	f
1510262030	2018-10-23 22:03:51.426334+00	up	failed	f
1510262030	2018-10-23 22:04:26.275514+00	up	failed	f
1510262030	2018-10-23 22:05:20.591896+00	up	failed	f
1510262030	2018-10-23 22:08:05.592514+00	up	failed	f
1510262030	2018-10-23 22:09:05.630985+00	up	failed	f
1510262030	2018-10-23 22:09:28.253451+00	up	failed	f
1510262030	2018-10-23 22:13:20.735638+00	up	failed	f
1510262030	2018-10-23 22:14:07.53764+00	up	failed	f
1510262030	2018-10-23 22:14:30.278525+00	up	failed	f
1510262030	2018-10-23 22:18:24.563722+00	up	failed	f
1510262030	2018-10-23 22:19:21.634351+00	up	failed	f
1510262030	2018-10-23 22:19:40.386001+00	up	failed	f
1510262030	2018-10-23 22:23:28.6204+00	up	failed	f
1510262030	2018-10-23 22:24:28.50565+00	up	failed	f
1510262030	2018-10-23 22:24:52.460674+00	up	failed	f
1510262030	2018-10-23 22:28:37.577366+00	up	failed	f
1510262030	2018-10-23 22:29:37.428703+00	up	failed	f
1510262030	2018-10-23 22:33:49.750433+00	up	failed	f
1510262030	2018-10-23 22:47:57.219383+00	up	failed	f
1510262030	2018-10-23 22:47:59.89553+00	up	failed	f
1510262030	2018-10-23 22:48:17.597057+00	up	failed	f
1510262030	2018-10-23 22:48:47.573377+00	up	failed	f
1510262030	2018-10-23 22:49:38.676429+00	up	failed	f
1510262030	2018-10-23 22:49:44.645984+00	up	failed	f
1510262030	2018-10-23 22:49:46.861564+00	up	failed	f
1510262030	2018-10-23 22:50:10.627322+00	up	failed	f
1510262030	2018-10-23 22:50:32.723291+00	up	failed	f
1510262030	2018-10-23 22:51:03.63018+00	up	failed	f
1510262030	2018-10-23 22:51:20.493196+00	up	failed	f
1510262030	2018-10-23 22:52:47.504089+00	up	failed	f
1510262030	2018-10-23 22:53:56.574463+00	up	failed	f
1510262030	2018-10-23 22:55:39.525395+00	up	failed	f
1510262030	2018-10-23 22:55:52.148752+00	up	failed	f
1510262030	2018-10-23 22:55:54.56834+00	up	failed	f
1510262030	2018-10-23 22:55:55.668139+00	up	failed	f
1510262030	2018-10-23 22:55:58.329878+00	up	failed	f
1510262030	2018-10-23 22:56:10.46026+00	up	failed	f
1510262030	2018-10-23 22:56:26.729408+00	up	failed	f
1510262030	2018-10-23 22:56:32.645586+00	up	failed	f
1510262030	2018-10-23 22:56:58.10141+00	up	failed	f
1510262030	2018-10-23 22:57:18.439862+00	up	failed	f
1510262030	2018-10-23 22:57:40.082543+00	up	failed	f
1510262030	2018-10-23 22:58:52.671192+00	up	failed	f
1510262030	2018-10-23 22:59:02.092881+00	up	failed	f
1510262030	2018-10-23 23:01:32.384311+00	up	failed	f
1510262030	2018-10-23 23:01:34.642273+00	up	failed	f
1510262030	2018-10-23 23:02:01.334181+00	up	failed	f
1510262030	2018-10-23 23:02:30.576382+00	up	failed	f
1510262030	2018-10-23 23:03:17.175454+00	up	failed	f
1510262030	2018-10-23 23:04:46.200648+00	up	failed	f
1510262030	2018-10-23 23:07:31.169948+00	up	failed	f
1510262030	2018-10-23 23:12:42.563358+00	up	failed	f
1510262030	2018-10-23 23:17:45.336218+00	up	failed	f
1510262030	2018-10-23 23:22:53.194139+00	up	failed	f
1510262030	2018-10-23 23:27:58.184239+00	up	failed	f
1510262030	2018-10-23 23:33:10.387742+00	up	failed	f
1510262030	2018-10-23 23:38:15.2005+00	up	failed	f
1510262030	2018-10-23 23:43:21.301342+00	up	failed	f
1510262030	2018-10-23 23:47:54.817915+00	up	failed	f
1510262030	2018-10-23 23:47:57.873845+00	up	failed	f
1510262030	2018-10-23 23:48:20.639072+00	up	failed	f
1510262030	2018-10-23 23:48:51.579979+00	up	failed	f
1510262030	2018-10-24 00:05:46.044425+00	up	failed	f
1510262030	2018-10-24 00:05:48.443102+00	up	failed	f
1510262030	2018-10-24 00:06:09.491186+00	up	failed	f
1510262030	2018-10-24 00:06:31.513924+00	up	failed	f
1510262030	2018-10-24 00:07:14.497338+00	up	failed	f
1510262030	2018-10-24 00:08:44.523261+00	up	failed	f
1510262030	2018-10-24 00:13:46.321625+00	up	failed	f
1510262030	2018-10-24 00:18:50.67046+00	up	failed	f
****
```

**Comment by ddadlani** [comment]
For anyone encountering this exact issue in the future, this is likely because of unexpected interaction between multiple ATCs and the database while one ATC is migrating up.

To restore the database schema to a sane state:

CAUTION: This only applies if you are updating from any version < 4.1.0 to 4.1.0 or above. This also only works if the rows in the `migrations_history` table are all `dirty=f`. If any of the migrations are `dirty=t`, your database is in a dirty state and you should probably not change anything unless you are absolutely sure of what you are doing.

1) ensure that the only row in the `schema_migrations` table is version: 1510262030, dirty: false.
2) ensure that the only failing migration  in the `migrations_history table is 1510262030.
2) (optional) remove any `failed` entries where `dirty=false` from the `migrations_history` table. 

You can then start up one ATC, allow it to complete the `up` migrations and then start up any other ATCs.

We are currently investigating the cause of this issue.

**Comment by ddadlani** [comment]
@wesm-outreach For some more debugging context, could you tell us how your Concourse instance is deployed? Do you use BOSH?

**Comment by ddadlani** [comment]
@wesm-outreach Can you also confirm whether or not your database user has permissions to `information_schema.tables`? You can run this to find out:
```
SELECT table_catalog, table_schema, table_name, privilege_type
FROM   information_schema.table_privileges
WHERE  grantee = '<your_pg_user>' AND table_name='tables';
```
Our migration depends upon the ability to read this table, so that might be the issue.

**Comment by ddadlani** [comment]
We confirmed that the issue is related to not having permission to view `information_schema.tables`. Our fix is to check for the existence of a table by doing `select * from table...` in the case where `information_schema.tables` returns false.

This will cause there to be error logs in the database, such as `error: pq relation 'table' does not exist` but these are safe to ignore.

**Comment by dprotaso** [comment]
I've just encountered the same problem upgrading from 3.6.0 to 4.2.1

**Comment by dprotaso** [comment]
I've discovered the problem

When migrating away from the old `migration_version` table to the `schema_migration` it stages the version here

https://github.com/concourse/concourse/blob/ed215777de0f2ba5e95c382a0e7cd5da21093af0/atc/db/migration/migration.go#L136

When querying the version to determine which migrations to run it uses a different table `migrations_history` here:
https://github.com/concourse/concourse/blob/ed215777de0f2ba5e95c382a0e7cd5da21093af0/atc/db/migration/migration.go#L192

This table is not populated when `schema_migration` is initially staged.

**Comment by ddadlani** [comment]
The `schema_migrations` table gets populated for the first time in Concourse v3.7. The new `migrations_history` (added in v4.1) expects the `schema_migrations` table to be populated as it uses that to determine what migrations have already been run.

What happened here was the @dprotaso attempted an upgrade from v3.6 to v4.2.1 (because our website didn't mention anything about v3.7+). The website has since been updated to mention that you should upgrade to any version between v3.7-v4.0 inclusive, before upgrading to v4.1 or above.

**Comment by geofffranks** [comment]
Running into this issue as well. I had upgraded from 3.6 to 4.2.1 not having seen a note about going to 3.7-4.0 first. I then backed off from 4.2.1 to 4.0.0, which launches fine, but any subsequent upgrades to 4.2.1 or 5.2.1 or 5.4.1 all fail with this same migration failure.

```

atc=> select * from migrations_history;
  version   |            tstamp             | direction | status | dirty
------------+-------------------------------+-----------+--------+-------
 1510262030 | 2019-08-25 02:42:32.322161+00 | up        | failed | f
 1510262030 | 2019-08-25 02:42:32.754525+00 | up        | failed | f
 1510262030 | 2019-08-25 02:42:33.259359+00 | up        | failed | f
(3 rows)

atc=> select * from schema_migrations;
  version   | dirty
------------+-------
 1530824006 | f
(1 row)
```

Not sure what to do here since i feel like if 4.0.0 is launching, it should then be able to upgrade past 4.1? A `select * from information_schema.tables` returns a ton of results, so it seems like it's not the permissions issue mentioned here.

Any help would be much appreciated

**Comment by geofffranks** [comment]
Amazing! Thank you!
