### ISSUE TITLE
Custom Ordering of Jobs

### ISSUE THREAD

**Issue by simondiep** [concourse/concourse#2762]
## What challenge are you facing?

It is very difficult and frustrating for me to find a specific job in a pipeline that displays jobs in a single column, when the jobs are not ordered in any reasonable manner.

For example: 
```
[ B ]
[ A ]
[ D ]
[ E ]
[ F ]
[ C ]
```

## What would make this better?

Display the jobs in the order I specify in my pipeline.yml file.

```
jobs:
    - A
    - B
    - C
    - D
    - E
    - F
```

## Are you interested in implementing this yourself?

Possibly, if pointed in the right direction

**Comment by marco-m** [comment]
I like the idea. I would even call this feature (and so the ticket) "natural order of jobs", there is nothing custom here :-)

**Comment by OvermindDL1** [comment]
> The current pipeline rendering algorithm is done so that it minimizes the frequency of crossing lines.

Just passing through but it is definitely not minimizing crossing lines?  At https://ci.gregtech.overminddl1.com/teams/gregtech/pipelines/GT6 the `regen-static-site` inputs could be swapped so they don't cross, the `broadcast-update-versioned` could go between `deploy-forum-post` and `-regen-static-site` just as an initial notice (right now `broadcast-update-versioned` is being put into the middle of `deploy-snapshot`'s later pipeline entries, which is very weird...).

> Combine this with the upcoming spatial resources feature, we are leaning towards a pipeline that's rendered purely in HTML.

I'd be for that.  This whole Elm interface is *very* irritating at times, it stops updating randomly (especially in firefox), lags at odd times, etc...  Using a server push for updates would be far better as well instead of client polling (which with a lot of views is noticeable costly on the server...), where a simple server push or websockets would be far *far* superior in efficiency (or websockets with fallback to longpolling, as long as it is not the hugely inefficient quickpolling it is doing now).

**Comment by simondiep** [comment]
@jama-pivotal Would it be easy to add an opt-out of auto ordering flag?  That way, my single column of jobs could be ordered the way I want, since they are not connected in any way to each other.

**Comment by draeron** [comment]
ordering seems to be by label's length, it would be useful to have it alphabetically

![image](https://user-images.githubusercontent.com/2256246/50181530-a8d26e80-02da-11e9-946c-2a1a580630f6.png)

**Comment by vito** [comment]
FWIW, we're planning a new pipeline UI, so I wouldn't recommend making any changes to the current one. If you stare into that code it will stare back into your soul.

I don't really like the idea of customizing the ordering in the YAML, since tying it so closely to UI feels like a smell, but it could be interesting to preserve the order that the jobs are defined in in tie-breaker scenarios where there is no natural order as determined by the pipeline layout heuristics.
