### ISSUE TITLE
Create a Metric that displays how long a worker has been stalled

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#2778]
**Summary**

We recently completed a story to allow us to emit metrics for worker by state: https://github.com/concourse/concourse/issues/2186

We've run into some incidents on Wings recently where workers are stalled for extended periods of time. Now that we can emit metrics for stalled workers, it would probably be a good idea to display how long a worker has been stalled. 

**Proposal**

Create a metric that will display the length of time a worker has been stalled. It may also be a good idea to play with the possibility of providing an alert when a worker has been stalled for a given amount of time.

**Comment by cirocosta** [comment]
Hey @scottietremendous ,

I just noticed that this issue is a duplicated of:

- https://github.com/concourse/concourse/issues/2499

Although at first, it might seem like there are no timestamps, that's just because the timestamps are provided by the system that's picking these metrics (be it Prometheus or InfluxDB). 

I'll go ahead Closing it in order to keep the discussion in the original one. 

thx!
