### ISSUE TITLE
A way of preventing a pipeline from triggering when already executing

### ISSUE THREAD

**Issue by Jonty** [concourse/concourse#282]
We have several pipelines that must not execute multiple times concurrently, and should not trigger again until the pipeline finishes running. While we can use `serial_groups` to prevent the jobs executing concurrently, and `pool` locking to prevent it triggering until it has completed, this is very verbose, ugly and easy to get wrong.

Ideally we would love to see an option on a pipeline that prevents it from triggering again until it has finished executing.

**Comment by vito** [comment]
The semantics for this are really awkward to me. A pipeline is just a set of jobs, and may actually contain multiple sub-pipelines. I prefer having these relationships expressed explicitly via the `pool` resource, but I can see how it can sometimes be error prone or verbose. I'd like to see a proposal for this that doesn't operate on the whole pipeline, but has some way to express which parts should be serial without getting too verbose.

Perhaps we could replace `serial_groups` with this proposal, since that's often how people expect it to work?

**Comment by vito** [comment]
Closing this for the reason I initially stated, but having some proposal related to redoing `serial_groups` could be an interesting next step.
