### ISSUE TITLE
Worker should sweep containers and volumes in parallel

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2833]
## What challenge are you facing?

If a worker has a bunch of containers and volumes coming and doing, the sweeper can be too slow to keep up.

## What would make this better?

Right now we delete all the containers one by one, and then delete all the volumes:

https://github.com/concourse/concourse/blob/2a2e30516336ab09974939572f7c45af82c3e4b0/worker/sweep_runner.go#L77-L97

We can/should do this in parallel with a reasonable max-in-flight for the containers.

There might not be much point in deleting the volumes themselves in parallel to each other, but we should at least be able to do it while we're destroying containers.

Note: if we *do* want to delete volumes concurrently to each other, we'll need to change BaggageClaim, since right now that's a single API call with a big list of handles.

**Comment by vito** [comment]
FWIW it looks like we do destroy volumes in parallel, though I kind of wonder how effective that is and whether it's just unnecessary strain on disk. Would be nice to measure that.

https://github.com/concourse/baggageclaim/blob/8c6fe76a80e6bf0a5c8e651bea8877f32b98c2ae/api/volume_server.go#L257

**Comment by topherbullock** [comment]
Oof, especially given some of @kcmannem 's discoveries around btrfs' ability to keep up in terms of block gc and fragmentation of the volumes we're throwing at it, and the frequency of volume creation / COW creation / deletion Concourse throws at it.

Maybe we should add some bounds to the parallelism here, rather than wildly spawning go routines

**Comment by vito** [comment]
Yeah definitely.

Also: these should probably be parallelized on their own intervals. An implementation that simply GCs containers and volumes in parallel and waits for both to complete before the next tick could still end up slowing down container or volume GC if either end is slow enough. It would be better if there was a separate container GC interval and a separate volume GC interval.

**Comment by ddadlani** [comment]
Containers and volumes now each have their own sweeper. Each sweeper still runs on a 30s interval, but since they are decoupled, volume deletion does not wait on container deletion and vice versa. 

In addition, volumes and containers are also deleted in parallel. We made changes to baggageclaim to expose the `DestroyVolume` method to the API to facilitate individual volume deletion.

Using trial and error, we found that setting a max-in-flight of 5 for containers was optimal, i.e. provided the lowest latency(average deletion time per container) while keeping CPU load low (on the local `docker-compose` `overlay-fs` setup). For volumes, a max-in-flight of 10 is better, but because `docker-compose` does not use `btrfs` we are keeping both max-in-flight values to 5 (which we can later adjust based on observed system load). 

For now the max-in-flight value is a constant. Are there any benefits to making it configurable via a command-line flag? @kcmannem and I think that it shouldn't be configurable as users may not know what its impact is (ie. a bigger number doesn't mean better performance even on larger vms).

**Comment by cirocosta** [comment]
> In addition, volumes and containers are also deleted in parallel.

For a container that is still running but somehow is meant to be destroyed (assuming this case exists, even if edgy), should we expect the deletion to succeed? I can see that such a thing might work with `btrfs` as we're doing `btrfs` operations only ([`btrfs subvolume delete $path`](https://github.com/concourse/baggageclaim/blob/685f90a56bed9a883301df0857e70559b3fe9a7e/volume/driver/btrfs.go#L66)), but in the case of `overlay` though, [we're issuing just `umount`s](https://github.com/concourse/baggageclaim/blob/685f90a56bed9a883301df0857e70559b3fe9a7e/volume/driver/overlay_linux.go#L31-L32), which could result in `EBUSY` errors given that a process might have an open file / anything like that 🤔 

I can see that it'd eventually suceed at some point, but should we consider moving a bit away from these scenarioss? Like what we already have regarding not being able to delete volumes when child volumes are still around (damn, I can't find that issue) 🤔

Wdyt?

**Comment by vito** [comment]
@cirocosta I don't think that's an issue - volumes will only be destroyed when their containers are gone, so there shouldn't be a single 'sweep' tick that destroys a container in parallel with its volumes.

So the full flow for a container and its attached volumes is something like this:

```
volume CREATED, container CREATED
=> container marked DESTROYING by ATC
=> real container destroyed by sweeper
=> container row removed by ATC; volume owner is now gone
=> volume marked DESTROYING by ATC
=> real volume destroyed by sweeper
=> volume row removed by ATC
```
