### ISSUE TITLE
Fly Login success screen needs a proper design

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2845]
When doing a `fly login`, you are redirected to the Concourse instance to proceed with the login flow. Upon success of that flow, we push you onto a very basic and bare login success screen:

![screen shot 2018-11-21 at 11 09 30 am](https://user-images.githubusercontent.com/19274230/48864957-1f438580-ed9c-11e8-8dc8-b55a3494035d.png)

# Proposal
We need a new design for this screen because its weird, awkward, and jarring. In 90% of the use cases the person looking at this screen is going to do an `alt+tab` back to their terminal, but they'll eventually want to go back to the Dashboard. It would be nice if this screen was:

- updated so that the text at least is displayed in the Concourse UI
- user is prompted to return to fly OR go back to the Concourse dashboard

# Design

cc @Lindsayauchin for design help

**Comment by Lindsayauchin** [comment]
![success_login](https://user-images.githubusercontent.com/27746614/48910824-f4f6d400-ee3e-11e8-85e2-f56a389272cb.png)

**Comment by jama-pivotal** [comment]
Actually, we could include two new features on this page:

1) copy token to clipboard
2) click button to send token back to the fly cli in terminal

**Comment by vito** [comment]
Once this is fixed up we should also be able to remove the `-r/--remote` flag from `fly login` since they can just click the "copy to clipboard" button.

We should also remove the `redirect_uri` aspect of the login flow, and communicate the token via JS/Elm code instead when the 'send to `fly`' button is clicked.

**Comment by pivotal-jamie-klassen** [comment]
1. [ ] remove sky/token
1. [ ] have fly always request redirects like this:
http://localhost:8080/sky/login?redirect_uri=http://127.0.0.1:8080/fly_success%3Ffly_port%3D62345
1. [ ] remove `-r`
1. [ ] have indexhandler read your token from your Cookie header and render it into the source HTML
1. [ ] have web try to send your token to fly by via the given port on localhost

**Comment by pivotal-jamie-klassen** [comment]
Elm is gonna handle the `/login` endpoint, and it's gonna figure out what kind of skymarshal URL to send you to based on the presence/absence of `redirect_uri`/`fly_port` query params. Also skymarshal is no longer going to send tokens via query params, and publichandler will figure out how to extract tokens from cookies instead of query params.

**Comment by vito** [comment]
Some UX feedback: I think the big button kind of begs for it to be clicked, and it's not obvious that the page automatically transferred the token to `fly` and that the user won't usually need to copy it, since that's only for logging in via a remote shell where your browser can't reach the `fly` server.

Google's `gcloud` CLI does a very similar login flow, and at the end you end up at [this page](https://cloud.google.com/sdk/auth_success), where it says:

> The authentication flow has completed successfully. You may close this window, or check out the resources below.

Login flows like this are still a bit magical to a lot of people so it may help to have more verbiage there explaining "what just happened" and suggest that if their `fly` didn't automatically log in, they can click a (less "hero"-like) button to copy the token to their clipboard instead.

Also, maybe because I'm so used to GitHub's click-to-copy UI elements, but having an icon like this instead of/in addition to the button text would feel more intuitive: https://octicons.github.com/icon/clippy/

![image](https://user-images.githubusercontent.com/1880/49827109-8a0e2e00-fd56-11e8-9e78-a29e8d5774f3.png)

(...except we probably wouldn't want to put the token in a visible field on the page, heh.)

Style-wise it feels a bit odd to have all the blank space to the right of the box - maybe we can center this instead, similar to the login UI (but a bit wider if we need to fit more content in there)?:

![image](https://user-images.githubusercontent.com/1880/49827279-f2f5a600-fd56-11e8-8165-b30ac71bc6e5.png)

@Lindsayauchin wdyt?

**Comment by pivotal-jamie-klassen** [comment]
Talking over these points with @Lindsayauchin we've got this intermediate stage:

![screen shot 2018-12-12 at 9 47 10 am](https://user-images.githubusercontent.com/22056320/49877253-02c2c800-fdf3-11e8-9341-62d79e130c65.png)

only concrete decision there is horizontal centering, centered text and 300px width.

The verbiage is probably really bad. It might even make sense for there to be different text depending on whether the attempt to send the token to fly was successful? like

```
Your token has been sent to fly
```
or
```
A network issue prevented sending your token to fly, but you can still copy it by clicking below
```


Also we haven't yet addressed the click-to-copy thing. You've rightly identified the sense of "sensitivity" around a token. If it's really going to be helpful to have a github-like interface, it might make sense for it to be something like `<input type=password>` where the text is obscured initially (optionally with a button to show it). Or maybe it might even be good enough to add a clipboard icon to the existing button?

**Comment by pivotal-jamie-klassen** [comment]
Success:
![screen shot 2018-12-12 at 10 18 15 am](https://user-images.githubusercontent.com/22056320/49879138-51726100-fdf7-11e8-86ba-d0be8b16daf5.png)

Failure:
![screen shot 2018-12-12 at 10 20 50 am](https://user-images.githubusercontent.com/22056320/49879274-a7df9f80-fdf7-11e8-9f6d-3daad55e051e.png)

https://material.io/tools/icons/?icon=file_copy&style=baseline

**Comment by vito** [comment]
@pivotal-jamie-klassen Yeah, the clipboard icon is all I'd need in order to recognise it as a copy-to-clipboard UI element. The text field isn't so important.

I'd reduce the amount of text as much as possible since it's such a small box. There's already an icon at the top left to go to the dashboard so I don't think further instruction is necessary.

I like the idea of showing different text if sending the token failed.

How about this for a successful log-in and token transfer:

> check-in complete!
>
> Your token has been transferred to `fly`. You may now close this window.

I wouldn't bother showing a copy-token button if the token was successfully transferred.

And this for a failed token transfer:

> check-in complete!
>
> However, `fly` could not be reached for transferring the token, so you'll have to manually copy it over:
>
> [ copy token ]

This almost feels like self-service check-in kiosks vs. manual check-in so I went a little aviation themed for the header. :stuck_out_tongue:

**Comment by pivotal-jamie-klassen** [comment]
github-ized:
![screen shot 2018-12-12 at 10 31 08 am](https://user-images.githubusercontent.com/22056320/49879961-196c1d80-fdf9-11e8-95b9-11b958252e6e.png)
```
<div id="success-card" style="background-color: rgb(50, 48, 48);padding: 30px 20px;margin: 200px 30px;display: flex;flex-direction: column;width: 300px;align-items: center;text-align: center;"><p id="success-message" style="font-size: 18px; margin: 0px;">you have successfully <br> logged in!</p><p id="success-details" style="font-size: 14px; margin: 10px 0px;">A network issue prevented sending your token directly to fly, but you can copy it below:</p>
    <div style="
    display: flex;
    padding: 10px;
"><input style="
    background-color: transparent;
    color: white;
    height: 30px;
    border: 1px solid #504b4b;
    margin-right: -1px;
    outline: 0;
    font-family: Inconsolata, monospace;
    font-size: 1.15em;
" type="password">
    
    <span id="copy-token" style="border: 1px solid #504b4b;/* margin: 10px 0px; */padding: 5px;/* width: 212px; */cursor: pointer;text-align: center;background-color: rgb(50, 48, 48);display: flex;justify-content: center;align-items: center;"><div style="width: 20px;height: 20px;/* margin: 5px; */background-size: contain;background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBmaWxsPSJub25lIiBkPSJNMCAwaDI0djI0SDB6Ii8+PHBhdGggZmlsbD0iI2ZmZiIgZD0iTTE2IDFINGMtMS4xIDAtMiAuOS0yIDJ2MTRoMlYzaDEyVjF6bS0xIDRsNiA2djEwYzAgMS4xLS45IDItMiAySDcuOTlDNi44OSAyMyA2IDIyLjEgNiAyMWwuMDEtMTRjMC0xLjEuODktMiAxLjk5LTJoN3ptLTEgN2g1LjVMMTQgNi41VjEyeiIvPjwvc3ZnPgo=);"></div>
```

</span></div></div>

**Comment by pivotal-jamie-klassen** [comment]
success:
![screen shot 2018-12-12 at 11 32 05 am](https://user-images.githubusercontent.com/22056320/49883914-9f8c6200-fe01-11e8-809c-4e58d516979e.png)
```
<div id="success-card" style="background-color: rgb(50, 48, 48);padding: 30px;margin: 50px auto;display: flex;flex-direction: column;width: 330px;align-items: center;text-align: center;"><p id="success-message" style="font-size: 18px;/* margin: 0px; */">login successful!</p><p id="success-details" style="font-size: 14px;margin: 5px 0px;background-color: rgb(50, 48, 48);/* margin: 20px 0; */">
    your token has been transferred to fly.
</p>
    <p style="
    font-size: 14px;
    margin: 5px 0;
">you may now close this window.</p>
</div>
```

**Comment by pivotal-jamie-klassen** [comment]
for the record, we are using https://octicons.github.com/icon/clippy/ for the clipboard icon.
