### ISSUE TITLE
Concourse 5.0.0 Upgrade performance testing

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2874]
Concourse 5.0.0 Upgrade performance testing...because we need some upgrade simulations before we even think about doing a deployment to Wings for general user testing

**Comment by topherbullock** [comment]
Here are some ( reproducible ) things we can plan to test:

1. Run the "web-development" pipeline (or a similar pipeline) many times before upgrading
   > The web-development pipeline on prod caused a failure due to the resources migrations when we first deployed global resources
   > **post upgrade:** ensure that the dashboard + pipeline pages aren't broken 🤷‍♂️ 
1. Many pipelines configured in different teams with the same resource configured
   > **pre upgrade:**  There should  be _**x**_ check containers (x = # of teams using that resource config)
   > **post upgrade:**  there should be 1 check container
1. A pipeline with a paused resource with version(s) in use
   > **post upgrade:** paused resource should become pinned
   > **post upgrade:** Ensure that the resource can be un-pinned
1. Resource with disabled versions
   > **post upgrade:** the versions should stay disabled when the check happens again
1. Pipeline "mid-run"; 3 jobs chained together with passed constraints and **job 2** is running
   > **pre upgrade:** The versions should show as build inputs
   > **post upgrade:** The pipeline should be in a state where it needs to run again to progress to **job 2**

**Comment by cirocosta** [comment]
Hey @topherbullock @jama-pivotal,

<br />

Do you think this is something that we could have reproducible such that it could even be part of our "upgrade&downgrade" testing?

I was wondering if we could start with something like:

1. deploy 4.2.1 (or any other version that we're 
2. populate with these test pipelines and generate some "load" there 
  - automatically triggering the pipelines a bunch of times
  - pause some stuff
  - etc
3. upgrade to 5.0.0 (or, latest?)
4. perform the assertions

Wdyt?

Thx!

**Comment by topherbullock** [comment]
One note from talking to @scottietremendous and @cirocosta about this. We should ensure that this can be run against a Helm deployed Concourse so we can have additional testing to vet that it is ready for use in production and is a supported way to deploy Concourse ( #1731 )

**Comment by vito** [comment]
@clarafu and I had a chat about the different facets of this.

I think there are a few different goals we're jumbling up right now, and they each have different indicators of "success":

1. Upgrade path testing: these are specific, targeted tests for tricky cases we can think of before and after a *specific* upgrade path like v4.2.1 to v5.0.0.
    * Example: the migration for #2386 and how we represent paused/disabled resource state.
    * Success means: "before" test suite passes before the upgrade, and the "after" suite passes after the upgrade.
1. Longevity/soak testing: these are not tied to specific upgrade paths, and are meant to be a realistic (yet consistently measurable) workload exercising common *and* corner cases.
    * Example: running unit test builds periodically, exercising things like tagged workers, etc.
    * Success means: the same workloads have the same results before and after the upgrade.
1. Performance testing: similar to longevity testing, but we may have more specific examples (e.g. running Docker builds, running on tagged + untagged workers, running tests that do a bunch of I/O with tiny files, etc. etc.)
    * Examples: running Docker builds, running builds with many tasks to exercise container scheduling, configuring pipelines that share resources across teams/etc. to exercise #2386.
    * Success means: resource utilization (e.g. # containers, CPU, RAM) stayed the same or went down, builds took the same amount of time or became faster, and there are no observable leaks over time (goroutine, memory, etc).

I think for longevity/soak/performance testing, we'll want to be looking at metrics and logs instead of test suites. This would be a really information-dense way of seeing anything that stands out. We can even capture per-job metrics to see if builds became faster or went from succeeding to erroring/failing/etc. before and after the upgrade.

So the process for all of this would be...

1. Stand up a new environment that we intend to be our long-lived/upgrade path test. This can be done however we want (BOSH, K8s, whatever), and in principle we should be able to create many of these.
1. Configure a Grafana dashboard for the environment, and point the logs at Papertrail.
1. Seed the environment with the longevity/soak/performance testing data, i.e. run a script to create all the teams and pipelines.
1. Let the environment soak for a while so that we can observe a stable time range of metrics.
1. When we want to upgrade, first run any "before" suites for the upgrade path.
1. Perform the upgrade.
1. Observe critical metrics during the upgrade.
    * We don't currently expect zero-downtime, but we should avoid things like filling workers with 2x containers or other resource usage spikes.
1. Next, run the "after" suites for that upgrade path.
1. Let the environment soak for an equivalent amount of time as in step 3.
1. Compare the dashboards before and after the upgrade:
    * Are all of the jobs in the same state they were before? (e.g. succeeding jobs are still succeeding, failed jobs are still failing)
    * Do any of the metrics look better? Do any of the metrics look worse? (Are there any goroutine/memory leaks? Are we running fewer containers?)
1. Compare the logs:
    * Did we become way more chatty?
    * Are there more errors being logged? (Side note: should we expect any?)

I think it's critical that we make it easy to add examples for corner case after corner case in a reproducible way. These are things that engineers probably think of during implementation or PMs think of during acceptance. Testflight only really covers common cases, and TopGun is too heavyweight/slow to cover everything.

How's that sound?

**Comment by pivotal-saman-alvi** [comment]
For test case3 post (paused resource should become pinned), https://github.com/concourse/concourse/issues/2702 will need to be completed first.

**Comment by pivotal-jamie-klassen** [comment]
@mhuangpivotal and I were experimenting today with having a local concourse send metrics up to the prod metrics instance. Hoping to continue figuring out a way to measure 'soaked' metrics (grabbing mean and standard deviation over a fixed time period perhaps, via InfluxQL queries) of a baseline and maybe automatically set up alerts so that after the change we will automatically be notified if the metrics deviate greatly from what they were.

**Comment by clarafu** [comment]
The performance tests will not be required to be complete for the 5.0.0 release, it will be more of a long-running task where we can continue to add more use cases.

For the 5.0.0 release, we need to finish the upgrade tests and also we are hoping to do some manual check container stress testing. The concern about the check container testing comes from the fact that even with global resources disabled by default, the resources will be fetching unique version histories but they will be using one check container per resource config within the whole concourse instance. Before 5.0.0, the check container per resource config was still scoped to a team so the amount of resources using one check container was less than after 5.0.0 even with global resources disabled where any team that configures the same resource config will be using one check container. 

The stress test can consist of a very simple setup of a single pipeline config with a lot of resources. This pipeline should be set many times within many different teams. We should see that the check containers are able to handle the large amount resources requiring a check. Lets say we will use an approximate amount of 50 resources within each pipeline and 15 pipelines set.

**Comment by vito** [comment]
Calling this done:

* There's a new repo called [drills](https://github.com/concourse/drills) with a pretty dope README.
* There are metrics emitted to [this dashboard](https://metrics.concourse-ci.org/dashboard/db/concourse?refresh=1m&orgId=1&var-deployment=drills).
* There's a (minimal) pattern for adding more and more longevity/soak/performance-tests [here](https://github.com/concourse/drills/tree/master/longevity).
* The upgrade tests for 4.2.2 -> 5.0.0 are done and even found some problems.
* The performance tests also found some problems!

Nice job y'all!
