### ISSUE TITLE
Commenting on pin for Resource Pinning

### ISSUE THREAD

**Issue by jama22** [concourse/concourse#2875]
This is related to the discussion going on in #2870 

With the introduction of resource pinning and this whole auto-pinning of paused resources on upgrades, it would be nice to have a messaging function to let users know why we pinned the resource for them, but also let users add their own annotations. This is also related to the larger epic of `annotation` stories, like #2025 

In this case, we're asking for a much simpler implementation:
* Allow users to submit a comment after they pin
* Display the comment for the duration of the pin
* When the pin is removed the comment goes away

Long term, I could see this tying into the larger story for a global commenting system

cc @Lindsayauchin

**Comment by Lindsayauchin** [comment]
## Default State:

![2_00_resource_pinned_comment_empty](https://user-images.githubusercontent.com/27746614/49748433-a4bba680-fc73-11e8-8e65-4dda1dc8d62c.png)

- [ ] move pinned version to below the resource name
 - [ ] svg icon #616060 and outlined pinned display field #616060 grey and no fill,  outlined comment field #616060 grey and no fill
- [ ] split the area 50% pinned version 50% comment input/display field
- [ ] comment svg asset: [ic_comment.svg.zip](https://github.com/concourse/concourse/files/2664140/ic_comment.svg.zip)


## On selection of the resource version to be pinned in the UI: 

![2_01_resource_pinned_comment_selected](https://user-images.githubusercontent.com/27746614/49748436-a5ecd380-fc73-11e8-9049-cd5e75d6a853.png)

- [ ] input should focus on the comment input
- [ ] user must sleect confirm to save/complete the comment
- [ ] input focus is always populated with the username, date and time stamp

## Comment confirmation state

![2_02_resource_pinned_comment_confirm](https://user-images.githubusercontent.com/27746614/49748438-a84f2d80-fc73-11e8-8104-b710d3d97ea5.png)
- [ ] #196AC8 blue fill the confirmation button
- [ ] input comment is deleted when the pinned version is unpinned

## Active State: Comment and Pin version 

![2_03_resource_pinned_comment_active](https://user-images.githubusercontent.com/27746614/49748443-aab18780-fc73-11e8-9479-58208f7ead7d.png)

**Comment by Lindsayauchin** [comment]
## Comment: Edit
![5_01_resource_pinned_comment_edit](https://user-images.githubusercontent.com/27746614/49894279-90b2a900-fe1b-11e8-89f2-d9c1dca324fc.png)

## Comment: Saved
![5_01_resource_pinned_comment_saved](https://user-images.githubusercontent.com/27746614/49894286-93150300-fe1b-11e8-8209-ba7220344f62.png)

**Comment by pivotal-jamie-klassen** [comment]
### Implementation requirements:
* users with the role `member` or `owner` on the team can comment on any pinned resources.
* whenever the resource is pinned, comment form appears. it is of a fixed height, always positioned at the bottom of the viewport.
* the 'message' icon is https://material.io/tools/icons/?icon=message&style=baseline
* the placeholder text in the textarea is a faded grey
* the versions list should have an appropriate margin-bottom so that it is possible to scroll to the bottom without the pin comment section overlapping.
* if the currently pinned version is multiple rows (like a PR resource) it will push down, but the 'message' and pin icons to the left of it will stay top-aligned.
* the textarea expands to fill the remaining height, scrolling _using the default browser scroll style_ when the content overflows
* the save button is grey whenever the textarea contents match the server-side comment, and turns blue when they differ. Furthermore the grey button has a default cursor and the blue button has a pointer cursor. Assuming there will be no hover state for the blue button (@Lindsayauchin ?)
* for an unauthenticated user or `viewer`, the the save button is always grey? Obviously those folks will be confused when they see a textarea, but it might be the best MVP solution? otherwise we might be back to having an 'edit' button.
* clicking save should show some kind of loading indicator (spinner inside the button maybe? Either instead of the word `save` or appearing beside it? @Lindsayauchin I'm ok using the `fa-circle-o-notch` fontawesome trick until we settle on a new solution?)
* if saving fails, the button is blue again
* Navigating away from the page with unsaved changes to the comment could prompt some kind of default javascript alert about unsaved changes? Honestly, maybe that's not even MVP and people just lose their changes if they navigate away.

### potential gotchas
* anyone with the right role can change the comment
* unpinning should zero out the comment

Maybe we should pick a specific placeholder for the textarea? @vito are you happy with `This resource was pinned for reasons`?

**Comment by Lindsayauchin** [comment]
## Comment: Edit
![5_01_resource_pinned_comment_edit](https://user-images.githubusercontent.com/27746614/49898964-64515980-fe28-11e8-984f-ef9cb41fe9b8.png)

## Comment: Save
![5_01_resource_pinned_comment_saved](https://user-images.githubusercontent.com/27746614/49898918-48e64e80-fe28-11e8-9fab-04dcae55c223.png)

## Hover state on save button: 
![screen shot 2018-12-12 at 4 14 12 pm](https://user-images.githubusercontent.com/27746614/49899188-02ddba80-fe29-11e8-875a-d61dce3e834f.png)

## Comment: View only
![5_01_resource_pinned_comment_viewer_role](https://user-images.githubusercontent.com/27746614/49898919-497ee500-fe28-11e8-9191-fb5ce31b1a81.png)

**Comment by vito** [comment]
I've added this to the API backlog as well.

So there should be (at least?) two PRs for this - one to implement the API aspect, which can be accepted/merged *without* closing this issue, and then another PR for the UX aspect.

**Comment by pivotal-jamie-klassen** [comment]
@clarafu @mhuangpivotal @pivotal-jwinters ^

**Comment by clarafu** [comment]
I think it would be fine if you guys PRed the API aspect, it seems like a pretty simple addition to the API and the database so I don't think we would have any special technical choices for it? (@pivotal-jwinters can confirm) Maybe you can just add us in the reviewers list for the PR? 

Thanks for letting us know!

**Comment by vito** [comment]
@pivotal-jamie-klassen I think that'll be OK because page refreshes just make more show up on a newer (previous) page instead of disrupting page content. Something to try though, as I wouldn't want the DOM to be re-set or something.

**Comment by vito** [comment]
foo
