### ISSUE TITLE
Users of new teams can't un-pause their first pipelines 

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/concourse#2882]
This is a regression that came about because of our RBAC work. Users of new teams can't unpause their first pipelines, they get 403 errors. 

**Steps to Repro**
1. `docker-compose up` a new concourse
2. Login as the main user `test`/`test`
3. Execute a `fly -t ci set-pipeline`
4. In the UI, try to unpause your pipeline

**Expected**
You should be able to do this

**Actual**
You can't! You have to logout and log back in again. Un-pausing from fly seems to work fine though

**Comment by jama-pivotal** [comment]
Additional detail: on step `2` I log in using the browser flow, NOT with the flags

**Comment by pivotal-jamie-klassen** [comment]
@pivotal-jwinters I would really like to better understand the choice to store CSRF tokens in browser localStorage. The cause of this issue is that during the fly browser login flow, the following happens:

1. Fly listens for the auth token on `127.0.0.1:<random port>`
1. The user visits `<concourse url>/sky/login?redirect_uri=http://127.0.0.1:<random port>/auth/callback`
1. User authenticates, and skyserver redirects the browser to `http://127.0.0.1:<random port>/auth/callback?token=<auth token>&csrf_token=<CSRF token>`
1. Fly saves the auth token in `~/.flyrc`, ignores the CSRF token and redirects the browser to `<concourse url>/public/fly_success`.

Thus the CSRF token doesn't end up saved in localStorage like it would in the web login flow, and so if you keep using that browser to access the web UI, you will get 401s for CSRF violations on any state-changing action (like unpausing a pipeline).

For the time being, I plan to change the last step so that fly will instead redirect the browser to `<concourse url>/public/fly_success?csrf_token=<CSRF token>` and `fly_success` will call some Javascript to save the CSRF token in localStorage appropriately, but it feels kludgy. I might just be unfamiliar with the security world and find this unpleasant, but maybe it's worthwhile to revisit this strategy? Hopefully you will enlighten me.

**Comment by pivotal-jamie-klassen** [comment]
@jama-pivotal a note about acceptance - right after you hit 'login' after typing in your username and password, you may need to do a (cacheless) hard-refresh on the 'success' page (the one with url `/public/fly_success` that just says) before continuing. This is mostly of concern if you perform the test on a browser that has cached this file before -- there's a very long cache policy on stuff under `/public`. I decided this was OK because one day, eventually, the browser's cached old version of this page will go stale and load the new-and-improved javascript version.
