### ISSUE TITLE
Using external credential managers for build credentials

### ISSUE THREAD

**Issue by xoebus** [concourse/concourse#291]
## Motivation

There are so many credentials flowing through a Concourse server at the moment that it's keeping me up at night. Some of this risk can be mitigated by [fetching the secrets](https://github.com/concourse/concourse/blob/c0998decb243fd5ac761864a69bf7ec9c637fa31/scripts/reconfigure.sh#L22) as late as possible and using [pipeline templates](https://concourse.ci/fly-cli.html#parameters) to insert them into the pipeline. This at least means that you'll never have the pipeline secrets stored on local workstations.

_This isn't good enough._

Credentials are still stored in the Concourse database, aren't internally rotated, and do not have any audit trail as to which jobs and builds used them. Let's fix these things.
## Goals
- Build credentials are never stored on a disk (apart from in Vault where they are stored encrypted).
- Build credentials are never stored locally when setting the pipeline using `fly`.
- An audit trail of which build used a secret and when it used it should be visible.
## Proposal

I don't want to have to build a secret management system. This means that we're looking to use one of the existing ones. There are a [few](https://aws.amazon.com/kms/details/) to [choose](https://square.github.io/keywhiz/) from in this regard but I'd like to go forward by using [Vault](https://www.vaultproject.io/). Vault seems to strike the right balance of confidence in implementation, good technical decisions, and generically usable. I'm not ruling out the ability to use a different secret store in the future. In fact, a good implementation of this proposal would allow pluggable secret stores with minimal effort.

So, what would this look like?

``` yaml
resources:
- name: s3-file
  type: s3
  source:
    access_key_id: {{!vault.s3-file.access_key_id}}
    secret_access_key: {{!vault.s3-file.secret_access_key}}
```

Here we have a snippet of pipeline configuration. Everything looks normal except the secrets on the last 2 lines. This would be a new syntactic convention that the regular templating would ignore and pass directly up to the server. When the server needed to do something that required a realized value of one of these references it would fetch it as late as possible from the server and then handle revoking it once it isn't required anymore. This means that (assuming Vault is set up correctly) each check run and each build would get a single use credential that would become invalid immediately. **This is rad.** :100:

The syntax shown above is not finalized but needs to have a few components:
- `vault` refers to the name of the secret store from which the credential should be fetched. This would allow multiple stores per Concourse server as long as they were all named uniquely. A secret store should probably belong to a team rather than being global.
- `s3-file` refers to the name of the secret inside Vault.
- `access_key_id` and `secret_access_key` refer to the attributes on the secret.
## Open Questions
- What if the server goes down in the middle of using one of these secrets. Who revokes it?
- How does Concourse authenticate with the secret store? Does this just move the problem?
## Risks
- Yet another thing to deploy next to Concourse in order to use the feature. This moves away from secure by default. This could be partially mitigated by making it easy for people to get started with Vault. (BOSH release, adding something to [the monolithic binaries](https://github.com/concourse/bin))

**Comment by cppforlife** [comment]
one thing to think about is pipeline scoped creds e.g. two pipelines with same config but different creds. (same problem exists for similar style of creds in bosh where each deployment may need different scope of creds).

**Comment by zachgersh** [comment]
Hey @xoebus I've been thinking about this question:

> How does Concourse authenticate with the secret store? Does this just move the problem?

Why doesn't fly handle unsealing / sealing the secret store? Each ATC could also be provided with a read-only token to the secret store. The secret store could be resealed and the token could be set to expire after a reasonable time period (don't know whether the ATC handles these things). Even though you've "moved the problem" you still have made the pipelines more secure by default.

**Comment by robdimsdale** [comment]
@zachgersh if the ATC can't renew its token automatically it could potentially be a poor user experience: "my builds all stopped working after a month". If it can renew its token, how much more secure is it? I think I agree with you that it's probably more secure, but it doesn't feel like the final answer in security to me.

**Comment by eddiewebb** [comment]
thanks for starting this conversation!  I love the potential that concourse brings, but it's not viable in our environment until we address the encryption and management of secrets.

@cppforlife - agree on need for pipeline scoped credentials. Seems plausible to align to vaults tree concept.

@xoebus - is the revocation risk not addressable with reasonable lease windows in vault? I would prefer to trust a lease to destroy cred than a final type task in pipeline.

**Comment by holstvoogd** [comment]
I have been thinking about how this could be set up with the [App ID auth backend](https://www.vaultproject.io/docs/auth/app-id.html). I would say each worker should have an unique User ID and each Pipeline should have an unique App ID. Builds get access to secrets based on their App ID and User ID, so they would be scope-able per pipeline and it ensures only known workers are used.

This all would require some manual configuration whenever you add a new pipeline and/or worker. But I guess that is kind of the point of ensuring it is secure: all secrets are managed out of band in vault as well as the access to it.

I've considered some setups where ATC manages App & User IDs for you, but this just seems to break the security model of vault and it becomes very complicated fast ;-)

**Comment by eddiewebb** [comment]
ANyone know how Stark & Wayne's planned summit topic relates? 
https://cfsummit2016.sched.org/event/6Zld/air-marshal-no-more-secrets-in-your-manifests-michael-brodhead-stark-wayne

> Enter Air Marshal. Air Marshal acts as a proxy between staff workstations and BOSH or Concourse. Manifests checked into source control have placeholders wherever secrets are necessary. Air Marshal reads secrets from a secure back-end, adding them to manifests where needed.

**Comment by xoebus** [comment]
It's an interesting, pragmatic, and novel solution but doesn't solve the core problem of the credentials being stored in plain text in the system.

**Comment by eddiewebb** [comment]
Yeah, i agree @xoebus,
 I reviewed the video with my team today, might be suitable for some use cases, but not the enterprise ready solution that moves away from assuming such frequent human access over CLI.

We'd like a system (or user) to configure the pipeline independent of cipher values, which should be decrypted at time of use, not time of configuration.  This is important to allow key rotation and the like.  

So any solution that depends on fly interaction to replace values in manifest is not viable.

**Comment by freelock** [comment]
I've come up with a similar solution -- I have a bot in a Matrix chat room that listens for git commits, and when it sees them, it uses fly to update the pipeline to the latest version. The bot has access to the secrets, regular users don't. So this allows our regular users that the bot authorizes to update the pipeline without having access to the secrets.

I'm still interested in how secrets may be stored in the ATC, though, especially as we add clients that may have more governance issues to address than we currently have, and might need to have different sets of secrets for different clients/pipelines.

**Comment by eddiewebb** [comment]
The use of variables is one area that has pretty wide impact. Validation in fly cli for instance doesn't like {{!secret}} and using {{secret}} requires vars provided at config time.

So do we want to invade fly and other points to tolerate a new format, or find something that flies under the radar of yaml validation, or more simply use a hack of forcing quotes of an alternate format
```
resources:
- name: s3-file
  type: s3
  source:
    access_key_id: "{{!vault.s3-file.access_key_id}}"
    secret_access_key: "{{!vault.s3-file.secret_access_key}}"
```
Playing a bit all components support that pattern without validation or configuration errors.

That also lets the altered manifest go unnoticed by all existing systems, and would let us focus enhancements in ATC as the place to trade out properties for actual values (I think -- ATC is aware of pipeline config, assigns workers, and could grant and revoke secrets based on lifecycle of workers.).

I'm still learning/exploring concourse architecture, would love feedback on those thoughts.

**Comment by vito** [comment]
Doing some more thinking and investigation for what this may look like now.

Here's one syntax I landed on:

```yaml
yaml_syntax:
  abc: $vault.foo/bar.baz

json_syntax: {abc: $vault.foo/bar.baz}

double_string_yaml_syntax:
  abc: "$vault.foo/bar.baz"

single_string_yaml_syntax:
  abc: '$vault.foo/bar.baz'

double_string_json_syntax: {abc: "$vault.foo/bar.baz"}

single_string_json_syntax: {abc: '$vault.foo/bar.baz'}
```

Each scenario parses as the same value, so it seems to work pretty well. I also like that it moves away from `{{foo}}` syntax, and implies that it's bringing in a value in full, whereas `{{foo}}` implies that it supports interpolation (e.g. `{{foo}}bar`). The one downside is that it may imply that you can do `${vault.foo/bar.baz}` which brings us back to square 1, but hopefully no one tries that. 😉 

We may end up deprecating `{{params}}` functionality altogether and only supporting these credential variables, based on where https://github.com/concourse/concourse/issues/360 went.

**Comment by vito** [comment]
Interesting blog post detailing one approach to the tricky bootstrapping problem with authorizing the ATC with Vault:

https://www.hashicorp.com/blog/vault-cubbyhole-principles.html

I'm a little concerned about how extreme we want to go with this - having Concourse become a pain in the arse to automate would be an unfortunate result. We obviously want to get unencrypted credentials out of the database, though, and storing an unencrypted Vault token in there is a non-solution. We may want to land on a middle ground where we've made it trivial to rotate and automate pipeline credentials via Vault, have removed all unencrypted creds from the DB, but don't try to solve the bootstrapping problem completely. This could mean the ATC storing encrypted Vault tokens in the DB and using a local key, similar to the session signing key. Then the risk is at least localized to the `web` nodes.

**Comment by vito** [comment]
Tying in with https://github.com/concourse/concourse/issues/360#issuecomment-233411189 which has more thoughts on the templating question (and suggests *not* doing `$vault.foo/bar.baz`).

**Comment by eddiewebb** [comment]
> This could mean the ATC storing encrypted Vault tokens in the DB and using a local key, similar to the session signing key. 

@vito - just to clarify, are you saying the encrypted creds that ATC needs are for Vault access, and not the secrets within vault correct?

(if not, why aren't we considering ATC grabbing the creds from vault directly at time of execution?)

**Comment by vito** [comment]
@eddiewebb Yes, encrypting the credentials to Vault itself. Everything else would be fetched on-demand from Vault.

**Comment by vito** [comment]
Another alternative would be to have the ATC configured with a single Vault, have teams only support configuring a token, and then use Vault for encrypting the tokens themselves. But then we'd need a token for that single Vault anyway.

Still chewing on this.

**Comment by vito** [comment]
Re: the bootstrapping issue, we've settled on storing it encrypted in Postgres. We'll also likely support having a static credential store, which is encrypted in the same manner. This allows us to implement a pattern for generic credential stores (now that we have two implementations).

**Comment by vito** [comment]
Cross-referencing https://github.com/concourse/concourse/issues/517 - we should also support loading values from the credential store in `fly execute`, i.e. from creds embedded in the task .yml. This ends up working nicely since the credential store is per-team.

**Comment by wernerb** [comment]
As far as I can see there are actually two use-cases here.
1. Have ATC optionally use vault to store (temporary) secrets
2. Be able to use vault secrets

As far as 1. is concerned, this is really about ATC handling secrets correctly and that you can integrate vault in concourse to optionally handle this. It must be seen as completely separate from the usecase where the team/user might use vault secrets in their pipeline.

The second usecase I rather have solved with a resource that someone apparently already made:
https://github.com/Docurated/concourse-vault-resource
This keeps stuff organic and simple, keeping in line with concourse! Now the problem is, can the user trust that concourse handles passing these parameters back and forth between jobs/resources? This is where use-case 1 comes in where you must create a chain of trust from initially authenticating a user (i see a clear usecase here also for vault..) to passing parameters to/from resources internally.

**Comment by eedwardsdisco** [comment]
Would definitely love to see Vault support, and Vault officially supports [Response Wrapping](https://www.vaultproject.io/docs/concepts/response-wrapping.html) now.

**Comment by Seraf** [comment]
Using the resource https://github.com/Docurated/concourse-vault-resource will not allow to use them as {{ secrets }} in the pipeline.

It's a problem because this kind of resource can't be used to specify parameters directly.
For example, I wanted to use the https://github.com/ljfranklin/terraform-resource and provide my aws credentials that are stored in vault. But accessing these credentials with the vault resource doesn't allow me to use these creds as param for the terraform resource.

One thing that can be interesting is to find a way to export secrets from tasks

**Comment by ljfranklin** [comment]
@Seraf The Terraform resource supports a `var_file` [param](https://github.com/ljfranklin/terraform-resource#put-parameters) that would probably work for your specific use case.

**Comment by Seraf** [comment]
@ljfranklin you're right but it doesn't cover the fact that s3 credentials are required on this resource and aren't read from a file

**Comment by squeedee** [comment]
I wrote a component for (de)hydrating any kind of state file of credentials. It's but a hack at the moment, and the command line DSL could easily become a declarative DSL, but the intent is clear if you look at the [test examples](https://github.com/bunniesandbeatings/offspring#testing). I want to write a resource that can bookend tasks that consume/create/store state for these files, and my approach is slightly at odds with the vault. I want to explain why because I think it might be important.

A task is typically re-entrant, where the absence of input state often indicates a 'create' mode vs the 'update' mode when state exists...  given s0 = nil;  s1 = t(s0);  s2 = t(s1) and so forth. when s is nill, t(s) is create, otherwise t(s) is update.

Habitualizing the provision of credentials as something orthogonal to the reactive-pipeline that is concourse, causes tasks to stop being written as uni-directional functors.

Just some thoughts. Please hit me up if I'm not making sense.

**Comment by eddiewebb** [comment]
@vito - based on your comment above https://github.com/concourse/concourse/issues/291#issuecomment-236266242

I just want to confirm that nothing is encrypted in DB/cred-store today.  Even without vault support having creds in plain-text will be a non-starter for us.  Using a local key and encrypting creds in DB would be enough to move forward while more strategic integrations are considered.

**Comment by willejs** [comment]
@vito I heard that this was going to be the next Epic you guys were going to tackle. Have you started working on this? I really like the idea of pluggable secrets providers. KMS especially.

**Comment by vito** [comment]
@willejs It is indeed the next epic, it's just taking a bit longer than expected to finalize our current epic (#629), as a lot of security-focused things came up for 2.7.1, plus a few other factors unrelated to Concourse itself. We do plan on making it pluggable, as we want to support both Vault and [CredHub](https://github.com/cloudfoundry-incubator/credhub). I think we can take what we learned from the security fix for Generic oAuth issue in 2.7.1 and use that to have a nice pluggable, safely-PRable interface for credential providers. See [here](https://github.com/concourse/atc/blob/wip-flags-refactor-new/auth/provider/provider.go) for example.

In the interest of solving the MVP of this issue (no more plaintext credentials in the DB), we're going to bite off an easier-to-digest form of this in simply encrypting the existing data at rest (pipeline config, team auth config). Which we'd need to figure out anyway as part of the long-term goal of using Vault/CredHub/etc. for credential management (we'd need to encrypt the credential for the credential manager). Hopefully that answers @eddiewebb 's question as well, which I missed (sorry!)

**Comment by norman-abramovitz** [comment]
Actually, AirMarshal would work since a token is stored in the manifest file.   There is a better solution coming down the pike though that Pivotal is coming up with called CredHub.    It was mentioned on the community call that past couple of months.

**Comment by jchesterpivotal** [comment]
@vito When Concourse is deployed by BOSH, CredHub could solve the bootstrapping problem you mentioned. BOSH can request and drop a certificate next to Concourse and CredHub can accept MTLS authentication without needing UAA.

You could go as far as handing out distinct certs for distinct components, if you wanted.

**Comment by clarafu** [comment]
Doing some investigation, we are thinking of having the token and server URL for whichever credential manager be passed as a flag and have it be global. In terms of vault, the path to the secrets will be team/pipeline.

We are also thinking of limiting the things that you can populate from a credential manager to (probably) resource and resource type source and task params at least for the first pass.

**Comment by clarafu** [comment]
I have a question for anyone following this issue, we are currently thinking of having the credentials plugged in when a build plan is constructed. This means that if you have a build that will run an hour long task and you have secrets in vault that rotates every 30 minutes, the secrets that we pulled (when your build started) will be old. We're wondering if that will be a problem, or if this is even a case we should be worried about. Your input would be very helpful!

**Comment by jchesterpivotal** [comment]
My gut sense is to ignore this problem for the first release of credential support and come back to it later. At that time you'll probably have more data points on what exact pain is being felt and what shape users would prefer relief to take.

**Comment by farcaller** [comment]
Safe to ignore for initial release. I'd say that if credentials are needed further in pipeline, they should be pulled only as the relevant step is reached, though.

**Comment by schubert** [comment]
+1 Agreed. I think the 80/20 will be solved with the first implementation and folks where they need credentials much later in the process can either break it up into multiple tasks or deal with their own particular problems some other way.

Just having this first pass implementation would make a huge reduction in risks to secrets to make it worth everyone's time.

**Comment by GooseYArd** [comment]
I don't know the architecture of Concourse well enough to make a really meaningful statement, but I can tell you that the reason I'm following this issue is that, in order to consider using Concourse, Id need to ensure that secrets obtained via the plugin mechanism were exposed only to the environment where they're being used. For example, in my case I need a client cert in order to access the docker repository where my images live. I need to make sure that the cert is retrieved at the time the docker resource establishes the https connection to the repo and isn't stored afterward.

If instead there's some step at the beginning of the pipeline where the cert is fetched, and then passed along on disk or over the wire to later processes that use it, we'd have something that conflicts with the intent of using the secret management system. Would this be the case with Concourse?

**Comment by vito** [comment]
@GooseYArd It will have to go over the wire, but it'll never touch disk either in ATC or Postgres, and in most cases not even in the receiving container, as we communicate to resources via stdin. Some write to `/tmp` in their container, which is a problem that should be addressed separately.

Tracking where the credential flows over the wire depends on how your workers are registered with the TSA. If your workers are registered via their direct internal address and the ATC can reach them, it'll go over plaintext from the ATC to the worker. Granted, in this configuration your worker should be in a private network, but that's still not ideal.

When forwarding through the TSA in the mix, the traffic to/from the worker will be encrypted via the SSH connection to the worker. However the credential will be traveling in plaintext between the ATC and the TSA. Often however there's only one ATC so this shouldn't even leave the VM.

To cover the remaining gaps, we'd need to configure TLS for communication to/from the workers. That's a later step we can take, which will probably need some work from Garden. Alternatively we can deprecate the direct worker registration and force everything down the SSH forwarding code path, and then do TLS between the ATC and the TSA.

**Comment by GooseYArd** [comment]
awesome, thanks for the explanation and confirmation @vito. I think this'll work for me!

**Comment by iSynaptic** [comment]
It might be useful have Concourse issue tokens associated with Vault policies based on task/resource configuration and then allow the underlying container to use that token to retrieve/renew secrets it's authorized to see via that token.

**Comment by norman-abramovitz** [comment]
That is exactly what I have been working on with our vault/concourse integration.   The work is in figuring out how to setup the policies since the various paths you want to protect are documented all over the place.  You want people to read policies but not update them, etc, etc.    With credhub now being released, that subsystem could be evaluated.

**Comment by clarafu** [comment]
We have an update! We will retrieve the secrets from vault when the step runs (eg, get for a resource) instead of when the build plan is generated because we realized there would be a few problems if we retrieve them during the build generation. We were going to ignore (for the first pass) the fact some steps might take time, and in that time secrets could be rotated for a subsequent step which would still have the old ones that were retrieved at the time the build started but we actually found it to be cleaner to have it retrieve the secrets during the step.

A task step can be part of a pipeline or `fly execute`d which would make it part of a team, so we will need to have options for team scoped secrets or pipeline scoped secrets. For the case of a step in a pipeline, we will first try to retrieve from the Vault server at the **pipeline path**: `/<team-name>/<pipeline-name>/<secret>` and if that doesn't exist we'll fall back to the **team path**: `/<team-name>/<secret>`. For anything that is team-scoped (eg. `fly execute`d ) we'll just use the **team path** since there's no associated pipeline. 

- clara & @pivotal-topher-bullock

**Comment by vito** [comment]
Is anyone here already using Vault (or CredHub) for other things? I'm wondering how you'd like Concourse to "plug in" to it. Right now we're just looking up under `/<team>/<pipeline>` as @clarafu said but that may be awfully presumptuous if your Vault is already being used for other things.

Would being able to specify a key path prefix (e.g. `/concourse`) be enough? Or is this all solved by per-token access control and such?

**Comment by jamestoyer** [comment]
@vito At the least I'm happy for the ability to specify a key path prefix, providers like [Hiera Vault](https://github.com/jsok/hiera-vault) do this. However, ideally I'd prefer the ability to pick where the secret comes from, but understand this may make things more difficult

**Comment by norman-abramovitz** [comment]
When you say 'other things', do you mean other than Cloud Foundry?  
 It may be our misuse or abuse of Vault, but a single path would not work.   If you take the philosophy that single copy should exist in Vault, then your path structure could be different.    In this case, we are trying to control access using Vault policies assigned to tokens.   

If you take the philosophy that your secrets can be duplicated then a single path is an option, but now you have a major headache keeping secrets in sync.  

It really comes down to how your security and compliance conventions are defined.

**Comment by vito** [comment]
@norman-abramovitz One goal of having the paths be 100% convention is that it leaves the pipeline configs specifying only a key name. This makes the config more portable/reusable as you can specify them with `-v` or `-l` instead of a credential store if you so desire. This portability would be lost if the keys started to reference specific paths or anything too Vault/CredHub-specific.

I do see the risk in having to duplicate already-existing credentials to the Concourse-specific path. I wonder if Vault could somehow support symlink-style paths, where there's a single source of truth for the actual lifecycle of the credential under one path, but other paths can "link" to it. (Just spitballing, don't know if that feature actually exists.)

**Comment by elasticdog** [comment]
We're using Vault pretty extensively, and the namespacing/organization can be tricky, especially until the [symlink support](https://github.com/hashicorp/vault/issues/1284) is figured out upstream. I have some questions:

* I assume this discussion is strictly related to the [generic secrets backend](https://www.vaultproject.io/docs/secrets/generic/index.html)?
* Which authentication backend is being used by Concourse and what's the expected workflow to authenticate?
* Is it a token being stored in the DB, or some other credentials that are then used to grab a token? 
* How are access control policies being handled, or are they expected to already be in place?
* What about secrets with multiple fields? Ignore them out of convention and just use a single `value` field?

If you want to have a conventional structure, I think a key path prefix would enough, but keep in mind that users may also have the backend on a non-standard mount point (i.e., not `secret/[...]`).

**Comment by xoebus** [comment]
@vito The way that the the CredHub BOSH integration handles this is that relative paths are namespaced but absolute paths can reference anything in the credential filesystem (somewhat as you would expect).

```
((cool-credential)) => /DIRECTOR/DEPLOYMENT/cool-credential

((/totally/different/namespace/cool-credential)) => /totally/different/namespace/cool-credential
```

Could Concourse do something similar with teams and pipelines instead of directors and deployments?

**Comment by norman-abramovitz** [comment]
@vito @elasticdog 
We need to live with what exists and do our best, so symlinks do not exist yet. 

I have used AppRole, AppID and Token auth backends as well as the generic auth backend in pipelines.

I am working with the model that the token is stored externally.

I am in the midst of trying to decide how to deal with setting up Vault policies, but policies must be assigned when tokens are created/updated.

I do not see multiple fields as an issue since you have a concept of a path that can contain multiple fields. 

I did see yesterday that Hasicorp has built a [cf service broker](https://github.com/hashicorp/cf-vault-service-broker) that could be interesting.

**Comment by vito** [comment]
@xoebus Yeah that makes sense. The default behavior is enough to push people towards the path that would support portability, while providing an outlet for people that have a pre-existing path they need to use, in which case portability is likely not a concern.

@elasticdog That should address the missing symlinks concern, but for the rest:

* I don't consider this limited to the generic backend. I'd want people to be able to use whatever backend makes sense for each credential, e.g. [AWS](https://www.vaultproject.io/docs/secrets/aws/).
* For our first pass, the ATC will just be given a token and API endpoint.
* The token won't be stored in the DB; it'll be configured as a flag (or env var) on start. This does however push the management of the token up to the orchestrator of the deployment. Having a script with a token sitting there in plaintext wouldn't be great, for example.
* They will be expected to already be in place.
* That'll be `((key.field))` and we'll default `.field` to `.value`.

**Comment by elasticdog** [comment]
@vito thanks for the details...sounds good to me.

**Comment by clarafu** [comment]
We are making progress, heres the steps we outlined so far!

* [ ] Interpolate for resource `check`s.
* [ ] Interpolate for resource `get`s.
* [ ] Interpolate for resource `put`s.
* [ ] Interpolate for custom resource types.
* [ ] Interpolate for task params in a pipeline.
* [ ] Interpolate for `image_resource` in a task in a pipeline.
* [ ] Interpolate for `image_resource` in a task in a one-off build.
* [ ] For `((/foo))`, look up that exact key.
* [ ] Add config for default path prefix, default to `/concourse`.
* [ ] When not found in pipeline scope, look up in team scope.
* [ ] Look up directly in team scope for one-off builds.

**Comment by endemics** [comment]
Hi,

@vito said:
> We do plan on making it pluggable, as we want to support both Vault and CredHub

We're currently using AWS SSM parameter store to manage our secrets and would love to be able to use that in concourse too.

AWS SSM parameter store has a very low entry cost since it's a managed service. It allows role based access control through IAM, logs access to cloudtrail and encrypts data at rest using KMS. 

You can access secrets under an encrypted or decrypted form using the aws cli and sdk, so integration is pretty easy too.

Secrets can be decrypted on the fly by SSM when you request it. If I understand correctly, the API endpoint is always accessed over TLS so it should be protected while in transfer.

@vito added:
> For our first pass, the ATC will just be given a token and API endpoint.

While this is OK for a MVP, in the context of SSM it would be interesting to have the workers requesting the secrets directly when the step runs, instead of having the TSA retrieving them on behalf of the workers, since it would limit the exposure and provide more fine grained control.

You would be able to use IAM instance profiles to allow workers to retrieve keys with a policy such as:
```
{
    "Sid": "",
    "Effect": "Allow",
    "Action": "ssm:GetParameters",
    "Resource": "arn:aws:ssm:${aws_region}:${account_id}:parameter/path.to.concourse_worker_keys.*"
}
```
(IAM instance profile provides short lived AWS credentials so you don't have to store any AWS keys on either the TSA or the workers)

@vito also wrote:
> One goal of having the paths be 100% convention is that it leaves the pipeline configs specifying only a key name

AWS SSM parameter store doesn't have a notion of path, it's a flat key/value store. Common practice is to use `.` as a path separator for things like IAM ACL.

I guess this use case would work too with your approach, as it could either be assumed that:
- $path is empty and you would provide the full key name
- `.` is a path separator and $path becomes a prefix to the key name

**Comment by jchesterpivotal** [comment]
> AWS SSM parameter store doesn't have a notion of path, it's a flat key/value store. 

It's worth noting that Credhub also follows S3-like semantics in this regard. There are "paths" delimited by `/`, but it's a convention.

The illusion is completed by [prepending `/` to any Credhub key name that doesn't have it upon saving](https://github.com/cloudfoundry-incubator/credhub/blob/87139258d12e68bc09e7159e7e302fe4535888fe/src/main/java/io/pivotal/security/aspect/CredentialNameAspect.java).

**Comment by jchesterpivotal** [comment]
That said: Credhub may change in this respect. Right now one main track of work is to build a permissions scheme for credentials. In future this may be extended to be applicable to "subpaths". 

Whether the implementation introduces an internal concept of paths, or whether it uses S3-style pattern matching instead, is probably up in the air.

@ishustava @ebeer please let me know if I'm leading anyone astray here.

**Comment by vito** [comment]
@endemics The problem with pushing credential resolution to the workers is that it would imply a few things:

1. Granting access to credential manager to your workers, which is a bad idea in a multi-tenant Concourse or when you're running untrusted code like pull-requests.
1. The workers having network access to your credential manager, which won't be the case all the time (lots of people have workers living in private networks or other strange environments).

For the first reason alone we do not recommend anyone to use EC2 IAM profiles. It seems like a great idea until you want to do things like run pull-requests, or run a large multi-tenant Concourse installation.

We also don't have any Concourse-specific "agents" running on the workers; they're just Garden + BaggageClaim plus a SSH client registering them, so all the brains are in the ATC. This is purely an implementation concern, granted.

For your other points, that sounds like a matter of just writing a SSM backend. So far the Vault-specific code has ended up being about 10 lines. So writing another backend should be pretty straightforward, assuming there's a Go client available.

**Comment by endemics** [comment]
@vito wrote:
> The problem with pushing credential resolution to the workers is that it would imply a couple things:
> -  Granting access to credential manager to your workers, which is a bad idea in a multi-tenant Concourse or when you're running untrusted code like pull-requests.
>  -  The workers having network access to your credential manager, which won't be the case all the time (lots of people have workers living in private networks or other strange environments).
>
>For the first reason alone we do not recommend anyone to use EC2 IAM profiles. It seems like a great idea until you want to do things like run pull-requests, or run a large multi-tenant Concourse installation.
>
>We also don't have any Concourse-specific "agents" running on the workers; they're just Garden + BaggageClaim plus a SSH client registering them, so all the brains are in the ATC. This is purely an implementation concern, granted.

Thanks for those explanations!

Now this raises an interesting point: At the moment we have hard-coded AWS keys/secrets provided via '-l' when setting the plan.

SInce everyone can see those by doing a `fly gp`, we considered that this is not safe and instead were planning to use short lived credentials obtained through EC2 IAM profiles on the workers.

We are not in a multi-tenant environment so that part should be OK in our case.

I agree that the EC2 instance profiles need to have enough privileges for *all* the potential actions that could be triggered in a plan and that this is probably not fine grained enough: there is always a risk of a step using those credentials sneakily since they are available to all, whereas in the case of TSA-controlled solution the credentials have to be explicitly provided. I guess that your first point?

Are you planning, as part of this ticket, on allowing the TSA to retrieve credentials through its instance profile and providing key/secret/token to the workers or is the fine grained control issue a blocker in your opinion?

A concern I have is that in the recommended installation, the TSA and ATC are the same machine(s) and are exposed to the outside world through the web UI. It feels that if the TSA is allowed to retrieve credentials on behalf of the workers, there is an increased security risk if that server is breached.

For instance, in our current set up, the TSA/ATC nodes are in a public VPC behind an ELB and accessible from the internet, whereas the workers are in a private VPC and not directly accessible.

> For your other points, that sounds like a matter of just writing a SSM backend. So far the Vault-specific code has ended up being about 10 lines. So writing another backend should be pretty straightforward, assuming there's a Go client available.

Excellent news, it should be straight forward to add SSM parameter store support too then, since as mentioned it is supported by the AWS golang SDK (see https://godoc.org/github.com/aws/aws-sdk-go/service/ssm#SSM.GetParameters).

**Comment by vito** [comment]
@endemics One point of clarification: it'll always be the ATC managing anything Concourse-domain-specific; TSA just serves as an SSH proxy to aid in worker registration. It doesn't do anything beyond that, and won't be the component touching any credentials.

Regarding `fly get-pipeline`, using any form of credential manager will solve that problem as the pipeline will be returned back with the `((params))` uninterpolated.

But yes, at the moment the ATC will be both "exposed" (hopefully via a load balancer and not directly) *and* the component handling credentials, which has some level of risk, but IMO much lower than the risk of workers managing the credentials directly. We could introduce some middle-tier component, and maybe that really just means breaking the ATC up into smaller components, if we decide that the increased complexity is worth the amount of reduced risk.

**Comment by vito** [comment]
Update on this: we've completed what I think is a reasonable candidate for MVP, and hope to ship this very soon as 3.3!

Here's what we've left out:

* Absolute path references with `((/foo))`. This raised a couple security questions that we don't have great answers for yet. Primarily, it would allow a pipeline in team B to reference credentials from team A, which is pretty bad. We may want to go forward with either this feature being disabled by default (risking "knobs" anti-pattern) or instead have per-team tokens configured. Either way we need to think about it a bit more.
* For configurations that fetch separate fields off the same key, we will currently fetch the same key each time, meaning if you have keys that rotate on every fetch, the fields won't match up with each other. For example, `foo.access_key_id` and `foo.secret_access_key` will result in a secret key for the wrong access key, if you're using Vault's AWS backend with dynamic IAM.

One other thing we may want to tackle in another iteration is automatic revocation of keys after their build has finished. No one's mentioned this since the original opening of the issue, but I imagine people will want it. (I want it, anyway.) 

We will address these in later iterations, and ship what we have so far to get quicker feedback. So I propose those be made as separate issues once we close this one.

**Comment by vito** [comment]
Upon attempting to dogfood what we have so far, I found that our auth support wasn't quite realistic. We only supported being given a token, and had no periodic renewal set up. This is unrealistic as Vault tokens are always set to expire after some amount of time (max 32 days by default), and having to re-generate a token and re-deploy the ATC periodically would be quite burdensome.

As part of our implementation for TLS support, we had opted to support configuration for [client cert based auth](https://www.vaultproject.io/docs/auth/cert.html) in addition to token-based, as it's a bit easier to securely manage and rotate with our BOSH + CredHub tooling. However upon trying to actually use it we found that you need to explicitly log in to Vault with the client cert/key to acquire a token, so then we added that.

We may want to additionally implement automatic token renewing however, as the initial log in grants a token that expires after some amount of time configured by the Vault operator. It would be a bummer if the ATC suddenly stopped being able to acquire credentials and had to be restarted periodically. We would want to do the same for the client token specified, which should in most cases be a [periodic token](https://www.vaultproject.io/docs/concepts/tokens.html#periodic-tokens) so that the initially configured token remains valid after an ATC restart (as long as we've been renewing it).

**Comment by vito** [comment]
Slight change from before: we went ahead and just made the auth fully generic. So you specify `--vault-auth-backend` and `--vault-auth-param`.

For example, to use TLS auth, you'd just say `--vault-auth-backend cert` (or whatever you named your `cert` auth backend mount) and specify a client cert/key. To configure `approle` you'd do something like `--vault-auth-backend approle --vault-auth-param role_id=db02de05-fa39-4855-059b-67221c5c2f63 --vault-auth-param secret_id=6a174c20-f6de-a53c-74d2-6018fcceff64`.

We also now test cert, approle, and direct token configurations, and also test that they're renewed by the ATC automatically (using a periodic token for direct token configuration).

Next step is to try dogfooding again now that we've got the auth flow fleshed out.

**Comment by vito** [comment]
I've converted all our pipelines over to Vault, and all is going well so far. I wrote a little [tool](https://github.com/vito/vaultchuck) to make the migration easier.

**Comment by vito** [comment]
Looks good so far; calling this done as of now! The remaining bits of work will be modeled as separate issues.

**Comment by SleeperSmith** [comment]
Hi Guys. Tinkering around with Concourse.

I am running concourse workers on ECS and ECS Task Role doesn't seem to be working. From https://github.com/concourse/docker-image-resource/issues/109 it seems that the preference is to explicitly define the credential is it?

- When executing docker-image push to ecr, it seems to be picking up the EC2 IAM role. This should be disabled if the design goal is to be explicit?
- Perhaps model the IAM task role permission as a provider and allow it to be used upon explicit reference? The permission is attached to the deployment of worker "groups" (as a service on ECS) so perhaps make it a requirement to specify worker requirement alone with the configuration?

I just find it odd the worker can access the ec2 task role while not the ecs task role.
