### ISSUE TITLE
Check containers will only be placed on global workers

### ISSUE THREAD

**Issue by vito** [concourse/concourse#2910]
Now that resource checking is global (#2386), we should only place the 'global' containers on workers usable by all teams. Otherwise we could end up in a kind of awkward scenario where team A's periodic check ends up running on team B's worker.

Until we can reason about this more easily, let's just make sure check containers are placed on global (non-team) workers.

In the future we'll probably want to support deployments that have exclusively team-scoped workers. We can/should plan that as a later story once someone requests it.

**Comment by vito** [comment]
There's also a potential security reason for enforcing this: now that resource version history is shared across teams, there's a concern with using team-owned (and managed) workers for executing `check`s since now they affect global state. I don't know if there's any good reason to exploit this, because all you can do is return bogus versions, but hey.

**Comment by clarafu** [comment]
We are currently still deciding whether to make resource check containers able to be placed on team workers. The complexity lies within the fact that check containers are now global, meaning that they can be used by any team. Having them global makes placing the containers on team workers possibly introduce a security risk and also could raise more questions to users (such as the scenario where team A and B use the same check container and the container was placed onto team A's worker, team B will be able to see the checks are successful from the UI but if they run `fly containers` they will not be able to see the check container).

There are a few options that we currently have:
1. Having check containers be placed on both team and global workers: This option would be how the world existed before our commit to make check containers only be placed on global workers. This would result in the containers for a team that had a team worker to be placed on it and if other teams had the same resource, it would create a separate check container for the other team (because the other team's radar could not see the check container on the team worker). This also results in some weirdness where if the scenario that two teams use the same resource and there was one team worker (for one of the teams), it would result in two separate check containers but still have shared version history. 
2. Having check containers only be placed on global workers: This option makes the most sense in terms of how check containers exist globally, since they are shared they should only be placed on shared workers. But this also introduces the restriction of users that only have team workers to now need to add shared workers in order to have resource checks work.
3. Introduce a strategy for the placement of check containers on team and global workers: 
```
placing check container:
* if there are global workers, use those
* otherwise, use team workers
* only create on untagged workers, unless tagged

finding check containers:
* only find on untagged workers, unless tagged
* find on team workers and/or global workers (doesnt matter?)
```
Basically the strategy is to use global workers first and then use team workers if there are no global workers available. This seems to make the most sense but the question still lies within whether or not it makes sense to place check containers on team workers. Also, this option will take longer to implement because the current strategy for choosing a worker independent of the type of container is that we prefer to use team workers if they are available, which is the opposite for what this option prefers for check containers.

Currently, we have resource check containers only placed on global workers (the second option) but we will continue to discuss until we have decided on a solid solution.

**Comment by vito** [comment]
Closing this in favor of https://github.com/concourse/concourse/issues/2951
