### ISSUE TITLE
Enhancement: more visible display of the current pipeline name

### ISSUE THREAD

**Issue by spikymonkey** [concourse/concourse#295]
Hi Concourse team,

We have several pipelines which are visually identical - same jobs, tasks etc, just configured to build different branches. Over the course of the day we flip back and forth between them all in multiple browser tabs, and find it's pretty easy to get confused about which pipeline we're actually looking at.

The pipeline name is there on the browser tab title, and also forms part of the URL in the URL bar, but once you've opened way too many tabs as we tend to do (or pin it), the title gets squashed out of sight, and the URL is quite hard to scan quickly.

At the top of the pipeline view we have the hamburger and home icons, and then job group names in a nice chunky font that's really easy to read quickly. We wondered what you'd think about making the current pipeline name equally visible?

**Comment by xoebus** [comment]
I hear you. Our planned new navigation style should make this better.

**Comment by robdimsdale** [comment]
@vito as a result of some recent changes including a sticky hamburger and especially https://github.com/concourse/concourse/issues/700 the lack of clarity of which pipeline you are on has caused me to inadvertently trigger the builds of similar-looking pipelines, including accidentally shipping more than one product.

I'd like to see this prioritized because it's shockingly easy to run the wrong build when multiple pipelines have the same topology.

**Comment by dmason17** [comment]
@vito Has there been any headway with this?

**Comment by richarddowner** [comment]
Hello, any progress?

**Comment by sampeinado** [comment]
Please see comment on issue #1207 for a proposed solution to this issue.
