### ISSUE TITLE
Allow outputs to overlap with inputs

### ISSUE THREAD

**Issue by xoebus** [concourse/concourse#297]
Not sure we should do it but it might be worth thinking how we could do it.

**Comment by Gisleburt** [comment]
I'm not sure why this wouldn't be allowed. Perhaps I'm trying to do things incorrectly, however I want to build my pipeline so that it builds, tests and dockerizes a web application built in node. The build step will introduce files into the source directory, but I can't output it to the next job. This is what I'd like to do. This SO question explains my problem in more detail.

http://stackoverflow.com/questions/37750463/concourse-ci-build-artefacts-inside-source-pass-all-to-next-task

Am I doing it wrong, or is this a legitimate issue?

**Comment by andrewedstrom** [comment]
@xoebus I'm not exactly sure what you mean by allowing outputs to overlap with inputs. If this is still something you'd like would you mind reopening the issue and elaborating?

@Gisleburt To pass resources between jobs in a pipeline requires an external source of truth. This is by design, as [this user](https://stackoverflow.com/a/39041780/8216928) mentions on SO.
