### ISSUE TITLE
an empty worker tag array is interpreted as [ "" ]

### ISSUE THREAD

**Issue by xtreme-gavin-enns** [concourse/concourse#299]
this prevents us from just using vars in fly set-pipeline to determine worker tags - instead we must use an external tool to remove the worker tag lines from our yml since it looks for a worker satisfying the tag ""

**Comment by rmasand** [comment]
We think we're encountering a similar issue:

- we also want to use `--load-vars-from` to allow tags to be specified at configure-time
- we need to be able to pass an empty array when there are no tags
- an empty array, `tags: []`, works fine when we do it directly in the pipeline.yml - this seems to contradict this issue, but we suspect it's actually the same thing, since @xtreme-gavin-enns mentions using vars.
- when we try and use `tags: {{iaas_tags}}` in the pipeline yaml along with `iaas_tags: []`, we get the following error:
```
failed to load variables from file (secrets/creds.yml): yaml: unmarshal errors:
  line 12: cannot unmarshal !!seq into string
```

**Comment by keymon** [comment]
+1 it is quite annoying. 

In general we workaround the issues by:
 * Adding logic before uploading the pipeline in a shell script, doing the interpolation before and uploading different variables. For example, for a bucket name like `{{env}}-a-bucket`, we have to create a variable before uploading the pipeline `--var bucket-name=${ENV}-a-bucket` and use it.

 * For cases where pure YAML is required, as @rmasand describes, we have to do string substitution in the pipeline before uploading. Other option is using [spruce](https://github.com/geofffranks/spruce) or [spiff](https://github.com/cloudfoundry-incubator/spiff)

 * If the variable is going to be consumed by tasks, we do interpolation using environment variables and shell script in the task. 

All of these solutions are suboptimal workarounds.

**Comment by xtreme-gavin-enns** [comment]
Yeah, this is probably an instance of https://github.com/concourse/concourse/issues/360#issuecomment-215712431

This issue can probably be closed as a duplicate?

**Comment by keymon** [comment]
Actually I am not sure if your original issue is related to #360, I will move my comment there.

**Comment by vito** [comment]
consolidating into https://github.com/concourse/concourse/issues/360
