### ISSUE TITLE
master branch (and tag v.0.46.0) not merged into develop

### ISSUE THREAD

**Issue by robdimsdale** [concourse/concourse#30]
Meaning that bosh releases are currently being created as `0.45.0+dev` instead `0.46.0+dev`

**Comment by vito** [comment]
Yeah this is something we've sort of done as a way to prevent the typical bosh "infinite CI loop" (commit in release goes through pipeline, causing another commit at the end of it all). We basically only have our final release artifacts on master. It only slightly affects developers so we haven't bothered to do much more.

Has this impacted your external contributor workflow or was it just an oddity you noticed? I could see it being surprising if you e.g. had a final release already uploaded, and a deployment manifest that said `latest`, and your dev releases never got picked up since the latest final release version was more recent. In that case we could fix this.

**Comment by robdimsdale** [comment]
Yes it has an impact as a developer, because I have to mentally add 1 to the minor version of every release that's on local bosh-lite, and also to make sure I never upload the most recent final release, for the reason you mention - `latest` will pull in the final release instead of what I'm developing on.

I see the problem you face in principle, but it would only be an issue if you created final releases automatically, which I don't think you do (the minor versions come out every few days/weeks, rather than multiple times per day).

To be clear, this isn't preventing me from developing dev releases, but it's cognitive overhead that it feels is unnecessary. I imagine as we get more interest and hence developers (internal and external) it will become more pressing.

**Comment by vito** [comment]
We're now continuously merging master into develop.
