### ISSUE TITLE
Opening build info frequently gets stuck

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3047]
![image](https://user-images.githubusercontent.com/18585861/51153501-6f762a00-18ab-11e9-85f6-2a6fab2efbde.png)

![2](https://user-images.githubusercontent.com/18585861/51229192-7463d800-1996-11e9-910d-cff3537aa232.png)

## Bug Report

Sometime when I click on a build, it’s pending with loading message, but most of time it can quickly open build logs. Is it a known issue? We have seen this problem on all our Concourse clusters.

## Steps to Reproduce

This happens on all our concourse clusters with all pipelines. Frequently UI seems stuck, when we click on a build, it's just stuck at "loading" prompt. But after 10 or 20 minutes, UI backs to work.

Sometime the UI is stuck on "loading" for long time, and finally shows "501 Unauthorized" error.

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: Web nodes on K8S and Worker nodes on VM (vSphere)
* Browser (if applicable): Chrome, Firefox
* Did this used to work? Yes. As mentioned, this is an intermittent issue.

**Comment by vito** [comment]
I don't think #3044 is related; the screenshot only has 4 builds in its history, and that's all fetched async anyway.

@evanchaoli Do these builds have a lot of output? Does `fly watch`ing the same build demonstrate the same issue? Does it happen consistently with some builds or is it inconsistent overall?

**Comment by edtan** [comment]
@evanchaoli When the problem occurs, do you see anything in the browser's console logs?  I ran into a similar issue recently and remember seeing a `BadPayload` message in the browser logs, but I wasn't able to reproduce the issue later on.

**Comment by evanchaoli** [comment]
@vito I just found an occurrence of one of our clusters, UI is stuck at "loading", then I ran `fly -t test watch -j local-task-example/test`, the `fly` was also stuck. After several minutes, felt like 10, UI got build info loaded, and in the meantime, the `fly watch` showed build logs and returned.

**Comment by evanchaoli** [comment]
@edtan Not sure what console log you meant. I'm using Chrome, from "Developer/Developer Tools/Console", I don't see "BadPayload".

**Comment by vito** [comment]
@evanchaoli This sounds like it could be some sort of load balancer issue. How is yours configured? May also want to check ATC logs for anything suspicious.

**Comment by evanchaoli** [comment]
@vito What load balancer configuration should we check?

**Comment by vito** [comment]
I dunno. I don't know what kind of load balancer you have set up.

These kinds of issues are next to impossible to debug from afar, so I'd just keep digging and looking for clues. Look for a 10 minute timeout somewhere. I doubt there's a Concourse bug here but I'll leave the issue open for now since there's already some context.

**Comment by SimonXming** [comment]
We have fix this issue. We think the root cause is DB session is broken(maybe network glitches or something) and `bus.listener.Listen(channel)` will wait for the server response infinitely until IPVS connection timeout and close the TCP. The similar issue is #1738.
We fix this problem by implementing a new Dialer with query timeout for `lib/pq`. This patch running fine on our instance for about 3 days. @evanchaoli Anything else do you want to add? 
We plan to open a PR for it recently.
