### ISSUE TITLE
error: open /dev/stdin: permission denied: v4.2.1

### ISSUE THREAD

**Issue by gowrisankar22** [concourse/concourse#3071]
Getting error: open /dev/stdin: permission denied while running the intercept and hijack using fly.
$ fly intercept -j ops-pipeline/new-test-job -b 3
1: build #3, step: landscape-test, type: get
2: build #3, step: new-test-job-task, type: task
3: build #3, step: send-an-email, type: put
4: build #3, step: timer6h, type: get
choose a container: 1
error: open /dev/stdin: permission denied

**Comment by damzog** [comment]
Hi, had the same issue and struggled quite a bit to find out the root cause. For me it was actually that I was logging into a remote system and changing my user contect with sudo su <username> . This effectively causes issues with /dev/stdin, /dev/stdout, ... which is very well explained in https://unix.stackexchange.com/questions/38538/bash-dev-stderr-permission-denied .

I was able to work around this issue by using sudo login <username> instead. Hope that helps.
