### ISSUE TITLE
Allow for multi-tenant teams to not appear if they do not have exposed pipelines

### ISSUE THREAD

**Issue by loghen41** [concourse/concourse#3087]
I work in an organization where our concourse host is being divided into teams to represent different smaller organizations in our department.  In particular, we are dividing different pipelines into the different teams so that users only have access that pipelines that pertain to their workflow.

However, we have noticed that even if a member only belongs to one team, they are displayed all of the different teams on the host (despite not having exposed pipelines)  

I assumed that if a pipeline is exposed, it makes sense to display the team demarcation, and the pipelines associated with it.

But if the team doesn't have exposed pipelines, I am surprised that the team is displayed at all to the user.

We're currently operating with about 8-9 different teams, with most users only belonging to about 1-3 of those teams (some positions have overlap)

I have included an image of what it looks like below when a team is shown, with no pipelines set due to them not being exposed.

![image](https://user-images.githubusercontent.com/18034425/51348332-ac831d80-1a5f-11e9-8f5d-02f4623cd4f7.png)

This particular user has no authorization for this team, and is just being shown the empty box in case something eventually gets exposed.

I would assume my request would be that if there are no pipelines exposed on a team, and the member does not have authorization for that team, that the user doesn't see the team at all.

Or as an admin, I can toggle whether or not the user can see those teams.

I can potentially assist with this contribution, but it would take me a good deal of time as I'm the system admin for this tool in our department, and get pulled to a lot of other tasks.

**Comment by vito** [comment]
@pivotal-jamie-klassen My memory here is fuzzy - is this something we only show if you're an admin, i.e. so that you can still see what teams are all set?

**Comment by loghen41** [comment]
@vito so far, my experience is that all of the users can see.  We're using the LDAP auth (which you folks have integrated through dex.) 

In particular, we are both establishing users through ldap, and using the group search to find associated Security Groups the users are attached to.

There is an admin level SG that has access to all of the teams  (being set through `--ldap-group=admin_group_name`) 

As well, we have an admin level local user that has access to all teams (`--local-user=admin_user_name`)

Every other team has an explicit SG or whitelisted set of users associated with them.
`--ldap-group=team_sg_group`
"--ldap-user=user_one, "--ldap-user=user_two`

If I've misconfigured any of that in a way that causes users to be seen, I'm more than open to changing that configuration.

**Comment by pivotal-jamie-klassen** [comment]
@loghen41 Based on the appearance of the MEMBER/EXPOSED pills I'm thinking you're running 4.2. The dashboard will show the union of teams from two sources:
1. looking at the `/api/v1/pipelines` response and gathering up the `team_name` fields
1. looking at the `/api/v1/teams` endpoint

(cf. https://github.com/concourse/web/blob/master/elm/src/Dashboard/Group.elm#L59-L64)

My understanding of the authorization model is that the `/api/v1/teams` endpoint will expose teams of which you are a member, and  `/api/v1/pipelines` will expose pipelines with the `public` field set to true and pipelines from teams of which you are a member -- @pivotal-jwinters probably has more context than I do regarding how access to these resources is controlled. The one exception to this, in my experience, is if you are an admin as @vito mentioned (specifically if your `/sky/userinfo` response includes `is_admin: true`), which normally only happens if you are a member of the `main` team in 4.2.

This last point may be worth expanding on. I'd really like to know how your `main` team is configured (don't know if you're using bosh, but [this](https://bosh.io/jobs/atc?source=github.com/concourse/concourse-bosh-release&version=4.2.2#p%3dmain_team) is decent documentation for those options), to see if something funny is going on causing this issue.

If we can confirm this I'm inclined to look a bit closer at the LDAP connector, or maybe understanding a bit better what's going on on the LDAP side.

**Comment by loghen41** [comment]
@pivotal-jamie-klassen Good call on the main team.  We're actually running a cluster of dockers on ec2 instances for our process.  (we're a very different approach than most teams)

It looks like I had set the web node to allow for all users to be part of the main team.  

I'll update that now, and see if the problem persists.

**Comment by vito** [comment]
Ha, that'd do it. Related: #2721

**Comment by loghen41** [comment]
I just updated my configuration, and found that it is working as expected now.  I'm going to close this issue. Thanks for the quick replies.
