### ISSUE TITLE
Upgrading to 5.0.0 causes resource type checking become unrecoverable

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#3241]
After upgrading from 4.2.2 to 5.0.0, resources that use a custom resource type fail to check with `volume '<volume-id>' disappeared from worker <worker-handle>'`. These resource checks were never able to recover by itself. We observed that after we recreated the workers and manually triggered the checks, it seemed to check successfully. Not sure if we manually triggered the check before recreating, if that would've fixed it too? Even after recreating the workers, the resources were not able to recover on their own.

This was the pipeline that was used [link](https://github.com/concourse/drills/blob/master/longevity/shared-check-containers-across-teams/pipelines/check-containers-stress-test.yml)

**Comment by vito** [comment]
Note: this only happens when the workers are upgraded without being re-created. A re-create is necessary for the deploying the 5.0 BOSH release because now that it uses the binary, it configures a `--work-dir` which is different from the old volumes location, so the old volumes aren't there.

This acutely affected resource types however, which is interesting - the rest of the resources all recovered (via #2588 which is new in 5.0). I won't block shipping 5.0 on this, though, because it still recovers better than in previous versions. We're going to document in the release notes that a worker recreate is required for BOSH users.

**Comment by clarafu** [comment]
For now, a possible solution that we will spike on is having resource type radar scanning to not loop on acquiring the lock and just have it exit when it fails to acquire (like how it worked before). This solution is possible because we still share resource type versions even when global resources is disabled, so there is no real point to needing to require similar resource types between pipelines to fetch it's own versions.

**Comment by vito** [comment]
> This acutely affected resource types however, which is interesting - the rest of the resources all recovered (via #2588 which is new in 5.0). I won't block shipping 5.0 on this, though, because it still recovers better than in previous versions. We're going to document in the release notes that a worker recreate is required for BOSH users.

Turns out this was wrong and it was just the thing @clarafu found - this will be in v5.0, then!

What's cool is after her fix was deployed everything recovered gracefully within a few minutes. So our release note won't even have to sound very dire.

**Comment by cirocosta** [comment]
> a possible solution that we will spike on is having resource type radar scanning to not loop on acquiring the lock and just have it exit when it fails to acquire (like how it worked before).

Would this possibly remediate https://github.com/concourse/concourse/issues/3249?

**Comment by vito** [comment]
fixed by #3275
