### ISSUE TITLE
Question: Is concourse susceptible to CVE-2019-5736?

### ISSUE THREAD

**Issue by duncanmortimer** [concourse/concourse#3276]
## Bug Report

[CVE-2019-5736](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5736) refers to a vulnerability in runc, versions <= 1.0-rc6, where an attacker can overwrite the host runc binary (and consequently obtain host root access).

My understanding is that concourse manages its containers through garden, which is in turn based on runc.  Looking at the dependencies in concourse's go.mod, it looks like there is a dependency on [runc](https://github.com/concourse/concourse/blob/a988db838444cc380b24fabb1d9eec9cc30a4c8d/go.mod#L129), version 0.1.1.

Is this something to worry about?

Thanks for your help.

## Version Info

* Concourse version: 4.2.2

**Comment by vito** [comment]
Yep. We're working on getting a fix out as v4.2.3. Hopefully today or tomorrow.

For anyone wondering, judging by the CVE report this vulnerability should only affect [privileged tasks](https://concourse-ci.org/task-step.html#task-step-privileged) and [privileged resource types](https://concourse-ci.org/resource-types.html#resource-type-privileged) - including the commonly-used `docker-image` resource, though we haven't investigated this exhaustively.

Thankfully the `docker-image` resource never executes any of the container image's code while fetching it, but it's still pretty scary. We should start transitioning everyone to the [`registry-image` resource](https://github.com/concourse/registry-image-resource) with v5.0.0 - it doesn't require `privileged: true`, so that'd be one less attack vector.

**Comment by duncanmortimer** [comment]
Thanks Vito

**Comment by shinji62** [comment]
Can't wait for the patch! :)

**Comment by goldstar611** [comment]
Also waiting for this one to be resolved. I'm sure there's a bunch of QA testing to be done when upgrading a core component. Thanks for everyones work on Concourse CI!

**Comment by vito** [comment]
Just checking in as it's been a few days since my initial comment. We've almost got a release ready, aiming for some time today. :+1:

**Comment by xyloman** [comment]
Is there an ETA when the release will show up here:  

https://bosh.io/releases/github.com/concourse/concourse-bosh-release?all=1

**Comment by vito** [comment]
Late update: as those monitoring our releases will have noticed, we managed to get 4.2.3 out on Friday, so I'll go ahead and close this.

@xyloman We ran into a problem that prevented the release from appearing on bosh.io - we'll get that all sorted out on Tuesday (Monday is a holiday here in Canada). In the meantime you can bump the Garden-runC release version in your deployment straight to v1.18.2 which should work just fine with v4.2.2 of Concourse. The v4.2.3 release is important for non-BOSH users since we embed Garden-runC directly in that scenario, but BOSH users already have the capability of bumping the Garden-runC dependency without waiting for a new release of Concourse. Let me know if you have any problems though!
