### ISSUE TITLE
Mixed feelings about absolute time in build history.

### ISSUE THREAD

**Issue by bwinter** [concourse/concourse#3321]
The new switch to using absolute time on concourse job history seems like a step in the wrong direction to me. My general use case is to see how long something has been failing, the specific date seems less useful generally. I have a suspicion I will now just be forced to do this date math in my head every time I want to know how long ago something started failing.

Maybe there is a middle ground here or maybe I just need to spend time with this new UI either way, I wanted to get this conversation started.

**Comment by bwinter** [comment]
Someone suggested a hybrid that uses github's technique. Namely showing "ago" notation on recent changes then switching to absolute times further out. This seems like a good compromise and seems to support my use cases.

**Comment by vito** [comment]
related to #3162

/cc @analytically who left similar feedback here: https://github.com/concourse/concourse/commit/3544de50b0f073eaa864661396c67df1c1fd8854#commitcomment-32307862

**Comment by bwinter** [comment]
Looks like this is the conversation that started the change: https://github.com/concourse/concourse/issues/3019

**Comment by analytically** [comment]
Another option would be in-place replacing the date text when clicked. Flip from relative to absolute with a click on the time.

**Comment by analytically** [comment]
And store the selection of relative/absolute client-side?

**Comment by evanchaoli** [comment]
I like @analytically 's idea of "flipping". Seems like different people think in different perspectives. We initiated the absolution time change, because our users strongly asked for that. As we made the absolution change, we'll try to implement the "flip" feature.

**Comment by vito** [comment]
@evanchaoli FWIW, before this change the absolute time was available as a tooltip on hover. Guessing that wasn't enough? Just checking to make sure it wasn't an oversight.

**Comment by Twiknight** [comment]
The change was submitted by me. The reason is, relative time looks confusing in my use case.

Since there are supports on both side, I think it would be better if we can have a choice on how the history time looks like.

Well, 2 rough ideas in my mind is, 

1. Add tooltip to the history time, and show `some time ago` in the tooltip
   
<img width="546" alt="screen shot 2019-02-18 at 10 20 21 am" src="https://user-images.githubusercontent.com/11556597/52924262-fca71580-3366-11e9-97ba-15452842ca2e.png">

2. Add a switch in header or bottom bar to switch the time format.

![screen shot 2019-02-18 at 10 40 16 am](https://user-images.githubusercontent.com/11556597/52924892-a7203800-3369-11e9-8f25-bec6b08d5efa.png)

Any ideas?

I don't mind to contribute one more once we reached agreement

**Comment by vito** [comment]
I'd really like to avoid having a knob for this. Can we find a middle ground? Next we'll be deliberating over what the default value should be. 🤔

GitHub for example shows relative time, with absolute time available as a tooltip (just like we used to do). Once difference is that it switches to absolute time after something's "old enough" (not sure what the threshold is). Would that make things better?

For example, could we show relative time if it's within 24 hours, and absolute time if it's any older than that? @jama22 mentioned this idea here: https://github.com/concourse/concourse/issues/3019#issuecomment-455218963

@Twiknight Could you provide some background on what it is about your use case that makes relative time less helpful? Concourse has been used for all kinds of things over the years and this is the first time this has really come up (that I can find). There seems to be a bit of pushback here and we haven't even shipped it yet so I'd like to know more about the motivations for the change. Thanks!

**Comment by Twiknight** [comment]
@vita, In my org, we need to track builds over weeks or even months.

In cases of older builds, showing something like `24d 15h ago` is actually not helpful, especially when you are trying to associate a ci build with events tracked in other systems.

**Comment by vito** [comment]
@Twiknight Gotcha - in that case, would showing relative if within 24 hours and absolute if it's older than that work? It sounds like this is mainly a problem with older builds.

**Comment by evanchaoli** [comment]
@vito Before this change, when we move mouse cursor on a relative timestamp, it take a few seconds to show a tooltip of absolute time, which made the tooltip hard to find. So, yes, when I filed the original issue, I didn't notice the tooltip, and seemed that none of our users realized the tooltip either.

Based on above discussion, we think there are several solutions:

1. Flipping between  absolution and relative times by clicking on timestamp.
2. Show relative if within 24 hours and otherwise absolute time.
3. Add an switch on GUI to allow user to choose absolute or relative.

Options 1&3 will lead to the other issue: what should be a default option when one opens a build? Once a user makes a choice, he will expect concourse to remember his choice. To archive that, concourse will have to store per-user choices to database, thus I feel these two options are low ROI.

Then option 2 comes out. The only problem is how to decide the threshold. 24-hours sounds a reasonable threshold, but I'm not sure if every user likes it. Thus it would be great if we add a global configuration for the threshold, and default to 24 hours. On our cluster, we may set the threshold to be 1 second, which equals to always show absolute time; and on @bwinter 's cluster, he may set the threshold to 1 year or whatever long. 

No matter which solution, tooltip should be still there. If currently shows absolute time, the tooltip should show relative time, and vice versa.

**Comment by Twiknight** [comment]
showing different format according to relative time value looks good for me.
But there are a bit more details to discuss if we want to go this way.

Say if I have a build that started a day ago and finished today, I would get something like
```
started   Feb 13 2019 02:56:28 PM
finished  10h 59m 59s ago
```
which looks a little inconsistent 

Or we only consider start or finish time when choosing the format. It would look better, but that would require some refactoring on how to generate the banner area, (approximately 50 to 70 lines on my first sight, correct me if I'm wrong)

**Comment by vito** [comment]
@Twiknight Ah good point. I actually think that example is pretty reasonable as-is though. It makes it easy to notice when a build that started a long while ago only just recently finished.

@evanchaoli +1, though I really don't think it's worth adding a config for the duration threshold unless people really really want it...and for good reasons. I would rather just pin this down to a consistent behavior across all Concourse instances that makes most people happy. The only complaints I've heard are for viewing old builds, so I'm thinking we should just fix that and see how people like it.

**Comment by bwinter** [comment]
Like @evanchaoli I also did not realize the tooltip existed previously. I agree that my ignorance was likely due how long it takes for the tooltip to show up (maybe just speeding this up would mitigate some of the concerns here?).

FWIW: For our team, we rarely need to cross reference a build date with anything outside concourse and usually a ball-park "it started failing 10 days ago" captures enough context for us to suspect what might have caused breakage (beyond a month and it starts to feel like our current state has moved far beyond that context).

I can definitely see how being able to copy paste a date into a search would be useful, I think with that in mind the tool tip being the "ago" format is probably pretty good. I think it would be nice if it showed up a little quicker but thats basically a "nice to have".

**Comment by vito** [comment]
Closing this as #3333 has been merged. Seems like a good middle ground, so let's see how people feel about it in 5.0. Thanks for the feedback everyone!

There may be room for polish by making the tooltip show up faster, maybe with the same style as the new tooltip we have for the 'yellow arrow' icons. Right now it's just a standard HTML tooltip so it's up to the browser UI to determine timing/rendering.
