### ISSUE TITLE
Issues caused by exposing build ENV via a resource

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3325]
### Background
As my request of expose build ENV to task being rejected with the issue https://github.com/concourse/concourse/issues/494, then I followed the suggest from https://github.com/concourse/concourse/issues/494 to implement a resource type, let's name it `buildinfo`, that `get` build ENVs to files, so that `task` may fetch build info from files.

### Problems I have seen

When I implemented `buildinfo`, I initially returned a fixed version from `check`, because I thought `buildinfo` is not actually a resource, there is no version for build as `check` doesn't see any build ENVs. Then immediately I realized that that way didn't work, because all builds' tasks got same build info file. Looks like that Concourse will cache a resource, if `get` a same version, cached `get` results be used, which obviously doesn't fit `buildinfo`, as every build has different build id, build name, etc..

Then I changed `check` to return `timestamp + a random number` as version, which seemed to work until I found one build wrongly got its previous build's build name. See the screen shots:

![build30](https://user-images.githubusercontent.com/18585861/52984247-90411a80-3429-11e9-9696-10eab1658efa.png)

![build31](https://user-images.githubusercontent.com/18585861/52984255-9800bf00-3429-11e9-9901-e8d80b6a2a93.png)

From the screen shots, we can see that, both build 30 and 31 got same version of `build` resource, thus build 31 got wrong build ENV.

Then I noticed that `build` resource also `check`s every 1 minute:

![buildinfo](https://user-images.githubusercontent.com/18585861/52984380-21b08c80-342a-11e9-87cb-1d4315b6df43.png)

which seems to mean if two builds are triggered within 1 minute, then they will get same version of `buildinfo`, thus the later build will get wrong build ENV as above screen shot I attached. I also tried to set `check_every: 2m` for the `build` resource, then since `git` resource gets new version every 1 minutes, so many builds got wrong build ENV.

### My thoughts

1. If I implemented `buildinfo` in wrong way, please correct me.

2. Use a resource to get build ENV still looks weird, `buildinfo` has no version, but it's still `checked` periodically, the we have to make sure `check` interval is short enough, otherwise if a version is cached, a build might get wrong build ENV.

3. If Concourse insist on exposing build ENV via a resource, then `buildinfo` is a type of special resource that doesn't have meaningful version. For this type of resource, `check` should never be called, and `get` should be passed with a "NA" version, and `get` should not be cached. This could be implemented by `check_every: 0`.

4. Related to https://github.com/concourse/concourse/issues/3321. The above builds screen shots show a use case that we prefer absolute time than relative, then comparing multiple builds, relative time stamps make comparison hard as they keep changing. Though there is tooltip on hover, but it's not convenient for taking tooltip into screen shot. 

## Steps to Reproduce

As described above.

## Expected Results

Every build task should get correct build ENV.

## Actual Results

Some build task got wrong build ENV.

## Version Info

* Concourse version: 4.2.2
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: K8S
* Browser (if applicable): Chrome
* Did this used to work? No

**Comment by vito** [comment]
You'll need to use `put` for this, as `get`s are cached. The `put` should return a version unique to the build (perhaps the build ID?) and the `get` will then always run fresh.

**Comment by evanchaoli** [comment]
@vito Thanks for the sample code. With the sample code, you dump build ENV in `in`, and `out` returns build id as version, so looks like we should use `- put: build` in a job, and the implied `get` does the actual work? Which means that we need invoke two containers in order to build build metadata. The reason of not exposing build ENV to `task` stated in Concourse doc is to emulate versioning. Can you please explain why that is a concern? As anyway user may get build ENV from resource, not exposing them add just some overhead to what user wants to do.

**Comment by vito** [comment]
@evanchaoli Concourse is designed to eliminate the many ways to shoot yourself in the foot with automation, not enable them. There are enough CI systems that do that. It does this by making it hard, or at least feel weird, to do the wrong thing. If it feels weird that it takes 2 containers to do this, well, that's feedback from Concourse that what you're doing might be weird. Or it might just be something Concourse hasn't accounted for in its design yet, and we should figure out how to improve it.

Typically, uses of metadata fall into the following cases:

1. For emitting notifications about the build status, linking to the build, etc.
1. For annotating externally published artifacts with metadata about where it came from (for auditing purposes, or just visibility in general).
1. Using the metadata to simulate increasing versions for each build, i.e. using it to version your artifacts like `foo-$BUILD_ID.tgz`.
1. Using the metadata to annotate artifacts themselves. And I mean *pure metadata* (like `--build-info` or whatever).

Cases 1 and 2 are the justification for exposing metadata to resources. Those are operations affecting external state, so resources are the correct way to do them. This way we at least keep the capability away from tasks, which are typically where filenames are determined, and which shouldn't be modifying any external state in the first place.

Case 3 however is a terrible idea and Concourse tries to prevent people from doing it. The reasoning is pretty simple: if you were to move your pipeline to a new Concourse cluster your versions would start over at 1 and your pipeline would start clobbering its old versions with new ones. Whatever you're versioning now implicitly depends on ephemeral state in your CI server.  Pipelines are meant to be self-contained, and the CI server itself is meant to be non-critical and replaceable (as is The Concourse Way).

Case 4 is sort of the less-bad version of case 3 I suppose - as long as it's just being used as metadata that's OK, but it is a little weird to tie artifacts to ephemeral state that way, since Concourse is supposed to be "disposable".

Yes, technically by exposing this metadata via resources we still technically allow someone to shoot themselves in the foot and accomplish case 3 anyway. But now they at least have to take the safety off.

If you're completely sure that what you're doing doesn't have any risks and you're "in the clear" as far as anti-patterns go, 2 shortlived containers that do basically nothing should really be nothing to worry about. And as I mentioned before, you could also just be trying to do something that we haven't gotten to implementing the "proper way" yet, i.e. notifications (https://github.com/concourse/rfcs/issues/10). If you explain your use case some more I can get you an answer there.

**Comment by evanchaoli** [comment]
@vito Thanks for the detailed explanation. I now understand your idea of "stateless concourse". Actually a lot of our users are doing case 3, that's reason why they keep asking me for exposing build ENV to tasks. In our environment, we maintain a production concourse cluster, users don't expect to switch to another cluster. Also we backup Concourse db, so if the production cluster gets down, after we recover it, build history is expected to retain.

But I personally have hit the build start-over issue when I destroyed a pipeline and reset the pipeline with same name, then build name started over from 1, and my build output was overwritten, which was bad.

I'll communicate with our users, and try to convince them to not use build metadata to version build artifacts.
