### ISSUE TITLE
concourse couldn't correctly handle finishing build/step when build_event_sequence not exist

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3417]
## Bug Report

Last weekend, our Postgresql had some issue and broke for 10 minutes. After the database was recovered, `concourse web` still reported errors like:

    {"timestamp":"1551437987.452131271","source":"atc","message":"atc.syncer.pipeline-B747-21:scheduler.tick.failed-to-acquire-scheduling-lock","log_level":2,"data":{"error":"pq: pgbouncer cannot connect to server","session":"20.150.27393"}}

All pipelines were hung up until we manually restart `concourse web`.

## Steps to Reproduce

Shutdown database and restart database.

## Expected Results

Concourse is expected to auto reconnect to database.

## Actual Results

Concourse keeps raising db error, all pipelines hang up.

## Version Info

* Concourse version: 4.4.2
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: K8S
* Browser (if applicable): Any
* Did this used to work? No

**Comment by SimonXming** [comment]
We have a about 50 pipelines with similar YAML. Each one contains three jobs `job-1 -> job-2 -> job-3`. 

Take `pipeline-1` for example, during the DB outage, whole scheduler timeline according the concourse UI:
```
// DB down at 03-01-06:58:39 PM
// DB back at 03-01-06:59:47 PM

1. Job-2-701 (success)
   03-01-06:40:57 PM - 03-01-07:01:13 PM
2. Job-3-697 (success)
   03-01-07:01:21 PM - 03-01-07:21:33 PM
3. Job-1-715 (success)
   03-01-07:21:44 PM - 03-01-07:41:54 AM
4. Job-2-702 (failed)
   03-01-07:41:57 PM - 03-02-03:44:14 AM
5. Job-3-69x (**not exist**)
   03-01-08:02:00 AM - 03-01-08:22:10 AM
6. Job-1-716 (success)
   03-01-08:22:18 PM - 03-02-03:45:42 AM
7. Job-2-70x (**not exist**)
   03-02-03:45:45 AM - 03-02-04:06:00 AM
8. Job-3-698 (success) 
   03-02-04:06:24 AM - 03-02-04:26:35 AM
```
According the log, `Job-2-702` duration is about 8 hours(normally should be 20 minutes), and seems stuck at `engine/db_engine.go` `Resume()`(no log after printing `atc.syncer.pipeline-1:scheduler.tick.scheduling.try-start-next-pending-build.starting`)

I guess it db lock issue because I saw a lot of logs like:
* `lock was lost while held, possibly due to connection breakage`
* `scheduling.try-start-next-pending-build.lock.release.failed-to-release`
* `cannot execute UPDATE in a read-only transaction`

* Pipeline YAML and Log: https://gist.github.com/SimonXming/ad274cab792d3c002f096388e60c4f44
