### ISSUE TITLE
runtime : allow creation of ephemeral check containers

### ISSUE THREAD

**Issue by topherbullock** [concourse/concourse#3424]
Step 1 of the Runtime side for #3079 is to create a method to create ephemeral check containers, and handle their destruction ( and the destruction of their RootFS Volume ) 

Probably some work to clean up GC now that it doesn't need to consider resource check containers, but we also need some way to ensure they are retained until Garden's TTL expires them.

### GC: 
  - Garden won't deal with GC of the RootFS COW Volume
  - We could have an image plugin deal with the deletion of the COW volume when the container is destroyed
  - Ensure that distributed GC's diffing of what's on the worker against the DB doesn't clean up the check containers from underneath us ( depending on the direction "missing since" looks, and where the source of truth is.. _probably_ the DB )
  
### Performance
 - Ensure we don't have a lot of overhead on creating these containers
 - provide a mechanism to measure the performance once we implement ephemeral check containers
 -  add some metrics to track the check containers across the cluster of workers, as we won't have anything in the DB.

### Peas!
see :[ Garden's `ProcessSpec`](https://github.com/cloudfoundry/garden/blob/62470dc86365fb365be099df5c4b59650d695c4b/container.go#L136-L172)
 - Maybe this would address some of the concerns around GC?
 - Investigate how much is shared between the peas and from the original container to the peas
 - Do all the peas in the "pod" have a TTL?
 - Can we use the image plugin with the peas?
 - How many peas can we create off an initial "pod" container?

**Comment by ddadlani** [comment]
We are spiking on the ability to create image volumes for ephemeral containers in #3607

**Comment by ddadlani** [comment]
Blocked on #3607

**Comment by ddadlani** [comment]
We unblocked this because of the amount of time #3607 is going to take. The reason it was blocked on #3607 was because we needed a way to keep around image volumes and a cache for the git-resource check (git-resource checks currently have an implicit "cache" because the check containers stick around for an hour).

Currently, we fetch images for check containers and keep them around using a [`db.ForContainer` resource_cache_use](https://github.com/concourse/concourse/blob/2f76f04ff2a0f9ddb5afa0f7273ed6a33749f2d2/atc/db/resource_cache_user.go#L27). For ephemeral containers, there is no db container created, which means that we cannot create a `db.ForContainer` resource_cache_user for them.

We found that because image volumes fetched for checks become `resource_cache`s, they do not get garbage collected even if there is no resource_cache_use. We can therefore keep image volumes for ephemeral check containers around by simply removing the resource_cache_use.

We would also need the concept of "check caches", similar to resource caches, but created for a check container, to codify the implicit "caching" that the git-resource does. As an interim solution, the checks work without this cache, i.e. a git-resource check would clone the repo every time.

**Comment by ddadlani** [comment]
The way this currently works is that we created a `garden_plugin` for baggageclaim to create COW volumes of existing volumes to use as the rootfs for ephemeral containers. Code for this lives in https://github.com/concourse/baggageclaim/tree/gdn-plugin . 

The garden.ContainerSpec used for creating ephemeral containers specifies a GraceTime for the containers, which means that the container (and its associated COW rootfs volume) will self-destruct after GraceTime since the last request. We created separate flows for creating ephemeral containers and fetching images for ephemeral containers. Code for this lives in https://github.com/concourse/concourse/tree/ephemeral_containers.

**Comment by cirocosta** [comment]
Hey,

I remember in the early chatting around this that we were not aware of how costly
container creation is, so I got interested in having a deeper look into how long each 
step involved in creating a "guardian container" takes so that we could have some
insights into how that whole process looks, so here's some data from that.


### steps involved

The main part in [`cloudfoundry/guardian`][guardian] where we can see the container creation
steps is `gardener/gardener.go`.

There we found the three main routines associated with the process of setting up
a container:

#### volume creation

```go
runtimeSpec, err := g.Volumizer.Create(log, containerSpec)
if err != nil {
        return nil, err
}
```

*(see [gardener.go:220](https://github.com/cloudfoundry/guardian/blob/68bc58c21c62d5fb05781ea62875675a6ea42ffd/gardener/gardener.go#L220-L223))*

#### container creation

```go
desiredSpec := spec.DesiredContainerSpec{
        Handle:     containerSpec.Handle,
        Hostname:   containerSpec.Handle,
        Privileged: containerSpec.Privileged,
        Env:        containerSpec.Env,
        BindMounts: append(containerSpec.BindMounts, networkBindMounts...),
        Limits:     containerSpec.Limits,
        BaseConfig: runtimeSpec,
}


if err := g.Containerizer.Create(log, desiredSpec); err != nil {
        return nil, err
}
```

*(see [gardener.go:230](https://github.com/cloudfoundry/guardian/blob/68bc58c21c62d5fb05781ea62875675a6ea42ffd/gardener/gardener.go#L230-L242))*


#### network set up

```go
if err = g.Networker.Network(log, containerSpec, actualSpec.Pid); err != nil {
        return nil, err
}
```

*(see [gardener.go:255](https://github.com/cloudfoundry/guardian/blob/68bc58c21c62d5fb05781ea62875675a6ea42ffd/gardener/gardener.go#L255-L257))*


### local tracing

As a quick way of checking how those times look like, I started with `pprof`,
injecting few trace points in the code, wrapping those methods mentioned above.

See https://gist.github.com/cirocosta/7e53cde47405f422ef66c8c2ff563630 for the patch.

Here's how it looks like:

![](https://user-images.githubusercontent.com/3574444/58750580-cb6cd400-8483-11e9-81bb-ce8b3aa774df.png)

As we can see, almost all of the container creation time gets split in just
setting up networking and the actual containerization, which is what we'd expect
as `concourse` uses `gdn` with `--no-image-plugin` (Concourse deals with the
"volumization" itself).

Looking at few more samples, we can see the distribution over few counts:

![](https://user-images.githubusercontent.com/3574444/58750582-cb6cd400-8483-11e9-93ba-dc99fd2e3b48.png)


### tracing in `hush-house`

As a way of having the same as the "tracing" step before running continuously in
`hush-house`, the approach changes a bit - instead of using `pprof` and hitting
its `/trace` endpoint to capture the traces for a while, [Jaeger][jaeger] instead,
instrumenting those very same points in the code (see my [`tracing` branch under
`cirocosta/guardian`](https://github.com/cirocosta/guardian/tree/tracing)).

Interestingly, the results don't change all that much, aside from the fact that
the numbers are higher.

Looking at the last 3 hours in `hush-house`, here's the breakdown of time to create a container in a worker (`volumizer` + `containerizer` + `networker`):

<img width="1434" alt="Screen Shot 2019-06-02 at 7 08 36 PM" src="https://user-images.githubusercontent.com/3574444/58803087-a770d600-85dc-11e9-99f1-4977c8be0142.png">

Looking at few traces:

<img width="730" alt="Screen Shot 2019-06-03 at 8 48 06 AM" src="https://user-images.githubusercontent.com/3574444/58803183-d25b2a00-85dc-11e9-8b69-d6560ebb007f.png">
<img width="730" alt="Screen Shot 2019-06-03 at 8 48 16 AM" src="https://user-images.githubusercontent.com/3574444/58803184-d25b2a00-85dc-11e9-9550-fbda9403bf9d.png">
<img width="729" alt="Screen Shot 2019-06-03 at 8 48 23 AM" src="https://user-images.githubusercontent.com/3574444/58803186-d25b2a00-85dc-11e9-83cd-f89ab7495fdd.png">

I didn't find a way of doing some math on top of all of the traces captured, but looking at some traces "randomly", it seems like the time ratio seems consistent with the times reported with the `local` experiment.

note.: this is an almost "idle" worker.

[guardian]: https://github.com/cloudfoundry/guardian
[jaeger]: https://www.jaegertracing.io/

---

thanks!

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta this is super cool!

**Comment by kcmannem** [comment]
@cirocosta my test didn't produce cool graphs and is less scientific but I found that. If you create 250 containers in serial it takes around ~.5s each on docker composed environment and ~4 mins if you make them in parallel.

**Comment by kcmannem** [comment]
Non-issue but I thought I'd note it down. Docker-image resource requires a privileged container to run so we'll have to go through the chown the rootfs flow every check container. This would be a problem if the fs had lots of files but its only a few.

**Comment by ddadlani** [comment]
@cirocosta this is pretty cool. I would be interested to repeat this with the ephemeral check containers code merged in, because for those `garden` needs to initiate COW volume creation (for the container image).

@kcmannem Did we collect any stats on a good number of containers to create in parallel? Of course it would depend on the available resources on a worker but it might be useful information for container scheduling in the future

**Comment by kcmannem** [comment]
@ddadlani nothing more concrete then a basic for loop hitting garden apis in go routines. That test lead to creating all 250 containers in around 4 mins. Parallel load is hard to work around because there is a global iptables lock to make sure each network is mutually exclusive.

**Comment by vito** [comment]
Could we mitigate the network create/delete overhead by placing all `check` containers in the same network? :thinking: 

https://github.com/cloudfoundry/garden/blob/e9c503bfdeedec3e591f46a85e3cd0e7b1ebecc1/client.go#L132

(Would that be a security concern? :thinking: )

**Comment by kcmannem** [comment]
might be worthwhile to ship this along side global-resources defaulted to true  so we reduce the container creation load.

**Comment by ddadlani** [comment]
@cirocosta to add analysis for performance impact of extra cgroups on the VM

**Comment by ddadlani** [comment]
pending performance testing + check cache implementation

**Comment by kcmannem** [comment]
and tests in general

**Comment by ddadlani** [comment]
This is paused for now, waiting on a chance to pair with Core on creating check caches. Some resources (e.g. git resource) have "implicit" caches which persist for the entire resource config check session. However, with the introduction of ephemeral containers, check sessions will go away so we need to create explicit check caches for each check container to use.

A lot of work in Core (e.g. #3788) will affect the implementation of check caches, so this will wait until that is completed.

**Comment by ddadlani** [comment]
If we switch over to `containerd` (#3891) the implementation of this will change. Just a note for any future changes

**Comment by vito** [comment]
I'm going to close this out as I think we have a much shorter path to victory with LIDAR as the default. :+1: 

There are interesting findings here which I'll make sure to reference from issues in the [new project](https://project.concourse-ci.org/projects/MDc6UHJvamVjdDM5Nzg3OTk=).

**Comment by dlbock** [comment]
@vito 👋 I've been following links from https://github.com/concourse/concourse/issues/3588 -> https://github.com/concourse/concourse/issues/3079 -> to here -> and finally to the [linked project](https://project.concourse-ci.org/projects/MDc6UHJvamVjdDM5Nzg3OTk=) and correct me if I'm wrong but it looks like work hasn't started to address the core issue? Or am I misunderstanding things?
