### ISSUE TITLE
Allow fly to force kill containers

### ISSUE THREAD

**Issue by danrspencer** [concourse/concourse#346]
I've had an issue a couple of times where I've had containers (not 'check' ones) which refused to obey their TTL and die. Possibly because a hijack session hasn't ended correctly. I've also encountered issues with a check resource failing and being unable to bring it back without nuking the resource/pipeline state to force a restart on the containers.

Allowing a 'kill' type command following the same syntax to the 'hijack' / 'intercept' commands would be useful for handling situations like this quickly and easily.

**Comment by DanielJonesEB** [comment]
Encountered the same thing here - I think an `intercept` didn't close cleanly, and some containers with jiggabytes of stuff in keep having their TTL reset at 4:30. Killing the pipeline worked.

**Comment by roberttaylor426** [comment]
Killing the pipeline sometimes helps, sometimes there are still containers lingering.

**Comment by Osis** [comment]
Do we feel like this could be merged with https://github.com/concourse/concourse/issues/346?

**Comment by DRuggeri** [comment]
Maybe a dense question, but how does one see the TTL of a container? With fly? I'm seeing lots of containers hanging around (264, actually) with "none" defined for pipeline, job, build #, build id and name wreaking havoc on the ability to launch pipelines. They are all "check" type containers, so I'm curious if concourse even *thinks* they should be cleaned up.

**Comment by iswix-llc** [comment]
That's a great question.  I see the same behavior with containers hanging around and the result is I can't start anymore pipelines.
https://github.com/concourse/concourse/issues/1620

**Comment by vito** [comment]
This issue is very old and we've since completely redone how containers are kept alive - there should no longer be the original case of a hijack session keeping containers alive forever. (In fact, we now seem to have a new problem of them being killed too early.)

I'm going to close this to prevent it from becoming a dumping ground - if you still have a use case where you'd specifically like to kill an individual container (as opposed to doing something Concourse should automatically do for you and is failing at - i.e. GCing them), feel free to open a new issue!
