### ISSUE TITLE
deleted resources remember their history

### ISSUE THREAD

**Issue by craigfurman** [concourse/concourse#372]
Not sure if this is intentional or not. We are using 1.0.0.

To reproduce:

1. configure a pipeline with some resource (a Git resource in our case)
1. On the resource page of the web UI, a new version should be shown, as expected. Record the URL
1. re-configure the pipeline, removing that resource and all jobs that depend on it
1. The resource URL still works on the web UI, complete with history
1. re-configure the pipeline, re-adding the resource.
1. It remembers its history

**Comment by JamesClonk** [comment]
I'd be interested about this too.
For us it presents as a problem when trying to remove a version resource, then add it back hoping it would resets its history, but it doesn't.
Is there any other way to reset a resources history?

**Comment by vito** [comment]
This is intentional; we never delete anything from a pipeline, since you may just be temporarily commenting it out. I totally agree that there should be a way to clear out resource versions though, either in bulk or individually - not sure which use case is more common yet. I see the latter a lot with the semver resource (accidentally bumped to 2.0, etc), but this sounds like the former. What is it you were trying to do?

**Comment by MatthiasWinzeler** [comment]
We ran multiple times in the latter (exactly with semver resources or cached git resources) - so clearing out resources individually would suffice for us.

**Comment by craigfurman** [comment]
Clearing out resources by name would work for our use case.

**Comment by vito** [comment]
Closing in favor of #145 then. Thanks.

**Comment by craigfurman** [comment]
thanks @vito, I didn't notice #145 at first!
