### ISSUE TITLE
Concourse worker to support reload built-in resource types.

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#3763]
## What challenge are you facing?

Starting from Concourse 5.0.0, we added some our own built-in resource types on Concourse workers, which is working fine. Because on our cluster, some resource type's docker image is huge, larger than 1GB, making them built-in significantly saves image downloading time. The other benefit is we, as admin, fully control versions of those resource types.

The only issue is, when we need to upgrade those built-in resource types, we have to restart Concourse workers to get new versions to work. Our current operation model is, 1) download new versions of resource type files to workers, 2) landing workers, 3) upgrade built-in resource types, 4) restart worker. Because there are a lot of pipelines running, landing workers takes time, so upgrading built-in resource types always requires a maintenance window.

## What would make this better?

We want Concourse worker to be able to automatically reload built-in resource types, maybe triggered by SIGHUP.

## Are you interested in implementing this yourself?

Yes. We are willing to contribute.

**Comment by evanchaoli** [comment]
@vito Can you please comment on this?

**Comment by vito** [comment]
I would hold off on this as we're in the middle re-designing how resource types are loaded onto workers: #3810 

The plan is to have the `web` node stream them to the workers rather than have the workers provide them itself. This would mean you no longer have to manage the resource types on the workers themselves.

Technically this just moves the problem from the `worker` nodes to the `web` nodes, however `web` nodes are much easier to reconfigure + restart as they don't involve a lengthy draining process.

@ddadlani @kcmannem This is probably a good opportunity to think about how updating resource types with multiple ATCs behaves.
