### ISSUE TITLE
Configurable metric emitting behavior

### ISSUE THREAD

**Issue by SimonXming** [concourse/concourse#3769]
## What challenge are you facing?

We are running a load test on Concourse 5.0.1. During the load test, we observe quite a lot `xxxx.queue-full` error log from console and data loss from Grafana dashboard.

Turns out concourse have a metric event sending channel([Code](https://github.com/concourse/concourse/blob/master/atc/metric/emit.go#L100)) with hard-coded buffer size. When it fulled, it will drop the metric event.

## What would make this better?

1. We could have a configurable buffer size for event sending channel
2. Also we could have a configurable number of emit worker(`goroutine`) for emiting the metrics.

## Are you interested in implementing this yourself?

Yes.

**Comment by pivotal-bin-ju** [comment]
@deniseyu and I are seeing this issue as well - it looks like a channel size of 1000 is too low when lots of metrics are being emitted, or when downstream consumers are too slow at processing the message. The speed at which messages are consumed is entirely determined by the implementation of `emitter.Emit` interface method.

It makes sense to make this parameter configurable, and maybe also look into batching metrics where possible for emitters. It would be good if batch size was also configurable, to allow for cases where consumers might want high-cardinality events.

Maybe it would be much better to have batch points rather than more `emit workers`.
https://github.com/concourse/concourse/issues/3570

It would also be helpful if the event consumer got tuned to process message in time. Larger channel size may help with high-volume event emission in short periods of time, but it doesn't help the consistent slow consumption downstream.
