### ISSUE TITLE
Resource/job display name

### ISSUE THREAD

**Issue by fullstacktester** [concourse/concourse#3793]
## What challenge are you facing?

Jobs and resources in a pipeline need to have a unique name. 
However, we end up with multiple jobs/resources in a pipeline that have longer names than necessary in order to deal with this. eg, job1-abc, job2-def. This makes the pipeline harder to read and also makes the pipeline longer which then zooms out the pipeline.

## What would make this better?

Jobs/resource to have an optional display name attribute as well as a name. The display name, if it exists, is the one shown in the UI. If it doesn't exist, the name attribute is used instead.

## Are you interested in implementing this yourself?
Possibly

**Comment by pivotal-jamie-klassen** [comment]
I remember a brief conversation with @pivotal-kahin-ng on this topic - perhaps they'd like to weigh in?

**Comment by pivotal-kahin-ng** [comment]
Hey! 

Glad you brought this issue up! I actually thought of this as a solution for this [issue](https://github.com/concourse/concourse/issues/1128) way back, but opted for a different approach in the end. 

I remember vaguely running into some issues with displaying the name properly for builds due to it the job name coming from a different source but maybe that has changed recently? If you want to reference anything to get started, it seems like I haven't deleted the branch when I was first trying this out and it lives [here](https://github.com/pivotal-kahin-ng/concourse/tree/retain-job-history). 

Good luck and happy contributing!! 😄

**Comment by fullstacktester** [comment]
Thanks, @pivotal-kahin-ng.

I'll take a look.

**Comment by fullstacktester** [comment]
Unfortunately, I moved jobs and no longer use Concourse so won't be able to
pick this up.

I still think it's a good feature for somebody to implement though.
