### ISSUE TITLE
Security: Add autocomplete="off" for form fields for sensitive data

### ISSUE THREAD

**Issue by damzog** [concourse/concourse#3839]
## What challenge are you facing?

As part of a vulnerability scan we got a finding indicating that the form field for password in the login dialog should have the attribute autocomplete="off".

## What would make this better?

I suggest you put this attribute into every form field containing sensitive data. 

## Are you interested in implementing this yourself?

No.

**Comment by marco-m** [comment]
If this means that the browser will not ask anymore if I want to save the password, then I am against this. I care about security and I protect very well my computer and my browser, I don't want to be forced to copy and paste each time my secrets, since I use random generated secrets I cannot remember. The output of a security scanner, as anything else, must be validated by a human given the specifics of the system.

**Comment by mockersf** [comment]
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields
`autocomplete="off"` for password fields is actually ignored by most browsers
