### ISSUE TITLE
Sidebar feedback round 2

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#3872]
The new sidebar looks great!! 

Feedback 1: It might help to use a different colour (maybe darker) font for the team names within the sidebar so that at a quick glance it's easy to differentiate between the teams and pipelines? 

<img width="1188" alt="Screen Shot 2019-05-15 at 9 33 36 PM" src="https://user-images.githubusercontent.com/19290703/57820068-26e75400-7759-11e9-9613-378d20ae8f40.png">

Feedback 2: `j`/`k` keybindings for switching between pipelines would be diggity dope. 

Feedback 3: Drag to reorder would be nice but maybe that should be a separate issue?

Thx!!

@vito and @clarafu

**Comment by pivotal-jamie-klassen** [comment]
Love these ideas. Mildly concerned about overloading j/k on the build page, unless there's a hotkey to focus/expand the sidebar too...

**Comment by StevenArmstrong** [comment]
Having deployed 5.2 yesterday the two main features that would really enhance useability would be a search filter at the top of the sidebar like the dashboard view that could generate a list of matching pipelines based on regex. 
Also nesting pipeline groups as a collapsable links under a pipeline. So the drill through is team -> pipeline -> pipeline groups would also be awesome.

**Comment by clarafu** [comment]
@StevenArmstrong Those are great ideas!

@pivotal-jamie-klassen Oh I totally didn't know j/k was used in the build page already, you're right it would only make sense if there was a hotkey for opening the sidebar.

**Comment by pivotal-jamie-klassen** [comment]
@vito I don't recall where we settled for the scope of this. Which of the following do we expect to achieve during the course of this issue?
1. [ ] Color of team vs pipeline text in sidebar
1. [ ] keyboard shortcuts
1. [ ] drag to reorder
1. [ ] drill into groups
1. [ ] filter input

**Comment by Lindsayauchin** [comment]
## UI Feedback: 



1. Active State team name: 
- [ ] no opacity on any element

1. Active State pipeline: 

- [ ] background of the container should be: HEX 272727
- [ ] outline of the container should be:
- [ ] no opacity on any element

2. Hover: 
- [ ] opacity of the container should be 40%
- [ ] pipeline name, team name

3. Inactive pipeline name
- [ ] reduce the opacity of the pipeline names to 30%

4. Inactive team name
- [ ] keep team names at 60% opacity

5. Active toggle on team name
- [ ] chevron at 70% opacity when the team expanded, 100% when there is a pipeline selected in that list

![Screen Shot 2019-05-22 at 6 03 22 PM](https://user-images.githubusercontent.com/27746614/58212164-f30db080-7cbb-11e9-90b6-dfb7c9f1ac7c.png)


## Additional:
- [ ] only display tooltip on long names that are truncated

- [ ] The border at the top of the panel is creating a tiny misalignment in contrast to the Lower nav (L2). A border should be added to the top nav container (L1) bottom to even this out.
   
Current:
![Screen Shot 2019-05-22 at 4 05 16 PM](https://user-images.githubusercontent.com/27746614/58212843-2bae8980-7cbe-11e9-88ce-61b4b361a1b6.png)

Expected:
![Screen Shot 2019-05-22 at 6 20 16 PM](https://user-images.githubusercontent.com/27746614/58212889-4da80c00-7cbe-11e9-94ba-0404ec180558.png)

**Comment by xtreme-james-thomson** [comment]
@Lindsayauchin Hi! You have a task `outline of the container should be:` but didn't put in a colour. I looked at the screenshot and it looks like it should be #979797. Let me know if that's not right!

**Comment by pivotal-jamie-klassen** [comment]
For

> only display tooltip on long names that are truncated

here's what I'm thinking:
1. Add `id` attributes to each of the team names and pipeline names in the sidebar. This will involve one of two strategies:
    * create an [injective](https://en.wikipedia.org/wiki/Injective_function) function `DomID -> String` that generates __valid HTML id strings__ (see below). This could in principle be reused for any element that has event listeners, including clicks and inputs, etc.
    * create two injective functions, `PipelineIdentifier -> String` for the sidebar pipelines and and `String -> String` for the teams, that both generate valid HTML id strings. Narrower scope, but also less reusable.
1. Add a new `Effect` that calls [`getViewportOf`](https://package.elm-lang.org/packages/elm/browser/1.0.1/Browser-Dom#getViewportOf) with the above IDs, and the corresponding `Callback` just contains the relevant [`Result Viewport`](https://package.elm-lang.org/packages/elm/browser/1.0.1/Browser-Dom#Viewport) of the element in question.
1. Any time the list of pipelines might change (which is probably just whenever `Application.handleCallback (PipelinesFetched _)` happens), run the above effect for each sidebar team and pipeline.
1. Referring to https://github.com/concourse/concourse/blob/master/web/public/index.html#L164, handle the abovementioned `Result View` callback as follows: ensure that the `title` attribute only gets set on those sidebar teams and pipelines for which `offsetWidth < scrollWidth`. 

### potential concern

When the pipelines refresh,  will trigger a re-rendering of the view, but at _maybe the same time_, the side effects that ask the browser for the viewports for each of the sidebar entities is running. I'm not sure exactly how the Elm runtime will sequence rendering the view and running the commands, so if there is a race condition here let's figure out a decent way to exercise it, or carefully study the Elm source code to be confident. 

### improvements

1. Bring existing dashboard functionality in line with the above changes
    * Refactor [these](https://github.com/concourse/concourse/blob/master/web/public/index.html#L157-L178) to use the `Effect` described above instead of a port.
    * Convert the dashboard tooltips to use inline styles; cover them with tests.
1. Extract some kind of reusable tooltip functionality from the above, and use it instead of the `title` attribute on the sidebar teams and pipelines.

#### notes
HTML ID strings:

> must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

https://www.w3.org/TR/html4/types.html#type-id

**Comment by xtreme-james-thomson** [comment]
@pivotal-jamie-klassen just a quick question, looks like html5 id spec stipulates that "The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters."

https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute

we're good with good ol' html5, right?

**Comment by xtreme-james-thomson** [comment]
With our current implementation, you can click/hover on the team icon and some action happens, but hovering/clicking the pipeline icon does nothing. (Mostly a note for myself to follow up with @Lindsayauchin)

**Comment by xtreme-james-thomson** [comment]
As it stands, the tooltips are the `title` attribute. I'm starting to think there should be a separate issue for:
1. switching the `data-tooltip` styles to be inline. (currently they are in web/assets/css/dashboard/less)
2. switching the sidebar title `title` to `data-tooltip`.

**Comment by xtreme-james-thomson** [comment]
@pivotal-jamie-klassen some of your fears (or potential concerns) might be true with the current implementation... with lots of big ol' pipeline names and hovering across many of them REALLY quick, we get this:

![Screen Shot 2019-06-18 at 3 28 16 PM](https://user-images.githubusercontent.com/2362482/59713630-de023f80-91dd-11e9-8524-6a21d01b5747.png)

the text updated properly, but the hover isn't on the proper name.

this comment is partially just letting you know, and partially making sure i don't forget about it!

**Comment by xtreme-james-thomson** [comment]
Just talked to @Lindsayauchin and there are a couple more changes to make

- [ ] Add some space to the bottom of the sidebar
- [ ] Fix the z-index of the higher sidebar items tooltips with respect to the fixed header on job pages

Additional (maybe break into a new issue)
Scrollbar:
- [ ] Investigate scrollbar colours (transparent background with dark grey/black scroll progress)
- [ ] Get it to 'auto-hide'
