### ISSUE TITLE
Abort a pending build is no op

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#3900]
## Bug Report

![Screen Shot 2019-05-22 at 11 34 05 AM](https://user-images.githubusercontent.com/4583837/58187982-e2424800-7c85-11e9-915c-d921b6db212a.png)

When trying to abort a build that is pending due to resource checking failing, the request to abort is successful but the build is stuck in pending.
You can also see this in the backend `builds` table. The build is flagged to be aborted, but the status is stuck in pending.

## Steps to Reproduce

pipe.yml
```
resources:
- name: test
  type: registry-image
  source:
    repository: blah

jobs:
- name: test
  plan:
    - get: test

```
config the above pipeline, un-pause it, then trigger `test` job. Observe the build is in pending state with
```
waiting for a suitable set of input versions
test - no versions available
```
abort the build by clicking the `X` button. Observe the request is 204 successful but if you refresh the page notice the build is still in pending state.

So now if you change the repository to `busybox` to make the resource check successfully, the pending build will exit the pending state and then become aborted immediately.

## Expected Results

The build aborts immediately or shortly after clicking abort. Some kind of feedback that the abort button did something.

## Actual Results

The build is stuck in pending.... forever....

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): bosh & docker (saw on both)
* Did this used to work? Not sure!

@xtremerui

**Comment by CraigTRichards** [comment]
We are seeing very similar results since upgrading to 5.2.0. Sometimes the abort goes through after 3 - minutes.

**Comment by StevenArmstrong** [comment]
we are also seeing this in version 5.2.0 where the abort takes 3-5 minutes to show as aborted. This causes users to say the abort button isn't working.

**Comment by xtremerui** [comment]
Update:

Seems `abort` action (through either UI or api ) can only abort a build that is in `started` state.

When a build that got kicked off first as `pending` state, there is no abort listener attached to the build yet so clicking the `X` can only mark it as `aborted` in DB but no one could take action on that.

We could have a notification listener attach to the pending build in [TryStartPendingBuildsForJob](https://github.com/concourse/concourse/blob/45c135a1d4d0f653eaa61f9b69235b7965dc2f99/atc/scheduler/buildstarter.go#L50) . But in this case, an `abort` state might not be accurate since the build never got started. 

Should we introduce a state in this case? For example, `cancelled`.The difference between a cancelled build and an aborted build is that:
cancelled build doesn't have start_time and end_time while aborted build has both

Or should we also treate them the same by giving both `aborted` state? In this case, should we put an end_time to the aborted pending build? @pivotal-jwinters @vito

**Comment by pivotal-jwinters** [comment]
I think we just need skip the manually-triggered-build input checks if the build is aborted:
https://github.com/concourse/concourse/blob/master/atc/scheduler/buildstarter.go#L91

**Comment by pivotal-jwinters** [comment]
Or actually skip over almost everything in tryStartNextPendingBuild

**Comment by xtremerui** [comment]
@pivotal-jwinters that is the implementation details you talk about but I think we need to think about the implications that this brings to UI.

Now take this for example https://ci.concourse-ci.org/teams/examples/pipelines/job/jobs/job/builds/24, it is in brown colour and marked as aborted with `started` and `finished` timestamp. If we do what you mentioned above, which I like, then the build becomes `aborted` without those two timestamps. Should we still put it in colour brown? Same when you goes to dashboard that it will show as brown  without telling when it is ran last time. 

Or should we just not returning it as a "build" since it never got started and no next inputs available?

**Comment by pivotal-jwinters** [comment]
@xtremerui I think we should still show it in the UI as brown. 

If we don't have timestamps (because it never ran) then let's just not show them on the build page? Can we just not show them on the dashboard page as well?

**Comment by xtremerui** [comment]
@pivotal-jamie-klassen just a heads up that for a pending build got aborted, there won't be timestamps available from api request. It's possible that some work needed to make sure null value of timestamps to not break anything after this change.

**Comment by pivotal-jamie-klassen** [comment]
@xtremerui yes some work will be needed! Right now the app is hard coded to say "pending" when there are no timestamps in the API response lol:
https://github.com/concourse/concourse/blob/master/web/elm/src/Views/BuildDuration.elm#L14-L16
