### ISSUE TITLE
tooltip for "new version" in build view goes under topbar

### ISSUE THREAD

**Issue by mockersf** [concourse/concourse#3921]
## Bug Report

When the first line of a build in the view is a new resource, the tooltip goes under the topbar. Same for tooltip with durations

## Steps to Reproduce

Go to a build with a new version of a resources that is used as the first step of a job. Mouse over the yellow arrow

## Expected Results

I can read the tooltip

## Actual Results

The tooltip is hidden under the topbar

## Additional Context

<img width="1266" alt="tooltip-topbar" src="https://user-images.githubusercontent.com/8672791/58388953-ce039f80-8025-11e9-908d-fbb134b92a80.png">

It looks like it's a CSS problem with the overflow behaviour that has changed with the addition of the sidebar, but I'm not sure how to fix it

## Version Info

* Concourse version: 5.2
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: kubernetes
* Browser (if applicable): Safari & Firefox
* Did this used to work? yes

**Comment by xtreme-james-thomson** [comment]
Maybe this could fit into a slightly broader 'smart tooltip' epic together with #3813

**Comment by pivotal-jamie-klassen** [comment]
Since #4206 was reverted, this issue persists.

**Comment by pivotal-jamie-klassen** [comment]
I noticed today, that `updateTooltip` is exposed by `StepTree` but only called in `Build` (to handle the hover and clock tick cases):
https://github.com/concourse/concourse/blob/master/web/elm/src/Build/Build.elm#L329
https://github.com/concourse/concourse/blob/master/web/elm/src/Build/Build.elm#L425

I think we should refactor things so that the `.hoverCounter` field lives closer to `StepTree`, where it is accessed. Hopefully then we can make use of the `Tooltip.handleCallback` a little more seamlessly.

**Comment by pivotal-jamie-klassen** [comment]
The plan right now is to move the tooltip outside the `scrollable-body` container, so that it is not affected by overflow attributes. @matthewpereira wisely observed that this approach might impact accessibility in some way, and I'm just writing it down here in case I forget.
