### ISSUE TITLE
Spike: Nomad runtime backend

### ISSUE THREAD

**Issue by vito** [concourse/concourse#3925]
@xoebus and I spiked on Nomad and the only major blocker we ran into (...as far as we got, anyway) was propagating artifacts. This would be made easier if we had a central blobstore (https://github.com/concourse/concourse/issues/3924), so maybe we could motivate that spike by having a Nomad backend that uses it?

/cc @marco-m

**Comment by marco-m** [comment]
Wow this really makes me happy, thanks @vito !!!

**Comment by vito** [comment]
This may be a useful starting point: https://github.com/xoebus/asylum

**Comment by xoebus** [comment]
I've been meaning to write down my thoughts around this work and this issue seems like as good a place as any.

Large, shared Concourse deployments fall prey to a tragedy of the commons. There's two main contributing factors towards this:

* Concourse tries to be as responsive as possible to user requests to schedule and run new work. This provides a great initial experience and an interactive workflow with small deployments but I think it's the wrong trade-off for larger deployments. Trying to blindly schedule work or perform when the system is overloaded causes the system to become even more overloaded until it fails and needs to be recovered.

* All jobs want themselves to run as fast as possible. For example, everyone runs with Ginkgo's `-p` flag in CI. There are often already far more jobs running than cores available on the machine and so all of them trying to grab as many of them as they can causes everyone to run slower as a result.

I think the scheduling and runtime environment needs to be modified in order to be able to accommodate some of these larger, multi-tenant deployments while keeping the utilization of a cluster high to avoid costs rising. This was my original impetus into looking into Nomad as a scheduling backend.

The above two issues would be addressed by:

* It's acceptable to hold a CI job for a few minutes until a machine with enough capacity is available to run it. Holding it longer than that is a shame but still better than the cluster becoming unresponsive. This is essentially equivalent to a queue. The queue can be monitored to check that the time a job spends in the queue is not outside an SLO.
 
  Being able to tell the free capacity of a machine requires us to both size the machine and the jobs running on them. This is not currently part of the Concourse task interface but I hope adding a reasonable default should get us pretty far.

* To prevent greedy jobs affecting the stability and performance of the whole we need to apply performance restrictions to them (or, more optimistically, performance guarantees) to avoid starvation. This fits in well with the previous point as the size of a task is both useful in global scheduling as well as local resource allocation.

[Nomad](https://www.nomadproject.io/) is a system which already implements a number of these concepts. I think we can try using it to address the issues above.

The brief spike that Alex and I did found a few issues:

* the built-in Docker driver was an impedance mismatch for the kind of operations we wanted to perform (no easy stdin, etc.)
* the log collection mechanism was suitable for logs of the running of the task but not the task itself (maybe lossy, line-based)

To remedy these I think we need to write a new custom (but simple) task driver for Nomad which would run Concourse jobs. This driver could target a containerd instance on each host. I've found containerd to be a great match for the kind of things we want to do. The rough sequence of actions that this driver would perform would be:

1. Receive a task specification from Concourse (the ATC would fire and forget this information into Nomad and instead switch to a callback model for getting updated on the state of a task). This specification would contain the input information and task definition. The inputs would be references to blobs in a central blobstore.

2. The driver would download the required blobs from the blobstore (potentially into tmpfs?).

3. The task would be started with the environment that we know and love. No tasks or jobs should need to change. Logs would be forwarded by the driver back to an endpoint in Concourse (delivered via the specification) for storage and display.

4. When the task is done then a callback is hit in Concourse to update it's status and any outputs of the task are put back in the blobstore for later use (need to think more about garbage collecting the blobstore).

This process is then boringly repeated for every task. This process looks like it loses a lot of the optimizations of the current scheduler but I think it will scale better and perform better once at scale. However, some benchmarks would be nice before committing to it fully. The throughput and latency of blobstores when running in the same cloud provider is enormous.

Resources can be done in a similar way except they don't have inputs, just outputs.

**Comment by marco-m** [comment]
@xoebus thanks for the write up, I both appreciate the effort and clarity and I agree with your analysis. I wanted to quote some parts to say I agree but hey I agree with everything there :-)

**Comment by vito** [comment]
@xoebus Thanks! I forgot a couple of those hangups we ran into.

I'm open to having our own driver. To me the primary benefit to having our own driver would be to insulate ourselves from changes to Nomad's bundled drivers and have more control over our own destiny. My only reservation is that it's more for the Nomad operator to set up; my understanding is that the driver has to be installed and configured on each server.

I want to play devil's advocate and suppose that we could instead submit pull requests upstream for the functionality that we need.

For example, being able to send a payload to `stdin` [wasn't too hard to implement for their Docker driver](https://github.com/hashicorp/nomad/compare/master...xoebus:master).

The other problems were linewise log streaming and no support for uploading artifacts. Could these be PR'd too? Maybe Nomad could support streaming chunks of log output instead of individual lines? Maybe Nomad could have an `upload_artifact` stanza symmetrical to its [`artifact` stanza](https://www.nomadproject.io/docs/job-specification/artifact.html)?

Then we could just use `artifact` for fetching, the `docker` driver for running, the Nomad API for receiving logs, and `upload_artifact` for uploading. Have I missed anything? :thinking:

**Comment by marco-m** [comment]
Attempting to submit PR upstream is a wise idea indeed, it would reduce the maintenance costs and it would provide functionalities that might be useful outside of Concourse.

**Comment by nader-ziada** [comment]
As part of the investigation into using a blobstore for sharing artifacts between tasks, we came across the limitation of adding a dependency between nomad tasks. 
We were trying to inject a task that will upload the generated output of the a task to the blobstore but failed because we were not able to make the injected `upload task` wait for the running task to finish.

This is a pending feature in nomad tracked by [this](https://github.com/hashicorp/nomad/issues/419) issue

cc @xtreme-sameer-vohra

**Comment by ddadlani** [comment]
@nader-ziada would we be able to get around the `upload task` issue by writing our own task driver? If so, what kind of effort would that be?

**Comment by ddadlani** [comment]
This spike was meant to validate our assumptions about using a blobstore with Concourse. At this time, we feel that the work that would be required to write our own task driver is overkill for this purpose. For now, we are pausing this line of work until we get further along with the [runtime interface](https://github.com/concourse/concourse/projects/16)  and k8s implementation.

As for the upload task issue, it could be solved either by writing our own task driver or by https://github.com/hashicorp/nomad/issues/419 , for future reference.

**Comment by marco-m** [comment]
@vito @ddadlani @xoebus 

Good news!
I tried my chance by tweeting to HashiCorp asking about planning information for  hashicorp/nomad#419. I got lucky enough to get an answer by the man himself

> I’m not sure exactly what version this is slated for but I can say that this is now on the near term roadmap. I don’t think 0.10.0 which is due soon but perhaps a patch release or next.

and by the Engineering Manager of Nomad:

> Yes, this is planned for a point release in the 0.10 series.

For reference, Nomad is currently at 0.9.3 with 0.9.4 in preparation.

**Comment by vito** [comment]
Shelving this for now. We're continuing to focus on the K8s backend, and also working to replace Garden with `containerd`: https://github.com/concourse/concourse/projects/44

Our end goal is to have a pluggable backend interface, so we still *want* to have a Nomad backend at some point (at least I do), but right now we don't have the bandwidth to work on all three. :slightly_smiling_face:

**Comment by jackgray** [comment]
Outside of this thread I have felt like the only one who wants to manage jobs on a nomad cluster with concourse :/

Any chance of this getting revived, or ideas on the best way of implementing this? Or maybe it's not a production-ready path to explore..?

**Comment by marco-m** [comment]
@jackgray I have not lost hope, because I _know_ the power and simplicity of Nomad.

I plan one day to have a stab at this integration, but I don't know when I will have time; I cannot speak for the Concourse team.

You could try a low-integration approach (or maybe you are already doing this?), simply using Nomad to provide compute for Concourse. Each Nomad node could have a Concourse worker as a system job. Be careful not to schedule more than one Concourse worker per Nomad node, since a worker is meant to have a 1:1 mapping with compute.

It should even be possible to autoscale that setup. But for autoscale, no matter the technology, I don't think that Concourse is ready. We autoscale Concourse on AWS EC2 with a certain amount of glue logic such as https://github.com/buildkite/lifecycled, sending retiring signals to the workers when scaling in, but still, due to volume management, the setup is flaky.
