### ISSUE TITLE
Pipeline view: Resource Pinning Polish 

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#3960]
Users have been using this feature for sometime and based on user feedback we can add higher fidelity of polish to the pinning feature. 

## Inactive state of the pin icon

- [x] update to 'inactive' state, similar to the other icons in the app, of 0.5% opacity for consistency of UI app wide

![UI_polish_pipeline_view_not_active](https://user-images.githubusercontent.com/27746614/58761850-7e9b0300-8540-11e9-8acb-99bb72647a23.png)

![Screen Shot 2019-06-21 at 2 08 28 PM](https://user-images.githubusercontent.com/27746614/59942580-14ce9480-942e-11e9-85d7-ca2ec5433c45.png)

## Active pinned resource dropdown list UI style Pipeline 

- [x] Bold the resource name and leave the version number unbolded
- [x] Active selection of the pin to display as full background colour change to #2A2929
- [x] Update list display UI to be consistent with sidebar 

![Screen Shot 2019-06-21 at 2 18 56 PM](https://user-images.githubusercontent.com/27746614/59943204-a25eb400-942f-11e9-80a1-5d5daebe0a6f.png)

**Hover state on the list item**
![Screen Shot 2019-06-21 at 2 30 09 PM](https://user-images.githubusercontent.com/27746614/59943776-1b124000-9431-11e9-9264-1f6439b83702.png)

**Comment by jomsie** [comment]
I thought I'd just give a bit of an update on our progress on this story. The inactive state on the pin icon itself is [done](https://github.com/concourse/concourse/commit/0063bc3ecea2ce131b27009106f92bbe4e40fb9f).

We are going to pull out the pin menu component into its own module, while refactoring the current pin menu code to look more like the [build header refactor](https://github.com/concourse/concourse/tree/16c934bc9f6cf8dc33085316ac25aaa9d66b0863/web/elm/src/Build/Header). Have an intermediate view model between the data and the html itself.

**Comment by pivotal-jamie-klassen** [comment]
now the preliminary refactors are pretty much done, so we'll get started on the style changes tomorrow.

**Comment by pivotal-jamie-klassen** [comment]
Intuitively I find myself wanting the dropdown to dismiss whenever I 'click off' of it. As I understand it, this means detecting _any_ click event, regardless of whether it actually has a DOM element handling it, so we'd need to use a `Subscription` instead of just a `Message`. To make matters a bit worse, we have intentionally bundled all mouse events into a single subscription previously (`OnMouse` is mouse [moves and clicks](https://github.com/concourse/concourse/blob/master/web/elm/src/Message/Subscription.elm#L89-L93)), so I'm thinking the best choice is to add a separate subscription for just clicks, and probably some kind of higher-level test (like with a name like `*Feature.elm`) to ensure those clicks get wired to the right place. Just making a note of this for the 'test list' before delivering this story.
