### ISSUE TITLE
Remove ability to see secret in build logs

### ISSUE THREAD

**Issue by ashleystendel** [concourse/concourse#3972]
# Feature request
## What challenge are you facing?
We currently use Concourse with Vault as our credential manager. The majority of tasks files are written in Bash. As secrets from Vault are set as environment variables, developers are able to either echo the environment variable or add a set -x to their script and be able to see all secrets.  

## What would make this better?
Redact all secrets coming from a credential manager. 

## Are you interested in implementing this yourself?
No.

**Comment by jchesterpivotal** [comment]
Related: https://github.com/concourse/concourse/issues/1469

Previously I've pointed folks to `concourse-filter`: https://github.com/pivotal-cf-experimental/concourse-filter

I don't fully agree with @vito's reason in #1469; it might be worth revisiting if event delivery/rendering changes.

**Comment by vito** [comment]
I'm still skeptical of having people rely on this behavior but it would be pretty nifty to do it automatically based on credential values that we know we fetched from the credential manager for the build.

**Comment by ukabu** [comment]
I agree that we should not rely on this to be 100% reliable, but other CI tools already do that. Also this would prevent easy access to credentials by running one-off tasks (sure if you encode the credential, they will still show up). And this will prevent accidental exposure.
We could appease ou security people a bit by having that feature.

**Comment by evanchaoli** [comment]
This feature is also important to our users. Redacting based on credential manager is a good idea. I think we can redact before store build logs into database, so that it also avoids leaking secrets via database.

**Comment by evanchaoli** [comment]
I just read through related code today, and realized that it's not easy to redact credential manager stored secrets in build logs. The main problem is that, secret evaluation is done by a third party module `github.com/cloudfoundry/boah-ci/director/template`, and there are two restrictions from this module:

1. The function `Template.Evaluate()` doesn't return information of which vars are populated, so that in Concourse side, it won't know what will be replaced in build log.

2. We only want to replace credential manager stored secrets, but two types of variables, static and cred, might be passed to `Template.Evaluate()`. Obviously `Template.Evaluate()` should not handle Concourse specific data types.

From the other perspective, blindly redacting all credential manager stored things in build log might not be a good idea. I have seen some crazy users not only store secrets, but also configure files in Vault (because Concourse can only fetch vars from credential manager for standalone task files). So that things stored in Vault doesn't really secrets. Redacting all of them will 1) generated unexpected build log, 2) add too much workload to ATC.

I'm thinking/proposing a solution to allow users to explicitly define what should be redacted, which is archived by adding a "secrets" section in pipeline YAML like:

     resources:
        ...
     secrets:
        - ((password))
        - pass: ((pass))
     jobs:
        ...
Where `secrets` is a list of secrets to redact. And we support two forms of secrets:

* For `((password))`, say `password` is "hello" in Vault, then all "hello" appearing in build log will be replaced, like "[redacted ****]".
* If some user uses simple password, like "hello", then it may unintentionally replace non-password "hello". So we also support patterned secret as `pass: ((pass))`. In this case, say pass is "hello", then only "pass: hello" will be replaced, like "pass: [redacted ****]".

@vito WDYT?

**Comment by vito** [comment]
@evanchaoli On `master` I've actually switched us over to using our own `vars/` package, which is a stripped-down version of the `bosh-cli/director/template` package. So if we need to modify it to keep track of vars that were used, that's possible now.

I think I would prefer automatically redacting credentials, since this feature feels geared towards preventing accidental leakage; if someone had the foresight to list the credentials they don't want to leak, they may be careful enough with their scripts to have prevented it already.

I also think it would be fine to just redact everything that comes from a credential manager, even if it's being used for non-secret parameters. We should be designing for the intended use case IMO and not worry too much about edge cases.

**Comment by evanchaoli** [comment]
OK, I will fetch and read latest code from `master` branch. I agree auto redacting can be a good start.

**Comment by evanchaoli** [comment]
@vito In `concourse/vars/template.go`, I see two regular expressions for var matching:

    var (
       interpolationRegex         = regexp.MustCompile(`\(\((!?[-/\.\w\pL]+)\)\)`)
       interpolationAnchoredRegex = regexp.MustCompile("\\A" + interpolationRegex.String() + "\\z")
    )

But I cannot find any Concourse documentation mentioning about the second syntax. So I just want to confirm with you if the second regexp just comes from copy-paste as the template module from moved from a third part module?

**Comment by clarafu** [comment]
Would this issue be completed with the merging of #4311 or is #4398 also required?

**Comment by evanchaoli** [comment]
@clarafu Yes, #4398 is also needed.

**Comment by evanchaoli** [comment]
#4398 is also merged, thus closing.
