### ISSUE TITLE
On the main pipeline view, I would like to visualize how long a job has been in a certain state

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#399]
/cc @kimeberz 

If something has recently gone green or red, I would like it to look different than something that has been green or red for a very long time.

There are two separate types of "long time" that matter as well: 1) clock time 2) number of builds in a row with that state.

Thanks!
@wendorf

**Comment by vito** [comment]
Jenkins accomplishes this via the weather icons, which I miss (and which has come up before).

**Comment by jama-pivotal** [comment]
Closing this because of the recent multi-pipeline dashboard view work ref https://github.com/concourse/concourse/issues/1494 and https://ci.concourse.ci/dashboard  

That said, our recent work only solved 1/2 the problem: we only convey how long the pipeline has been in a certain state. We do not have a similar solution to Jenink's weather icons.  This is something we're researching.

Anyways, @wendorf take a look at our new pipelines and see if that would be helpful to you. Feel free to re-open the issue if you felt like i missed something! Cheers
