### ISSUE TITLE
I would like a simple "global green vs red" view

### ISSUE THREAD

**Issue by wendorf** [concourse/concourse#400]
/cc @kimeberz

I bury a lot of my jobs in separate pipelines and/or pipeline groups because they're normally not visually interesting to me, but I would like a small widget that displays information like "You are 80% green across your builds and 20% red" so if I'm not 100% green, I know I should look at some of my less-important pipeline groups.

Thanks,
@wendorf

**Comment by jama-pivotal** [comment]
@wendorf Thanks for submitting the feature request. I'm going to close this issue because we've started working on two major epics: https://github.com/concourse/concourse/issues/1442 and https://github.com/concourse/concourse/issues/1462 with the express purposes of helping users visualize the status of multiple pipelines. Give those a gander, we'd love your feedback!
