### ISSUE TITLE
Inconsistent execution time issuing destroy pipeline through Fly cli

### ISSUE THREAD

**Issue by cdugga** [concourse/concourse#4044]
Using Concourse version v3.13.<company>.20180912

When issuing destroy-pipeline command, execution time is indeterminate, sometimes timing out sometimes hangs for several minutes before completion. Previous suggestions that special characters in pipeline name could manifest in this failure however pipeline name is simply text string.

Is it possible run destroy command with additional trace info to see what is happening? 

Does this issue arise from resource contention?

**Comment by pivotal-jamie-klassen** [comment]
@clarafu here's my attempt at describing the situation. Feel free to correct me!

From looking at https://github.com/concourse/concourse/blob/master/atc/db/migration/migrations/1510262030_initial_schema.up.sql, I see that when you delete a row in the `pipelines` table, it cascades deletes like crazy. At first glance I can draw at least this dependency tree:

```
pipelines
├ builds
│ ├ build_image_resource_caches
│ ├ build_inputs
│ ├ build_outputs
│ └ resource_cache_uses
├ jobs
│ ├ jobs_serial_groups
│ ├ builds // redundant to above
│ ├ independent_build_inputs
│ ├ next_build_inputs
│ └ worker_task_caches
├ resource_types
└ resources
  ├ versioned_resources
  └ resource_pins
```

I'll bet if you ran an `EXPLAIN` on a `DELETE FROM pipelines` query, you'd see an unsettling amount of sequential scanning going on. @cdugga I think your observation is caused by slowness at the data layer. While adding some feedback would help the UX, I'm not sure Postgres will give us the best ability to make these queries more transparent.

Instead I think we could actually afford to address to the root cause of the slowness: common DB wisdom for slow cascading deletes says to add indexes for the various foreign key relationships associated to those deletes: https://dba.stackexchange.com/questions/37034/very-slow-delete-in-postgresql-workaround.

**Comment by clarafu** [comment]
Related #3383

**Comment by clarafu** [comment]
@cdugga You might want to upgrade, in the later releases we added some indexes that might speed up the destroying of pipelines due to the cascading rows it also needs to delete. (https://github.com/concourse/concourse/pull/3382 this PR should speed things up)
