### ISSUE TITLE
Create the container image to upload/download from the blobstore

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4054]
When running on k8s with a blobstore, we will need a separate container to upload and download each artifact before/after running a step. How would this work?

We should maybe have an image that allows us to do this.

**Comment by ddadlani** [comment]
@kcmannem could you give us a short status update here please? :)

**Comment by kcmannem** [comment]
During the previous spike @nader-ziada and I worked on using init/final containers to pull and push blobs that represent the inputs/outputs of a task.

For all inputs/outputs we create a empytDir volume used to inflate/populate the contents. This usecase was also justified by the kubernetes docs; it mentions emptyDirs should be used for "holding files that a content-manager Container fetches while a webserver Container serves the data" this is similar to our usecase.

For Inputs we used init-containers which did a `gsutil cp` into the emptyDir volumes. Since Volumes are shared within the Pod, after the init-containers finished the task-containers will have volumes inflated with the inputs the task requires.

For Outputs a simple monitor container is used which neighbors the task-container. It would continuously loop and make Get calls on the task-pod. From this we can parse `pod.status.containerstatuses` to determine wether the task-container has exited. ContainerStatus also contains a ExitCode property which informs you of the containers exit code. This allows us to make a decision wether to push outputs into the blobstore or not. We only push when the container exited and exited with a 0 code.

For the real implementation we reimplemented the described behavior but with more concrete use of the k8s client apis and tolerance for edge-cases. It's being worked on at concourse/porter.

**Comment by kcmannem** [comment]
For an alternative to the porter name https://travel.stackexchange.com/questions/36680/what-is-that-device-at-an-airport-which-transports-packages-to-the-aircraft-call

**Comment by kcmannem** [comment]
We're trying to figure out the semantics of the push cmd that needs to written into the pod spec when ATC runs a step. In an ideal world this would be different for each cloud providers but each cloud provider does auth in a different ways. Google expects a path to a service account at GOOGLE_APPLICATION_CREDENTIALS vs Amazon with accesskey and secretkey pair.
Should we be explicit with separate push cmds for each provider or interpret which bucket driver to use based on the bucket url provided?

For GCS:
	- we need gcs creds located at a filepath specifed by ENV["GOOGLE_APPLICATION_CREDENTIALS"]

Option 1:
```
push task-pod task-container
		  		-sourcePath /some/output
		  		-destinationUrl gcs://my-bucket/GUID
```
Option 2:
```
push gcs task-pod task-container
		  		-sourcePath /some/output
				-bucket my-bucket
				-serviceaccount=/.config/
```

For AWS:
We need the region of the bucket as part of the url query params
	
Option 1:
```
push task-pod task-container
				-sourcePath /some/output
		  		-destinationUrl gcs://my-bucket/GUID
```
Option 2:	
```
push s3 task-pod task-container
		  		-sourcePath /some/output
		  		-bucket my-bucket
				-region north-virginia
```

We think that going with option 1 and reading the required creds through evnvars might be the best approach. This will ensure that we can support multiple bucket providers without being explicit. We'll only need validation logic that the required envvars are present.

**Comment by kcmannem** [comment]
Remaining work

- [ ] Compiling `in/pull` action

- [ ] Integration tests for `in` & `out` 

**Nice to have**
- [ ] Unit test with K8s rich API client 
- [ ] investigate whether to have a watcher container for each output or a single watcher for all outputs, this will need improvements to porter later on

**Comment by nader-ziada** [comment]
pipeline at https://ci.concourse-ci.org/teams/main/pipelines/porter

**Comment by nader-ziada** [comment]
image pushed to dockerhub at `concourse/porter-dev:latest`

**Comment by kcmannem** [comment]
@nader-ziada One last thing to do, rename porter
