### ISSUE TITLE
[Spike] How do we ensure containers inside a pod run one after the other?

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4056]
We need to run multiple containers in each pod and they have to run in series.

For example, we will be using containers to upload/download artifacts from the blobstore (#4054). How do we ensure that these containers run in the order we expect?

**Comment by kcmannem** [comment]
The order we are concerned with is ensuring inputs are mounted before a task runs and outputs are pushed after the task runs. We don't need to worry about step planning as the exec engine and its meta steps already takes care of this ordering. So we need to ensure the ordering of containers in a pod.

We've investigated a few approaches lightly before we decided to spike on one we liked.
We considered using binary entry point such as a wrapper around the task which manages the ordering. Another was to use init containers alone instead of regular containers as their order of operations are guaranteed. This meant an init for pull, task, push. We found out this doesn't work as init containers do not allow for sidecars (needed for logs, hijacking, etc...).

So we came up with a hybrid approach where we still use init containers to pull inputs but then spawn off a real container to run the task while also having another neighboring container which polls until the task container terminates. Depending on the termination state, it pushes the outputs. Here's the example code we used to prove the approach.

```
package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	//
	// Uncomment to load all auth plugins
	// _ "k8s.io/client-go/plugin/pkg/client/auth
	//
	// Or uncomment to load specific auth plugins
	// _ "k8s.io/client-go/plugin/pkg/client/auth/azure"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	// _ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
	// _ "k8s.io/client-go/plugin/pkg/client/auth/openstack"
)

func main() {

	podname := flag.String("pod", "", "name of the pod")
	containername := flag.String("container", "", "name of the container to wait for")

	flag.Parse()

	fmt.Println("running your watcher cmd with args", *podname, *containername)

	// creates the in-cluster config
	config, err := rest.InClusterConfig()
	//config, err := clientcmd.BuildConfigFromFlags("", "/Users/pivotal/.kube/config")
	if err != nil {
		panic(err.Error())
	}
	// creates the clientset
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}

	max_retries := 10
	for i := 1; i <= max_retries; i++ {
		pod, err := clientset.CoreV1().Pods("default").Get(*podname, metav1.GetOptions{})
		if err != nil {
			panic(err.Error())
		}
		for _, c := range pod.Status.ContainerStatuses {
			fmt.Println("searching containers", c.Name)
			if c.Name == *containername {
				fmt.Println("looping on containers", c.Name)
				if c.State.Terminated != nil && c.State.Terminated.ExitCode == 0 {
					fmt.Println("ready to upload output")
					os.Exit(0)
				} else if c.State.Terminated != nil && c.State.Terminated.ExitCode != 0 {
					fmt.Println("container step failed with exit code", c.State.Terminated.ExitCode)
					os.Exit(5)
				}
			}
		}
		time.Sleep(2 * time.Second)
	}
}

```
