### ISSUE TITLE
Change the default filesystem for baggageclaim back to overlay

### ISSUE THREAD

**Issue by ddadlani** [concourse/concourse#4071]
Again.

**Comment by ddadlani** [comment]
We've moved our prod and Wings environments over to using Overlay for the past few weeks, and have not seen/heard any issues. Given the frequency of `btrfs` causing workers to fall over, it seems to make sense to switch back to `overlay` at this point.

/cc @vito

**Comment by cirocosta** [comment]
Hey @ddadlani, 

Something might be worth considering is that for those coming from a `detect` who had been running `btrfs` because of that detection indicating that `btrfs` is "the chosen one", but no machine recreation is needed (e.g., no stemcells bumped), they *might* (I'm not entirely sure) have to clean things up / perform some manual operations.

If that's true, it'd be nice if we had that all documented too 😁 (oor just ignore this comment if those points are not true)

thanks!!

**Comment by ddadlani** [comment]
@cirocosta Absolutely true, you need to recreate your workers to switch from btrfs to overlay. We should definitely put that in the upgrade docs. That being said, I thought upgrading should recreate your workers anyway so it should "just  work"? We should test it regardless.

**Comment by ddadlani** [comment]
The default should still be "detect", so if it's already btrfs it should stick to it. However for new deployments "detect" should choose overlay.

**Comment by eedwards-sk** [comment]
I'll be curious to see if this negatively impacts docker-compose workflows.

**Comment by antonu17** [comment]
As far as I remember, we had a big issue with overlay a year ago: there was a big performance regression while passing outputs/inputs between steps. The delay between steps was up to a minute or even more.
But thanks for pointing this out. We'll definitely try overlay next week and I'll provide feedback.

**Comment by kcmannem** [comment]
@eedwards-sk we use overlay for our docker-composed environments. Haven't seen any problems there.

**Comment by rhoughton-pivot** [comment]
We are seeing 60-90 task initializations for tasks that use the `teliaoss/github-pr-resource` on all occurrences. Could this be related?

**Comment by taylorsilva** [comment]
done #7427
