### ISSUE TITLE
Display Who/What Triggered a Job in UI

### ISSUE THREAD

**Issue by esauser** [concourse/concourse#4120]
## What challenge are you facing?
We are unable to determine who triggered a job, be it a user or an automated trigger.  At times, it would be be nice to know who or what triggered the job when looking at the history.

## What would make this better?
Simply displaying the user name and/or ID or the resource and relevant ID that triggered the job in the UI.

## Are you interested in implementing this yourself?
I could assist if I also had some assistance.

**Comment by jama22** [comment]
Thematically similar to #2687 around adding rich information around jobs

**Comment by shemau** [comment]
As a work around to viewing this in the UI, you can enable auditing and check the logs.

https://concourse-ci.org/concourse-web.html#audit-logs

This addresses who started a job from a security/audit perspective, but lacks the finesse of being able to view the information through the UI.

**Comment by skreddy6673** [comment]
@shemau What particular log do i need to look for getting information like Who/What Triggered the build? 
```{"timestamp":"2019-05-09T14:42:36.704864093Z","level":"info","source":"atc","message":"atc.audit","data":{"action":"GetPipeline","parameters":{:build_name\":[\"19\"],\":job_name\":[\"XXX\"],":pipeline_name":["booklit"],":team_name":["main"]},"user":"test"}}```
 
Even though i didn't trigger the build, when i'm looking through the builds my name is displayed in the place of `user`

**Comment by deniseyu** [comment]
*Context: this is follow-up documentation of an offline conversation, for visibility! that's why this message reads somewhat awkwardly*

As we're working on #4337, it may be a good opportunity to revisit this. (We also might want to do this for user-triggered resource checks? but haven't heard as strong signals around that.)

This PR, which made it into v5.2, partially addressed #2752 and enabled an operator to turn on log-based auditing of user names for a bunch of different events: https://github.com/concourse/concourse/pull/3577/files, which is reflected in [our documentation](https://concourse-ci.org/concourse-web.html#audit-logs).

Looks like we'd need to investigate @skreddy6673's observation that user tracking might not be working correctly first.

Related, but different:
#2687, #2025, #569 - requests to add metadata or additional descriptions to builds

cc @Lindsayauchin @scottietremendous

**Comment by skreddy6673** [comment]
Changing the action parameter to CreateJobBuild solved the issue. 
`{"timestamp":"2019-05-09T14:42:36.704864093Z","level":"info","source":"atc","message":"atc.audit","data":{"action":"CreateJobBuild","parameters":{:build_name\":[\"19\"],\":job_name\":[\"XXX\"],":pipeline_name":["booklit"],":team_name":["main"]},"user":"test"}}`
