### ISSUE TITLE
[Web] Confirm UI functionality for Admin user

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#4194]
Epic: #4192

### Description
Given the changes done in the API story (#4193) add some tests to ensure the web UI functions as expected for an admin.

### Branch
`4194-super-admin-web-ui`

### PR
https://github.com/concourse/concourse/pull/4319

### Acceptance Criteria

Things we can't but should be able to do in the web UI for teams admin is not a member of:

- [x] pause/unpause a pipeline
- [x] force a check resource
- [x] expose a pipeline

**Comment by pivotal-jamie-klassen** [comment]
For the most part I'd hope that if we have confidence in the API piece, we'll get confidence around the UI for free. 

I have one thought about the 'Admin should be able to see all teams' point: Should there maybe be an extra tag on dashboard teams for the teams you can see purely because you're an admin (i.e. a new `Admin` variant [here](https://github.com/concourse/concourse/blob/master/web/elm/src/Dashboard/Group/Tag.elm#L12-L16))? I don't think its necessary since we can probably assume the admins know that they're admins, but this seems like the only suitable place to ask the question.
