### ISSUE TITLE
Incrementally migrate build inputs/outputs to successful_build_outputs

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4214]
Populating `successful_build_outputs` is going to take a long time - we have a migration in place, but we should maybe do it as a batch operation instead, to be performed after the new Concourse is up and running.

Upgrading should keep the existing data in place, create the new schema, and stop there. A `concourse migrate-algorithm-v3` command will be added to carry over all the old data.

Validate that this is safe to do; the idea is the batch operation purely backfills.

**Comment by clarafu** [comment]
@cirocosta We tested out the migration on the algorithm environment (which is bosh deployed) with 30 mil build inputs and it took approx 4 minutes. We wanted to see how long does an app have to start up in k8s and what are the health checking mechanisms that cause it to get killed (process, http, etc)?

**Comment by vito** [comment]
add a log line

**Comment by clarafu** [comment]
@cirocosta I just ran the migration query on my algorithm environment and it took around 280 seconds like usual and this was the metrics I got.

<img width="488" alt="Screen Shot 2019-09-17 at 9 45 20 AM" src="https://user-images.githubusercontent.com/19290703/65069202-302b3c00-d958-11e9-9ecb-a60058ca82d7.png">
<img width="477" alt="Screen Shot 2019-09-17 at 9 44 56 AM" src="https://user-images.githubusercontent.com/19290703/65069203-302b3c00-d958-11e9-92f1-dafa42fb8f0d.png">
<img width="476" alt="Screen Shot 2019-09-17 at 9 44 41 AM" src="https://user-images.githubusercontent.com/19290703/65069204-302b3c00-d958-11e9-9d20-2400aea7cfbd.png">
<img width="481" alt="Screen Shot 2019-09-17 at 9 44 24 AM" src="https://user-images.githubusercontent.com/19290703/65069205-302b3c00-d958-11e9-8a5b-d13405075300.png">

The black vertical line is the point in time when I ran the migration query. It looks like there is an increase in DB CPU but it isn't heavy enough to affect any of the other systems. 

To that point, and to @cirocosta and @vito suggestion, I tried out batching the query and turns out it takes approximately the same amount of time to do them in batches and all at once. So it is probably safer for us to do it in batches, even though it does make it more complicated than just running a query haha.

Considerations for batching the migration:
- How are we going to keep track of where we left off? 
      So we can't just keep in track in memory because the ATC could also fully die when we are in the middle of the migrations. Maybe we can just create a temporary table that we will have a column for the `current_migration_build_id` that holds the last build id that we migrated.
- Whats a good number of builds to migrate at once?
      Honestly I have no idea, I'm just going through out a random number of 10,000 until someone convinced me of something else.
- How are going to know when to stop migrating?
      So, this is a bit more complicated because typically I would think to just have it stop when the rows it deleted equal to 0 but I think we can't trust that since the builds are not always going to be there. (there can be deployments that have build ids starting from 10000) I think I'm going to have to grab the last build id in the table and keep migrating until I hit that number.

Good thing about this is that we don't have to stop the build tracker from running because we can just let things populate the table while we continue to batch migrate the data over. We do still need to keep the schedulers from running until it is all finished.

**Comment by clarafu** [comment]
Using our lidar-drills environment as a benchmark, we found that if we were to do the migration in batches while most components within the ATC are running (lidar, build tracker, etc), it will take almost a week to migrate all the data over to the new table. This introduces some complexities because we are not gonna have our users (mostly affecting users with gigantic deployments) wait a whole week before their scheduler can start. The only option we would have to is have the scheduler start after it has migrated a certain amount of builds.. but this is also difficult because when do we know how many builds is "safe" to start the scheduler?

So we ran another test to see how long it would take to migrate the data without any components running, and it took about 4 minutes total. Our best bet now is probably to stop everything for a few minutes at startup to migrate all the data in batches.

**Comment by clarafu** [comment]
This is currently blocked on #4534. In order to successfully migrate all the data into the new `successful_build_outputs` table, we need to run the migration when all the ATC components are stopped. We determined that probably the best way to go about this is to add component tracking, so that we can stop all the components manually and then run the batch migration smoothly. 

This means that for a user to upgrade to v6.0.0, they would need to first upgrade to the version of concourse that introduces the component tracking and then upgrade to v6.0.0. This upgrade patch is probably better than having our users upgrade to v6.0.0, and then have to manually run the batch command separately after all their ATCs have been successfully upgraded.

**Comment by vito** [comment]
Let's try doing batches of 100 builds instead of 1000. It might be better to just do more queries more quickly in the failure case, because at least in the happy cases they won't hold the connection for as long.

**Comment by pivotal-jamie-klassen** [comment]
This is something I wrote on this topic a while ago. @clarafu do you think you could succinctly describe the conclusions?

# charting the upgrade path for the new algorithm in Concourse v6

We're planning to make a breaking change to the build scheduling algorithm. In
order to get there, we need to massage a lot of data in the database (basically
the new algorithm will depend on data in a new table that can be fairly
expensive to construct). Hereafter we will refer to the process as a "datafix".
Running the datafix alone (with no other database clients) has taken up to 4
minutes in reasonably-sized datasets. With other database clients (i.e. web
nodes) contending for locks on the same data, this time has been observed to
expand to over a week.

The three approaches we discussed were:

1. Automatically perform the datafix during the upgrade
1. Rely on the operator to manually perform the datafix
1. Have the code know how to gracefully fix the data as necessary

## Automatically perform the datafix during the upgrade => components table => intermediate upgrade

The most obvious place to run this datafix is during the web node's
startup - this is already the component that handles all the interaction with
the database, and it already runs migrations on startup. The problem with this
approach is that there can be multiple web nodes in a deployment and there is no
global object to help synchronize them. There is a migration lock, but that just
prevents two web nodes from running the same migrations at the same time - until
now we have assumed that it was safe to run migrations while queries related to
"normal operation" were still in progress.

We spun out a story about adding the "global backend component synchronizer",
alluded to above, in the form of a `components` table in the DB (#4534).

There is a bootstrapping problem with using such an approach, though -- you
need the component table to already exist if you're going to rely on it to
orchestrate your upgrade.

If we remained committed to this strategy we incur a great deal of operator
burden -- you have to upgrade once to create the component table, and then
upgrade again to use it to coordinate the components during the datafix.

## Rely on the operator to manually perform the datafix => risk losing data

This scenario is the simplest for the Concourse developers - we want the web
nodes to just assume that the datafix has already occurred by the time they
start up after the upgrade. 

This requires us to provide a tool that lets operators manually run the datafix.
However, without making any other changes to the web nodes, there's nothing
keeping the system safe from just being upgraded without the datafix running
(which would mean that the record of which versions passed which builds would be
ignored by the scheduler and pipelines would need to re-run from their first jobs),
or running the datafix without scheduling downtime.

Before the upgrade, web nodes will be interacting with a `build_inputs` and
`build_outputs` table to determine when to schedule jobs in a pipeline. While
doing the normal operations related to scheduling, the web nodes will be reading
and writing to both of those tables.

If new builds are recorded in `build_outputs` after the data fix runs, then the
upgraded web nodes (unless concessions are made in the code) will not know about
them. This means that the scheduler would ignore the impact of builds that
finished during the window between running the datafix and upgrading the web
nodes.

## Have the code know how to gracefully fix the data as necessary

Roughly speaking, scheduling in Concourse works as follows: there is one
job scheduler goroutine per job across the entire cluster, whose job it is to
notice when to run new builds of its associated job. So here "as necessary" ends
up meaning "fix the data when the job-scoped goroutine figures out whether to
run a build", or "run the datafix one job at a time". When we experimented with
running this migration in job-sized pieces, it ended up adding a lot of load to
the database -- for context, the dataset above that took 4 minutes to migrate
in total took 1 minute _per job_ when split up in this fashion.

However, we still have hope for this strategy. The old algorithm worked roughly
as follows:

For each of the jobs directly upstream (via `passed:` constraints) of the job
being scheduled, look at the last handful of builds of the upstream job.
Cross-referencing these handfuls of builds against each other, see if there is a
single set of versions that passed through a consistent set of successful builds
of the upstream jobs.
* if you found such a set of versions, use it as inputs for the new build.
* if you didn't find such a set of versions, look further back in the build
      histories of the upstream jobs.

We're going to try modifying this strategy to actually perform the datafix: the
plan is for the scheduler to lazily scan through the inputs and outputs tables
in similar chunks or 'pages', fixing just enough data at a time (and running
the new algorithm against the results) to get a build scheduled. In the worst
case this will still mean fixing all the data for a single job, but in such
cases there would be no build to schedule anyway, so there should be minimal
end-user impact.

## Conclusion

It's still possible that the 'lazily fix data as necessary' approach will
passively increase the load on the database too much. If this is the case, we
may need to fall back to a more intrusive upgrade path where the scheduler
does nothing until the datafix has run, and all users on the cluster are
notified appropriately.

All this means that we are not currently in a position to confidently say
whether the next scheduled release will be 5.7 (if we need more time to
determine the upgrade path and we leave our algorithm work on a branch) or 6.0
(if all goes well).

**Comment by vito** [comment]
Did acceptance locally and observed the incremental migration happening as I requested scheduling of jobs. Observed the same after upgrading old-prod and Wings.
