### ISSUE TITLE
Growing resource version table with Concourse 5.3

### ISSUE THREAD

**Issue by RaphaelVogel** [concourse/concourse#4259]
## Bug Report
Since our update to Concourse 5.3 we see that pipelines take long to start (sometimes several minutes!). We found that the postgresql table `resource_config_versions` has a lot of entries (3-4 mio). Our pipelines look like the one here -> https://gist.github.com/RaphaelVogel/d55c473cafe6948c6e7d51da9dbf6bf2
In every job we get the meta resource.

After we have removed records out of this table, jobs are starting faster again.

## Version Info

* Concourse version: 5.3
* Deployment type (K8s):

**Comment by clarafu** [comment]
Hi! The resource_config_versions table is used to hold all the versions for your resource so you probably saw that some versions were missing from your resource versions page after you removed records from that table.

When you say that pipeline takes long to start, do you mean that it takes long to even schedule a new (pending) build for a job or is it stuck in pending build state for a long time? If it takes long to schedule a new build, that's probably because of the way we do the scheduling of builds which loads all the resource versions into memory and then does some number crunching to figure out the next build inputs. As a result, if your resource is constantly getting new versions then the versions table will keep getting bigger and the scheduling will take longer. We are currently working on a new way of scheduling builds that will mitigate this (#3602).

**Comment by ccwienk** [comment]
hi @clarafu : we did some further analysis. It turns out, the underlying database will scale badly for a large amount of resource version insertions (in our case, we have/had about 200 "meta" resources, which were checked each minute, resulting in 200+ insertions per minute). We saw a very high CPU load on the node running the concourse database. Reducing the check frequency would mitigate the issue, but come at the cost of potentially outdated meta resource versions.

Now I am of course aware that said "meta" resource is actually a workaround for discovering information about a running job from within the job (which concourse explicitly wants to avoid). As with many workarounds, this one lead to other problems (namely performance issues).

So we went for a different approach. We now generate a UUID for each job execution and print it to the build log of a special build step (we call it "meta", like the "meta" resource). We now instrument the concourse-API from running jobs to find our own job, thus removing the need to use the "meta" resource.

I am sharing this hoping it might help somebody else with similar issues. Problem is resolved for us with this (new) workaround.
