### ISSUE TITLE
Core: re-triggered builds should not 'jump the queue' for the new algorithm

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4269]

**Comment by clarafu** [comment]
We modified the algorithm to account for rerun builds by having it order the builds (both for the latest build and the passed constraint builds methods) that are used to compute the inputs by build ids and rerun ids. If there is a rerun id, then order by that and if there is not a rerun id then order by build id.

The inputs for rerun builds are not computed through the algorithm, but actually is just copied over from the inputs of the build that is being rerun. This means that if you reran a build that has input versions that are now currently disabled, the rerun build will be created with that disabled version and will successfully run. We're not too sure if that is the behaviour that we want, but at least for now having the rerun builds not need to go through the algorithm allows the algorithm to not have different behaviours because of different purposes (for example, that it is for a rerun build then we want to pin inputs to specific versions of this build, but if it's for a normal scheduler run then we want it to find best set of versions for the constraints).

**Comment by vito** [comment]
Confirmed that they don't 'jump the queue' and that they *do* propagate downstream once they become the latest available candidate (i.e. by disabling all of the versions after it).
