### ISSUE TITLE
Fly login (and getting a token) should be easier

### ISSUE THREAD

**Issue by keithkroeger** [concourse/concourse#4278]
## Bug Report

Fly in 3.x and earlier, used to give you a nice URL that would return a token directly to the browser, even if you were using a remote fly login.  This isn't so easy in 5.2.

When you try to log on in fly, you see:
```
# fly -t target login -c https://sandbox.concourse.fmr.com
logging in to team 'main'

navigate to the following URL in your browser:

  https://sandbox.concourse.fmr.com/login?fly_port=34862

or enter token manually:
```

If you use that URL, you will be brought to the login screen, where you log in but will never receive a token that you could use locally.

The URL that should be here is https://sandbox.concourse.fmr.com/fly_success?fly_port=34862.

From here, there are other issues.

When you go to the /fly_success page, you are immediately presented with a page that notes that you can copy your token to the clipboard.  What you aren't told is that you need to first log in (seems obvious, but the page doesn't tell you that fact).

So, two issues:
1)  The URL requested by fly
2)  The page for /fly_success when the user hasn't logged in

## Steps to Reproduce

Try to log on through fly with a remote session.

## Expected Results

Present user with meaningful instructions

## Actual Results

Somewhat confusing and requires manual effort

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): BOSH
* Did this used to work?  Yes

**Comment by vito** [comment]
This doesn't sound right. If you're presented with a screen to copy your token, that means you've successfully logged in - otherwise there would be no token to copy!

This change is precisely to improve the flow when logging in to a remote server. You log in, and that gives you a button to copy the token, which can then be pasted to `fly`.

I just tested this from a Docker container to simulate the remote login and it worked fine for me:

![image](https://user-images.githubusercontent.com/1880/63050617-81539600-bea9-11e9-82ad-196018235320.png)

```
logging in to team 'main'

navigate to the following URL in your browser:

  https://ci.concourse-ci.org/login?fly_port=41187

or enter token manually: Bearer <snipped>
```

**Comment by keithkroeger** [comment]
Thanks for writing, Alex, and, after further testing, I rescind and will remove this issue.

The user happened to have the fly login command running locally and remotely and wanted to use the token in both places...think again Bozo.

Have a great day
