### ISSUE TITLE
Can't fly get-pipeline from another teams

### ISSUE THREAD

**Issue by hdiass** [concourse/concourse#4301]
Hello,

I've two teams (including main team), some pipelines we're created on another team, and i can see them on the UI, but from fly i can only do `fly pipelines --all`, besides that no other command to the secondary team works.

I'm from the main team and my user is localuser and owner on the secondary pipeline.

I'm on concourse 5.4.1. Upgraded from 4.2.0.

**Comment by pivotal-jamie-klassen** [comment]
for the time being, this is expected, and in order to run secondary commands
related to another team you must `fly login` passing the relevant team name via
the `-n` or `--team-name` flag to `fly login`. #4240 (which is currently in
progress) will provide a fairly convenient way around this in the case that you
are on the main team.
