### ISSUE TITLE
Unit Image used for CI causes CPU load to increase drastically

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#4302]
We noticed that the upgrade/downgrade jobs never being able to pass once the Unit image was updated. @pivotal-jamie-klassen  noticed that a recent change to the underlying golang image may have caused this. The debian image that golang is based on, incurred a major version bump from v9 to v10. We're gonna investigate this some more and report back.

**Comment by xtreme-sameer-vohra** [comment]
## New Golang Image
```
root@a84db633b799:/go# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

## Old Golang Image
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Both images are for Golang 
```
root@a117dc08abf3:/go# go version
go version go1.12.7 linux/amd64
```

# Current Theory
The new Debian Buster image has performance issues introduced by certain kernel patches [ref](https://www.phoronix.com/scan.php?page=news_item&px=Debian-10-June-Benchmark). At this point it looks probable that this has an impact on running Concourse as well. 
- specifically, the `unit` job history from [#Build 1011](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/1011) through [#Build 1020](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/1020) all seem to be experiencing failures as a result of a timeout. 
- the same behaviour also appears to be observable on the `upgrade` and `downgrade` jobs. Specifically, we observed the `check the internet` yarn test not run to completion. This is strange because all it does is pull the alpine image and `echo hello world`.

**Comment by kcmannem** [comment]
our attempt to resolve this is to convert the base image used by dev/unit images to be based on `concourse/golang-builder`. the builder image is based on ubuntu and should not be seeing these performance issues. With the builder image we can also more carefully control the golang dependancy upgrades while keeping the base image the stable.
