### ISSUE TITLE
Moving pipelines from one team to another causes links to break

### ISSUE THREAD

**Issue by betarelease** [concourse/concourse#4304]
> Please remove all lines starting with '>' before submitting!
>
> Bug reports on this repo should be related to core Concourse functionality.
>
> If the bug has more to do with *running* Concourse, consider opening the
> issue on a platform-specific repository instead:
>
>    BOSH: https://github.com/concourse/concourse-bosh-release
>    Docker: https://github.com/concourse/concourse-docker
>    Kubernetes: https://github.com/concourse/charts
>
> It's OK if you open it here, but we may move it to a more appropriate repo.
>
> If you're not sure that this is a bug and just need help with something,
> please ask in our support forum instead:
>
>     https://discuss.concourse-ci.org/c/support

## Bug Report

I moved a pipeline from one team to another by changing the foreign key in the pipelines table. The pipeline was previously in `main` team. 
After the move the job/stage boxes in concourse UI still point to the main team and thus are showing 404 when clicked.

## Steps to Reproduce
I moved a pipeline from one team to another by changing the foreign key in the pipelines table. The pipeline was previously in `main` team. 
After the move the job/stage boxes in concourse UI still point to the main team and thus are showing 404 when clicked.

## Expected Results

The links should point to the correct team that pipeline belongs to

## Actual Results

The links point to previous team

## Additional Context

> (delete this section if not needed)

## Version Info

* Concourse version: 5.2
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS: GCP
* Browser (if applicable):
* Did this used to work? No idea

**Comment by vito** [comment]
Moving pipelines between teams is not yet supported, and manually updating database records isn't exactly a supported API, so I'm struggling to see how this is a bug. :wink: 

There's already an open issue for moving pipelines between teams in https://github.com/concourse/concourse/issues/1164, so I'm going to close this. That issue is marked 'help wanted', so if you find the time maybe you'd be interested in submitting a PR? Sounds like you have a head start, or at least know what *doesn't* work! Maybe there are just other foreign keys that need to be updated, too?
