### ISSUE TITLE
Space encoding in search query changed during login process

### ISSUE THREAD

**Issue by coffee-squirrel** [concourse/concourse#4313]
## Bug Report

Space encoding in the `search` URL param changes from `%20` (`search-input-field` value `status: running`) to `+` `search-input-field` value `status:+running`) when starting out unauthenticated and then logging in.  This results in an invalid search query after getting redirected back.

## Steps to Reproduce

1. Access the Concourse Web interface and ensure you're currently logged out
2. Use `search-input-field` to search for something (e.g. `status: running`)
3. Click "login" in the upper-right and successfully log in
4. After getting redirected back, note that space characters have been replaced with `+`, resulting in something like "No results for status:+running matched your search."

## Expected Results

The original search value is preserved after going through the login process.

## Actual Results

The original search value is modified after going through the login process.

## Version Info

* Concourse version:  5.4.1
* Deployment type (BOSH/Docker/binary):  BOSH
* Infrastructure/IaaS:  vSphere
* Browser (if applicable):  Firefox 68.0
* Did this used to work?  Unknown

**Comment by coffee-squirrel** [comment]
This still exists under v5.6.0.

**Comment by pivotal-jamie-klassen** [comment]
I kinda want to describe the root cause here as a bug in the elm URL library: elm/url#32.

More specifically, the way golang handles URLs follows [the standard](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1), so that when skymarshal adds a CSRF token to the redirect URL, it actually decodes the `%20` in the query string (as Elm assigned it) into a space when [parsing the URL](https://github.com/concourse/concourse/blob/master/skymarshal/skyserver/skyserver.go#L239), and then [re-encodes it](https://github.com/concourse/concourse/blob/master/skymarshal/skyserver/skyserver.go#L266-L268) as a `+` following the standards: https://golang.org/src/net/url/url.go?s=8661:8697#L308.

Technically encoding spaces as `%20` isn't wrong. Ideally golang would provide some way to mutate the query parameters on a URL without re-encoding (since decoding and encoding are not proper inverses), but as far as I can tell it doesn't. So we kinda have to handle this on the Elm side. When [parsing the search parameter](https://github.com/concourse/concourse/blob/master/web/elm/src/Routes.elm#L194-L199), if you see a `+` you have to workaround `elm/url`'s bug and replace it with a ' '.
