### ISSUE TITLE
Feature Request: Restart Specific Build

### ISSUE THREAD

**Issue by avhetman** [concourse/concourse#4329]
Current Concourse v4.2.3

Expected behavior: When clicking the `+` icon in the upper right for a specific build, the currently selected PR should restart.

Actual behavior: The most recent PR is restarted, forcing one to push another commit to restart the build.

**Comment by deniseyu** [comment]
hi @avhetman! this happens because resource types are generally designed to always pull the latest and greatest available version of resources.

You can achieve your described workflow by running `fly check-resource -r pipeline/resource-name` and de-selecting all versions that are more recent than the version you want to run with in the UI. Note that if you have your job configured to trigger on new version, this will cause a new build to kick off with the latest checked version. 

If you're able to upgrade to at least v5.0.0, you can use the [pinned resources feature](https://github.com/concourse/concourse/releases/tag/v5.0.0).

**Comment by avhetman** [comment]
Awesome, thanks @deniseyu! This will achieve the result we want.
