### ISSUE TITLE
set the colour of a pipeline job/task

### ISSUE THREAD

**Issue by speculatrix** [concourse/concourse#4338]
I have a lint and style test stage in my pipelines, using a do/try so as to ignore the return code as I want the pipeline to continue despite linting errors.

however, if the job fails, the task is still shown as green. I'd like to have a third colour indicating a task failed but didn't stop the pipeline. or, better yet, be able to set the task colour programmatically, so I could set it to turquoise or something.

I'm afraid I know nothing of the code in concourse to even be able to start writing this feature myself.

thanks

I had to create a duplicate because I was away and github's bot decided to close it as "wontfix"

**Comment by speculatrix** [comment]
here's the once they force closed: https://github.com/concourse/concourse/issues/4072

**Comment by pivotal-jamie-klassen** [comment]
@speculatrix something the concourse team has done to solve this problem without opening up the color system in the UI to the extent you're describing is just running a lint in a separate job. So your downstream jobs (maybe stuff like integration tests or deploys to staging environments) still have passed constraints on some unit test job, but there's a separate lint job alongside them that is also downstream of the unit tests. The lint job is free to go red without blocking the whole pipeline

**Comment by speculatrix** [comment]
thanks p-j-k, we might have to adopt that course. 
however, what we want to actually do is have the pipeline fail if linting fail, but at the moment that would be too disruptive. I've introduced git pre-commit-hooks to try and improve code quality and stop more poor code creeping in.

**Comment by pivotal-jamie-klassen** [comment]
@speculatrix I think that introducing arbitrary job colors into the UI would be a potentially risky change for a few reasons. Unless you sure that feature is really needed for your use case, do you think it's OK to close this issue?

**Comment by speculatrix** [comment]
since I haven't looked at the code, I don't know how hard it would be to have some code which allows a pipeline stage to set its own colour, so, it can pass but set its colour to a warning colour

**Comment by speculatrix** [comment]
Can anyone help with any ideas?

**Comment by pivotal-jamie-klassen** [comment]
@speculatrix I'm really hesitant about adding arbitrary colors to the pipeline UI - I really strongly want to encourage you to take a step back and try to think about achieving your underlying goal in a simpler way. I can totally imagine how nice it would be to just glance at the pipeline page and be able to say "hey, that job is turquoise (or whatever color you want to use) - I guess linting failed" and have everything work otherwise. But what if you sent some kind of asynchronous notification on a lint failure, like an email or a slack message? Or you just uploaded your lint results to a secondary system and used whatever dashboard that thing has to show your static analysis/code quality metrics? Maybe that would be almost as good?

Before I get into it, I'll play devil's advocate with myself for a second - maybe the right way to achieve your ask is to add a new static job status, something like a "conditional success" that doesn't affect scheduling and just means whatever users want it to mean in their use case. This would be a way to address a lot of the complexity problems I'm about to outline, but I still don't know if it's useful enough to make the change.

When I think about the implications of this change from both a user-experience and backend/scheduling perspective, I can see it having a fair amount of explosive complexity - for two main reasons:

## If I have an arbitrary color on a job, is that the equivalent of a new status?

Consequences of this include:
* what name does the new status have?
* does the status dynamically get described in this legend on the pipeline UI?
<img width="162" alt="Screen Shot 2020-01-02 at 8 45 27 AM" src="https://user-images.githubusercontent.com/22056320/71669950-6391ab00-2d3c-11ea-9b1f-ae0a179ea413.png">

* does the new color show up on the dashboard in the pipeline previews?
* Does the new status get described in the legend in the dashboard footer?
* How does it affect scheduling (I think the answer is "it doesn't", since in your use-case the new colour would effectively mean 'success' for the sake of determining whether downstream jobs with a `passed` constraint should run)?

## How do we actually put a job in this new state?

Beyond the whole "new job status" idea, we would need to decide what is the actual model for setting this "alternate success status" in an actual job plan? Maybe it would be a new [step type](https://concourse-ci.org/steps.html), something like `set_color`?

**Comment by speculatrix** [comment]
Ok, well, if the status values and colours are hard-wired and the pipeline logic is effectively binary - run/stop, then I guess you can close this ticket.

I think then that what I need to do is have two pipelines for each repository or build process, one which is the build, and independently have a lint/code quality pipeline. We can then build and test new features whilst code quality and optimisation is worked on separately.

I would like to say that personally I think linting failures should be a fatal problem and stop the pipeline from continuing, otherwise people get lazy and put off tidying up, however, I've been asked to look into this as a way to ensure it's harder to ignore yet doesn't stop progress.

**Comment by pivotal-jamie-klassen** [comment]
@speculatrix I absolutely agree, as an engineer, that the right time to fix code quality problems is always NOW, but code always has multiple stakeholders 😞. One option that I might suggest, though it would represent a decent chunk of work on your end, would be to have your lint job just check the change in lint errors - like fail if a new commit _adds_ errors, but pass otherwise?

**Comment by speculatrix** [comment]
I've have been pushing to have git pre-commit hooks which call a linting script, to prevent even git commit from passing. It works fine, so I'm beating on people to get them to run the 'git config "core.hooksPath" .githooks' command!

**Comment by tkellen** [comment]
Here is a pattern to do conditional logic in concourse where some things can fail but not turn the job red:

```yaml
- name: conditional-in-concourse
  plan:
  - get: repo
    trigger: true
  # run first task in a try block since we are going to allow failures without
  # making the build red
  - try:
    - task: logic-gate
      config:
        image_resource:
          source:
            repository: <image>
          type: docker-image
        inputs:
        - name: repo
        outputs:
        - name: output
        platform: linux
        run:
          # if you exit 1 here it means the on_failure step should happen
          # if you exit 0 here it means skip to the final step
      on_failure:
        do:
        - task: conditional-task
          config:
            image_resource:
              source:
                repository: ((registry/base))/ci-build
              type: docker-image
            inputs:
            - name: repo
            outputs:
            - name: output
            platform: linux
            run:
              # write something to outputs/ to indicate success
  - task: check-if-inner-step-failed
    config:
      image_resource:
        source:
          repository: <>
        type: docker-image
      inputs:
      - name: outputs
      platform: linux
      run:
        # if outputs doesn't look the way you wanted```

**Comment by tkellen** [comment]
The way I use this in practice is when I build a container I tag it with the sha of the commit. The first step is a "skip gate" that says if the container is already in the registry for this commit, skip right to the end. The final check looks in the registry for a container with the known sha and if is there it considers the build good. In the case where a build is needed but fails, the build itself won't fail the job but the final check to find it in the container will.

**Comment by tkellen** [comment]
I know that doesn't speak to your specific issue of coloring @speculatrix but it should give you the ability to start alerting around linting failures without breaking builds
