### ISSUE TITLE
Add a flag for max-in-flight job scheduling

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4351]
Right now this is hardcoded as 32. We're not really sure what a perfect number is, but that one seems to work well enough for up to 4500 jobs. Let's just make it a flag so we don't paint ourselves into a corner.

**Comment by clarafu** [comment]
Blocked on #4534, I want to see how fast one ATC can schedule all the jobs within a deployment in order to know if 32 is a good limit. Before #4534, we could rely on multiple ATCs each scheduling 32 jobs at a time but with the addition of component tracking we will make it so that only one ATC will schedule all jobs per tick.

**Comment by vito** [comment]
@clarafu Do you have any findings to report on the scheduling speed?

Also, let's call the flag `--job-scheduling`. `--max-jobs-in-flight` makes it sound like a "max in flight" for running builds.

**Comment by vito** [comment]
Let's do this with tracing if it's merged by then (#4607). Otherwise we can just mark all jobs as `schedule_requested` and see how long it takes for them all to be scheduled (by monitoring `last_scheduled`).
