### ISSUE TITLE
What is the deprecation plan for "aggregate"?

### ISSUE THREAD

**Issue by Pivotal-Christopher-Wong** [concourse/concourse#4379]
## Bug Report
Pivotal Documentation tooling uses PWS concourse for our publication purposes.
Their version of Concourse still uses `aggregate`. 

We'd like visibility on a deprecation plan, and possible migration steps to provide guidance for our teams moving forward.

## Steps to Reproduce

Occurred when running the following command:
`rake fly:set_pipeline[cf-services]`

## Expected Results
Command is carried out with no errors.

## Actual Results
See attached image:
![Screen Shot 2019-09-05 at 10 29 12 AM](https://user-images.githubusercontent.com/3769188/64368803-07ff1d00-cfe9-11e9-902c-8250e1b921ee.png)

## Additional Context
Current implementation:
![Screen Shot 2019-09-05 at 11 32 02 AM](https://user-images.githubusercontent.com/3769188/64369358-32050f00-cfea-11e9-8218-bace16e36005.png)

## Version Info
Not 100%, you would need to reach out to PWS Platform team.

**Comment by vito** [comment]
Historically we've left deprecated functionality in for a long time as long as there isn't any maintenance overhead. This strikes me as one of those cases. I don't feel the need to aggressively remove small things like this since it can just make upgrade paths tumultuous. IMO the loud warnings are enough of a motivator.

I think a time-based solution is probably better than a version-number-based solution for removing deprecated functionality. It's easier to say "you had a year!" than "you had 2 major versions!" since we could easily go up 3 major versions in a year if we're trying hard enough.

So, what do folks think of EOLing the feature on June 1, 2020?

It's certainly a long time from now, but `aggregate:` has been around ever since pre-1.0 versions, and I'm pretty sure literally every Concourse pipeline uses it somewhere. As long as the maintenance overhead is small I think any timeline should be fine.

@marco-m @itsdalmo does that sound OK?

**Comment by marco-m** [comment]
@vito: Fine for me.

@Pivotal-Christopher-Wong:

> possible migration steps to provide guidance for our teams moving forward. 

Migration is as easy as replacing all `aggregate` with `in_parallel` :-) (https://concourse-ci.org/in-parallel-step.html)

**Comment by vito** [comment]
Created https://github.com/concourse/concourse/issues/5716 - we'll remove it in v7.0, whenever we get there.
