### ISSUE TITLE
How to get the same input versions for different jobs in a pipeline?

### ISSUE THREAD

**Issue by leshik** [concourse/concourse#4383]
Hi,

I have two jobs in a pipeline, `test-master` and `deploy`, both with `serial: true`. Both need git resource input. Sometimes, a new commit is added to the `master` branch while it's testing, and the `deploy` job gets a different input version, which leads to incorrect behavior.

How can I make it use the same input version for both jobs?

**Comment by clarafu** [comment]
Hi @leshik! You can use `passed` constraints so that the git resource needs to run through the `test-master` job before it can run with the `deploy` job. You can read more about `passed` constraints here https://concourse-ci.org/get-step.html#get-step-passed. 

I'm also going to close this issue because this seems to be more of a question! If you want to discuss this question more or have any further questions that you want to ask, you can ask them here in our forums (https://discuss.concourse-ci.org/) and also on our discord channel ( https://discord.gg/MeRxXKW)!

Thanks!
