### ISSUE TITLE
Document PostgreSQL setup on multiple platforms

### ISSUE THREAD

**Issue by rickhull** [concourse/concourse#449]
I am trying to "Quick Start" via https://concourse.ci/single-page.html#installing   So far the experience has been frustrating and time-consuming, regarding the necessary Postgres setup.

I am starting with the default Ubuntu 14.04 AMI on AWS, using the binary Concourse install.  Here are the steps I took in my first attempt to get `concourse web` working per the docs.
1. Boot Ubuntu AMI, log in (SSH) as `ubuntu` user
2. `sudo apt-get install postgresql postgresql-contrib`
3. download concourse binary ("binaries" makes it sound like there are multiple downloads or programs involved)
4. _At this point I have accomplished the documented prerequisites_
5. `mkdir ~/concourse`
6. `mkdir ~/bin`
7. symlink ~/bin/concourse to ~/concourse/concourse_linux_amd64
8. create the 3 ssh keys in ~/concourse per docs
9. try to start `concourse web` and fail
10. read: "This assumes you have a local Postgres server running on the default port (5432) with an atc database, accessible by the current user."
11. hmmm, how to do this?  Spend 10-30m learning about the postgres user model via google and `psql` experimentation
12. `psql atc` # doesn't work
13. `sudo createdb atc`
14. `sudo createuser ubuntu`
15. `psql atc` # works!
16. try to start `concourse web` and fail: `{"error":"pq: password authentication failed for user \"ubuntu\"","session":"1"}}`
17. give `ubuntu` DB user a password via `psql` and `\password`
18. try to start `concourse web` and fail: `{"error":"pq: password authentication failed for user \"ubuntu\"","session":"1"}}`

At this point, I was pretty frustrated.  I wasted another 30 minutes trying to get this to work before going on Slack to learn I need (something like): `--postgres-data-source postgres://ubuntu:concourse@localhost/atc`

With this, I was finally able to get `concourse web` running.

**Comment by waits** [comment]
I second this. I spent a while figuring out that ATC requires a password even if psql doesn't.

**Comment by Boran** [comment]
I also go caught out, and did not find this thread soon enough, spent a long time digging.
As I was unable to get "unix user authetication to work", I had manually created a DB and created a psql user, added a pg_hba.conf with "host    atc  concourse  127.0.0.1/32  md5"   and started with --postgres-data-source postgres://concourse:SOMEPASS@127.0.0.1/atc

But I get 
"timestamp":"1465368578.973579407","source":"atc","message":"atc.db.migrations.failed-to-acquire-lock-retrying","log_level":2,"data":{"error":"pq: SSL is not enabled on the server","session":"1"}}

Which leads down another rabbit hole of enabling ssl on postgres.
Is there a way of disabling the need for ssl?
Would you ming sharing the exactly config you got working please (pg_hba.conf, concourse_linux_amd64 command line, ....) ?

**Comment by Boran** [comment]
To answer myself, what I had to do, on centos7

# as postgres user
create database atc; 
create database concourse; 
create user concourse password 'SOMETHING’

# as root
vi /var/lib/pgsql/9.3/data/pg_hba.conf
host    concourse  concourse  127.0.0.1/32  md5
host    atc  concourse  127.0.0.1/32  md5

#Enable SSL
cd /var/lib/pgsql/9.3/data
openssl req  -nodes -new -x509  -keyout server.key -out server.cert -nodes
vi /var/lib/pgsql/9.3/data/postgresql.conf
   #  ssl=true

sudo systemctl restart postgresql-9.3.service

useradd -m concourse
cd /home/concourse
wget  https://github.com/concourse/concourse/releases/download/v1.2.0/concourse_linux_amd64 
# generate keys
    ssh-keygen -t rsa -f host_key -N ''
    ssh-keygen -t rsa -f worker_key -N ''
    ssh-keygen -t rsa -f session_signing_key -N ''
    cp worker_key.pub authorized_worker_keys

sudo -i
su - concourse
# start the service manually
./concourse_linux_amd64 web  --basic-auth-username myuser  --basic-auth-password mypass   --session-signing-key session_signing_key   --tsa-host-key host_key   --tsa-authorized-keys authorized_worker_keys --external-url http://gitlab.vptt.ch --postgres-data-source postgres://concourse:SOMETHING@127.0.0.1/concourse
`

**Comment by jadekler** [comment]
+1, postgres documentation is lacking

**Comment by robdimsdale** [comment]
+1 getting postgresql running with the standalone binary took far longer than I expected and involved steps that don't appear in the docs at concourse.ci

This issue provides enough information to get the ATC communicating with postgresql - turning these steps into docs (or some script to be run) would greatly improve the experience of getting started with the binaries.

**Comment by RobertoPrevato** [comment]
Indeed. Since in the ["Concourse vs." section of your website ](https://concourse.ci/concourse-vs.html) you listed all _downsides_ of Jenkins, to be fair you should also list its upsides, compared to your product:

1. no need to use a database server - which may be a big plus for many people
2. much easier installation (installing Jenkins and start using it is a matter of **few minutes**, in both Windows and Linux hosts)
3. superior installation instructions

Who wrote the instructions for Concourse CI made a lot of assumptions about others' knowledge (mentioning, without explaining, Vagrant, PostgreSQL, Docker, Clusters with BOSH). This is like the worst mistake when writing documentation / trying to explain something to anybody.

**Comment by vito** [comment]
@RobertoPrevato Installation instructions are a delicate balance. Replicating the full stack every time results in misinformation as each dependency's instructions change. Each of those sections you mentioned links to the project it relates to (Vagrant, BOSH, Docker), which have their own installation instructions. We document the delta, and when you'd want to use one method over the other.

For PostgreSQL we initially left the docs out because we happened to use operating systems with sane enough defaults that it was pretty obvious how to configure things. So we assumed this "delta" was tiny enough to not matter. The only thing you need is a database. Which for us was literally just `createdb atc`. It wasn't until we made the binaries and started dogfooding them on different platforms that we saw how painful it could actually be. But we haven't had time to write it all down. There's a lot to do here as the instructions vary wildly from platform to platform, because no one can seem to agree how PostgreSQL should be configured out of the box.

If you actually want to help, leave a comment here saying which OS you're using and what steps you had to perform. Thanks to @Boran and @rickhull for doing this - hopefully we'll get to this soon.

**Comment by RobertoPrevato** [comment]
@vito 
I am glad you didn't take badly to my critic, and took time to answer.
I've been trying to setup Concourse on a Windows 7 vm, as I am assessing different tools for CI, and I pretty much had the same experience described by @rickhull. For now I stopped when psql is complaining about SSL not being enabled on the server.

About the first thing you say on documentation, I kindly disagree with you:
You say that writing terse documentation about external dependencies is better, because it would become out of date, as the other technologies are evolving, resulting in misinformation; while I understand your point and agree to some extent, there is a long way between "Replicating the full stack" and being simplistic, not exhaustive. In medio stat virtus, virtue stands in the middle, like in most things.

It's like if I had to explain somebody how to install Grunt Task Runner, and I said:
```
Just run:
npm install -g grunt-cli
```
Without saying first what _npm_ is and how to obtain it.

I think that you are scoring a own goal with the documentation, and not only about PostgreSQL. Another example: I had no problems creating the ssh keys using ssh-keygen, but I know there are professionals who worked for years in enterprises using Microsoft technologies, who have no idea how to do it, or just used PuTTYgen and don't know about the ssh-keygen command. Even if you added few more lines about it, describing the different options, this information won't become obsolete any soon. The right approach is, imho, not to remove the example with ssh-keygen altogether, but writing something more about it (e.g. ssh-keygen is installed by default on most Linux distributions, while is not installed by default on Windows, but becomes available in git bash after installing git from https://git-scm.com, or after installing cygwin).
Of course anyone can google for information on the internet, but it's not a good visiting card for your work. Don't you want to attract the biggest number of people possible?

As a side note, my previous comment about the Concourse Vs section, it's also because it's so prolific! It counts 1000 words. And why didn't you follow the same rationale there?
Also those information may become obsolete and lead to misinformation: what if tomorrow Jenkins authors released a new version, which make it easy to implement pipelines? Or GoCD was refactored to implement easier configuration mechanics?

I don't want to pester you, I just wanted to give a constructive critic. Concourse CI look great and I'm looking forward to try creating the first job with it.

**Comment by vito** [comment]
@RobertoPrevato No worries, I appreciate the feedback. I'd agree with your example regarding `ssh-agent` - I think it's a good principle to at the very least explain the tools directly being used, which is why we generally link somewhere to get more info, or say something like "one way to do this is `ssh-keygen`" so they at least know it may be different for them.

Again, the line has to be drawn somewhere - even in your example you could have gone on to explain what `git` or PuTTY or cygwin are. The balance to strike is "how much time is spent on this, and how off-track from the original document are we getting" vs. "how likely are people arriving here going to be familiar with one of those things already and be able to continue".

Re the "vs." section - what you've said is already the case. Jenkins 2.0 required some changes there, and we've maintained it to the best of our ability. That section is important in showing the differences in design between Concourse and other projects, so it has to be maintained regardless of the state of the rest of the docs. It's easy to say we maintain one section much better than the rest, and that the rest should be just as good. But that implies we just don't care enough about the other sections.

The reality is we have to spend our time wisely. Documentation is a full-time job - there's always something to improve. But there are also hundreds of open GitHub issues/feature requests to resolve, folks in Slack to help out, an OSS community that we're trying to grow, and actual feature work that needs to be done. If you want to see the docs improve, submitting PRs would go a long way.

Feedback for the bits that people find are confusing are what point us to the sections to improve. So far, PostgreSQL has been the only real case of that.

**Comment by wrl** [comment]
Huge stumbling block; glad I found this issue.

Is there any reason the ATC can't connect over `/var/run/postgresql`?

**Comment by panzon** [comment]
To install on Fedora 23 
At first I install postresql using  the fedora wiki http://fedoraproject.org/wiki/PostgreSQL
Then I notice that something was wrong, then I found this post of Boran that was really usefull
but in my opinion the post can be improved, this is my improvement:
#change to postgres user
su - postgres

#get into psql
psql

#create databases and user
create database atc; 
create database concourse; 
create user concourse password 'SOMETHING’
#check that role was created correctly
SELECT rolname FROM pg_roles;

# log out
ctrl+D
#exit postgres user
exit
#log in  as root
su
#backup configuration file
cp /var/lib/pgsql/data/pg_hba.conf /var/lib/pgsql/data/pg_hba.conf.bck
#edit the postgres configuration files
vi /var/lib/pgsql/data/pg_hba.conf
# adding  2 lines at the end of the file:
host concourse concourse 127.0.0.1/32 md5
host atc concourse 127.0.0.1/32 md5

#and change "ident" to md5 in these 2 lines
host    all             all             127.0.0.1/32            ident
host    all             all             ::1/128                 ident


# To solve certificates issues I followed this Posgresql post https://www.howtoforge.com/postgresql-ssl-certificates
#Remember that the .conf files use '#' as comment character, so you need to uncomment the used lines

su - myuser
#I did not created an OS user, with my user 
#I just created a directory "concourse" and there:
mkdir concourse
cd concourse
wget https://github.com/concourse/concourse/releases/download/v2.4.0/concourse_linux_amd64
#for then create all keys
ssh-keygen -t rsa -f host_key -N ''
ssh-keygen -t rsa -f worker_key -N ''
ssh-keygen -t rsa -f session_signing_key -N ''
cp worker_key.pub authorized_worker_keys


#Then run  concourse

./concourse_linux_amd64 web --basic-auth-username myuser --basic-auth-password mypass --session-signing-key session_signing_key --tsa-host-key host_key --tsa-authorized-keys authorized_worker_keys --external-url http://MYHOST.EXAMPLE.ch --postgres-data-source postgres://concourse:SOMETHING@127.0.0.1/concourse

**Comment by yellowmegaman** [comment]
So it's been half a year now. Makes me wonder about other features.

**Comment by vito** [comment]
@yellowmegaman There's only so much we can do at once ourselves. We don't have infinite resources, and what's important to you (or even 10 people) can be outweighed by the needs of many others.

If you'd like to see this improve, you can submit a pull request or something. Leaving snarky comments is not what pushes open-source projects forward.

**Comment by yellowmegaman** [comment]
@vito Sorry if that sounded harsh of "snarky", there's only disappointment that such valuable project lacks essential best-practice part of the installation docs. 
I think most open-source projects *should* be able to be run easily, plug-n-play style so they can gather major user base and committers/testers/contributors, especially written in go.

At the moment, **concourse** is by many newly defined standards almost best way to go to achieve modern pipeline-driven process, that's why i think proper installation should be well documented, so we can dive in this process.

Leaving docs-complementing PR was my first thought, but postponed just a little it seems not straightforward right now, anyway i think i could have missed something crucial during setup.

**Comment by tetralix** [comment]
@vito How we can render documentation .any files? Just to check if they look ok before suggesting changes.

**Comment by TerraPenguin** [comment]
@vito In the time it took you to explain how little time you have, you could have updated the Install docs to make them more user friendly.

It's now February, and currently the best install Document in existence is this thread.

One of our developers really wanted to start using concourse, and I have to say it's been nothing but trouble trying to find out how to use it. First we set it up with vagrant, then docker. Luckily enough I had some knowledge in both to fill the gaps. Except back in August I could not find the Concourse Client to go with the server, which is here BTW https://github.com/concourse/concourse/releases.  
Now I'm trying to setup the Binary server and the install docks are the worst of the bunch.

There seems to be a disconnect at the most basic levels of documentation with your team. Maybe have someone who is not familiar with Concourse go through each type of each setup and have them point out the areas they get lost? OR, you can listen to the people here (your users) and make some simple changes to the docs. If it wasn't for this thread I'd say screw it and just go back to Jenkins.

**Comment by tetralix** [comment]
@vito I suggested changes for "docs/setting-up/installing.any". Please review/accept.

@TerraPenguin @rickhull  @Boran @panzon please review after rebuild.

**Comment by vito** [comment]
@TerraPenguin If it were a function of time this would have been done long ago.

I've already stated in this thread how this is a function of complexity regarding how different PostgreSQL is out-of-the-box across various systems.

Concourse's requirements of Postgres are simple. You need a database. That's it. There are 1,000 guides out there already covering this in depth across various platforms. Use one of those. If you like, you can then submit a pull request to our docs either linking to the guide you followed (I would much prefer that) or documenting the steps you took, but be sure to note your starting setup as it varies from platform to platform.

At this point nothing is being accomplished by leaving this open. I'm locking it. PRs will be considered, but nagging and not providing the information I requested in previous comments doesn't help.
