### ISSUE TITLE
Being on a pipeline view the UI periodically calls out to /api/v1/pipelines

### ISSUE THREAD

**Issue by simonjohansson** [concourse/concourse#4569]
As you can see in this screenshot the UI periodically calls out to `/api/v1/pipelines` which gives back a list of all pipelines the authenticated user can see.. 🤔 

<img width="1918" alt="Screenshot 2019-10-07 at 15 09 54" src="https://user-images.githubusercontent.com/736248/66314773-cf6aa000-e914-11e9-9e9e-bd465771cc4e.png">

**Comment by robwhitby** [comment]
same on the build page

**Comment by pivotal-jamie-klassen** [comment]
every page does this in order to keep the sidebar up-to-date (cf. https://github.com/concourse/concourse/blob/master/web/elm/src/Pipeline/Pipeline.elm#L305 and https://github.com/concourse/concourse/blob/master/web/elm/src/SideBar/SideBar.elm#L80-L92). I'm interested in what prompted this issue - is the end-user experience being impacted? like maybe that pipelines call is really slow to return on your cluster?

**Comment by simonjohansson** [comment]
@pivotal-jamie-klassen 
> Every page does this in order to keep the sidebar up-to-date
>  I'm interested in what prompted this issue - is the end-user experience being impacted? like maybe that pipelines call is really slow to return on your cluster?

We just noticing it happening and assumed it was some bug. Thanks for the explanation!
