### ISSUE TITLE
Provide official Docker image

### ISSUE THREAD

**Issue by devth** [concourse/concourse#463]
This is the biggest thing preventing me (and many others) from trying out Concourse.

**Comment by DenisIzmaylov** [comment]
UP!

**Comment by holstvoogd** [comment]
I have a setup with concourse on k8s running locally. Definitely not suitable for production since not all secrets are managed properly, or unique for that matter; but I'll see if i can put it up on github as little guide orso.

**Comment by DenisIzmaylov** [comment]
@holstvoogd  Thank you. But should we keep it in k8s? It seems the good solution is keeping CC outside of the cluster with Private Docker Registry.

**Comment by holstvoogd** [comment]
@DenisIzmaylov Good point, depending on how everything ties together etc you might need your cicd to bootstrap a cluster. Though ideally I would like to be able to bootstrap my entire infrastructure, including cicd and an image registry, from scratch. If you can do that, running everything within k8s should not be to complicate (I think/hope ;-))
Or is that not what you meant?

Anyway, just to be clear: my example stuff is definitely not meant for anything but testing/development purposes.

**Comment by DenisIzmaylov** [comment]
I meant if we run CICD outside of the cluster we can just configure our clusters on-the-fly by some Concourse tasks and it would be really useful. For example we can configure a CICD task to setup new cluster from scratch, deploy app and make some UA, integration and load tests.

**Comment by holstvoogd** [comment]
Ah yes, if you use such a setup that is true. However if you are not spawning new clusters all the time, it seems reasonable to deploy cicd in the cluster. Or perhaps you have a 'core' cluster in which ao the cicd is running and that creates new clusters (perhaps with there own CICD for testing purposes? ;))

Anyway, after working with concourse on a local k8s cluster for a little bit, I'm actually going to setup a few VMs for running concourse and it's workers. Especially the workers are not a great fit for running in containers since they need root privileges to spawn their own containers and will probably need loads of resources anyway.

**Comment by vito** [comment]
We'll start putting together a Docker image soon, but I want to cut Kubernetes from the scope of this issue. Once the image is there it should be easy enough to just plug it in to Kubernetes, Docker Compose, etc. - I'd rather not burden ourselves with maintaining docs for each and every Docker tool.

**Comment by jcderr** [comment]
I know it's out of scope now, but for anyone following this issue and still interested, I released a kubernetes resource type yesterday.

https://github.com/jcderr/concourse-kubernetes-resource

**Comment by DenisIzmaylov** [comment]
@jcderr Which difference it has relatively to https://github.com/frodenas/k8s-resource ?

**Comment by jcderr** [comment]
I do both check and in. And for out, I update existing resources via appropriate tools (`set image` for deployments). 

Their resources corresponds to a cluster. Mine is a specific kubernetes resource.
