### ISSUE TITLE
Gitea support

### ISSUE THREAD

**Issue by carlokok** [concourse/concourse#4681]
## What challenge are you facing?

Concourse supports several git sources already. However it doesn't currently offer an easy way to build gitea branches and pull requests. 

## What would make this better?

Having full support for gitea, including responding success/failure state would make the combination of gitea and concourse a perf ft combination for lightweight (but still extremely powerful) vcs with ci.

**Comment by deniseyu** [comment]
Hey @carlokok, thanks for opening this issue. The core team generally doesn't have the bandwidth to work on ecosystem tools like new resource types or support for custom integrations, but if you wanted to give this a shot then we can provide support with answering any questions you have around design or implementation. It sounds like this best fits as a new resource type, so this page should help you get started: https://concourse-ci.org/implementing-resource-types.html

**Comment by SuperSandro2000** [comment]
Spam bot go away.

**Comment by avanier** [comment]
For those interested, I started working on a Gitea resource. It is currently untested and probably not functional, but not that far off.

I needed the resource for a series of workshops where participants would host a full environment. I didn't get to use it yet, but I think the MVP is about 80% there. It's meant to work like @Typositoire 's [github-pr-list](https://github.com/adgear/github-pr-list) resource. You're meant to use it with a [`set_pipeline`](https://concourse-ci.org/set-pipeline-step.html) step. Not the most accessible pattern right now, but once you got it setup, it's very reliable.

https://git.sr.ht/~avanier/gitea-resource

**Comment by bartol** [comment]
Any updates on this issue?

**Comment by vito** [comment]
I think this can be closed as it falls under an intersection of a few things that have other resolutions:

* A `gitea` resource type has been implemented (thanks for sharing @avanier!)
* Support for branches and pull requests can be added via the [v10 roadmap](https://blog.concourse-ci.org/core-roadmap-towards-v10/) by using the...
  * `across` step: https://github.com/concourse/rfcs/pull/29 (almost done)
    * for being able to run a step across all branches/PRs
  * `set_pipeline` step: https://github.com/concourse/rfcs/pull/31 (almost done, experimentally implemented in v5.8+)
    * for setting a pipeline `across` branches/PRs
  * pipeline archiving: https://github.com/concourse/rfcs/pull/33 (merged, partially implemented, aiming to finish in v6.4 or subsequent releases)
    * for auto-archiving merged/deleted PRs/branches
  * pipeline instances: https://github.com/concourse/rfcs/pull/34 (soon to be merged)
    * for grouping PR/branch pipelines together
  * prototypes: https://github.com/concourse/rfcs/pull/37 (almost done)
    * for actually implementing support for detecting the branches/PRs
* Support for updating the build success/fail status in Gitea can be implemented using...
  * notifications: https://github.com/concourse/rfcs/pull/28 (this is just a placeholder atm, but the blog post sheds some light on the idea)
  * prototypes (again) for implementing the Gitea notifications support

So, once we have all these pieces implemented, Concourse should be able to provide pretty complete support for branch/PR automation - it would just require someone to implement a `gitea` prototype that supports the various messages required for use as a var source (for `across` step), a notifier (however that RFC turns out), and perhaps a resource, though an alternative may be to just use the `git` resource for that aspect.

I'll be shepherding these RFCs through the process and keeping folks updated at our [Blog](https://blog.concourse-ci.org/), so that's probably a good way to follow all of the above. 🙂

**Comment by tooolbox** [comment]
@vito This sounds great, although it seems slightly premature to close the "Gitea support" ticket if it's not actually implemented.

Furthermore, if I want to get notified when it is implemented, I can subscribe to a GitHub ticket but I can't see an obvious way to subscribe to your blog.  Any thoughts?

**Comment by vito** [comment]
@tooolbox I hear ya, but having an issue open for every possible service that Concourse can integrate with is too difficult and time consuming to manage.

Issues are for our core team's backlog - this a recent change detailed in [this post](https://blog.concourse-ci.org/nobody-wants-a-stale-bot/). Our team is probably never going to be in a mindset of "Gitea support" or "GitHub support" or "BitBucket support" - we are going to be tracking the generic approach that applies to all services, and leaving issues open for all of them just fragments discussion and makes it hard for maintainers to know which issues can be closed whenever we finish a generic feature.

I would recommend following https://github.com/concourse/concourse/issues/1172 instead which is a more generic representation of this same issue that should end up closed as soon as all the required parts are there.

Also the blog has an [RSS feed](https://blog.concourse-ci.org/rss/) if that helps.

**Comment by tooolbox** [comment]
Thanks @vito I get where you're coming from.  I subscribed to that issue, and hooked up an IFTTT notifier to your RSS feed :)
