### ISSUE TITLE
Cannot view pipeline job with slash in name from dashboard

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#4709]
## Bug Report

Clicking a pipeline job from the dashboard where the name contains a `/` renders the dashboard (as the `/` is not URL encoded).

Note that this issue only happens from the dashboard - not the pipeline page.

## Steps to Reproduce

https://gist.github.com/aoldershaw/401e5ed015889370a371d2ab1636c7f9

From the Concourse dashboard, click on the `a/b` job.

## Expected Results

Linked to `.../pipelines/<pipeline>/jobs/a%2Fb` (`/` should become `%2F`)

## Actual Results

Linked to `.../pipelines/<pipeline>/jobs/a/b` (which renders the dashboard)

## Version Info

* Concourse version: 5.6.0
* Deployment type (BOSH/Docker/binary): Docker (Helm chart)
* Infrastructure/IaaS: GKE
* Browser (if applicable): Chrome 78

**Comment by deniseyu** [comment]
hey @aoldershaw! Thanks for filing this. This does sound like a bug, but we're probably going to fix it because stricter naming for pipelines is on the horizon, in this PR: https://github.com/concourse/concourse/pull/4508 That change is in part motivated by edge cases like this.

We may still support aliasing for display purposes, but the strategy we'd recommend is to start renaming your pipelines to not use slashes.
