### ISSUE TITLE
Schedule only jobs which need to be scheduled

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4717]
As a further optimization after #3704 we can mark specific jobs to schedule instead of scheduling entire pipelines. We can do this by keeping track of job inputs and marking only the jobs affected by each change.

We could do this by adding a table with 3 columns: `resource_id`, `job_id`, and `passed`.

**Comment by clarafu** [comment]
Proposed schema:

```sql
CREATE TABLE job_pipes (
  resource_id integer REFERENCES resources (id) NOT NULL,
  job_id integer REFERENCES jobs (id) NOT NULL ON DELETE CASCADE,
  passed_job_id integer REFERENCES jobs (id)
)
```

For the following plan...:

```yml
- get: some-resource
- get: some-other-resource
  passed: [a, b]
```

There would be 3 rows: one for `some-resource` with a `NULL` `passed_job_id`, and two for `some-other-resource` - one with `passed_job_id` => job `a` ID, one with `passed_job_id` => job `b` ID.

When a build for a job passes, any `job_id`s with a `passed_job_id` matching the job will be scheduled.

When a resource changes, any `job_id`s with the same `resource_id` and a `NULL` `passed_job_id` will be scheduled.

**Comment by clarafu** [comment]
Things to do:
- [ ] Add indexes
- [ ] Add migration for existing data

**Comment by clarafu** [comment]
When we update the request schedule times on the jobs or pipelines, a deadlock can occur if we run the queries all in one transaction which is why we originally ran each update in a separate connection. https://github.com/concourse/concourse/blob/342dc8b21a6bf841bfeaeb77fab67199186e9470/atc/db/resource_config_scope.go#L340-L346

We wanted to see if we could improve on this somehow in order to make it either more efficient (by reducing the number of queries it needs to run because the number of queries grows with the number of jobs or pipeline) or more resilient to refactors (it is not easily noticeable that making the queries run in one transaction will result in deadlocking). We first tried to combine all the queries into one query using the following:

```
 _, err := psql.Update("pipelines").
 	Set("schedule_requested", sq.Expr("now()")).
 	Where(sq.Expr(`id IN (
 		SELECT DISTINCT pipeline_id
 		FROM resources
 		WHERE resource_config_scope_id = $1
 		ORDER BY pipeline_id
 	)`, rcsID)).
 	RunWith(conn).
 	Exec()
```

It resulted in deadlocks still happening within our manual tests because the ordering of the select statement does not affect the ordering of the updates. In order to have the updates lock the rows in a specific order, you will need to use a `SELECT ... ORDER BY pipeline_id FOR UPDATE`. Since we are dealing with two different tables, adding the `SELECT ... FOR UPDATE` will cause the query to be more complicated and also add performance overhead. With this in mind, we decided to not use this approach.

Instead, we tried to simplify the code by not requiring each query to have it's own connection by first, using one query to select out the pipeline ids in order. Then using the result of the query, we loop through and run each update individually but with the same transaction. We ran the same manual tests against this approach and saw that no deadlocking occurred.
