### ISSUE TITLE
Job Scheduling speed slows down over time

### ISSUE THREAD

**Issue by radoslav-tomov** [concourse/concourse#4730]
We have a pipeline with 20 jobs, which are triggered in groups of 5 in 1,2,5 and 10 minutes intervals.
It all worked fine, until recently we noticed, that the time for scheduling the jobs in this pipeline started to increase. Once scheduled, every job in this pipeline was initialized and ran successfully without any performance degradation.

The PostgreSQL we use is Azure Managed, so we activated the Query Performance analyzer there for 2 hours and we stumbled upon a slow query.

![Top Slowest Queries](https://i.ibb.co/2sRxsML/top-queries.png)

You can see the size of the tables 

```
 Schema |                 Name                  | Type  | Owner |    Size    | Description 
--------+---------------------------------------+-------+-------+------------+-------------

 public | build_resource_config_version_inputs  | table | atc   | 824 MB     | 
 public | build_resource_config_version_outputs | table | atc   | 12 MB      | 
 public | builds                                | table | atc   | 3122 MB    | 
 public | pipeline_build_events_2               | table | atc   | 4502 MB    | 
```

```
atc=> select count(*) from builds;
  count  
---------
 2797664
(1 row)
atc=> select count(*) from pipeline_build_events_2;
  count  
---------
 8559847
(1 row)
atc=> select count(*) from build_resource_config_version_inputs;
  count  
---------
 6426291
(1 row)
atc=> select count(*) from build_resource_config_version_outputs;
 count 
-------
 33437
(1 row)
atc=> 
atc=> select count(*) from versioned_resources;
 count  
--------
 271336
(1 row)

```

Build log retention is set to 30 days

```
  build_log_retention:
    days: 30
```

Once we  deleted the pipeline and uploaded it again, scheduling was back on track and it was instant

This is how the DB looks after that

```
 Schema |                 Name                  | Type  | Owner |    Size    | Description 
--------+---------------------------------------+-------+-------+------------+-------------
 public | builds                                | table | atc   | 3122 MB    | 
 public | pipeline_build_events_50              | table | atc   | 243 MB     | 
 public | build_resource_config_version_inputs  | table | atc   | 824 MB     | 
```

```
atc=> select count(*) from builds;
 count  
--------
 581429
(1 row)


```

My suspicions are with this query
https://github.com/concourse/concourse/blob/04d7a1a43ebb2227ccf07c9a073d704881ca462e/atc/db/pipeline.go#L727

You can see that builds table had 2797664 entries and now 581429, which would explain the improvement in performance, once we did the deletion of the pipeline.

it makes me think if we should have also an option to specify the number of builds, which should be kept and not only the build log retention. If my assumptions are right, every pipeline is bound to eventually slow down if it was running long enough. 

 

## Version Info

* Concourse version: 5.2.0
* Deployment type (BOSH/Docker/binary): Bosh
* Infrastructure/IaaS: Azure

**Comment by acarsercan** [comment]
+1

**Comment by deniseyu** [comment]
I suspect that some of this slowdown is caused by how Concourse currently figures out the answer to the question "what is the version of this resource that I should use for this task, given the web of previous `passed` conditions?" Not sure if you are tracking your CPU over time with dashboards or anything, but a metric that corresponds to the growing complexity of that computation is higher CPU usage over time. The good news is that big improvements are coming in v6.0.0, including an overhaul of the version calculation algorithm, which should make one substep of job scheduling a lot more performant, especially for Concourses with rich build history.

Putting a retention period on builds overall is interesting. Concourse is designed with the assumption that operators care about build history and want things like the historical record of resource versions, are these things less important for your use case? I don't know enough about that part of our codebase yet so don't feel confident speculating on the complexity of doing something like that.... cc @clarafu @pivotal-jwinters @xtremerui

**Comment by radoslav-tomov** [comment]
@deniseyu I'll dig into the monitoring stack and try to see how the CPU stats have changed over time. unfortunately, on our Azure setup, we don't have a good integration of Azure's monitoring of the DB and our monitoring stack, so I'm not sure how much data will be available.

I would not say, that the historical record is of less importance to us, but we are using concourse for a "continuous thing doer" and amongst other things, I would say that history is important up to a month or maximum 2 in the past. 

A core use case is for continuous deployment.  For each instance of our platform (Cloud Foundry, Bosh and tons of other software like Logging, Monitoring and etc...) we have a Concourse Instance.  It has an "update" pipeline, which is configured to monitor for new releases and then it automatically picks them up and updates the components of the platform (like Cloud Foundry, Bosh,  network layouts ... basically everything). The pipeline is like a k8s resource controller constantly trying to reconcile the current platform version to the desired(new) platform version.  I guess you can see how history plays very little role, once we start talking about months back. Also, we use a form of git ops, so each change that was initiated was tracked beyond Concourse History.

The very critical use case we have for Concourse is for Availability Monitoring.  We have a Monitoring pipeline, which implements a sort of heartbeat. Each Job there is responsible for the heartbeat of some service and on predefined intervals of time the jobs are triggered and they send a pulse check to an external system. If the external system does not get a message for service in the defined timeframe, then it assumes the service is down and then operators kick in and it gets ugly.  Here again, history is important, but only to troubleshoot recent failures. Beyond a month I see no use of it.

**Comment by clarafu** [comment]
@radoslav-tomov Hi! Thanks a lot for taking the time to give us as much information as possible, it's incredibly appreciated!

You are definitely on to something that the Concourse team has been working on for the past few months. The way that the current algorithm/scheduler within Concourse works is that it uses that `LoadVersionsDB` method to load up all the data it needs to run it against the algorithm in order to figure out which versions should be used for the next build for a specific job. The problem is that it loads up all the resource versions, build inputs/outputs for an entire pipeline and, as you have experienced, the query will get slower as the dataset gets larger.

We have a [project board](https://github.com/concourse/concourse/projects/22) that is tracking the progress of the change to fix this problem, there is also an issue #3602 for reimplementing a new algorithm that does not depend on us loading up all the data using that slow query. The work for it is finished and we are currently in the final stages of testing, this feature should be out in the next major release.

**Comment by radoslav-tomov** [comment]
@clarafu thanks for the info. I'll check out in more detail #3602. Can you give me a hint of the timelines for the next major release?

**Comment by clarafu** [comment]
@radoslav-tomov We usually try to release every three weeks but since this will be our first beta release, it might take a bit longer.
