### ISSUE TITLE
Show teams using an external worker in the workers output

### ISSUE THREAD

**Issue by pivotal-gabriel-dumitrescu** [concourse/concourse#4743]
## What challenge are you facing?

We (CF Toolsmiths) are wondering if there is any way for us to find out the teams that are using the vSphere external workers we currently have deployed on Hush House for several teams in R&D.

## What would make this better?

This feature would help us diagnose, inform and improve our service for the R&D teams.

**Comment by deniseyu** [comment]
Hey @pivotal-gabriel-dumitrescu, thanks for opening an issue! I just want to clarify so we are on the same page: your team currently owns and operates some external workers, but you don't admin this Concourse. And you might have a user account on the Concourse, but your user isn't necessarily a member of all the teams that are using this worker.

I'm not sure that the admin user even has high visibility over this right now, to be honest. We have some log-based auditing features that operators can enable, which means we might be able to set up a dashboard for you if we could get the right information into those logs (I don't think it's in there yet).

There's sort of the opposite conversation happening in threads like #4337 where folks are searching for a solution to the question, "Given that I have a task, where is it running?", since your question is "Given I have a worker, what's running on it?"

I don't think that we've discussed the persona of "external worker provider/operator" in much depth before, but I can see a case for solidifying some user needs and journeys. cc @vito @scottietremendous

**Comment by pivotal-gabriel-dumitrescu** [comment]
@deniseyu Thank you for looking into this issue for us.

*"your team currently owns and operates some external workers, but you don't admin this Concourse. And you might have a user account on the Concourse, but your user isn't necessarily a member of all the teams that are using this worker."*
That is correct.

*"folks are searching for a solution to the question, "Given that I have a task, where is it running?", since your question is "Given I have a worker, what's running on it?""*
In the end, we would like to be able to answer the question: "Given I have a worker, what's running on it and which team is running that job/task on it?"
