### ISSUE TITLE
((redacted)) showing in build logs

### ISSUE THREAD

**Issue by esauser** [concourse/concourse#4749]
## Bug Report

`((redacted))` is showing up occasionally in the build logs when secrets aren't present.  It consistently happens with certain output, but we don't know _why_ it happens.

## Steps to Reproduce

One example of where it always happens is when output the result from `terraform plan`.

```
# vault_jwt_auth_backend.keycloak will be updated in-place
  ~ resource "vault_jwt_auth_backend" "keycloak" ((redacted))
```

There is no secret there.  As far as we can tell, it's just whitespace and/or newline.  But it certainly doesn't happen on every whitespace or newline.

## Expected Results

```
# vault_jwt_auth_backend.keycloak will be updated in-place
  ~ resource "vault_jwt_auth_backend" "keycloak"
```

## Actual Results

```
# vault_jwt_auth_backend.keycloak will be updated in-place
  ~ resource "vault_jwt_auth_backend" "keycloak"
```

## Additional Context

We have the `CONCOURSE_ENABLE_REDACT_SECRETS` set to `true`.

## Version Info

* Concourse version: 5.7.0
* Deployment type (BOSH/Docker/binary): Binary
* Infrastructure/IaaS: GKE web, GCP Computer VM workers
* Did this used to work? Redacting secrets is new in 5.7.0.  We didn't start using it in 5.6.0 due to https://github.com/concourse/concourse/issues/4656

**Comment by evanchaoli** [comment]
@esauser Is there any invisible chars defined in your credential manager? We only redact non-empty secrets as the code:

```go
func (it *credVarsIterator) YieldCred(name, value string) {
	for _, lineValue := range strings.Split(value, "\n") {
		lineValue = strings.TrimSpace(lineValue) // trim space from a secret first
		if lineValue != "" { // then only redact non-empty secret
			it.line = strings.Replace(it.line, lineValue, "((redacted))", -1)
		}
	}
}
```

**Comment by esauser** [comment]
@evanchaoli noticed another instance this morning.

```
* google_project_iam_member.velero_server_role_binding: Error applying IAM policy for project "MY_PROJECT_NAME": Error setting IAM policy for project "MY_PROJECT_NAME": googleapi: Error 400: The role name must be in the form "roles/((redacted))role((redacted))", "organizations/((redacted))organization_id((redacted))/roles/((redacted))role((redacted))", or "projects/((redacted))project_id((redacted))/roles/((redacted))role((redacted))"., badRequest
```
should read
```
* google_project_iam_member.velero_server_role_binding: Error applying IAM policy for project "MY_PROJECT_NAME": Error setting IAM policy for project "MY_PROJECT_NAME": googleapi: Error 400: The role name must be in the form "roles/role", "organizations/organization_id/roles/role", or "projects/project_id/roles/role"., badRequest
```

None of our secrets contain invisible characters.

**Comment by evanchaoli** [comment]
@esauser With this information, I cannot reproduce the problem by myself. Is it possible to show me your pipeline YAML code?

**Comment by agurney** [comment]
Possible clue: I believe from other sources that the googleapi error message _actually_ reads

```
The role name must be in the form "roles/{role}", "organizations/{organization_id}/roles/{role}", or "projects/{project_id}/roles/{role}"
```

which would produce the cited output if `{` and `}` are considered "secrets". I assume OP isn't using `{` as a password, or something ;-) but perhaps does have a multiline secret formed like

```
  {
     "foo": "bar",
     "other": "stuff"
  }
```

where the `lineValue` iteration will find the curly brace lines, trim surrounding spaces, and then diligently purge those characters whenever it sees them in logs.

**Comment by esauser** [comment]
@agurney wow, that's exactly it.  Each instance we see is a curly brace.  Nice catch.  We were having trouble figuring out what was actually causing it.

**Comment by vito** [comment]
@agurney Hahaha, nice catch. I guess linewise secret redaction is trickier than we thought. :thinking: 

Maybe we could just maintain a whitelist. Or just not bother redacting single-character values? Feels arbitrary but I can't imagine a single letter ever being useful to redact. (I can imagine two, i.e. `ci` is a common username.)

**Comment by agurney** [comment]
The short-string heuristic seems plausible. Perhaps only applied to lines that come from a multi-line string - but I am wary of complicated rules here. One day it's "we'll avoid redacting strings of up to four characters of digits only, or two-character strings of exclusively punctuation", the next day it's "this entire thing is a debugging nightmare because we can't see people's secrets to advise them on what specifically went wrong".

**Comment by evanchaoli** [comment]
@vito I was actually thinking to not redact single char secret yesterday, I also thought to add a CLI option like "MinLenOfScecretToRedact", so that folks may even set to 8, because many security rules enforce 8 chars or even longer password.

@agurney Thanks so much for the finding. I'm just curious that, in the case of such JSON formatted secrets, what are real secrets? Is the entire json as a secret?

**Comment by esauser** [comment]
@evanchaoli we do have legit JSON secrets where the entire JSON is a secret.  Our use case for this is Google Cloud Service Account Keys.  They are JSON objects.

Note, however, that those are not related to the redaction issues we're seeing.  The JSON `{` and `}` that are being redacted are parts of JSON output, not JSON secrets.

**Comment by agurney** [comment]
@evanchaoli It is a difficult one. I feel like multi-line secrets are mostly things like TLS certs or private keys - in any case, a big blob of data that we expect to see as a unit. If someone has structured data then maybe they are printing out bits and pieces of it in different ways; I don't think there's a feasible way to trace the provenance. By the same token, though, if I have a cert then I'm almost certainly not printing out random lines here and there - I'm either printing the whole thing as a unit, or not at all.

I was thinking about logic that would differentiate between:

1. a "simple string" secret - recognize and redact it anywhere
2. a "multiline" secret - redact only if the current log line is an exact match for any line from the multiline secret (or maybe allow for whitespace differences)

Then we don't hide random `{` or `],` just because somebody set a JSON-format secret, but we do still get to redact when somebody echoes out their private key. If I have a structured secret and choose to print out information drawn from inside it, I'm on my own. 

The rule (2) is assuming we still prefer to use the log-line-at-a-time method for scanning for secrets - it's not doing an "actual" multiline match, so has some chance of incorrectly redacting log lines that happen to coincide with secret lines. For example, with the Terraform output, there's pretty often going to be a line containing just `}`.

A possible refinement to rule (2) would be:

3. Match and redact _if_ the current log line is an exact match (barring surrounding whitespace) for a line from the multiline secret, _and_ that line is "a small amount of punctuation".

That is, lines like the following are not secrets: `{`, `}, {`, `]]}`, `,`. And if I try to print out a secret JSON object, what I would then see is something like:
```
{
   ((redacted))
   ((redacted))
}
```
which seems sort of OK. That's broadly similar to the proposed single-char rule as well, but additionally prevents spurious censorship of a few more things.

**Comment by vito** [comment]
@agurney Agreed.

> By the same token, though, if I have a cert then I'm almost certainly not printing out random lines here and there - I'm either printing the whole thing as a unit, or not at all.

This is true. One big reason for redacting line-by-line is to cover cases where a multiline credential is re-formatted in some way, e.g. JSON formatted like `"foo\nbar"`. If we were to replace the secret verbatim, this would escape the pattern-match because of the pesky `\n` in between the lines. Replacing line-by-line will at least turn this into `"((redacted))\n((redacted))"`.

> 3\. Match and redact _if_ the current log line is an exact match (barring surrounding whitespace) for a line from the multiline secret, _and_ that line is "a small amount of punctuation".

I think you meant "not a small amount of punctuation" here? :) (i.e. *don't* redact if it's a small amount of punctuation)

**Comment by evanchaoli** [comment]
Sounds like a similar solutions is, if a secret line contains only white spaces and punctuation, then don't redact it. What do you guys think? @agurney @vito

**Comment by esauser** [comment]
I may be off base here, but it seems to me the root issue here is that when we have multi-line secrets, the system is treating each line as a secret instead of all lines.  I think any solution that doesn't properly treat all lines as the secret is going to be vulnerable to inaccurate redaction.  For example, these JSON secrets we're talking about have many lines in them that could very well show up elsewhere in the output, and they are neither short nor whitespace or punctuation.

```
{
  "type": "service_account",
  "project_id": "((my-project-id))",
  "private_key_id": "((redacted))",
  "private_key": "((redacted))",
  "client_email": "((service-account))@((my-project-id)).iam.gserviceaccount.com",
  "client_id": "((service-account-id))",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/((service-account)%40((my-project-id)).iam.gserviceaccount.com"
}
```

I can imagine scenarios where these individual likes could contain literally anything, thus until we address the root cause I think we'll be chasing this forever.  Having said that, I don't have a good solution.

I thought about buffering the output for the length of the largest secret, but that could result in the end user seeing literally nothing during extended operations.  I also thought about not allowing multi-line secrets (and instead doing something like base64 encoding them like we do with Kubernetes secrets), but that becomes annoying because then you have to decode it before you can use it.

This is definitely tricky to solve perfectly.  Do we want to solve it perfectly or just get around the one issue I presented here?

**Comment by evanchaoli** [comment]
@esauser We by sure want to solve it perfectly, but we just don't know what a perfect solution is. So I think solving happened issue is a way to move forward.

Ideally, users should never print secrets to build logs. But users may badly print secrets in unpredictable ways. So the redaction feature can only "try the best", but never accurately handle all the cases.

When I implemented the feature, I didn't consider json secret at all, to be honest. We don't have json secrets in our Vault. Now one thing I can come out is, for JSON/YAML secrets, treat every value as a secret. So that, say we have a secret:

```json
{
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
}
```

If it's printed to build log, it will be redacted as:

```json
{
  "token_uri": ((redacted)),
  "auth_provider_x509_cert_url": ((redacted)),
}
```

**Comment by esauser** [comment]
@evanchaoli technically, that would work in our case.  One would think that the name would never be a secret, but who really knows.  In our case, the only value that is truly a secret is the `private_key`, but the relevant CLI expect all of that information together.  So we put it all in the secret instead of massaging it outside the CLI.

**Comment by vito** [comment]
@evanchaoli 

> Sounds like a similar solutions is, if a secret line contains only white spaces and punctuation, then don't redact it. What do you guys think? @agurney @vito

Makes sense but I'm not sure it's worth the trouble, to be honest. That'd probably spend a few more CPU cycles on every chunk of build output just to cover an edge case. Checking for length is probably cheaper and almost as effective. :thinking: It won't catch secrets like `{}` but I'm not really sure that's worth worrying about.

@esauser 

> I may be off base here, but it seems to me the root issue here is that when we have multi-line secrets, the system is treating each line as a secret instead of all lines.

For context, this is a conscious design decision so that redaction isn't thwarted by re-formatting of multiline credentials: https://github.com/concourse/concourse/issues/4749#issuecomment-553985073 ... which happens fairly often, i.e. when `echo`ing a value to a file with `set -x` or when a CLI you're using prints a "diff" of values that have changed.

It may not help as much with JSON values though which may get re-formatted in more subtle ways: `{"foo": "bar"}` => `{"foo":"bar"}`. Or by just printing `bar` somewhere.

Being semantic with JSON and treating the 'values' as credentials is a possible next step. If a returned credential is valid JSON, for example, we could parse it and register each value as something to redact. For non-JSON values, we can do per-line redaction. This may lead to more complication though, for example what happens when there's a non-trivial JSON value? Do we just walk the structure and collect all strings present?

This will probably get us closer to technical perfection but I think we should be conscious of the runtime cost and whether it's worth spending effort on this vs. other things - it seems like it could be a constant source of work. :thinking: Right now my main goal with redaction is to just keep people safe from simple mistakes like `echo`ing a credential (in full) with `set -x` enabled in the script. For that use case, I think what we have is sufficient, aside from the funny business around redacting super-short lines.

**Comment by evanchaoli** [comment]
> Makes sense but I'm not sure it's worth the trouble, to be honest. That'd probably spend a few more CPU cycles on every chunk of build output just to cover an edge case. Checking for length is probably cheaper and almost as effective. 🤔 It won't catch secrets like `{}` but I'm not really sure that's worth worrying about.

@vito I agree. So in that case, shall we take #4757?

**Comment by vito** [comment]
@evanchaoli Sure, I'll go ahead and merge!
