### ISSUE TITLE
Resource view: Edit Comment inline

### ISSUE THREAD

**Issue by Lindsayauchin** [concourse/concourse#4781]
As a concourse user capable of pinning/unpinning resources (a `pipeline-operator` or above, by default)
I want to be able to edit the pin comment via an inline form near the top of the page where the currently-pinned version is displayed
So that I can interact with a single widget responsible for all the actions I might take in response to a pinned resource

## Add inline form for editing pin comment

![Screen Shot 2019-11-20 at 5 00 14 PM](https://user-images.githubusercontent.com/27746614/69281964-3f787100-0bb7-11ea-9c8d-cf994fb0d6a6.png)
Note: If the current session is not authorized to edit the pin comment, no icon appears.

For an authorized user, the icon has a pointer cursor and the background darkens on hover (unfortunately the screenshot shows a default cursor):
![Screen Shot 2019-11-20 at 4 58 36 PM](https://user-images.githubusercontent.com/27746614/69281894-1f48b200-0bb7-11ea-9812-077a86415c6b.png)

After clicking the edit button, the background becomes purple and the edit icon is replaced with a save button:
![Screen Shot 2019-11-20 at 4 58 24 PM](https://user-images.githubusercontent.com/27746614/69281879-1657e080-0bb7-11ea-8fe7-d6ebb6fbe5ac.png)

The save button turns almost-black (frame color) on hover:
![Screen Shot 2019-11-20 at 5 00 58 PM](https://user-images.githubusercontent.com/27746614/69282039-5f0f9980-0bb7-11ea-821e-73144b45b23a.png)

Edit Icon: 
[edit-24px.svg.zip](https://github.com/concourse/concourse/files/3860180/edit-24px.svg.zip)

### Notes
* The pin tools' width should always be split 50/50 between the pinned version widget and the comment-editing widget.
    * overflowing resource versions should ellipsize
    * overflowing comment lines should wrap?
* There have been some questions about the html tag/attributes to use for the comment-editing widget. @zoetian and @pivotal-jwinters know more about this.

**Comment by kcmannem** [comment]
Small request:
Instead of having a blank comment box when you want to pin a resource. Can we add faded text in the background for why the comment box exists? Sort of like how twitter labels their tweet compose window with "what's happening", it prompts an intention to comment.

![Screen Shot 2019-11-18 at 3 18 48 PM](https://user-images.githubusercontent.com/9054726/69090373-dce86f00-0a16-11ea-9bff-ddfcc027d06c.png)

We could do something like "Let others know why..."

Thoughts?

**Comment by pivotal-jamie-klassen** [comment]
@kcmannem at present the comment box gets pre-populated with `pinned by <username> at <timestamp>` - maybe we could do some magic where the default comment is there, plus some kind of placeholder too. In the long run, it still might make sense to enrich the `pin_comments` table so that the user and timestamp are independent of the comment text

**Comment by vito** [comment]
Instead of doing an overlay, let's use this issue to split out the editing behavior from this comment:

https://github.com/concourse/concourse/issues/4765#issuecomment-556390003

**Comment by zoetian** [comment]
Quick notes for the next steps:

* comment bar should display the pin author and pin comment instead of the pinned version
* use html5 `contenteditable` instead of `textarea` for pin comment
* click on pin comment text area should enter the "edit" mode
* on hover, the save button has style changes

**Comment by zoetian** [comment]
Next Step:
We're almost done!! Only need to add the `Save button` & adjust some of the awkward stylings around the icon and buttons to make sure these aligned properly on top.
