### ISSUE TITLE
Manually triggered builds should be scheduled once their checks complete

### ISSUE THREAD

**Issue by vito** [concourse/concourse#4789]
Currently, the following sequence (likely) happens:

1. Manually trigger build.
1. Pipeline schedule requested.
1. Checks start.
1. Pipeline schedule completes. Build is not started because checks haven't completed.
1. Checks finish.

At this point, the build just remains 'pending' forever because nothing requests scheduling again after the checks complete.

**Comment by vito** [comment]
A suggestion: now that we have `job_pipes` we could use it in `(db.Job).ScheduleBuild` to know not to schedule a build if it's manually triggered and has `job_pipes` whose resources `last_checked` is before the build's `created_at`.

Very rough query:

```sql
SELECT b.manually_scheduled AND EXISTS (
  SELECT 1
  FROM job_pipes p
  JOIN resources r ON r.id = p.resource_id
  WHERE p.job_id = b.job_id
  AND r.last_checked < b.created_at
)
FROM builds b
WHERE b.id = $1
```

**Comment by clarafu** [comment]
Things that need to be finished:
- [ ] Refactor check to see if all resources have been finished checking for manually triggered builds into a single query
- [ ] Don't request schedule if the algorithm computation needs to be run again, just propagate the value back up so that it doesn't request schedule (scheduler.go, build.go)

**Comment by clarafu** [comment]
Ran into a little roadblock with refactoring the check to see if all resource have finished checking for manually triggered builds. The query will need to take into account if the resource is pinned, and the config pinned version cannot be determined within a sql query. https://github.com/concourse/concourse/blob/0f986f5a298b43a9fdc133b68ff9b7f30aa28acd/atc/scheduler/build.go#L30

Going to punt on this for now and probably place it into the db optimization project so that we can reevaluate it later.

**Comment by clarafu** [comment]
I looked at refactoring code for algorithm computation resulting in the job needing to be scheduled again. The current way it tells the scheduler to run again is by explicitly running requesting schedule, while the other methods in the scheduler does it by not updating the last scheduled value. In order to have it be consistent with the others, I tried seeing what it would look like if we converted it to not update the last scheduled value rather than requesting schedule.

For the first place we compute the algorithm in 
https://github.com/concourse/concourse/blob/manually-trigger-fix/atc/scheduler/scheduler.go#L34-L39
we can easily have it not update last scheduled by propagating the `runAgain` value back up to the runner.

For the second place we compute the algorithm, which only happens when we manually trigger a build, it is a little more difficult.
https://github.com/concourse/concourse/blob/manually-trigger-fix/atc/scheduler/build.go#L49-L54
Propagating the `hasNextInputs` boolean back up to the runner will involve changing the interface for `BuildInputs` to return back this `hasNextInputs` boolean. This isn't optimal because the interface for `BuildInputs` has no relation to this new boolean.

As an alternative, it might be fine if we keep requesting schedule explicitly for algorithm computation. The `hasNextInputs` boolean is only true when we have successfully found a set of inputs, but also know that there is a possible next set of inputs. But for the other cases in the scheduler where we want it to run again, those are cases where we were not able to find a set of inputs for the build, such as the checks have not finished or max in flight is reached. Keeping that in mind, it might make sense for the algorithm computation to explicitly request schedule because it *did* find a set of build inputs, but we know we can possibly find a second one in the next scheduler tick, so we request schedule on ourselves.
