### ISSUE TITLE
Add volume management for a containerd container

### ISSUE THREAD

**Issue by deniseyu** [concourse/concourse#4890]

**Comment by cirocosta** [comment]
I don't fully recall if this issue was any different from taking bind
mounts from `gdn` spec and converting it into OCI spec :thinking:

As I'm ~100% sure that's the case, I'll close it as that's something we're
already doing during container creation.

And for further improvements w/ regards to leveraging containerd's snapshotter,
we already have https://github.com/concourse/concourse/issues/4363.

thaanks!
