### ISSUE TITLE
Time Resource Invokes twice (second time at a non-specified time)

### ISSUE THREAD

**Issue by DennyHoang** [concourse/concourse#4904]
## Bug Report
We have a time resource that triggers each day 7:21am.
However, occasionally, it triggers multiple times later in the day.

## Steps to Reproduce
![Screen Shot 2019-12-16 at 1 12 29 PM](https://user-images.githubusercontent.com/6331476/70932237-3be5d780-2007-11ea-8405-1e4f00dfba5c.png)
 
![Screen Shot 2019-12-16 at 1 12 07 PM](https://user-images.githubusercontent.com/6331476/70932249-430ce580-2007-11ea-93e3-f653e292b4ec.png)

![Screen Shot 2019-12-16 at 1 12 15 PM](https://user-images.githubusercontent.com/6331476/70932252-44d6a900-2007-11ea-8340-dd3135700e43.png)

![Screen Shot 2019-12-16 at 1 24 10 PM](https://user-images.githubusercontent.com/6331476/70932297-69cb1c00-2007-11ea-88b9-649c3c3a9cfa.png)

A pipeline task is set to trigger from this resource.

## Expected Results

The resource should trigger my task only once during the day.

## Actual Results

Every so often, it just triggers by itself around noon-ish

## Version Info

* Concourse version: v5.6.0
* Deployment type (BOSH/Docker/binary): Bosh
* Infrastructure/IaaS: GCP
* Did this used to work? Yes.

**Comment by pivotal-jwinters** [comment]
possibly related https://github.com/concourse/time-resource/issues/45

**Comment by agurney** [comment]
Considering your pipeline as a whole, are there other resources in play which could have triggered a build? (I see `sec-eng-ci-repo` in one screenshot.) The version history, together with the down arrow in build 98 being gray rather than yellow, make it look like the time resource isn't generating a new version outside the expected window. So I wonder if the builds are happening for another reason, either a different resource or maybe somebody manually triggering.
