### ISSUE TITLE
[Runtime] Implement Garden.Container.Stop() Method with the containerd backend 

### ISSUE THREAD

**Issue by pivotal-bin-ju** [concourse/concourse#4918]
For the larger epic #4877
We use Stop() to send SIGTERM/SIGKILL to the process inside the container. NOTICE: a Stopped container is not a DESTROYED container, file copies are still feasible to or from a stopped container.

TODOs:
- [x] How can we operate a `containerd` garden container? Do we need a reference to the original `containerd` container, and delegate the request to `containerd` container?
- [x] Match the `Stop()` to `containerd` container's operation (<- Task kill and delete)
- [x] Test cases (unit & integration)
- [ ] Think about `Delete` container

**Comment by pivotal-bin-ju** [comment]
when we Stop a `containerd` garden container(garden interface, `containerd`is behind ), we stop and delete the task inside the container.  Since there is no other interface that could delete the task from garden interface, we decide to delete the task.

Any other thoughts?

**Comment by deniseyu** [comment]
There's a bit of duplication between `backend.Destroy(container)` and `container.Stop()` now. We repeat the logic of finding and killing the task, but it's implemented in a slightly more resilient manner in `backend.killTasks`. I think this is duplication that we're unfortunately stuck with because containerd requires tasks to be stopped before deletion can happen, but we should at least choose one implementation and reuse it.

I looked into how Guardian handles this logic today and it turns out they have another layer called `containerizer` that both the backend (`gardener.go`) and the container delegate to: https://github.com/cloudfoundry/guardian/blob/eeaffb15ac326eb33c5c39b214a69c084bab3c10/gardener/gardener.go#L366

Inside the containerizer, `Stop` and `Delete` are separate operations: https://github.com/cloudfoundry/guardian/blob/eeaffb15ac326eb33c5c39b214a69c084bab3c10/rundmc/containerizer.go#L286-L319

We don't need that level of abstraction just yet, and we probably can't get as clean a split because of the containerd task deletion requirement, but we can probably at least reduce some of the duplicated logic and handle task deletion just at the container level.

So the backend's Destroy function, in pseudocode, ignoring error checking: 

```
func (b backend) Destroy(handle string) {
  container := GetContainer(handle)
  container.Stop()
  b.client.Destroy(container)
}
```

and move most of the backend's `killTasks` logic into `container.Stop()`.

**Comment by BinJu** [comment]
Thanks for the comment @deniseyu !
I think so far we have 2 levels of abstraction/implementation of `containerd`, `backend/client`(backend calls `containerd` client) and `container`(which implements the interface `garden.Container` ).
Unlike the code `containerizer`, the code `Delete` is in `container`, while `Destroy` is in the `backend`.

Something that I am not sure is the `task` inside a `container`:
- Can we create a task after a task is killed? Or we have to create a new task in a new container?
- The `Stop` interface which is from garden, what does garden expect the `containerd` container to be when it is `Stoped`? 
My first intuition is to clean the `Task` when we stop the `container`. While `Destroy` which is from `backend/client` is going to delete the container from `client` level, not the container itself (The container can not destroy itself).

I will take sometime to learn more about this.

**Comment by pivotal-bin-ju** [comment]
The PR is [here](https://github.com/concourse/concourse/pull/4921)

**Comment by cirocosta** [comment]
superseded by https://github.com/concourse/concourse/pull/5114

thx!!
