### ISSUE TITLE
USER POLL: manually triggered builds

### ISSUE THREAD

**Issue by pivotal-jwinters** [concourse/concourse#4941]
Hey everyone, 

We'd like your feedback around how you think `manually triggered builds` should behave:

❤️  It should do a check for new versions of each build input, and run with these new versions.

🎉  It should show me what version it already has for each build input, and run with those known versions.

follow up question: how do you use manually triggered builds?

**Comment by pivotal-jwinters** [comment]
For some background:

In concourse, there are two types of builds (manual and auto):

- **manual** builds are created based on user interaction, when you click the `(+)` button in the UI, or run `fly trigger-job`. 

- **auto** builds get created whenever a new input is available for something you have marked as `trigger: true`.

For this poll we are interested in how you think `manual` builds should behave.

**Comment by eedwards-sk** [comment]
I think `+` makes sense to me as "add a new job", which means "run all the checks and surface new versions".

A retry button, on the other hand, to me implies "run this specific job (at existing versions) again"

![](https://image.shutterstock.com/image-vector/icon-reload-button-260nw-491656921.jpg)

Which to me, would be a _new_ UI and CLI flow in concourse.

Thus my ❤️above

**Comment by pivotal-jwinters** [comment]
@eedwards-sk for what it's worth that `rerun` feature is already being implemented for concourse `6.0`.

What about the case where a job doesn't have any `trigger: true` inputs. I would consider that to be a manual job. What would you want the behaviour to be when clicking the `(+)`?

**Comment by eedwards-sk** [comment]
> What about the case where a job doesn't have any trigger: true inputs. I would consider that to be a manual job. What would you want the behaviour to be when clicking the (+)?

I would be very surprised if the behavior suddenly changed from the existing behavior, so I would learn towards the existing behavior, which is to run checks and then use the latest versions available.

**Comment by pivotal-jwinters** [comment]
@eedwards-sk sorry I didn't mean to indicate that the behaviour would be different for that specific case. I only bring it up because `rerunning` and `manual jobs` are fairly common use cases for manual triggering.

**Comment by agurney** [comment]
I think ❤️because I imagine that commonly, people trigger builds when they want to "just do the thing", implicitly with the latest available version of whatever. I can always fiddle with pins and whatnot if I want other versions, or use the rerun flow once that exists.

But if triggering worked like 🎉, then in order to build with the latest version of everything, I'd have to check all those resources first. (If they all have short check intervals then it may be OK. But if I'm triggering because I want to build against the state of something which I _know_ I just changed externally, I may outpace the timer quite often.) So I would be clicking around in the UI for a bit, or forget to do so and accidentally recreate an older build.

**Comment by odormond** [comment]
:heart: for me too. We rely on the resource check being run for manually triggered pipeline. I would even add that for pipeline that can only be started by a manual intervention, we would appreciate that no resource check be run until the manual trigger as they are basically useless and just waste resources.

**Comment by kmdouglass** [comment]
I second @agurney 's opinion that people want the CI to "just do the thing." I frequently see our developers get confused by the concept of resource versions; in almost case they want the most recent version to be built, and the first option (:heart:) supports this.

If the second case (:tada:) were implemented I suspect that it would create quite a bit of confusion.

**Comment by ari-becker** [comment]
Agree with @eedwards-sk that a `rerun` UI workflow is needed. Oftentimes I know that there aren't any new versions of resources, and I'm re-running because of flakiness etc. In such a case I do desire to avoid re-checking every single resource, as re-checking every resource eats up time and provides me no benefit.

With that said, the current behavior is safer, and safe defaults are a good thing.
