### ISSUE TITLE
Path template support for Vault credential manager

### ISSUE THREAD

**Issue by agurney** [concourse/concourse#4965]
## What challenge are you facing?

The Vault integration asks operators to configure a particular path where secrets will live. By default, this is `/concourse`, so that the credential manager will look for team secrets under `/concourse/myteam`, and pipeline secrets under `/concourse/myteam/mypipeline`. Concourse itself will have read access to the whole hierarchy, and probably each team has more restrictive access control in place for their namespaces.

We have a use case for connecting to an existing Vault instance which is used for a variety of secrets (not just Concourse-facing ones). Team members want to separate their CI-related secrets from other data, so that they can exercise control over which values are accessible from a Concourse pipeline. Equally, Concourse itself should not have unrestricted access to the whole store. The ideal scheme would be for each team to use the following:

* `/secret/myteam/ci/ `- team secrets for Concourse
* `/secret/myteam/ci/mypipeline/` - pipeline secrets for Concourse
* `/secret/myteam/foo/bar/` - some other existing secrets, not for Concourse

Then the policy in Vault would be for Concourse to be able to read anything from `/secret/+/ci/*` (using Vault policy notation from https://www.vaultproject.io/docs/concepts/policies.html), but nothing else. Individual team members would continue to have fine-grained policies referring to particular paths within their spaces, as needed.

Unfortunately, the credential manager configuration on the Concourse side only supports a fixed path prefix. Some of the other credential managers support a template, specifically using the Go `text/template` library - for example, the SSM one allows configuring a template for team secrets, defaulting to `/concourse/{{.Team}}/{{.Secret}}`. If the Vault manager did the same, we could configure it to use `/secret/{{.Team}}/ci/{{.Secret}}`, and likewise for pipeline secrets, to get the desired setup.

While we could have a parallel Concourse hierarchy (most secrets under `/secret/myteam`, Concourse-facing ones under `/concourse/myteam`, etc.), this would be quite inconvenient for management of the secret values and associated policy. Some stuff would be duplicated between the trees, and it would be more error-prone to keep Vault policy in sync. Another idea is to give Concourse a prefix of `/secret`, but use policy to limit its actual access to whatever each team considers to be a "CI secret". But this sounds really awful to manage and reason about.

## What would make this better?

I suggest that the Vault manager could grow two new options, for team and pipeline secret templates, by analogy with the other credential managers that support templates. For compatibility, the [PathPrefix](https://github.com/concourse/concourse/blob/master/atc/creds/vault/manager.go#L19) option should be retained, and setting `CONCOURSE_VAULT_PATH_PREFIX=/foo` would be implemented internally by choosing `/foo/{{.Team}}/{{.Secret}}` as the team template, and `/foo/{{.Team}}/{{.Pipeline}}/{{.Secret}}` as the pipeline template. (But it would be an error to try to set the path prefix at the same time as setting the explicit templates.)

I think SharedPath should just be the same since it's a static string in any case.

Behind the scenes, there is [current logic](https://github.com/concourse/concourse/blob/master/atc/creds/vault/vault.go#L27) to smash the various strings together with `/` to end up with a list of lookup paths. That would need to change to instantiate templates instead. There is a refactoring opportunity as well, where the credential managers right now either use the shared `creds.NewSecretLookupWithPrefix` (Vault, k8s, CredHub) or duplicate template-instantiation logic (SSM, Secrets Manager) - I could imagine having a shared `creds.NewSecretLookupFromTemplate` or whatever, instead.

## Are you interested in implementing this yourself?

Yes 😃

**Comment by vito** [comment]
Yay! This is the exact kind of feedback I was hoping to hear from someone using Vault in this way.

Here's why: we're introducing a new feature called `var_sources` (https://github.com/concourse/rfcs/pull/39, #4600) which allows pipelines to configure their own credential managers. With credential managers configured at a pipeline level, you can just your own auth and use proper Vault ACLs. So we don't have to rely on our hardcoded path lookup schemes to keep team's secrets from each other.

So far, `vault` is supported, but it currently has the same path lookup behavior as before - except you can also just reference a full path.

I think we can maybe just eliminate the path prefix, shared path, and default lookup paths for the `var_sources` usage, and instead allow users to just configure a list of path templates, pretty much as you said. If you're interested in doing that I would suggest adding a `lookup_paths`(?) field to [`VaultManager`](https://github.com/concourse/concourse/blob/6cd5e08cb268d87860457f1e07e81f358319071b/atc/creds/vault/manager.go#L16) and changing [`NewSecretLookupPaths`](https://github.com/concourse/concourse/blob/6cd5e08cb268d87860457f1e07e81f358319071b/atc/creds/vault/vault.go#L27) to respect it.

I'm thinking we can maintain support for `PathPrefix` and `SharedPath` in the old-style "global credential manager" use case, and only respect this `LookupPaths` config in the `var_sources` use case. (I guess both could cases respect `LookupPaths`, too.)

Does that make sense? 😅 I suspect it might not since this is kind of confusing to explain. Let me know if you have questions.

**Comment by agurney** [comment]
This does make sense (and I'm excited for `var_sources`). I made a start on pulling out the template logic to a common place, and then on top of that changing the vault cred manager to take team and pipeline template options, which is the pattern used in the other three credential managers that use templates.

Doing a generic `LookupPaths` is basically the same plumbing but more general, and that would automatically work for both global and pipeline-local manager instances. I like it for `var_sources` specifically since I can set up a source for some pool of shared secrets, which doesn't have an internal "teams" structure, but maybe does bring together a bunch of different paths.

I'll have a whack at supporting an arbitrary collection of path lookup templates, and trust that you have your eyes on the larger future plans. In particular, I feel like our users will eventually want to differentiate sets of vars by environment (dev/staging/prod, or different datacenter locations) using instanced pipelines as in [your RFC example](https://github.com/concourse/rfcs/pull/29/files#diff-da812354f1f76fc2fa3d9e34ebe7977aR137). Something like having a var_source where the lookup path is itself a parameter at set-pipeline time, but maybe there are other better ways to express the idea. In any case, I feel like something of this kind does emerge from the roadmap, even if the details are a bit murky to me right now, and I'm happy as long as this issue is broadly in line with the way things are going in the big picture.

**Comment by agurney** [comment]
I'd still like this to be live. I guess attention has been diverted by other 6.x things.
