### ISSUE TITLE
Cannot login to concourse via fly with username & password (401 error)

### ISSUE THREAD

**Issue by AutomationSpecialists-Halifax** [concourse/concourse#5027]
## Bug Report

> I'm getting a 401 error when attempting to do a fly login when providing credentials. I am currently using fly version 5.7.0

## Steps to Reproduce

> FLY login -t targetname -c "https://URL" --insecure -n "teamname " "--username=xxxx" "--password=xxxx"

## Expected Results
> Login Successfully

## Actual Results

> (what actually happened?)
show blow in cli:
logging in to team 'xxxxx'

error: oauth2: cannot fetch token: 401 Unauthorized
Response:

(I can login though web so it should not be caused by a bad username / password (LDAP) )

**Comment by xtremerui** [comment]
When you logging throught web, were you authenticated by `LDAP` (you go to LDAP auth page and input username1/password1) or `Username/Password` (you stay in concourse web ui and input username2/password2)?

In you case, it only works when you have created local user with username2/password2 durying concourse deployment, refer to [Local User Auth](https://concourse-ci.org/local-auth.html). 

If you tried to use username1/password1 with fly login, it will fail since the credentials are only known by LDAP as auth provider, not concourse.

**Comment by AutomationSpecialists-Halifax** [comment]
@xtremerui  Thanks Rui. I was trying to authenticate by LDAP. 

I found something
https://github.com/concourse/concourse/releases/tag/v5.8.0
https://github.com/vito/rfcs/blob/set-pipeline-step/031-set-pipeline-step/proposal.md

Is there a workround in new version of concourse?
