### ISSUE TITLE
Spike on infinite scroll approach to dashboard

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5031]
The goal of this is twofold:

1. Speed up the initial page load so we don't render all of the pipelines at once
1. Speed up scrolling and overall performance thereafter

**Comment by matthewpereira** [comment]
Reading:
https://developers.google.com/web/updates/2016/07/infinite-scroller

The idea here is limiting the number of dom elements and reusing them rather than just loading more and more as you would in a traditional lazyload strategy, an infinite scroll strategy.

![infinitescroll](https://user-images.githubusercontent.com/6372810/72753772-d18afe80-3b93-11ea-8751-77bdc4d42d77.gif)

**Comment by aoldershaw** [comment]
Our first approach was fairly easy to implement, but didn't significantly improve the overall lagginess when viewing a dashboard with 1000 pipelines.

We started experimenting with a true infinite scroll today and hit a snag around synchronizing the scroll event, the DOM updating and getting the browser viewport. We were trying to have a variable-height runway, and this seems to have been the cause of our problems.

Tomorrow we will try again, instead using a fixed-height container ("sentinel") and absolutely positioned pipeline cards.

**Comment by pivotal-jamie-klassen** [comment]
padding on "no pipelines set" card seems to be gone
