### ISSUE TITLE
Provide metric for tasks queue when using limit-active-tasks placement strategy

### ISSUE THREAD

**Issue by tenjaa** [concourse/concourse#5057]
## What challenge are you facing?

We switched to the limit-active-tasks placement strategy and so far it solved a lot of our problems. We want to improve now by scaling our workers depending on the size of the task queue.
We are running our Concourse in a Kubernetes environment.

## What would make this better?

It would improve the scaling of workers.

## Are you interested in implementing this yourself?

Sure :)
We already saw that the first proposed implementation had this metric exported: https://github.com/concourse/concourse/pull/4612

**Comment by pivotal-jamie-klassen** [comment]
Rather than implementing a full queue (like concurrency-safe FIFO guarantee or any kind of priority - which does not currently exist, for the record!) I suspect it would be enough for you to emit a metric whenever the "no workers available, please wait" event happens, which seems to be around [this block of code](https://github.com/concourse/concourse/blob/master/atc/worker/client.go#L439-L455). I can imagine this being a strong enough heuristic to say "my workers are getting busy".

Then I'm thinking you could autoscale if this event happens too often in a fixed time window?

Frankly I'm not sharp when it comes to k8s autoscaling, so I'd need a sanity check on this assertion. Am I making sense? off-base?

**Comment by tenjaa** [comment]
Oh I only looked at the linked proposed implementation and assumed the final one was more or less the same and it was just forgotten to expose the metric.

In general it should be possible to just build a custom metric based on the logs.
Using heuristics we could probably say "three logs in the last minute => three jobs in the queue".
But the FAQ advise against it: https://prometheus.io/docs/introduction/faq/#how-to-feed-logs-into-prometheus

What do you think about not having a queue but just a counter?
Maybe even the amount of currently active tasks should be enough. If we just substract the amount of workers (which is already known) we also have the amount of unscheduled tasks.

**Comment by tenjaa** [comment]
Hey @pivotal-jamie-klassen do you have any feedback about the counter idea?
Would it be fine that we'd propose a pullrequest for it?

**Comment by pivotal-jamie-klassen** [comment]
@tenjaa seems fair to me. Especially if you experiment with using that metric in your own environment! I guess you'd probably emit a counter per worker.
