### ISSUE TITLE
Serve CORS headers during fly login

### ISSUE THREAD

**Issue by ConnorJC3** [concourse/concourse#5062]
## What challenge are you facing?

When Concourse is served over any host other than 127.0.0.1 (as I suspect most/all installations are) and you attempt to `fly login` with a non-local auth provider such as OIDC Concourse fails to send the token back to fly because of a cross-origin error.

## What would make this better?

`fly login` should serve CORS headers to allow Concourse to send the token.

## Are you interested in implementing this yourself?

I don't have time to dig into the `fly` source and figure out right now, but I may return to it in the future if nobody else gets around to it as I would like to have this and it doesn't sound that hard.

**Comment by pivotal-jamie-klassen** [comment]
@ConnorJC3 can you give a specific example, say, with OIDC? And which browser? I regularly use fly to log into https://ci.concourse-ci.org via GitHub auth and my browser successfully sends the token to fly. To be super explicit, in the following diagram
```
local fly <---> browser viewing Concourse <---> browser viewing ID provider login page
```
it sounds like you're getting an error between fly and Concourse. Is that correct? or is the redirect from your ID provider actually breaking?

**Comment by ConnorJC3** [comment]
I'm using OIDC (specifically with a keystone instance). Logging into the concourse website works fine. Using `fly login` clicking the link brings up a page that says:
> login successful!
> however, your token could not be sent to fly.

Meanwhile, in my browser console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:39977/?token=Bearer%20eyJh...z8. (Reason: CORS request did not succeed).
```

The page allows me to manually copy a token and paste that into `fly`, which works.

**Comment by pivotal-jamie-klassen** [comment]
I have tried to reproduce this with Firefox 72.0.2 against https://ci.concourse-ci.org and been unable... 

@ConnorJC3 is there any chance there's some confounding factor going on here? Searching around and trying to guess at the conditions under which this could be reproduced, I heard some folks mention untrusted SSL certificates and privacy-related browser extensions. For the record, I assume `ci.mydomain.com` being accessed via HTTPS in your case?

(from https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed, I can definitely imagine we'd be falling in the

> Trying to access an http resource from a page with an https origin will also cause this error.

case... in fact, I'm a bit confused as to why I wouldn't be seeing the error...)

While playing around with this, I was able to reproduce the console error by visiting a page like `https://ci.concourse-ci.org/fly_success?fly_port=<bogus fly port>`, which is a bit odd. I guess on Firefox XHR maybe makes some initial HTTP OPTIONS request or something, and that fails because there's no token callback server listening at the bogus port. Another dumb question - but any chance you are running `fly login` on a different host (like some server you're SSHed into) than your firefox?

**Comment by ConnorJC3** [comment]
Ah, I've figured it out. I was using a browser extension (uMatrix) to block mixed content on webpages, and it was blocking the request to `http://localhost` because it is HTTP. I guess I have a different bug report/feature request to make. Sorry about the bogus report.
