### ISSUE TITLE
[UX] Build Output Markdown

### ISSUE THREAD

**Issue by kcmannem** [concourse/concourse#5074]
A few other CI tools give you the ability to stylize build output by specifying hints in your stdout/stderr stream.
For instance, if my script does 
```
echo "bold:hello"
```
The stdout stream will include a line with `bold:hello` but concourse could parse for `bold:` tags and render it differently compared to regular text.
This syntax could be extended to support inline images or other popular features like log folding.
In buildkite, you can do something like this:
```
echo "--- A section of the build"
produce_garbage_logs.sh
echo "+++ end of folded section"
```

This is obviously not supportable by the fly cli, however the cli could sanitize the tags and provide clean log output.

cc @Lindsayauchin

**Comment by matthewpereira** [comment]
@kcmannem instead of just stripping the tags for the CLI, maybe we could instead convert the tags to [ANSI Escape Codes](https://www.wikiwand.com/en/ANSI_escape_code#/Colors) to colorize and bold log output from `fly`. 🤔 

There are packages available for GO available (eg, https://github.com/fatih/color), or we might be able to roll our own.

**Comment by kcmannem** [comment]
@matthewpereira good suggestion. I'll look into that.

@pivotal-jamie-klassen I was looking to pick this up. Any concerns? It looks like everything isolated in the `viewLogs` `StepTree` module.

**Comment by pivotal-jamie-klassen** [comment]
@kcmannem can we get a bit more specific? I think you were speaking in general terms so as to invite further discussion, so I'll bite.

We seem to be talking about a few different things here:
* a user-friendly syntax for defining styles (i.e. bold) in log output
* inline links in build logs
* a syntax (and supporting front-end code) for specifying folds in log output
* inline images in build logs

### styles and links

The issue title mentions Markdown, but in your examples you mention  a syntax like `bold:` (I think this was just to illustrate the idea of a low-markup way of specifying document structure in your build logs, though?). In a similar vein to @matthewpereira's comment, you can actually already do basic styles in a fly-/web-portable way by using ANSI escape codes. For example, `\u001b[1m` sets the text output to be bold.

I definitely admit the developer experience of using raw escape codes is horrible. If you're looking for an easier way for folks to do that, it sounds a bit more like a job for a terminal-output-focused library in your language of choice?

As for inline links I'll mention the ANSI answer as well, because I notice myself thinking standards are a Good Thing, I guess: #4318

I hope I'm not missing the point here going on and on about "ANSI already supports what you want" when maybe you're trying to say "ANSI sucks and let's make something better" - feel free to call me out on that.

### folds

You seem to be alluding to the principles outlined in https://buildkite.com/docs/pipelines/managing-log-output#collapsing-output

I'm gonna give a bunch of reasons why we shouldn't do this, just to get them out of the way.

Once upon a time, a core principle of Concourse was that switching between it and other CI solutions should be minimum-cost - there have been some [ideological debates](https://github.com/concourse/concourse/issues/2105) about creating reasons for folks to couple their build processes to Concourse specifically. Anything outside existing standards kinda represents a risk in this sense. Of course there's no ANSI standard for log folding - but honestly maybe there should be! Part of me also wants to push back on this because I feel guilty every time I work on the build page doing anything other than making it faster overall.

Ok, I feel better now.

I'm sure we could discuss a bit about the ideal syntax for establishing folds, and the wacky edge cases (how does it scale? should some pre-processing be done on the backend, like a `start-`/`end-fold` build event? how do we handle unmatched fold markers? nested folds?) - you seem to have put in a vote for the syntax that buildkite uses, and, if we go down this route, there's something to be said for providing users with something familiar. I'm probably biased as a pointy-headed vim user (and the Concourse UI is prone to vim-isms anyway), but the first syntax that came to my mind was delimiting folds using the default values for [`foldmarker`](http://vimdoc.sourceforge.net/htmldoc/options.html#'foldmarker') which are `{{{` and `}}}`.

### inline images

I read https://buildkite.com/docs/pipelines/links-and-images-in-log-output, and I'm more interested in the 'Inlining Build Artifact Images' idea than I am in linking to external images (I dunno, maybe the Jake the Dog example just seems hokey to me :P). I guess it could be pretty cool to have stuff like code-coverage or benchmark graphs directly in the output, like an iPython notebook type thing.

I think doing this is an interesting engineering challenge because we'd need to store, serve and evict those images appropriately: my first instinct would be to try to reuse something from the `artifactserver`, but this whole idea doesn't fit very neatly into our existing binary-data-storing mechanisms - for example, GC/storage management would be pretty different for these types of artifacts.

However, this definitely makes Concourse more stateful, and probably the Concourse way would be to just upload your images to an external system, like with a resource. Hmmm, maybe it ends up making sense to let people link to external images, even though that has it's own security/networking concerns. It's cans of worms all the way down!

**Comment by aoldershaw** [comment]
@pivotal-jamie-klassen a small note on inline images: perhaps an easier (and less stateful) approach to this would be to store the images as base64 encoded directly in the logs. Not sure what kind of implications this might have, though, particularly if the images are large.

**Comment by pivotal-jamie-klassen** [comment]
@aoldershaw smart. I'd rather incur the well-defined cost of storing base64 in the DB, transmitting it over the wire and rendering it client-side than either of the (potential) worlds of hurt I identified above.

**Comment by kcmannem** [comment]
@pivotal-jamie-klassen few thoughts I had on the different ideas pitched.

For bold/links: Since this is already supported by asni codes Id rather not introduce a concourse way to do it unless it was a big ask. I do think we should be greping for links and making them clickable. Its a subtle feature that makes life a bit more convenient.

For Folds:

I've actually never seen that discussion before. Thanks for linking that. I def don't want to go into a scenario where its against the products goals. I will say that seeing a syntactic sugar like `>>>` isn't a strong signal that your running in a concourse env. The value of the feature would be high imo since you could collapse and mark sections of the log like output from `go get` but I'll leave this discussion to you and alex. I do see your point on making the page loading slower. 😞 

For Images:

I don't actually think we should be storing images in our db and all of this should be interpreted and rendered client side. If you specified `img: https://linktosomeimage.com/foo.jpg` I though we could just parse that on the client and do a lazy render as we need it.

**Comment by pivotal-jamie-klassen** [comment]
@kcmannem of all your suggestions the folding one is the most interesting. If it's not a huge time sink, play around with it! I'd be curious to see what you come up with. Who knows? if you maintain the assumption
> everything isolated in the` viewLogs StepTree` module.
I'd be curious to see what you come up with. Frankly I'm still wary of loading images from remote locations, but maybe that's just my Enterprise Readiness talking... @vito

**Comment by kcmannem** [comment]
@pivotal-jamie-klassen I really don't care for the image stuff, as its not a feature I'd use. I was just suggesting it to add a feature we don't have. The log folding seems to be the most beneficial for a user.

I'll see what I learn and come up with on the experiment. Thanks for the help!
