### ISSUE TITLE
concourse worker does not support cgroup v2

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#5080]
## Bug Report
v2 linux namespaces are not compatible with concourse worker

## Steps to Reproduce

Use a linux distribution which switched to namespaces v2.Try to run concourse. All containers (checks, tasks, ... ) fail to spawn.
See also:
https://discuss.concourse-ci.org/t/failing-workers-with-cgroup-already-being-mounted/1966/2

## Expected Results

Either be warned about the issue or just work as per usual :)

## Actual Results

Failing checks

## Additional Context

Reproducible with Fedora 31 which changed the default namespaces from v1 to v2 . 

## Version Info

* Concourse version: concourse 5.7.2
* Deployment type (BOSH/Docker/binary): binary/worker, docker/web
* Infrastructure/IaaS: Fedora 31
* Browser (if applicable): firefox
* Did this used to work? before there was a v2 namespace impl, yes

**Comment by cirocosta** [comment]
Hey @drahnr, thanks for reportting!

indeed, that's not something that the workers can deal with at the moment,
buuut, we have an ongoing track to leverage `contanerd` directly
(https://project.concourse-ci.org/projects/MDc6UHJvamVjdDMxNTcxMzE=), which, is
almost there to be able to completely leverage cgroupv2:
https://github.com/containerd/containerd/issues/3726

in the mean time, it seems like we could at least let folks know how to get
around that in systems (like fedora) that are comming with cgroupv2 enabled by
default.

wdyt?

if so, do you have any good sources that we could points folks to to have
cgroupv1 rather than 2? thinking about a possible documentation snippet.

thanks!

**Comment by drahnr** [comment]
Sorry for the long delay:

Viable resources for how to revert v2 back to v1 are:
The full story between v1 / v2 and rationale, but also how to downgrade.
https://www.redhat.com/sysadmin/fedora-31-control-group-v2

A more practical approach:
https://blog.christophersmart.com/2019/12/15/enabling-docker-in-fedora-31-by-reverting-to-cgroups-v1/

I am currently running one worker with `containerd` (unrelated rationale), but frankly I am not really keen on having this everywhere.
It smears configuration accross 3 config + systemd unit files in my case, instead of one concise for the worker, so it makes it more error prone.

**Comment by reynico** [comment]
Hi!
Any updates? I'm tail-catching a small error that may be solved by using Systemd v248 (that includes cgroup v2) but just hit the incompatibility issue on a Concourse worker.

**Comment by taylorsilva** [comment]
No concrete plans around this yet (we aren't feeling this pain ourselves), but should be easier to start supporting with the containerd runtime: https://github.com/containerd/containerd/issues/3726

**Comment by drahnr** [comment]
I moved to `containerd` workers since I filed this issue, so it's not relevant to me anymore.

**Comment by taylorsilva** [comment]
Tested with the latest `concourse/concourse` image using containerd on fedora 33 and had no issues with creating containers. I was able to replicate the error when using the guardian runtime. I'll update the docs with this info and close this issue.

**Comment by xpcone** [comment]
Now also an issue on debian bullseye ....

**Comment by vrga** [comment]
@xpcone https://github.com/concourse/concourse-docker/issues/76 seems to be the eventual fix for this, once they release it.
