### ISSUE TITLE
privileged: true is not taking any effect - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by sskmail14** [concourse/concourse#5112]
Fly Version : 5.7.0

I have tried using the docker image from docker.io
```
platform: linux
image_resource:
  type: docker-image
  source:
     repository: snirnx/docker-maven
     tag: latest
```
While trying to print **docker version**, getting the below error
```
+ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:20:43 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
I tried pulling the image in the local docker, ended up with the same error message, but when I tried running the docker image with **--privileged flag**, things are good.
I tried the same to do it via consoure via tasks
```
  - task: maven-build
    file: pr/ci/tasks/maven-build.yml
    privileged: true
```
Still the issue remains the same 
Any suggestion to make this work?

**Comment by pivotal-jamie-klassen** [comment]
Under the hood, Concourse doesn't actually use Docker to run containers, it uses https://github.com/cloudfoundry/guardian. So it's typical to see some differences in behaviour between `docker run` and `fly execute` with similar parameters. I don't know the specifics of your image and how it works properly with Docker (does it mount the host's Docker socket in the container? Run Docker as a systemd service? Etc) and I don't really want to commit to figuring this out on your behalf because it's a pretty big topic :grimacing:. However I can link you to the script that is used to run Docker in the tasks for testing Concourse itself: https://github.com/concourse/ci/blob/master/tasks/scripts/docker-helpers.sh.

Fair warning: if you're not familiar with the Linux kernel mechanisms underlying container technology, it can be a bit intimidating, but I encourage you to explore!

**Comment by sskmail14** [comment]
Thanks @pivotal-jamie-klassen 

My Intention is to build the docker images and push it to docker hub with the maven plugin(A maven project basically).
So basically maven is creating a docker image and pushing it to hub. So I has to have below things in the same image

1. Docker
2. Maven + JDK
3. Git

I had all these three in `snirnx/docker-maven`, Since the `privileged: true` flag is not taking any effect in concourse is stopping.

Would there be any possibility to make `privileged: true` work?

**Comment by pivotal-jamie-klassen** [comment]
@sskmail14 I guess I didn't say this outright in my comment above, but from the details you've given, I would have to argue that `privileged: true` _is_ working, but it's giving you a result you didn't expect.

The reason you're getting this unexpected result is that Garden (and thus Concourse) does not run containers in quite the same way as Docker. In particular, I suspect that the ENTRYPOINT of your image is being ignored, and so `dockerd` is not actually starting. I linked you to an example of how to get `dockerd` running inside a Concourse container, hoping it is enough information for you to figure this problem out by yourself.

Again, from the information you've shared here I strongly suspect that this is **not a bug** in Concourse, but an unfortunate surprise for users who are accustomed to running containers in Docker.

I hope that you don't give up and that my links help you figure out how to get your task workng!

**Comment by sskmail14** [comment]
Thanks @pivotal-jamie-klassen , `privilege:true` is working.

Switched to alpine for the building docker([dcind](https://github.com/meAmidos/dcind))

```
platform: linux
image_resource:
  type: docker-image
  source:
    repository: amidos/dcind
run:
  path: bash
  args:
   - -exc
   - |
     source /docker-lib.sh
     start_docker
     docker ps
     echo "docker started !!!!!!"
```

:)
