### ISSUE TITLE
Add back active user tracking

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#5119]
Due to #4950 active user tracking no longer occurs when users login via any login method.

How should we start tracking when users login?
Does this make sense to PR as a feature into dex?

Right now we're thinking we'll PR this as a feature back into dex. We should open an issue in upstream dex first to see if it's something the community would be interested in accepting.

A second idea, with every API request, log the user that made it.
 - side thought: with the new verifier token thingy which makes a call to the db to fetch all teams (could cache this to reduce db calls) we could also track the user when going through this workflow in the code

cc @pivotal-jwinters

**Comment by pivotal-jwinters** [comment]
Quick update: We've decided to go with Option 2.

Making changes to dex at this level could become challenging. We would need to figure out a more generic approach that could be useful to the dex OSS community in general and not just satisfy our own use case.

**Comment by pivotal-jwinters** [comment]
We also discussed a third option which would have forced operators to setup of third party tool to extract this information from concourse (i.e. auditing, metrics, etc). However we decided that this feature needs to be portable across different setups, and as a result, should be a first class feature in concourse.

**Comment by pivotal-jamie-klassen** [comment]
I tried to bring the implementation home on this one and made some surprising discoveries:
* since we upate user activity on every request, this seems to include unauthenticated and system requests, which means `fly active-users` has some unpleasant output with empty cells
* for some reason my browser got stuck in a crazy loop of logging in and getting the turbulence page. I guess it has to do with my cookies? Anyway, if it's a typical occurrence it could be pretty painful for an upgrade, so let's give it a bit more thought. It's possible #4950 is affected as well.

**Comment by pivotal-jwinters** [comment]
> for some reason my browser got stuck in an infinite back-and-forth of logging in and getting the turbulence page. Since I couldn't reproduce it on an incognito browser, I guess it has to do with my cookies? Anyway, if it's a typical occurrence it could be pretty painful for an upgrade, so let's give it a bit more thought. It's possible #4950 is affected as well, but I didn't take the time to check.

That'll happen when you rotate the signing key. The reason it loops is because when you hit the login page your token is still valid (we don't validate the signature, only the expiration) so it thinks you're still logged in. So if the login page thinks you're logged in, and every other page thinks you're not, you get a loop. It's mostly an issue during dev, but we should probably still fix it.

**Comment by pivotal-jwinters** [comment]
```

**Comment by pivotal-jwinters** [comment]
When adding a 30s cache to the GetTeams call on each request we see some improvements:

```
wrk -H "Authorization: bearer $TOKEN" http://localhost:8080/api/v1/pipelines
Running 10s test @ http://localhost:8080/api/v1/pipelines
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    32.99ms   14.12ms 204.61ms   81.68%
    Req/Sec   154.59     23.26   230.00     70.50%
  3088 requests in 10.03s, 121.20MB read
Requests/sec:    307.98
Transfer/sec:     12.09MB
```

**Comment by pivotal-jwinters** [comment]
The next thing to try would be buffering user info from each request and batch writing the result to the db.

**Comment by pivotal-jamie-klassen** [comment]
> Did some simple benchmarking with 100 teams, each having 5 pipelines

Derailing with some wild thoughts:
I'm assuming you're just checking out the branch and doing a `docker-compose up --build`? How does load-balancing play into the equation (assuming your caches are in-memory)? It might be worth having a `hack/override` for increasing the `replicas:` on the web service and putting in an HAProxy or something similar so that we can get a local simulation of running web nodes at scale... maybe it's not a big deal since max connections for postgres out of the box is 100 which (based on the default max pool sizes on the web node) means you can only meaningfully have 2 web nodes?
