### ISSUE TITLE
Finalize Concourse Backup and Restore user guide

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5130]
https://github.com/pivotal/concourse-ops/issues/136

**Comment by matthewpereira** [comment]
This might be almost complete at this point - I know @taylorsilva valiantly tackled a ton of documentation concerns in December. If someone could spend an hour running through the guide in the PR as it is now in order to confirm that the step-by-step process works, we could merge it and move this to 'Done'.

I'm happy to pair with whoever ends up working on this if I can be of any help navigating the docs system or proofreading! 🙌

**Comment by jomsie** [comment]
I think this is done. @scottietremendous @matthewpereira
