### ISSUE TITLE
containerd: make container subnet configurable

### ISSUE THREAD

**Issue by cirocosta** [concourse/concourse#5140]
### what challange are you facing

it's imposssible to tweak the subnet that the containers we create use.

despite us having `CNINetworkConfig` configurable, it's currently using a
default config that never gets modified - there are no flags to allow that to
happen (despite an option - `WithCNINetworkConfig` - existing)

https://github.com/concourse/concourse/blob/54991b2f1f17bd7d229a3ebbe6d6c16f3ff495a3/worker/backend/cni_network.go#L37-L41
https://github.com/concourse/concourse/blob/54991b2f1f17bd7d229a3ebbe6d6c16f3ff495a3/worker/backend/cni_network.go#L55-L84

### what would make this better

have a way of letting an operator configure the parameters used for setting up
the CNI network.

**Comment by vito** [comment]
For posterity, the current config for this is...:

```
- name: CONCOURSE_GARDEN_NETWORK_POOL
  value: "10.254.0.0/16"
```

Acceptance: I should be able to `fly intercept` into a build container and see that it's using an IP within the configured address space. (And is able to reach the internet still.)

**Comment by xtremerui** [comment]
@vito should the acceptance running cmd to be `concourse worker --garden-use-containerd --garden-network-pool 10.81.0.0/1`?

 I assume the goal of issue is allowing network pool configuration when using containerd as garden backend since `CONCOURSE_GARDEN_NETWORK_POOL ` already covers non-containerd case.

**Comment by vito** [comment]
@xtremerui we don't currently have a flag for it, so if we're adding one I don't want it to have Garden on the name. I think we talked about having the command fail if we detect `CONCOURSE_GARDEN_*` env vars being set with containerd enabled.

**Comment by xtremerui** [comment]
Thx @vito! So `--container-network-pool` does't depend on backend library but should work for any case. Does that mean after this issue is done, we should update bosh-release to remove CONCOURSE_GARDEN_NETWORK_POOL and add CONCOURSE_CONTAINER_NETWORK_POOL?

@cirocosta I don't see anywhere in the code that does what @vito mentioned. Is it tracked by an issue anywhere?
> command fail if we detect CONCOURSE_GARDEN_* env vars being set with containerd enabled

**Comment by cirocosta** [comment]
@xtremerui I think the closest one to that would be https://github.com/concourse/concourse/issues/5407 (is that right, @muntac ? not sure if there were any other issues created related to it 🤔 )

might be worth adding the details around failing when detecting `use-containerd` (I totally forgot about it when going for https://github.com/concourse/concourse/pull/5445 - would be good to have a PR to update the flag there)

**Comment by muntac** [comment]
@cirocosta Yup #5407 has a point about preventing use of `containerd` specific flags, and `guardian` specific flags simultaneously.

@xtremerui `--container-network-pool` should only work for `containerd` as we don't want to change the CLI flag usage for `guardian` anytime soon.
