### ISSUE TITLE
Switch all of our deployments to Let's Encrypt or other auto rotation

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5154]
We have a wildcard cert - `*.concourse-ci.org` - which expires next month. Instead of renewing it let's see if we can switch everything to Let's Encrypt or otherwise automate its renewal and propagation.

* ci.concourse-ci.org - this can just use Let's Encrypt, since Concourse supports it
* metrics-hush-house.concourse-ci.org - idk lol check if Grafana supports Let's Encrypt?
* project.concourse-ci.org - ask @vito; config lives in https://github.com/concourse/prod/tree/master/cadet - there might be a way to have GKE do cert stuff
* hush-house.pivotal.io - this is a different cert, but while we're in the area let's check on this too
* others?

When in doubt, consult our [Deployments page](https://concourse.github.io/boarding-pass/deployments.html) and consider opening issues for questions you had that weren't answered here.

**Comment by cirocosta** [comment]
`hush-house.pivotal.io`:

<img width="559" alt="Screen Shot 2020-02-10 at 2 20 15 PM" src="https://user-images.githubusercontent.com/3574444/74182148-82733f00-4c10-11ea-8f76-20bd86909968.png">

**Comment by cirocosta** [comment]
grafana's configuration (for `metrics-hush-house.concourse-ci.org`) lives here: https://github.com/concourse/hush-house/blob/290f5fdecc0c160147e6fef7c00349c6690f0a56/deployments/with-creds/metrics/values.yaml#L122-L142

(with secrets in the corresponding `lastpass` secure note (`hush-house-values-metrics`))

**Comment by YoussB** [comment]
The way dutyfree is configured is as follows, could be helpful for k8s deployed sites:
- Created a [managed certificate object](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) that allows GKE to create and manage a certificate for us (they use let's encrypt btw :grin:)
- might not be needed, but we created an global static ip and added the name to the ingress annotation:
https://github.com/concourse/resource-types-website/blob/03d64e8f8848ff3ddb498af885791cfb56c50d18/dutyfree-chart/values.yaml#L67-L72
- annotated the ingress in order to use this certificate and create a loadbalancer. 
https://github.com/concourse/resource-types-website/blob/03d64e8f8848ff3ddb498af885791cfb56c50d18/dutyfree-chart/templates/ingress.yaml#L17-L20

P.S. this doesn't support http to https redirection at the moment, so we had to just disable http.
this is a feature that is said to be [coming soon](https://issuetracker.google.com/issues/35904733#comment90) on GKE

**Comment by pivotal-jamie-klassen** [comment]
I think we will punt on the `hush-house.pivotal.io` part for now, since we don't actually manage that cert.

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta I'd say we achieved something like a 'consolidated strategy' by using the GKE cert manager, but it's not quite what you described. If you think further refactoring (and using `ingress`) would be useful, I'll ask that you split out a separate issue for that. Thanks!
