### ISSUE TITLE
Cut a new release of baggageclaim

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/concourse#5156]
The new version should be determined based on if the 2 features are going to break anything 
The two changes ( COW volumes fix & zstd lib ) are intended to be transparent

**Comment by cirocosta** [comment]
w/ regards to `cow-cow`, @xtreme-sameer-vohra and I were concerned about someone having volumes mounted with the previous behavior, and then upgrading. It turns out that the upgrade path should not be problematic as the swap here is just in how to pass different paths to `lowerdir`s, where no writes would occur anyway.

e.g.

```
before
	init
		/vol1

	first cow
		lowerdir=/vol1,upperdir=/cow-upper			mp=/cow


	cow cow
		lowerdir=/vol1,/cow-upper,upperdir=/cow-cow-upper 	mp=/cow-cow




after
	init
		/vol1

	first cow
		lowerdir=/vol1,upperdir=/cow-upper			mp=/cow

	cow cow
		lowerdir=/vol1,/cow,upperdir=/cow-cow-upper 		mp=/cow-cow
```

would not imply in any changes to anything other than `lowerdir` (which is read-only anyway).

thus, I'll go forward with making this a patch bump 👍

**Comment by cirocosta** [comment]
https://github.com/concourse/baggageclaim/releases/tag/v1.6.6
