### ISSUE TITLE
`fly execute` should be able to run jobs in addition to tasks

### ISSUE THREAD

**Issue by utako** [concourse/concourse#518]
I'd like the ability to execute a job with inputs so I'm not required to push my changes to those inputs before knowing if they're correctly configured.

**Comment by jtarchie** [comment]
It is easy for a task because it is single unit YAML file. Any proposal for running a job defined in a pipeline?

**Comment by cjcjameson** [comment]
Our teams' pain-point is that compile steps are separate from testing steps. We want to keep this separation so that we expose any test-dependencies on a compile-time environment.

So we were thinking of a new command like `fly execute-many` where we pass multiple task yamls, and define some behavior for using outputs of the first task as inputs to the second.

**Comment by vito** [comment]
Duplicate of https://github.com/concourse/concourse/issues/1346 - keeping the other 'cause there're more words.
