### ISSUE TITLE
Destroying a pipeline can get stuck

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#5287]
## Bug Report

When we tried to destroy a pipeline on our large Concourse deployment, there are times when the query to delete the pipeline in the database gets stuck. We saw two queries that have been running for 2 hours, one of them was the delete pipeline query

https://github.com/concourse/concourse/blob/a7716ae103636cdb15fbcfaca1211fd04d1cd749/atc/db/pipeline.go#L721-L726

and the other was one to delete build events https://github.com/concourse/concourse/blob/1756c865ae837c4141be4c0df98685c5ec7daf0e/atc/db/pipeline.go#L910-L911

We theorized that the two queries might have been deadlocked on each other, but that raises some suspicion because this normally would throw a deadlock error similar to the issue outlined in #3383.

## Expected Results

Deleting a pipeline does not get stuck.

## Actual Results

Deleting the pipeline gets stuck!

## Additional Context

As a result of this, the database CPU spiked to 100% and the API connection pool filled up. Because the API connection pool filled up, users would see slowness in the web UI and workers would stall because it is unable to heartbeat.

## Version Info

* Concourse version: 6.0
* Deployment type (BOSH/Docker/binary):
* Infrastructure/IaaS:
* Browser (if applicable):
* Did this used to work?

**Comment by fftorres** [comment]
We are facing the same issue.

When deleting pipelines that has a huge history for builds (like pipelines that runs jobs every 5 minutes for many months) the following events happen:

- Fly fail after a while with 504 Gateway time-out
- We can see in DB a lot of locks for DELETE pipelines (our request)
- DB CPU starts to go high and keep on it
- Concourse pods starts to crash due health check failures
- Lidar stops to perform

To fix this problem we have to login to PostgreSQL console and kill all locks related to DELETE pipelines

We are using Concourse 6.4 and our PostgreSQL is a RDS instance pretty large

**Comment by clarafu** [comment]
We saw this happen again on our `hush-house` deployment and it caused everything to stop working (no checks were running, no builds, etc). The db CPU was pegged at 100%, plus the connections and memory was maxed.

We ran a query in the database to figure out which queries are currently running

```
SELECT count(*), coalesce(max(age(clock_timestamp(), query_start)), '0 seconds'::interval) as age, regexp_replace(query, '[\s\t\n]+', ' ', 'g') as query
FROM pg_stat_activity 
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%' AND state = 'active'
GROUP BY query 
ORDER BY count(*) desc;
```

We saw that the `DELETE FROM pipelines...` and `DELETE FROM build_events..` queries had both been running for approximately 15 hours, which is the time that everything seemed to start failing. We cancelled the queries using `SELECT pg_cancel_backend(<pid>);` and found the `pid`s to cancel using `SELECT pid FROM pg_stat_activity WHERE state = 'active' AND query ILIKE '%DELETE FROM pipelines%' AND query NOT ILIKE '%SELECT pid%';`.

After cancelling the queries, builds started to run again and checks were being scheduled. The db CPU was still maxed possibly because of the work it needed to catch up on so we will keep an eye it to make sure it goes back down after. 

We thought of two possible theories to fix this bug but they haven't been proofed yet to know if these mitigations are possible implementation wise:
- Have the deleting of the pipeline not cascade delete build events. This would involve removing the cascade delete relationship between a pipeline and it's build events. Deleting of the build events would then be the responsibility of the `build_log_collector`.
- Delete the build events in the same order within both delete pipeline and delete build events queries. This will ensure no deadlocks can occur, but we arn't able to add an `ORDER BY` to a `DELETE` query. In order to get around that, we would need to separate out deleting of the build events when deleting the pipeline into a separate query run in the same transaction. It would look something like `DELETE FROM build_events IN (....)` and then `DELETE FROM pipelines`. The build ids that would be passed into the delete from build events would need to be the same order as the build ids deleted from the `build_log_collector`.

There might be better ways to fix this but these were the initial theories that were thought up.

**Comment by jchesterpivotal** [comment]
I'm confused -- is the `delete from pipelines` cascading to `build_events`?

There are two queries, but one proposed fix was "Have the deleting of the pipeline not cascade delete build events".

**Comment by aoldershaw** [comment]
@jchesterpivotal when a pipeline is deleted, we delete all of its build events in a trigger: https://github.com/concourse/concourse/blob/d0b12f86b6b47320e16a790b2e6b1575f8f6d19d/atc/db/migration/migrations/1530824006_create_pipelines_trigger.up.sql#L21

I believe the problem is that we *also* delete build events in our GC component (e.g. if they're older than `x` days), which is the second query mentioned.

**Comment by aoldershaw** [comment]
I'm thinking that dropping that trigger and just taking care of it in the build log collector makes the most sense - if my understanding of the problem is correct (we're deleting the build events at the same time in two different ways), we might as well just keep it to one place (that's guarded by DB locking).

I'm not sure how your second solution would work exactly, given that the way we delete all pipeline build events is by dropping a table: https://github.com/concourse/concourse/blob/d0b12f86b6b47320e16a790b2e6b1575f8f6d19d/atc/db/migration/migrations/1530824006_create_pipelines_trigger.up.sql#L2-L6

That said, it's also not trivial to have the build log collector detect what pipelines were deleted in an efficient way. We could `LEFT JOIN` from `build_events` to `builds`, but I imagine that could be really slow given the magnitude of both tables - plus, we lose the ability to `DROP` the `pipeline_build_events_x` table, which was introduced for this very case (optimizing deleting pipelines). Another option could be to add a new table, `deleted_pipelines`, that just stores the IDs of the pipelines when they're deleted. The build log collector could then scan from this table each tick, `DROP` the corresponding `pipeline_build_events_x` table(s), and then clear the `deleted_pipelines` table. Feels kind of awkward - not sure if there's a better way to do it.

---

Also, doesn't it seem weird that we aren't getting ShareLock deadlock errors in Postgres? Is it *possible* that we aren't deadlocking and we're just deleting a ton of build events? Seems unlikely given that the query ran for 15 hours, sure, but just putting it out there. It's also possible that the locking when you `DROP` a table (particularly an inherited table like `pipeline_build_events_x`) is different than performing a `DELETE` query - depending on how Postgres deals with this locking, it's possible that approach 2 wouldn't even solve the problem

**Comment by clarafu** [comment]
@aoldershaw Ya I'm not familiar with the locking around `DROP`ing a table vs performing a `DELETE`. From what I know, I think dropping a table tries to acquire an exclusive lock on the entire table rather than if you're doing a `DELETE` which would just grab row level locks. I do think my second suggestion isn't viable because it would require doing a `DELETE` using build ids rather than dropping the table, so it would be removing the benefits that we get from using partitioned tables.

I think it does make sense to go with the first option too! It would be nice to have only one component responsible for gcing the build events, and that can give us more flexibility around the reaping of build events (maybe we can keep around build events for deleted pipelines in the future if the user desires). It would be nice to be able to still `DROP` the `pipeline_build_events_x` tables, adding a new `deleted_pipelines` table would be the only thing I can think of that can allow us to do that 🤔 I do get how it feels a bit awkward to have this extra table just for gcing build events.

Another possibility which I haven't looked too much into is adding a `lock_timeout` on the `DELETE pipeline ..` query. In theory this should stop it from deadlocking but it doesn't really solve the underlying issue.
