### ISSUE TITLE
Launching/Migrating Concourse 6.0 fails with Postgres syntax errors

### ISSUE THREAD

**Issue by tprobinson** [concourse/concourse#5391]
## Bug Report

I'm running Concourse via Docker Compose on a CentOS 7 EC2 instance. Here's my [`docker-compose.yaml`](https://gist.github.com/tprobinson/66eb6cbb4e4a45b8b5022c2a0262a69e).

I was unable to launch Concourse 6.0 with a Postgres 9.5 database, only a clean Postgres 12.2 database worked.

## Steps to Reproduce

* Run the linked Docker Compose document (`docker-compose up -d`)
* Change the `web` service's image version to 6.0
* `docker-compose up -d` again to update services

## Expected Results

Migrations to succeed, and Concourse to launch at version `6.0`

## Actual Results

I get the following errors when going to 6.0 via:
* 5.6 -> 6.0
* 5.6 -> 5.8.1 -> 6.0
* 6.0 with a fresh Postgres 9.5 database

```
db_1   | ERROR:  syntax error at or near "NOT" at character 41
db_1   | STATEMENT:  ALTER TABLE pipelines
db_1   |            ADD COLUMN If NOT EXISTS "last_updated" timestamp with time zone NOT NULL DEFAULT '1970-01-01 00:00:00'
web_1  | {"timestamp":"2020-03-31T00:11:37.295126928Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
db_1   | ERROR:  syntax error at or near "NOT" at character 41
db_1   | STATEMENT:  ALTER TABLE pipelines
db_1   |            ADD COLUMN If NOT EXISTS "last_updated" timestamp with time zone NOT NULL DEFAULT '1970-01-01 00:00:00'
web_1  | {"timestamp":"2020-03-31T00:11:37.338327768Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":74521,"session":"1"}}
web_1  | error: failed to migrate database: 1 error occurred:
web_1  |        * Migration '1583868323_add_pipelines_last_update.up.sql' failed: 2 errors occurred:
web_1  |        * Transaction ALTER TABLE pipelines
web_1  |     ADD COLUMN If NOT EXISTS "last_updated" timestamp with time zone NOT NULL DEFAULT '1970-01-01 00:00:00' failed, rolled back the migration
web_1  |        * pq: syntax error at or near "NOT"
```

If I try with Postgres at version 12.2, I get the following errors when going to 6.0 via:
* 5.6 -> 6.0
* 5.6 -> 5.8.1 -> 6.0

```
web_1  | {"timestamp":"2020-03-31T00:37:00.019293662Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":65339,"session":"1"}}
concourse_web_1 exited with code 1
web_1  | {"timestamp":"2020-03-31T00:37:26.684459134Z","level":"info","source":"atc","message":"atc.cmd.start","data":{"session":"1"}}
db_1   | 2020-03-31 00:37:26.727 UTC [123] ERROR:  there is no unique constraint matching given keys for referenced table "builds"
db_1   | 2020-03-31 00:37:26.727 UTC [123] STATEMENT:  CREATE TABLE build_pipes (
db_1   |            "from_build_id" integer NOT NULL REFERENCES builds (id) ON DELETE CASCADE,
db_1   |            "to_build_id" integer NOT NULL REFERENCES builds (id) ON DELETE CASCADE
db_1   |          )
web_1  | {"timestamp":"2020-03-31T00:37:26.732123926Z","level":"info","source":"atc","message":"atc.cmd.finish","data":{"duration":90902,"session":"1"}}
web_1  | error: failed to migrate database: 1 error occurred:
web_1  |        * Migration '1579713177_create_table_build_pipes.up.sql' failed: 2 errors occurred:
web_1  |        * Transaction CREATE TABLE build_pipes (
web_1  |     "from_build_id" integer NOT NULL REFERENCES builds (id) ON DELETE CASCADE,
web_1  |     "to_build_id" integer NOT NULL REFERENCES builds (id) ON DELETE CASCADE
web_1  |   ) failed, rolled back the migration
web_1  |        * pq: there is no unique constraint matching given keys for referenced table "builds"
web_1  |
```

The only way I've launched 6.0 successfully is with a clean Postgres 12.2 database.

Let me know if there's any more information I can provide or tests I can perform. Thanks!

## Version Info

* Concourse version: 5.6, 5.8.1
* Deployment type (BOSH/Docker/binary): Docker
* Infrastructure/IaaS: EC2

**Comment by cirocosta** [comment]
Hey @tprobinson, thanks for reporting!

indeed, 9.5 seems to be having trouble with the migrations - just reproduced locally tweaking this repo's `docker-compose.yml`:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 9c3bd28a0..6592b0a76 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,7 +2,7 @@ version: '3'
 
 services:
   db:
-    image: postgres
+    image: postgres:9.5
     shm_size: 1gb
     ports:
     - 6543:5432
```

does lead to **web** failing:

```
error: failed to migrate database: 1 error occurred:
        * Migration '1583868323_add_pipelines_last_update.up.sql' failed: 2 errors occurred:
        * Transaction ALTER TABLE pipelines
    ADD COLUMN If NOT EXISTS "last_updated" timestamp with time zone NOT NULL DEFAULT '1970-01-01 00:00:00' failed, rolled back the migration
        * pq: syntax error at or near "NOT"

```

and **db** complaining:

```
ERROR:  syntax error at or near "NOT" at character 41
STATEMENT:  ALTER TABLE pipelines
            ADD COLUMN If NOT EXISTS "last_updated" timestamp with time zone NOT NULL DEFAULT '1970-01-01 00:00:00'
```

I tried verifying if that was the case for 9.6, and it seems like it isn't. 

I was curious if we indeed still said we support 9.5, and yeah, we do:

![Screenshot from 2020-03-31 20-56-13](https://user-images.githubusercontent.com/3574444/78088416-19978000-7392-11ea-9e81-65ee8c693af5.png)

(from https://concourse-ci.org/postgresql-node.html#db-running)

This makes me wonder if we should actually encourage 11+ .. even though we (Concourse) run against 9.6 Google Cloud SQL instances, it seems like the major cloud providers now all support the 11 series:

https://cloud.google.com/sql/docs/postgres/db-versions
https://postgres.docs.pivotal.io/11-1/index.html
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.DBVersions
https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions
https://bosh.io/releases/github.com/cloudfoundry/postgres-release?version=41

**Comment by vito** [comment]
Ack, that's a shame.

It would be nice to continue supporting 9.5 as long as it's still a supported version (by Postgres), so that Concourse can be as portable as possible. It looks like 9.5 is [supported until February 2021](https://www.postgresql.org/support/versioning/), with 9.6 supported until November of that same year. We could consider requiring 10 or newer at some point but I would only do so if there is a justifiable need for certain features in that version.

So I'd say until 9.5 is EOL we should probably be more conscious about testing against it in our pipelines. This might be as simple as explicitly tagging `postgres:9.5` in our testflight job (and maybe in our dev `docker-compose.yml`, though that could be annoying since you'd probably have to use an older client locally).

In this particular case we might be able to just remove the `IF NOT EXISTS` syntax from those migrations; I believe we only do that so the migrations are durable to our own dev environments which have already run older forms of those migrations from previous iterations.

...In fact it looks like things might have gotten a little strange with this migration. There are *two* files for it:

* https://github.com/concourse/concourse/blob/master/atc/db/migration/migrations/1580135204_add_pipelines_last_update.up.sql (without `IF NOT EXISTS`)
* https://github.com/concourse/concourse/blob/master/atc/db/migration/migrations/1583868323_add_pipelines_last_update.up.sql (with `IF NOT EXISTS`)

Should one of these just be removed? (Will that cause problems now that it's been shipped? 🤔)

**Comment by pivotal-jamie-klassen** [comment]
Either migration could be deleted as long as ci and hush-house are up to date - that's the only reason the second migration was introduced. Maybe the bigger issue is getting some testing against postgres 9.5 in our pipeline.

**Comment by xtremerui** [comment]
Since the incompatible syntax exists in https://github.com/concourse/concourse/blob/master/atc/db/migration/migrations/1583868323_add_pipelines_last_update.up.sql
we will remove this migration. 

With Postgres 12.2 and concourse going from 5.6 to 6.0, I couldn't reproduce this error `ERROR:  there is no unique constraint`. Will consider it  irrelated to postgres backward compatibility issue here.

For CI testing, the `testflight` job takes a `postgres-image` resource that is configured to latest as of today. And use that image to bootstrap docker env here.
https://github.com/concourse/ci/blob/ad82246e2c20d8129c4bdab7d32e14ecb1836245/tasks/scripts/with-docker-compose#L10


We could add another `postgres-image` resource that pinned to posrgres 9.5 and feed it to a new job/task that runs testflight against it. In this way we can make sure concourse works with both 9.5 and latest postgres without chaning docker-compose.yml
