### ISSUE TITLE
Implement and backport mitigations for slow `ListAllJobs` endpoint

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5405]
Minimum viable mitigations:

* Backport https://github.com/concourse/concourse/pull/5023 so that the dashboard doesn't "pile on" when the API is slow. (It looks like this diff is large - can we backport a more targeted patch?)
* Introduce a metric for active `ListAllJobs` endpoints so that operators can detect this situation happening.
* Somehow rate limit the endpoint so that 100 (made up number - it should be configurable and opt-in, i.e. no default) active users on a giant dashboard doesn't grind Concourse to a halt. Leaving users waiting at the dashboard is better than everything falling over.
  * API should return a 420 error, web UI should handle it gracefully

For posterity: this endpoint is fixed in v6.0 (see https://github.com/concourse/concourse/issues/5341), but we have folks who can't upgrade to v6.0 for a long time.

**Comment by pivotal-jamie-klassen** [comment]
Potentially it makes sense for this to become an epic with each backported behaviour as its own issue, plus one to ship a patch release.

**Comment by aoldershaw** [comment]
When working on #5466, @jomsie and I realized that it can be pretty easy for malicious users (or even just slow clients such as super admin users) to deny service to all other users based on the approach in #5429.

This is easiest to see with a malicious user - given that we don't have any sort of user-level rate limiting, any user could spawn a large number of concurrent requests to `ListAllJobs`, which could effectively prevent any user from accessing the dashboard. Even in a non-malicious way, though, given that super-admin requests on large clusters can take quite a bit of time, these requests could starve faster clients.

One possible way to remediate this would be to have some sort of server-side request queue. When a request comes in, add them to the queue. Then, the concurrent request limit can become the number of workers that are dequeuing requests from this queue. Rather than giving a 503 status code if the concurrent request limit is exceeded, we can keep the connection alive, and serve the client when they are dequeued. This doesn't prevent getting in a state where all of the concurrent request limit is consumed by super admins, which would bottleneck all other clients, but it does prevent completely denying service in the presence of greedy/malicious clients that hit the endpoint frequently.

**Comment by aoldershaw** [comment]
Another alternative (or additional configuration option) is to provide a user-based rate limit. We could return a 429 on rate limit exceeded, along with a `Retry-After` header. One thing to consider is how to deal with unauthenticated requests - we could have a rate limit for all unauthenticated users, or rate limit by IP.

**Comment by cirocosta** [comment]
Hey folks,

I was doing some testing here, and we can see how in practice the limiting
indeed does what we'd expect - by restricting the number of concurrent inflight
requests, the amount of memory that the `web` node demands stabilizes based on
the number of concurrent requests being served.

**with no concurrency limit**

![chart-before](https://user-images.githubusercontent.com/3574444/80139284-37609b00-8574-11ea-93a8-57d9dc2e67c9.png)

**with concurrency limit of 5 req at a time**

![chart](https://user-images.githubusercontent.com/3574444/80139293-3b8cb880-8574-11ea-9514-447bea769bb7.png)



The experiments above were made with a dataset consisting of 30k jobs, 90k
builds (3 builds per job), each job consisting of 20 tasks. It goes from 1
concurrent request, all the way up to 20, having no concurrency cap in the first
graph, and a cap of 5 concurrent requests in the second.

Naturally, if my machine had a limit of 8GB, it would've OOM killed `web`.

---


To reproduce my results, apply the following patch to get the `/debug/mem`
endpoint in `concourse`:

```diff
diff --git a/atc/atccmd/command.go b/atc/atccmd/command.go
index 1dc3add37..d30f27ca3 100644
--- a/atc/atccmd/command.go
+++ b/atc/atccmd/command.go
@@ -11,6 +11,7 @@ import (
 	_ "net/http/pprof"
 	"net/url"
 	"os"
+	"runtime"
 	"strings"
 	"time"

@@ -391,6 +392,17 @@ func (cmd *RunCommand) Runner(positionalArguments []string) (ifrit.Runner, error
 		logger.RegisterSink(&errorSinkCollector)
 	}

+	http.HandleFunc("/debug/mem", func(w http.ResponseWriter, r *http.Request) {
+		var memStats runtime.MemStats
+		runtime.ReadMemStats(&memStats)
+
+		fmt.Fprintf(w, "%d\n", memStats.HeapAlloc)
+	})
+
 	http.HandleFunc("/debug/connections", func(w http.ResponseWriter, r *http.Request) {
 		for _, stack := range db.GlobalConnectionTracker.Current() {
 			fmt.Fprintln(w, stack)
```

then update `docker-compose.yml` with the dataset I mentioned, and also expose
the debug endpoint (`8079`):

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 400598ee0..97c56be03 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -2,10 +2,11 @@ version: '3'

 services:
   db:
-    image: postgres
+    image: cirocosta/postgres:concourse-data
     ports:
     - 6543:5432
     environment:
+      PGDATA: "/data"
       POSTGRES_DB: concourse
       POSTGRES_USER: dev
       POSTGRES_PASSWORD: dev
@@ -19,6 +20,7 @@ services:
     depends_on: [db]
     ports:
     - 8080:8080
+    - 8079:8079
     environment:
       CONCOURSE_LOG_LEVEL: debug
       CONCOURSE_POSTGRES_HOST: db
@@ -29,24 +31,4 @@ services:
       CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
       CONCOURSE_MAIN_TEAM_LOCAL_USER: test
       CONCOURSE_CLUSTER_NAME: dev
+      CONCOURSE_DEBUG_BIND_IP: 0.0.0.0
```

and then run the following script: https://gist.github.com/cirocosta/58399a95f21c62177932e4c6903a1691
