### ISSUE TITLE
Log Highlight Auto-Scrolling stops working on pages with high amount of log lines

### ISSUE THREAD

**Issue by FabulousCupcake** [concourse/concourse#5454]
## Summary
When opening a link to a specific build with a highlighted log line (e.g. `/teams/<team>/pipelines/<pipeline>/jobs/<job>/builds/<build-num>#L5a1b2c3d4:1234`), sometimes the page does not jump/auto-scroll to the highlighted line.

After a bit of investigation, it seems to be happening only on pages with very high amount of log lines. Jobs with shorter logs either do not have the issue, or only stops auto-scrolling randomly on each refresh.

## Steps to reproduce
1. Open a build page with very high amount of log lines (2000+?)
2. Highlight a line and copy the URL
3. Open the URL in a new tab

## Expected result
Browser screen jumps/auto-scrolls to the highlighted log line.

## Actual result
Browser screen remains at the top.

## Triaging info
* Concourse version: `v6.0.0`
* Browser (if applicable): Firefox 75 @ macOS 10.14.4

## Links & References
- [Discord inital report & discussion](https://discordapp.com/channels/219899946617274369/413770960089382922/700673989328240710)

**Comment by aoldershaw** [comment]
I'm able to reproduce this. @pivotal-jamie-klassen suspected this was an issue with the highlighted log line not being in the first 1000 build events (see https://discordapp.com/channels/219899946617274369/413770960089382922/700690992269099078), though I don't believe this is the cause - the UI will continue to "retry" scrolling to the line for every chunk of build events it receives. This can be confirmed by highlighting a log line that's within the first 1000 build events (one of the earlier lines) - it still won't scroll to this line.

My guess is that it's a timing issue with rendering the log lines. Even after all chunks of events have been received by the UI, when there are many log lines, the browser takes a while to create all of the DOM nodes - and when it comes time to scroll to the log line, it can't find the ID of the element and give up.

**Comment by pivotal-jamie-klassen** [comment]
So maybe instead of retrying on each batch of build events, there should either be a separate timer for the scroll retrying, or it should just immediately retry every time the `getviewportof` attempt fails

**Comment by pivotal-jamie-klassen** [comment]
Or maybe instead of retrying on every batch of build events, it shouldnt even do the first attempt until all the events have been received. Then it could aggressively retry in case the DOM is just taking too long to load.

**Comment by pivotal-jamie-klassen** [comment]
If "aggressively" retrying is too expensive I can imagine doing some kind of circuit-breaker-ey timed limited backoff

**Comment by aoldershaw** [comment]
Though, if we waited for all events to be received, this would break log highlighting for builds that are still running. Not sure how useful it is to jump to a log line while it's running, but still.

Another option is to delegate this stuff to ports. I know ports should generally be as lightweight as possible since we have very minimal (if any) test coverage on them, but to be honest, handling this kind of thing in Elm seems to be a bit painful.

On the first `EventsReceived` message, we could send to a `scrollToId` port, that does something like the following:

```js
app.ports.scrollToId.subscribe(function(id) {
  const interval = setInterval(function() {
    const elem = document.getElementById(elem);
    if (elem == null) {
      return;
    }
    elem.scrollIntoView();
    clearInterval(interval);
  }, 50);
})
```

**Comment by aoldershaw** [comment]
I notice that the example port I provided used to be the implementation - almost verbatim - but was changed here: https://github.com/concourse/concourse/commit/495904da500188d89a9c9e62071d4ac0e3205ed7. The issue this commit was addressing was due to a Javascript bug (not checking if the element existed) in a different port, but I'm guessing the thinking was it would be better to have all of the scrolling behaviour in Elm.

**Comment by pivotal-jamie-klassen** [comment]
@aoldershaw great inference. Suffice to say I am not proud of the [almost-nonexistent](https://github.com/concourse/concourse/pull/3859#issue-278711695) [documentation](https://github.com/concourse/concourse/pull/3859/commits/495904da500188d89a9c9e62071d4ac0e3205ed7) @jomsie and I provided for that decision.

I think you've struck a good compromise in your choice of implementation here.
