### ISSUE TITLE
Pinning a resource to `version: latest` in the resource definition does not work

### ISSUE THREAD

**Issue by andy-paine** [concourse/concourse#5456]
## Summary

Pinning a resource to `version: latest` in the resource definition does not work, only in the `get` step

## Steps to reproduce

Set the following pipeline:
```
resources:
- name: timer
  type: time
  version: latest
  source:
    interval: 30s
jobs:
- name: test
  plan:
  - get: timer
    trigger: true
```

## Expected results
Pipeline sets okay and the latest version of the `timer` resource is used when the `test` job is run

## Actual results
Pipeline config fails validation as `version: latest` is not a valid `map[string]string`

## Additional context
The docs for the resource schema [here](https://concourse-ci.org/resources.html#schema.resource.version) state that:
> This has the same effect as setting [ `get` step **`version`** ](https://concourse-ci.org/jobs.html#schema.step.get-step.version) on every [ `get` step](https://concourse-ci.org/jobs.html#get-step) referencing the resource.

However using `version: latest` only works in the `get:` step and doesn't work in the resource definition.

Looking at the code it seems that the config for the resource uses the `Version` struct
https://github.com/concourse/concourse/blob/5e315c6ccfe2fdb087ecb40a7a5339b5dc31feb5/atc/config.go#L184
and the config for the get step uses the `VersionConfig` struct which supports the `every` and `latest` alternatives.
https://github.com/concourse/concourse/blob/5e315c6ccfe2fdb087ecb40a7a5339b5dc31feb5/atc/config.go#L486

I assume this _isn't_ intended behaviour and the two should be equivalent? Or is it just a docs problem and only specific pinning (e.g. `version: { ref: blah }`) is supported in resource definitions?

**Comment by pivotal-jamie-klassen** [comment]
I guess this is a docs problem - as I understand it, the purpose of the `version:` field on the resource config is strictly for pinning. Indeed it says

> A version to pin the resource to across the pipeline.

in the same spot you linked. Maybe it's worth explicitly saying that that it's equivalent to setting the `get` step version across the pipeline, *except* the `version: every` and `version: latest` options are not valid here.

Stepping back, though, why were you wanting to set `version: latest` at the resource level? What were you expecting to happen otherwise?

**Comment by DanielJonesEB** [comment]
@andy-paine and I have been working on this.

> Stepping back, though, why were you wanting to set version: latest at the resource level? What were you expecting to happen otherwise?

@pivotal-jamie-klassen We use an approach whereby we use identical pipeline definitions in different environments, and promote them through. For each resource that we care about testing, we set the version, e.g. for a resource named `foo`, it would have `version: ((resource_version_foo))`. 

In the 'dev' environment, we set `resource_version_foo` to be `latest`, ensuring that we pick up the latest new versions. These flow through the pipeline, and after integration testing, we write the versions of everything we tested to a vars file using [stopover](https://github.com/EngineerBetter/stopover), and typically upload it to S3.

The 'next' environment's pipeline (e.g. staging) then triggers on the S3 versions file, and the pipeline sets itself, using the versions file as a vars file. This means it is pinned to _only_ the versions that passed the previous pipeline. We can then repeat this process for as many environments as we have, and can do fancy stuff with the pool resource to effect rolling upgrades of prod environments.

We've blogged about the approach a couple of times:

* http://www.engineerbetter.com/blog/continuous-infrastructure-google-cloud/
* http://www.engineerbetter.com/blog/pipeline-promotion/

The advantages of this approach compared to other approaches for promotion include having a snapshot file that declares the version of absolutely everything we care about; instead of pushing files to dev/staging/prod buckets, we avoid a lot of needless I/O; it's also more robust in that it eliminates the chance of someone uploading the wrong asset to the wrong bucket.

Being able set `version: latest` on the resources would make our pipelines _much_ tidier, and would be less error-prone. Instead, we currently have to set them either on _every_ get (to be on the safe side), or on the first get for each resource.

If we were to PR resources supporting `version: latest` (and presumably `every`, for symmetry) would this stand any chance of being merged? (cc @vito)

**Comment by vito** [comment]
That sounds interesting! However if we're going to do that that I think we should make it support `every` too, and carefully consider whether we truly want these fields to always have the same semantics, and whether they remain just as clear/obvious as they did on the `get` step. It seems OK, that's just my gut reaction whenever unifying two concepts like this.

One advantage of putting `version: every` on the resource itself is that pull request resources would no longer have to carefully remind you to set it on each and every `get` step. It would be nice to have another example aside from pull request resources, though, and I would rather just see `version: every` go away entirely once we have spatial operations with the `across` step anyway.

**Comment by DanielJonesEB** [comment]
> However if we're going to do that that I think we should make it support every too

Yep, symmetry is good for UX, and it'll help uphold the principle of least astonishment.

I'll have a chat to the folks at EngineerBetter and see if we can find some time to implement this.

**Comment by clarafu** [comment]
I do have one question about this approach which is if we did the ability to set `version: every` or `version: latest` on the resource config, what if the user adds a different version setting on the get step? Would the version configuration on the get step take precedence? For example, I set `version: every` on the resource config but then set `version: latest` on the get step, which one would I expect to take precedence?

Naturally, I would think that the get step version configuration would always take precedence but the way pinning works makes me question that logic. This is because pinning works where if either the resource config or the get step is pinned to a specific version, that will always take precedence. So if I had a resource pinned to a version on the resource config and have `version: latest` on the get step, it will result in the input being pinned.

Knowing that, I might be leaning more towards having individual resulting behaviour based off of each pair of factors: where the version configuration is set (resource config, get step) and what the version configuration is set to (pinned, every, latest). Might be like a matrix format?

**Comment by andy-paine** [comment]
That's actually exactly how I wrote the tests for this behaviour - as a matrix of resource (`no config`, `latest`, `every`, `pinned`) and get (`no config`, `latest`, `every`, `pinned`). I did it so that pinning > every and get > resource so e.g. a get with every and a resource with pinned would be pinned.

**Comment by andy-paine** [comment]
So the workaround here is to use `~` for the versions in pre-environments. This makes it so that the `version` field is just never set (I guess fly omits any keys for which the value is nil). In pre-environments/test environments this essentially corresponds to `version: latest` and the same pipeline config can be used with a tool like stopover to pin the versions in later environments.

**Comment by andy-paine** [comment]
The workaround above solved this for our use case of `version: latest`. As we got deeper into this issue, it became clear that `version: every` may not be right for a resource itself. Given the v10 work with `across` etc. I'm going to close this until a need for `version: every` becomes more apparent.

**Comment by vito** [comment]
@andy-paine Awesome, thanks for following up! Excited to see how this all pans out.
