### ISSUE TITLE
Bump `git` in the Git resource

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5468]
We need to bump the `git` version in order to address [`CVE-2020-5260`](https://github.com/git/git/security/advisories/GHSA-qm7j-c969-7j4q).

It would also be worth taking some time to estimate the user impact of this exploit so we can provide a meaningful release note.

**Comment by vito** [comment]
We don't actually pin to a particular version; we just bring in whatever the packaging tools give. We might be able to just build a new image and ship it, but since we're tracking `git` CVEs we might want to build out the pipeline a bit and more precisely control the version. 🤔

**Comment by YoussB** [comment]
- For the sake of the CVE, since we have recently merged some PRs into the git resource, the latest builds already contain the latest patched version:
 - https://ci.concourse-ci.org/teams/main/pipelines/git/jobs/build-alpine/builds/8#L5e874c52:44
 - https://ci.concourse-ci.org/teams/main/pipelines/git/jobs/build-ubuntu/builds/8#L5e874c59:785

Step to resolve:
- [ ] The first step will be to release the resource
- [ ] Determine the effect on Concourse, and release a patch depending on the severity.
- [ ] Per Alex's comment, maybe we can track [Git's Github repo releases](https://github.com/git/git/releases) and build on a new release.
  - That will work fine with the Ubuntu, as we are now [tracking](https://github.com/concourse/git-resource/blob/1bf435a32a55b2ee943e47b36a80cab7ce7d9150/dockerfiles/ubuntu/Dockerfile#L17-L20) `git-core ppa` that has the [latest upstream version](https://git-scm.com/download/linux).
  - Since nothing is mentioned about the official apk being outdated, I am assuming that means it is updated with the latest release.
  - Not sure if the idea that git releases multiple minors at the same time could cause any problems, or which version would we need to stick to.
