### ISSUE TITLE
web: dashboard: show blank pipeline cards when ListAllJobs is disabled

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5470]
Given I am running my web node with `--concurrent-request-limit ListAllJobs=0`
When I load the dashboard from this web node
I see pipeline cards but no jobs displayed

**Comment by matthewpereira** [comment]
Suggestion:
Degrade the UI to remove any information normally loaded from the ListAllJobs endpoint. If possible, add a 'sync' icon with tooltip, which loads the job information for that pipeline tile when clicked.

Basic state:
![variations master](https://user-images.githubusercontent.com/6372810/79888165-2116db80-83ca-11ea-9441-af87f816cb2f.png)

Additional 'sync' button:
![Frame 1](https://user-images.githubusercontent.com/6372810/79888011-d1381480-83c9-11ea-8db4-bf532a3587d2.png)

On hover, sync button provides tooltip and allows a click to load job information:
![variations master](https://user-images.githubusercontent.com/6372810/79888100-fdec2c00-83c9-11ea-8f07-b6893d54178a.png)


Link to mockups:  https://www.figma.com/file/fuoFSVcTGptiS21P2POA2XbN/Concourse-UI-kit-and-Experiments?node-id=944%3A99002

Link to prototype: https://www.figma.com/proto/fuoFSVcTGptiS21P2POA2XbN/Concourse-UI-kit-and-Experiments?node-id=944%3A99260&scaling=min-zoom

**Comment by matthewpereira** [comment]
Suggestion:
Degrade the UI to remove any information normally loaded from the ListAllJobs endpoint. If possible, add a 'sync' icon with tooltip, which loads the job information for that pipeline tile when clicked.

Basic state:
![variations master](https://user-images.githubusercontent.com/6372810/79888165-2116db80-83ca-11ea-9441-af87f816cb2f.png)

Additional 'sync' button:
![Frame 1](https://user-images.githubusercontent.com/6372810/79888011-d1381480-83c9-11ea-8db4-bf532a3587d2.png)

On hover, sync button provides tooltip and allows a click to load job information:
![variations master](https://user-images.githubusercontent.com/6372810/79888100-fdec2c00-83c9-11ea-8f07-b6893d54178a.png)


Link to mockups:  https://www.figma.com/file/fuoFSVcTGptiS21P2POA2XbN/Concourse-UI-kit-and-Experiments?node-id=944%3A99002

Link to prototype: https://www.figma.com/proto/fuoFSVcTGptiS21P2POA2XbN/Concourse-UI-kit-and-Experiments?node-id=944%3A99260&scaling=min-zoom

**Comment by pivotal-jamie-klassen** [comment]
@taylorsilva wisely asked - "so I guess after you click the sync icon, the brower doesn't start polling for that pipeline's jobs?" For an MVP, this feels like a necessary assumption, because there complexities involved in either:
* starting to continuously sync after the button is clicked (this represent a technical challenge in the form of keeping track of which pipelines' data should be kept up-to-date), or
* allowing users to manually sync the same pipeline multiple times (the current design places the sync button where the status icon normally would be -- does this mean the button replaces the status icon? do we show both a button and a status icon? does the status icon become clickable?)

**Comment by pivotal-jamie-klassen** [comment]
Narrowing scope here to strictly showing the empty cards with the sync icon - hover state/tooltip and click behaviour is split out to #5556.
