### ISSUE TITLE
6.0.0: schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set

### ISSUE THREAD

**Issue by chrised** [concourse/concourse#5477]
## Summary

Pipeline stalls in the `preparing build` stage on certain pipeline jobs (varies from run to run, not consistent either - sometimes everything works)

From the log, I'm seeing errors related to the stalled jobs with the following content:
```
schedule job: get build inputs: adopt inputs and pipes: sql: no rows in result set
```

The only other place I can find this error message is in https://github.com/concourse/concourse/issues/5063#issuecomment-579287434

## Triaging info

* Concourse version: 6.0.0
* Browser (if applicable): N/A
* Did this used to work? This is a pipeline I refactored recently, so it's not impossible that there could be errors in it - but I would expect it to get stuck more consistently if that were the case.

Judging by the debug done on #5063, I'm probably going to have to dig through the database to get you some actual useful information to act on.
Please let me know what you need me to do in order to provide you with the required information!

**Comment by chrised** [comment]
@vito unfortunately I haven't been able to reliably reproduce it. Most recently I saw it in the following steps of the attached snippet:
- Build Dev Builder
- Build Production API Image

[snipped_pipeline.yml.txt](https://github.com/concourse/concourse/files/4516931/snipped_pipeline.yml.txt)

**Comment by vito** [comment]
Just looking at the underlying code, this part seems like the likely source of the error:

https://github.com/concourse/concourse/blob/3e7db0548bfe9e55fa28fe904bfdde0d079f19e6/atc/db/build.go#L1074-L1086

This would happen if the version chosen for the build is no longer available in the resource's version history. Has anything strange happened with your resource versions? e.g. has the version history 
for any of your inputs been truncated or reset?

**Comment by chrised** [comment]
See, I don't *think* they should have been truncated or reset - no one's touched it by hand, and the versions still exist upstream. 

Ah, but we do have *other* pipelines pushing to the same registry resources - at least locally to each pipeline. I've just realised it might be possible that they're *all* pushing with the 'latest' tag. Does the resource not store the sha256 reference of the image in the registry?

If this is the case, I can probably work around it by using our git sha as a tag, and you can feel free to close this issue :)

**Comment by vito** [comment]
@chrised The `docker-image` resource does track the `sha256` as the version, but one problem is that tags only ever point to one digest, so I could see weird things happening with multiple things pushing to the resource. I'm not really sure what would cause versions to go away but it'd probably be safer to give them different tags anyway.

Kinda related: https://github.com/concourse/registry-image-resource/issues/151

---

FWIW: someone ran into this in Discord and was able to identify the resource whose version history was reset and then run `fly check-resource --from (old version)` to resolve the stuck builds.

**Comment by chrised** [comment]
@vito Sounds like a good plan! I'll try and be more explicit with tagging, shouldn't hurt us in any case.
Your semver issue does line up with what I'm seeing, more or less, too.


> FWIW: someone ran into this in Discord and was able to identify the resource whose version history was reset and then run `fly check-resource --from (old version)` to resolve the stuck builds.

That is very useful, I'll definitely give that a shot when it next happens, thanks!

**Comment by kirillbilchenko** [comment]
Another work around for us was https://github.com/concourse/concourse/issues/145#issuecomment-573187422

**Comment by chrised** [comment]
> Another workaround for us was [#145 (comment)](https://github.com/concourse/concourse/issues/145#issuecomment-573187422)

Oh, that's very useful to know, will keep that in mind for when I next need to reset version history!



> @vito Sounds like a good plan! I'll try and be more explicit with tagging, shouldn't hurt us in any case.
> Your semver issue does line up with what I'm seeing, more or less, too.
> 
> > FWIW: someone ran into this in Discord and was able to identify the resource whose version history was reset and then run `fly check-resource --from (old version)` to resolve the stuck builds.
> 
> That is very useful, I'll definitely give that a shot when it next happens, thanks!

I meant to add (approximately 20 days ago, sorry) that setting up some more explicit tagging seems to have made behaviour a lot more consistent.

We've not seen this behaviour again since switching to more explicit tagging across the board.

**Comment by vito** [comment]
@chrised Thanks for following up!

---

Going to prioritize this for v6.2.0 - we should at least catch this error case and provide a better message (probably in the build preparation pane).

**Comment by sfunkhouser** [comment]
We have been seeing this issue consistently in many of our pipelines. We have been seeing this for jobs that have a trigger that includes `passed` of the previous job and it never gets triggered. The only workaround we have found is to pin the input resource which immediately starts the job without manually triggering it. Then we unpin it and things for that pipeline work okay for awhile again. When I looked into this in the db the version hash was incorrect, but pinning it forced it correct again, allowing it to start working again. This seems to be very inconsistent when it happens but I'm looking to see if I can find any more details.

**Comment by vito** [comment]
Hmm, I think this comes down to a difference in behavior with the new algorithm, which may explain why it's happening more often even though we haven't changed the situations in which versions would disappear.

The old algorithm would start from the version history and check each version to see if it satisfies the `passed` constraints. If a version disappeared, it would simply never try it.

The new algorithm doesn't look at the version history for `passed` constraints - it only looks at the upstream job's build output versions history, which sticks around even if the version went away. So it's possible for the algorithm to select a version that no longer exists, and then this error occurs when we actually try to use it for the build.

So, we may need to adjust the algorithm to handle this case by skipping versions which no longer exist and continuing to look further back in the build history.

@sfunkhouser Going on this theory, I'm guessing that the algorithm is choosing a version other than the one you've pinned - one that no longer exists (for whatever reason) but is technically the most recently used version by the upstream jobs.

**Comment by xtremerui** [comment]
@vito just to be the clear that the focus on this issue is catch the error properly? Should we create an issue for the algorithm change if that is the case?

**Comment by vito** [comment]
@xtremerui Yeah, let's just use this issue for improving the error messaging, since we'll have to deal with it for rerun builds too.

Can we have something show up in the build preparation? Maybe something like 'chosen version not available'? Unfortunately I think we only have the version MD5, so there's a limit to how helpful the message can be.

**Comment by sfunkhouser** [comment]
@vito Hm, going to dig into this more this morning to see if I can figure out how we are getting into this state. For some context, we are seeing this most frequently in a situation where we have a [pr-resource](https://github.com/zarplata/concourse-git-bitbucket-pr-resource) as the input --> job --> same pr-resource with passed constraint --> job. That second job about 50% of the time doesn't get triggered and we see this error in the logs. We pin the stuck input and that _same_ version runs. It seems to somehow get a bad version in the db but I have't tracked down how that happens. Let me see what I can find.

**Comment by xtremerui** [comment]
@vito The best we can do is showing the input name. Without knowing the disappeared old version one can't run `fly check-resource --from` though. 

To summary, if this error shows up, one can
a. purging the resource version history
b. going throught the version history to find out the missing one and run fly check-resource --from

**Comment by clarafu** [comment]
With #5675, it will now relay an error message to the user in the preparation build page. The error message will be `chosen version of input <input-name> not available`.

![Screen Shot 2020-06-01 at 11 06 49 AM](https://user-images.githubusercontent.com/19290703/83422827-1e130000-a3f8-11ea-9141-f078365f8d8f.png)

If you happen to see this error, it can possibly be a result of three different cases:
1. Your resource is pinned to a version that does not exist in the database anymore. This can be a pin from the web UI, resource configuration or the get step (https://concourse-ci.org/resource-versions.html#version-pinning). 
1. Your build is using an input with passed constraints and it is waiting for a version that does not exist anymore. That version was used by an upstream passed constraint job so now your current build can only be run with that specific version of the input because of it's passed constraints. You can figure out what version it is waiting for by first taking a look at which input the build preparation is waiting for the error `chosen version of input <input-name> not available`. Then, figure out which jobs are defined as that input's passed constraint. If you navigate to the latest build page of those passed constraint jobs, you should be able to figure out what version of the input was used. That version will be the one that the current pending build is looking for, and is most likely the missing version.
1. You are trying to rerun a build that is missing an input version. Rerunning a build will cause a `rerun build` to be created, and that rerun build will only run with the versions of the original build. If those versions that ran with the build you are trying to rerun no longer exists, it will cause the build to be stuck pending. 

In order to fix this error for all three of these scenarios, you can run `fly check-resource -r <pipeline>/<resource> -f <missing-version>`in order to have Concourse rediscover that missing version and that will allow the build to start. The solution to the problem is the same but the harder part is figuring out which version the build is looking for.
