### ISSUE TITLE
pipeline that continuously runs `terraform apply` to create a GKE cluster called `production`.

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/concourse#5508]
**Note** the creation of the terraform state bucket should itself be terraformed.

**Comment by vito** [comment]
Some notes from the progress so far...

We're trying to automate as much as possible, which may end up being overkill, but I'd rather over-automate and back out than end up asking how to do something 6 months from now.

So far we've got basic bootstrapping done to the point where the bucket can be created and a service account can be created associated to it. With this bootstrapping done we can now configure a pipeline, using credentials tied to the account and manually provided for now. The pipeline's first green build happened earlier:

* https://ci.concourse-ci.org/teams/main/pipelines/greenpeace/jobs/terraform/builds/6

Arbitrary decisions to be made upfront:

* zone/region: sticking with `us-central1-a`, no particular reason
* Kubernetes version: ? - we used to configure a `min_master_version` but its current value (1.12.5-gke.5) is no longer supported, so we had to [remove it](https://github.com/concourse/hush-house/commit/5f2ab0c70b762da59ca53e11d23e9885e4a68c0e) and let it just use the default, which is currently 1.14.10-gke.27. Do we think this is good enough or should we bump it to a newer one? 🤔

**Comment by vito** [comment]
Updates:

* For the K8s version, we now make use of [`release_channel`](https://www.terraform.io/docs/providers/google/r/container_cluster.html#release_channel) (an opt-in beta feature) which will supposedly automatically update our cluster. We have this set to "STABLE" for the production cluster. Maybe we can set it to "RAPID" for the dev/test environments?
* Rather than having two service accounts (one for the bucket state and one for "the rest") we opted to just have one account and give it the permissions it needs. Service account creation and permissions are now automated as part of bootstrapping. Every time we bootstrap the old keys will be revoked and a new one will be created and placed under a `secrets/` folder. This will also be used to generate a `vars.yml` file which can be used for bootstrapping the pipelines.

Open questions:

* We don't want this pipeline configured with a static credential in there, but we haven't figured out credential management yet. It's a bit of a chicken-egg problem. In fact configuring the pipeline in the first place is a bit of a chicken-egg problem. Maybe it could be configured against a local `docker-compose` instance? 🤷‍♂️

**Comment by vito** [comment]
Closing this out - we have [working pipeline](https://ci.concourse-ci.org/teams/main/pipelines/greenpeace) and a bootstrapping process documented in the [`README.md`](https://github.com/concourse/greenpeace).

Moving on to the next step, which is deploying Concourse to it.
