### ISSUE TITLE
aborting a build sometimes marks it as errored

### ISSUE THREAD

**Issue by jamieklassen** [concourse/concourse#5515]
## Summary

Normally I would expect aborting a build to mark it as aborted (brown), but sometimes I have seen jobs show as errored (amber).

## Steps to reproduce

1. `docker-compose up -d`
1. wait for web node to be available
1. `fly -t dev -c http://localhost:8080 login -u test -p test`
1. `fly -t dev sp -p long-output -c web/wats/fixtures/pipeline-with-long-output.yml`
1. `fly -t dev up -p long-output`
1. `fly -t dev tj -j long-output/long-output`
1. **wait for a very precise moment between when the task has initialized and when the task has started**
1. `fly -t dev ab -j long-output/long-output -b 1`

## Expected results

Build is marked as aborted.

## Actual results

Build is marked as errored.

## Additional context

I've been poking around in the debugger trying to understand the nature of the above-mentioned "very precise moment". The main anecdotal observation I have is that, with my manual sense of rhythm, I only seem to be able to invoke this behaviour on the very first build. I suspect this has something to do with setting up the image for the task, which will be cached on the worker on subsequent runs.

This evidence suggests that there is a tendency for builds to be marked as errored if they aborted while volume-streaming is in progress. However, I don't believe this can be a complete explanation of this kind of degenerate behaviour, because this build became errored with quite a different message, and it was not aborted during any volume-streaming:

https://ci.concourse-ci.org/teams/main/pipelines/release-5.5.x/jobs/build-rc-image/builds/76

## Triaging info

* Concourse version: 6.0.0 (deployed to ci.concourse-ci.org)
* Browser (if applicable): N/A
* Did this used to work?: Yes

**Comment by pivotal-jamie-klassen** [comment]
If I replace steps 6-8 the repro with the following:
6. `hack/trace web`
7. `(dlv) break image_resource_fetcher.go:208` (the call to `StreamOut` on the volume where the image metadata is read)
8. `(dlv) continue`
9. `fly -t dev tj -j long-output/long-output`
10. wait for breakpoint to be hit
11. `fly -t dev ab -j long-output/long-output -b 1`
12. `(dlv) continue`

Then you can reliably get the first build to error, with the message:
```
Put "/volumes/<volume handle>/stream-out?path=metadata.json": context canceled
```

**Comment by pivotal-jamie-klassen** [comment]
As for the linked build, all I can think at the moment is that it may be related to aborting an `In_parallel` step.

**Comment by vito** [comment]
Think we found it.

Detecting whether a build is aborted is done by checking if the `err` returned from running the step is `== context.Canceled`. This is obviously very brittle as it relies on direct equality - if any steps wrap the error, the detection won't work.

The `on_error` step, which wraps the entire build plan in the linked build, does just that:

https://github.com/concourse/concourse/blob/6b324b1161d35203931d543d065c777e847d851a/atc/exec/on_error.go#L37-L48

It actually checks for `context.Canceled` already to detect that it shouldn't run the hook (since it's aborted, not *errored*) - but then it goes and ruins it for the rest of us by returning a wrapped error.

I think we can fix this "for good" by bumping `go-multierror` to include [this commit](https://github.com/hashicorp/go-multierror/commit/58e4f1897fb08fd76f5fd4e81e2c6c5dddb59899) and then using `errors.Is` to detect whether the build was aborted.
