### ISSUE TITLE
Terraform Jaeger Helm release

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5562]
Not sure what's required beyond just the Helm release, though I imagine not too much.

**Comment by cirocosta** [comment]
The idea here is that **we'd like have the ability to derive insights from the tracing data that Concourse exports**.

Currently, the way we do so is by leveraging both the Jaeger UI, for that nice [Gantt Chart](https://en.wikipedia.org/wiki/Gantt_chart) visualization, and Kibana for aggregation of data across multiple traces.

The desire outcome of this issue is to continue to have such ability, but with the deployment of that infrastructure all automated, *assuming that we want to continue deriving those insights via infrastructure that we manage* (it could be discussed if it's wise to do so, especially with services like Wavefront and Datadog providing support for tracing data).


The current setup that we have consists of few services:


1. [nginx-ingress]: provides us an implentation of a Kubernetes ingress controller
backed by Nginx, giving us the ability to serve multiple services on the same
address (e.g., `tracing.concourse-ci.org`) but in different paths (e.g.,
`/jaeger` for jaeger, and `/` for `kibana`), having those paths only servable
for users who are authenticated.


2. [jaeger]: gives us the ability to have distributed tracing data sent to it and
persited in a backend, as well as providing us a UI for exploring that tracing
data.


4. [elasticsearch]: where jaeger persists the trace data that it receives

```
user            ==>             jaeger          =>      elasticsearch

          "let me see that              "hey ES, give me the spans
          trace"                         matching this query blabla"

```

```
concourse          ==>             jaeger          =>      elasticsearch

          "here are some spans"         "hey ES, store these for me .. "

```


3. [kibana]: a UI for querying data from elasticsearch (allows us to, e.g., create
dashboards based on the trace data, aggregating it in all sorts of ways that
jaeger isn't capable of)

```

user            ==>     kibana          ==>     elasticsearch

        "give me the average time               "alright ES, please give me the result
        that steps named `deploy-*`              of this query ..."
        took"

```


5. [oauth2-proxy]: a service that has the ability of only serving traffic to other
services once authentication has been granted by authorizing against an auth
provider

```

user            =>      nginx   => oauth2_proxy =>      jaeger
                                        |
 let me try accessing                   *-> github
 jaeger                                 pls, auth first ...

                                                => granted! go jaeger
```


[jaeger]: https://www.elastic.co/kibana
[kibana]: https://www.elastic.co/kibana
[oauth2-proxy]: https://oauth2-proxy.github.io/oauth2-proxy/
[elasticsearch]: https://www.elastic.co/what-is/elasticsearch
[nginx-ingress]: https://kubernetes.github.io/ingress-nginx/

As we access `tracing.concourse-ci.org` via HTTPS, we also have to provide to the controller the necessary TLS data. That's currently done via `cert-manager`.

The details of that deploy can be found here: https://github.com/concourse/hush-house/tree/d502e1e837ad17d83c95b1d9c28bffe768e61f90/deployments/with-creds/jaeger

**Comment by YoussB** [comment]
actually we're just gonna submit traces to wavefront and skip all this work.
