### ISSUE TITLE
tooltip on sync icon when job data unavailable

### ISSUE THREAD

**Issue by jamieklassen** [concourse/concourse#5578]
The sync icon looks _a lot_ like a button. Because people are probably going to want to click it, it's probably worth having a tooltip that explains what it means:

@matthewpereira's initial design looks like this:
![variations master](https://user-images.githubusercontent.com/6372810/79888100-fdec2c00-83c9-11ea-8f07-b6893d54178a.png)

but that design was assuming it would be clickable, as described in #5556. I would suggest that the icon stays transparent, and for consistency's sake I'm going to propose having a tooltip that matches the one on the expose button:

<img width="305" alt="Screen Shot 2020-05-12 at 3 00 54 PM" src="https://user-images.githubusercontent.com/22056320/81734394-6bd3c280-9461-11ea-846d-f0498458bdbc.png">

@matthewpereira if you want to take this time to redesign both tooltips to the white-with-black-text that you illustrated we can do that, but I think getting the tooltip present is a higher priority, and the two tooltips being compatible is non-negotiable. If you have time to think about these tooltips before this issue is complete let's definitely incorporate a new design for both, but otherwise I think it's safe to redesign later.

**Comment by pivotal-jamie-klassen** [comment]
~30 minutes of effort maximally following my nose yielded

<img width="154" alt="Screen Shot 2020-05-13 at 2 47 17 PM" src="https://user-images.githubusercontent.com/22056320/81852262-bbc98c80-9528-11ea-925e-b490664e834a.png">

The obvious problems with this - the opacity and positioning - are caused by the fact that the tooltip is an absolutely-position child of the icon, thus inheriting opacity and some positioning properties from its parent. This is an implementation detail of the [`iconWithTooltip` function](https://github.com/concourse/concourse/blob/master/web/elm/src/Views/Icon.elm#L16-L33). Resolutions include:

1. Using a "custom" implementation for this icon with tooltip to account for the parent icon's opacity, and tweaking the position of the child tooltip
2. Parametrizing the `iconWithTooltip` function to allow it to accomodate this new scenario
3. Refactoring the usages of `iconWithTooltip` in the Dashboard modules to use the `Tooltip` module, and reusing it here as well.

I'm going to take a 1-hour time-boxed attempt at 3. as it feels like the "right" thing to do. If we can standardize on a single tooltip abstraction it will allow us to make cross-cutting stylistically-consistent changes to tooltips. Plus the new module, though it has a more complex API, is much more flexible when it comes to positioning (it allows for `fixed` positioning to any viewport coordinate).

**Comment by pivotal-jamie-klassen** [comment]
At very first glance, it seems the `GetViewportOf` effect is sometimes used to display tooltips but also used to get viewports in non-tooltip-related scenarios. This makes the appearance of the `TooltipPolicy` type in the associated data a bit confusing. We should perhaps consider splitting this into two effects. Perhaps the tooltip-related one should be something more like `LocateTooltipParent`?

tooltip-related:
* https://github.com/concourse/concourse/blob/6b324b1161d35203931d543d065c777e847d851a/web/elm/src/Build/Build.elm#L316-L328
* https://github.com/concourse/concourse/blob/6b324b1161d35203931d543d065c777e847d851a/web/elm/src/SideBar/SideBar.elm#L69-L83
non-tooltip-related:
* https://github.com/concourse/concourse/blob/6b324b1161d35203931d543d065c777e847d851a/web/elm/src/Dashboard/Dashboard.elm#L120
* https://github.com/concourse/concourse/blob/6b324b1161d35203931d543d065c777e847d851a/web/elm/src/Dashboard/Dashboard.elm#L445-L449
* https://github.com/concourse/concourse/blob/6b324b1161d35203931d543d065c777e847d851a/web/elm/src/Dashboard/Dashboard.elm#L712-L713

**Comment by pivotal-jamie-klassen** [comment]
Took a little more than an hour, but I think pursuing approach 3. makes sense.

**Comment by matthewpereira** [comment]
@jamieklassen Getting the tooltip present is top priority for sure. Thanks for your work on this!

If it's blocked I'd be happy to pair on the styling, and if not do you mind if I make another issue for adjusting the styling on these at a later date? I'd like to see the text/background colours meet accessibility guidelines for contrast, but don't want to slow this down any further.

**Comment by jamieklassen** [comment]
@matthewpereira I'd vote for updating the styling for both tooltips in a later issue.
