### ISSUE TITLE
Bootstrap Vault secrets

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#5583]
When we bootstrap all of our pipelines, we'll also need to bootstrap all of the secrets in Vault that our pipelines use.

That means we'll need to store them in another credential manager. Since we're trying to avoid using LastPass if possible, we could store everything in GCP Secrets Manager and transfer the secrets over to Vault.

This kind of poses the question: what if we could use GCP Secrets Manager as a var source? That's a higher-effort solution, so for now, we could try to use it as an intermediate secret store.

**Comment by pivotal-jamie-klassen** [comment]
wild thoughts:

A bit late to mention it (and has financial implications), but we _could_ use a vault enterprise account so that we don't actually manage our own secrets. While we're at it we could potentially have a terraform cloud account so that we don't need a self-hosted concourse to do the bootstrapping.

> what if we could use GCP Secrets Manager as a var source?

This is such an interesting question. It forces me to realize how little empathy I have for _fully_-salted concourse deployments. It feels so obvious now, like how did I not think of this? All this time I've been satisfied to configure Vault as a snowflake/pet with all our critical secrets in it.

Throughout greenpeace I've been seeing how we're actually quite coupled to GCP, since it's the absolute first entrypoint into our automation. Even though this gives me a funny feeling of "vendor lock-in", it's giving a slightly more realistic idea of what the "first principles" or "atoms" of a concourse deployment are.

**Comment by aoldershaw** [comment]
Right now, the bootstrap process actually requires running a script to initialize Vault which we run in a Concourse task. So, if we still host our own Vault, I'm not sure if Terraform cloud will be sufficient for initial bootstrapping (though it would work well for upgrades to Concourse).

If we used a hosted Vault, I guess it would alleviate that problem, too.

**Comment by aoldershaw** [comment]
It looks like we might be able to lean even more into our GCP dependence: if we package our script in a Docker container and run it using Google Cloud Run, we can (probably) automate everything in a single terraform module (meaning we could look into using Terraform Cloud).

**Comment by YoussB** [comment]
### In order to automate the storage of secrets, we will need to consider the following:
- convenience to the person creating the secret; not having to create the secret in multiple places, and having a simple way to do so
  - the current way we do this is through logging in to the vault pod and adding the secret to specific location that will then be used by the pipeline.
- a way to map the human created secret to the secret in vault (most importantly, mapping the location of the secret)
- a way to know if a new secret was created so as to update the secret manager used by concourse.

### the current ideas I have on mind are:
- use a private repo with the filename being the path to the secret and the contents being the value of the secret.
  - this might be the less secure way, but will be very helpful in knowing when a new secret is added, can have a pipeline to trigger on the changes in the repo.
  - this option is less dependent on GCP
- use google secrets manager
  - this is more secure, but still not sure how to know if a new secret was added so we can update the secret manage.

**Comment by YoussB** [comment]
let's use a YAML file in an encrypted GCS bucket as the source of truth for our "working secrets" (those that will be accessed by concourse from vault) with a schema something like this:
```yaml
/concourse/main/concourse_bot_private_key:
  ---- private key ----
  as;dlfkjasdfo8hlskvj
  ---- end private key ----
/concourse/main/concourse/account:
  username: foo
  password: bar
/concourse/shared/datadog_api_key: baz
# ... i.e. either ...
/path/to/concourse/credential: credential-string-value
# ... or ...
/path/to/concourse/credential/with/multiple/keys:
  foo: bar
  baz: qux
```
we'd like to create a script/cli for consumers of the greenpeace-deployed environment to use that offers a few capabilities:
* `sync` so that the data in the running vault exactly matches the data in the YAML file
* `update path foo=bar baz=qux` as an alias for updating an entry in the YAML file and `sync`ing
* `delete path` as an alias for removing an entry from the YAML file and `sync`ing

if we can get the team consistently using this CLI then the specific choice of "a YAML file in an encrypted GCS bucket" as a source of truth should be an implementation detail that we will be free to change in the future (e.g. if we get a hosted vault).

we liked the choice of a file in a GCS bucket for the combination of flexibility (flat file) and the opportunity to use a `gcs-resource` to create a pipeline to continuously sync.

**Comment by aoldershaw** [comment]
We decided to take a slightly different approach from https://github.com/concourse/secret-syncer. Rather than writing/maintaining our own tool, we found https://github.com/adamdecaf/vault-backend-migrator. It's coupled to vault, but is pretty nice because it allows for importing/exporting a vault instance from/to a flat file (which is relatively vault agnostic, and should be easy to write an adapter for importing to a different backend if needed).

The approach is then as follows:
* As a one-time operation, export vault data from our current vault instance on `hush-house` (and clean up the cruft). Simple script for that here: https://github.com/concourse/greenpeace/blob/master/scripts/export-secrets
  * Vault data is encrypted as described in https://github.com/concourse/greenpeace#encryption, in addition to GCS's default encryption
* Upload that data to GCS under the production namespace
  * Note: each cluster/environment has its own namespace for vault secrets. This lets environments diverge, and means you can mess around with test clusters without screwing up prod
* (Manual trigger) job that clones the production data to a new cluster's namespace (`sync-secrets-with-production`)
  * When you create a new cluster, you need to provide a data bundle
  * Typically, you'll want to use the production cluster's data to bootstrap the vault instance, but you don't necessarily need to
  * In this common case, you'd trigger the `sync-secrets-with-production` job
* (Time triggered) job that backs up a cluster's data (from vault) daily (`backup-secrets`)
  * The GCS bucket is versioned, with 3 versions retained
* [Script](https://github.com/concourse/greenpeace/blob/master/scripts/edit-secrets) that allows for editing the secrets file in place
  * This will auto-trigger the `initialize-vault` job which re-imports the secrets

<img width="792" alt="Screen Shot 2020-12-07 at 3 12 12 PM" src="https://user-images.githubusercontent.com/26583442/101400367-cb326d80-389e-11eb-944d-fbf80e4e6683.png">
