### ISSUE TITLE
trace build creation

### ISSUE THREAD

**Issue by jamieklassen** [concourse/concourse#5602]
As a concourse operator
I want a way to link the [span context](https://github.com/concourse/concourse/pull/5575) associated with a resource version to the span context associated with a build
So that i can collect and reason about timing information for the complete causal flow of events through concourse

Given that a resource `r` has just checked
And produced a new version `v` with span context `sc`
And there is a job `j` with `r` as an input with `trigger: true`
When the scheduler creates a pending build `b` for `j`
Then `b`'s span context will be created with a [link](https://github.com/open-telemetry/opentelemetry-specification/blob/bdf39cb935a6f48badc687daeb78a66dc352761f/specification/overview.md#links-between-spans) to `sc`

**note** can we generalize the definition of `b` above to describe all cases where `b` is _caused by_ `v`? The definition of _cause_ has yet to be determined.

**Comment by pivotal-jamie-klassen** [comment]
unassigning myself as I seem to still be somewhat occupied with #5405 - I'll pick it up if I'm done in time, but otherwise it's up for grabs!

**Comment by clarafu** [comment]
When we add the span context to resource versions during the saving of versions from the check step, it would be nice if we can also create a new span within the same trace during the check step in order to capture any errors that comes from the check step. There is more context about the motivation behind this here https://github.com/concourse/concourse/pull/5575#discussion_r425823210.

There is some work that has been done for adding the span context to resource versions in the `wip-tracing` branch.

**Comment by zoetian** [comment]
We have done most of the preliminary refactoring for tracing version creation (a dependency of this issue), and it should be possible to continue tomorrow with driving out the `SaveVersions` method on the `db.Check` interface.
