### ISSUE TITLE
Release v6.2.0

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#5633]
TODO:
- [x] CBD tag needs to be on master: https://github.com/concourse/ci/issues/339
- [x] helm chart needs `CONCOURSE_VAULT_LOOKUP_TEMPLATES`

**Comment by taylorsilva** [comment]
Things to Release
- [ ] Concourse
- [ ] Helm Chart
- [ ] Bosh Release
- [ ] Bosh Deployment

**Comment by vito** [comment]
Here's a comment that explains what happened with tagging v6.1.0 in CBD: https://github.com/concourse/concourse-bosh-deployment/issues/218#issuecomment-637601252

tl;dr:

* The main pipeline is what's responsible for bumping the latest version, tagging it, and pushing to `master`.
* For v6.1.0, a tag had already been created on the `release/6.1.x` branch, so pushing the tag to `master` failed.
* Although the tag exists, it is not on the `master` branch. Users have to specify `master` branch when consuming our tags, otherwise their pipelines will trigger whenever we ship patch releases for old versions, because the version history with `tag_filter` is purely chronological and not semver-based.

Bonus sidequest: the main pipeline is also responsible for promoting `develop` to `master` upon shipping a new release.

With our goal of not shipping from the main pipeline anymore, we'll have to figure out where these responsibilities go.

So here's a proposal:

1. Get rid of the `develop` branch. Changes will be made directly to the `master` branch.
1. Continuously merge the `release/x.x.x` branch corresponding to the latest release into `master`.

In general, the guidance will be "if there's a tag for your version, `git checkout` to that tag". If you need to stray ahead for recent changes, then that's up to you. For example, https://github.com/concourse/concourse-bosh-deployment/pull/213 backported some changes to `release/5.5.x` and those weren't tagged until v5.5.9 was shipped around a month later.

When we need to make changes to the manifest or opsfiles in preparation for a new release, we can either make them directly to `master` or make them to the release branch that we're going to ship. We may also make changes to `master` and them use them as the basis for the release branch.

Continuously merging the latest release is kind of an interesting challenge. I think it can be done with a pipeline that configures another pipeline (or perhaps itself) in order to track the appropriate branch. The goal of this would be that there's always just a single commit and a single tag for each version bump, and the commit is always created by the release pipelines. The pipeline that continuously merges into `master` can be its own standalone pipeline.

**Comment by vito** [comment]
Per the previous comment, I added a [`promote` pipeline](https://ci.concourse-ci.org/teams/main/pipelines/promote) which monitors the latest shipped release and merges the associated tag into `master` - for both the `concourse-bosh-deployment` repo and the `concourse` repo.

It worked after shipping v6.2.0, but there was one hiccup: because the `release/6.2.x` branch in CBD had been created prior to merging the v6.1.0 tag into master, any pipelines that used `tag_filter` wouldn't pick it up because the v6.2.0 tree didn't [`--contains`](https://github.com/concourse/git-resource/blob/181e0e8f1c59d27bde0d22d770a154a95ba4cc38/assets/check#L139) the v6.1.0 tag.

I manually fixed this by re-pointing the `v6.2.0` tag to the merge commit. This shouldn't be a problem rolling forward because when we create these `release/x.x.x` branches on CBD from `master` they'll include the previously shipped tag (because it will have been merged in by the `promote` pipeline).
