### ISSUE TITLE
Bogus team and pipeline name should not be rendered on 404 page

### ISSUE THREAD

**Issue by vito** [concourse/concourse#5769]
## Summary

Values specified in the URL are not validated before rendering in the UI.

## Steps to reproduce

Navigate to https://ci.concourse-ci.org/teams/foo/pipelines/bar/jobs/baz

## Expected results

I should see a 404 page that makes it clear that the entities requested by the URL does not exist.

## Actual results

The pipeline and job name show up in the header up top, which may imply that they exist, or may be injected to mislead unknowing users.

![image](https://user-images.githubusercontent.com/1880/84788453-23a64380-afbd-11ea-8e94-589ebbe03602.png)

## Additional context

This was reported to our security email address.

**Comment by g-fusion** [comment]
Hello Colleagues,

Any update on progress of these issues?
Thank you.

**Comment by taylorsilva** [comment]
Looks like it's been fixed?

![image](https://user-images.githubusercontent.com/4583837/118664201-48073300-b7bf-11eb-8720-2f0ea1515a30.png)

**Comment by g-fusion** [comment]
@taylorsilva in which version? We are running v.6.5.1 and it is still present.

**Comment by taylorsilva** [comment]
Looks like this was fixed in 7.0.0. On 6.7.x it still shows up in the UI
<img width="812" alt="image" src="https://user-images.githubusercontent.com/4583837/118834244-13af7780-b890-11eb-8790-3cda41bee783.png">

and disappears on 7.0.0
<img width="785" alt="image" src="https://user-images.githubusercontent.com/4583837/118834532-478a9d00-b890-11eb-9a62-151b4da1163e.png">

Closing!
