### ISSUE TITLE
Automatically archive pipelines that are no longer set by their parent jobs

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#5835]
Create a new garbage collector that will archive pipelines that were previously set by a `set_pipeline` step and no longer are.

**Comment by alonikomax** [comment]
Hey, how can I disable this feature?
I am creating pipelines to do a later cleanup of failed tests but they get archived when the job that created them runs again.

**Comment by taylorsilva** [comment]
No way to disable it now that the feature flag is removed. Is there a reason you don't continuously set the pipelines?

**Comment by alonikomax** [comment]
Yes, what I did is a pipeline that creates infrastructure using Pulumi and
then run some tests of our product on that infrastructure.
If the test fails, someone might need to access that infrastructure so I
need to keep it up.
But after that, I need to destroy the infrastructure.
So when a test fails I create a pipeline that does the cleanup, and when
needed someone can just run the job manually instead of doing the cleanup
by hand.

I also wanted to create an instance pipeline whenever there has been a push
to a repository to create a pipeline of tests. And that way the developer
can see easily on the dashboard their tests (because the instance vars are
shown).

Now I need to create a task that uses the cli to set-pipeline instead.
