### ISSUE TITLE
Upgrading Concourse to 6.3.0 fails when credhub and UAA are colocated 

### ISSUE THREAD

**Issue by Hermen-Nicolau** [concourse/concourse#5863]
## Summary

When upgrading a concourse deployment, with UAA and credhub colocated, from 5.5.3 to 6.3.0 the upgrade failed to start the UAA and Credhub services. Looking at the logs we saw the following message:

`Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database: The server does not support SSL.`

`SQL State  : 08004
Error Code : 0
Message    : The server does not support SSL.
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60) ~[flyway-core-5.2.4.jar:?]
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72) ~[flyway-core-5.2.4.jar:?]`

## Steps to reproduce
- Upgrade a currently working Concourse deployment that has UAA and Credhub colocated
- Deploy a new Concourse deployment with UAA and Credhub colocated. 

## Expected results
- The uaa and credhub components would working using SSL and TLS. 

## Actual results
- The components do not trust each other over SSL or TLS and the upgrade fails 

## Additional context
We were able to pass this issue in two ways:
1 - By changing the database url in the uaa.yml file so that SSL was disabled:
`Before
url: jdbc:postgresql://q-s0.db.default.concourse.bosh:5432/uaa?sslmode=verify&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory`
`After
url: jdbc:postgresql://q-s0.db.default.concourse.bosh:5432/uaa?sslmode=disable&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory`

2- By using a custom ops file that accomplishes the same - https://github.com/concourse/concourse-bosh-deployment/issues/202
## Triaging info

* Concourse version: 5.5.x
* Browser (if applicable):
* Did this used to work? yes

**Comment by taylorsilva** [comment]
@Hermen-Nicolau We tried reproducing this but couldn't.

In one instance, we somehow broke our deployment after adding some ops-flles (didn't note down which ones) and UAA was unable to connect to postgres because the cert postgres was using didn't contain the right SAN. We got around this eventually by hard-coding the correct SAN into the cert, forcing bosh to re-generate the cert with the correct SAN. Not ideal.

In a second instance, if we used the same ops-files when first creating the deployment with Concourse 5.5.11 and then upgrading to 6.3.1, everything worked fine. The ops-files in concourse-bosh-deployment do change significantly between 5.5.3 and 5.5.11.

We were never able to get the error you got. Looking at it now, it reads as if postgres is not configured to use SSL. Unsure why this would be. 

We'll need more details to properly reproduce this. We need to know how Concourse was initially deployed on 5.5.3. Before [the secure-* ops-files](https://github.com/concourse/concourse-bosh-deployment/commit/46bd4dadca57729aa6159da55fa07e22bd329464) were added, how did users setup TLS between all the components? If we can replicate that as our starting state then I think we'll have a better chance at reproducing this.
