### ISSUE TITLE
concourse_linux_amd64 binary release size

### ISSUE THREAD

**Issue by nkts** [concourse/concourse#591]
Please strip down concourse_linux_amd64 binary size. Now it's something 10x ish times larger compared to Mac and Windows versions.

**Comment by vito** [comment]
And how do you propose we do that? It's 10x larger because it has 10x more stuff.

**Comment by nkts** [comment]
So obviously it's unstripped binary:
```
# file concourse 
concourse: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=a32ea33d259e6745a7a8983f2c0d1ac42283f074, not stripped
```

My suggestion: combination of build flags -ldflags="-s -w", upx/goupx, stripping. 

Perhaps untouched and stripped versions.

**Comment by vito** [comment]
Stripping would result in a pretty tiny reduction, but it may be worth a try. The Linux binary is so large because it embeds all the core resource types, which are each a stripped down rootfs, plus additional tooling (`iptables`, `btrfs` utilities, etc.) to make it portable.

**Comment by nkts** [comment]
I was not aware about embedded OS utilities. I guess it's difficult to squeeze that.

**Comment by moritzheiber** [comment]
@vito If the binary is meant to be portable, how about not linking it dynamically? Currently, concourse does not run on Alpine Linux because it's dynamically linked against what seems to be a set of libraries from 2.6.32 ...

```sh
# file concourse 
concourse: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=7455d7aa5a454ced4f2fcd9e1375e067c06ca9e0, not stripped
```

While the CLI is actually statically linked (which I would prefer for a statically linked binary, I guess):
```sh
# file fly 
fly: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```
I would suggest linking the binary statically. This will (of course) increase the size, but it will also make the binary truly portable.
