### ISSUE TITLE
Investigate whether to consolidate --external-garden-url under CONCOURSE_RUNTIME

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#5963]
In https://github.com/concourse/concourse-bosh-release/pull/112 CONCOURSE_RUNTIME was introduced to select either Guardian, Containerd or Houdini.

Investigate whether --external-garden-url should only be applicable when Guardian is being run, and implement appropriate validation logic and errors if that's the case.

**Comment by mikroskeem** [comment]
This should be definitely applicable only when Guardian is being used, especially since there are multiple runtime choices.

In ideal after merging #6428 I've considered adding an option to prevent worker from trying to launch containerd and connect to externally managed one.

Perhaps `--external-runtime-url` could be used instead?

**Comment by muntac** [comment]
Upon thinking this over with @taylorsilva we concluded that the `--external-garden-url` flag is probably only being used in a few special cases. And that its users are likely very aware of exactly what context it's meant to be used in. Therefore, we don't think automated validation of this would be very useful at the moment.
