### ISSUE TITLE
[SPIKE] Storage on k8s

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#6036]
## Summary
We want to get a clearer idea on what the best storage solution will be for the k8s runtime for Concourse. We want to explore three ideas:
1. [K8s POC](https://github.com/concourse/concourse/issues/5209) - uses a sidecar baggageclaim + beltloader 
1. [Porter](https://github.com/concourse/porter) Sidecar that uses external S3 compatible blobstore 
1. Registry to store artifacts (eg. [imgpack](https://github.com/k14s/imgpkg) )
1. Generic ephemeral volumes [GenericEphemeralVolume](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#api-change)
1. What CSI options are available ?
    - what is the tradeoff of going down these paths ?
1. What is the current state of Tekton for dealing with artifacts ?
1. and keep an eye out for other solutions

## Context

* Prior discussion: #5986 
* Part of #5682

## Requirements
An ideal storage solution can do the following for us:

- image fetching from the CRI k8s is using
- transfer artifacts between steps (whatever represents a step, most likely a pod)
- cache for resources and tasks
- stream artifacts across worker runtimes (k8s worker sends artifact to garden worker)

## Criteria
- security
- performance, aka initialization time (time spent running workloads on a single k8s worker, as well as across workers)
- resource usage to run this storage solution

## Feedback

If you, the reader, have any ideas or feedback for this issue please leave a comment!

**Comment by xtreme-sameer-vohra** [comment]
# Ephemeral Volumes
- while this simplifies the workflow for Concourse in terms of managing volumes, it doesn't provide any additional capabilities that weren't previously available to Concourse

# Baggageclaim Daemon set ( run a privileged baggageclaim pod that would work similarly to its current setup )
- The pod can be provided sufficient privilege to create overlay mounts
- The volumeMount object allows specifying a volume subPath to be made available ( however, overlay mounts aren't preserved between pods )

**Comment by taylorsilva** [comment]
Feedback from office hours:
- Can we PR making the CRI trust internal IP's for pulling images? Then we can do Ciro's POC storage solution with baggageclaim as a sidecar. Would also make running an internal registry viable!
- [VolumeSnapshot](https://kubernetes.io/docs/concepts/storage/volume-snapshots/) - the problem with "a get step that returns an image that is used by a proceeding task" makes this non-viable unless we hack our way around by detecting this case. Do we already hack around this use-case? I'm not familiar with that area of the code

**Comment by taylorsilva** [comment]
## CSI Driver
- The spec allows a spectrum of implementation options (eg. [image populator](https://github.com/kubernetes-csi/csi-driver-image-populator) which only implements NodeVolumePublish to more feature-filled options like [hostPath](https://github.com/kubernetes-csi/csi-driver-image-populator) ). There is a skeleton `csi-common` package that contains noop implementations 
- The spec also allows a variety of [deployment topologies](https://github.com/container-storage-interface/spec/blob/master/spec.md#architecture), the node based option would be suitable for us
- Using CSI would allow us to swap storage options more easily
- It could provide the option to de-couple Concourse from storage development, packaging and deployment 

Note
---
- Came across this [mount util](https://github.com/kubernetes/utils/blob/master/mount/mount.go#L39)which was being used the the CSI drivers

**Comment by taylorsilva** [comment]
Question
----
- can a CSI driver or pod interact with the CRI ? If so that would allow us to load images from disk bypassing the requirement for a registry ?

**Comment by taylorsilva** [comment]
# Mount Propagation Testing
## Docker
1. `mkdir bar`
1. `docker run --privileged --mount type=bind,source=$(pwd)/bar,target=/bar,bind-propagation=rshared -it ubuntu /bin/bash`
  1. In the container create  an overlay mount 
```
   root@cbc3fa49680a:/bar# mkdir lower
   root@cbc3fa49680a:/bar# mkdir upper
   root@cbc3fa49680a:/bar# mkdir work
   root@cbc3fa49680a:/bar# mkdir before
   root@cbc3fa49680a:/bar# mount -t overlay overlay -o lowerdir=/bar/lower,upperdir=/bar/upper,workdir=/bar/work /bar/before
```
1. The mount is visible on the host
```
   root@mount-prop-test:/home/pivotal/bar# mount | grep before
   overlay on /home/pivotal/bar/before type overlay (rw,relatime,lowerdir=/bar/lower,upperdir=/bar/upper,workdir=/bar/work)

```
1.  Create a second container with the `before` overlay mount mounted at `/bar`: `docker run -it --mount type=bind,source=$(pwd)/bar/before,target=/bar,bind-propagation=rslave ubuntu /bin/bash`
```
   root@9db6182a9d95:/# mount | grep bar
   overlay on /bar type overlay (rw,relatime,lowerdir=/bar/lower,upperdir=/bar/upper,workdir=/bar/work)
```

Docker mount propagation is working as we'd expect. We did a `docker inspect` on the second container, result is here: https://gist.github.com/taylorsilva/b38c4d59cf56f46f3d3d8d2aeae4311b#file-local-docker-inspect-json

## K8s

1. Create the `pvc` and **mount deployment** in this manifest (you may want to specify a node for the pod to land on to make debugging easier): https://gist.github.com/taylorsilva/b38c4d59cf56f46f3d3d8d2aeae4311b#file-k8s-propagation-test-yml
1. `kubectl exec` into the mount pod: `kubectl exec -it deployment/mount /bin/sh` and create an overlay mount inside the PVC
```
/mount-test # mkdir lower
/mount-test # mkdir upper
/mount-test # mkdir work
/mount-test # mkdir before
/mount-test # mount -t overlay overlay -o lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work /mount-test/before
```
1. Create the **step deployment** from the previous gist, targeting the same node as the mount deployment. exec onto the pod `kubectl exec -it deployment/step /bin/sh`
1. If you do `mount | grep before` there will be no results. The mount did not propagate

----
wip~~~~
k8s is doing a lot of stuff with our single overlay mount we made `/mount-test/before`. This is on the GKE node where our mount deployment is running:
```
$ mount | grep before
overlay on /var/lib/kubelet/pods/40d240e1-a42c-42d5-b996-6e202a8c6cf8/volumes/kubernetes.io~gce-pd/pvc-b5820782-5e64-4ca8-bbe7-8cbcc161ec95/before type overlay (rw,relatime,lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work,xino=off)
overlay on /var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts/gke-topgun-ab0b08d2-dy-pvc-b5820782-5e64-4ca8-bbe7-8cbcc161ec95/before type overlay (rw,relatime,lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work,xino=off)
overlay on /var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts/gke-topgun-ab0b08d2-dy-pvc-b5820782-5e64-4ca8-bbe7-8cbcc161ec95/before type overlay (rw,relatime,lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work,xino=off)
overlay on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts/gke-topgun-ab0b08d2-dy-pvc-b5820782-5e64-4ca8-bbe7-8cbcc161ec95/before type overlay (rw,relatime,lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work,xino=off)
overlay on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts/gke-topgun-ab0b08d2-dy-pvc-b5820782-5e64-4ca8-bbe7-8cbcc161ec95/before type overlay (rw,relatime,lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work,xino=off)
overlay on /var/lib/kubelet/pods/40d240e1-a42c-42d5-b996-6e202a8c6cf8/volumes/kubernetes.io~gce-pd/pvc-b5820782-5e64-4ca8-bbe7-8cbcc161ec95/before type overlay (rw,relatime,lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work,xino=off)
overlay on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/40d240e1-a42c-42d5-b996-6e202a8c6cf8/volumes/kubernetes.io~gce-pd/pvc-b5820782-5e64-4ca8-bbe7-8cbcc161ec95/before type overlay (rw,relatime,lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work,xino=off)
overlay on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/40d240e1-a42c-42d5-b996-6e202a8c6cf8/volumes/kubernetes.io~gce-pd/pvc-b5820782-5e64-4ca8-bbe7-8cbcc161ec95/before type overlay (rw,relatime,lowerdir=/mount-test/lower,upperdir=/mount-test/upper,workdir=/mount-test/work,xino=off)
```

- Is this simpler if we use hostPath instead of a GCP volume?
- why does mount propagation work when a step pod already exists?
- our docker inspects were different between our vanilla docker and k8s docker. What is k8s doing differently when requesting docker creates a container with mounts that should propagate?
- found an issue in the k/k repo that matches our use-case. user didn't provide good reproducible steps; we could share ours that we have above?

**Comment by taylorsilva** [comment]
**Reminder** 
- cleanup gcp instance `mount-prop-test`

**Comment by xtreme-sameer-vohra** [comment]
Observed the same behaviour on vSphere as on GCP
- the mount doesn't propagate if the `consumer` pod isn't running when the `mount` command was executed. It does propagate if the `consumer` pod was running.

**Comment by xtreme-sameer-vohra** [comment]
# Definitions
* **cache object** a BLOB and relevant metadata that Concourse needs to persist. These could be Resource Caches, Task Caches or Build Caches. 

# Options
## Baggageclaim Daemonset 
### Description
A privileged baggageclaim pod would manage all the **cache object** for step pods. The pod can be provided sufficient privilege to create overlay mounts using `BiDirectional` value for `mountPropagation`. The `volumeMount` object allows specifying a volume `subPath`.

This approach didn't work using GCE PDs or vSphere Volumes ([Issue](https://github.com/kubernetes/kubernetes/issues/95049)). It does work using `hostPath` option, however, that would require a large root volume and wouldn't be able to leverage IaaS based persistent disks. 
 
### Pros
+ Leverage baggageclaim
+ Concourse would have complete control over volume lifecycle
+ would be very performant for steps scheduled on a single worker as no input/output stream would be required

### Cons
- Not being able to use IaaS based persisent disks doesn't offer a viable solution. K8s nodes would need to have large root volumes.
- Wouldn't have support for hosting images by default. However, `baggageclaim` could be extended to add the APIs
- `baggageclaim` itself doesn't have any authentication/authorization or transport security (https) mechanisms built into it

## Image Registry to store artifacts
### Description
Each **cache object** is represented as a image layer for a repository in an image registry. [SPIKE using registry to store artifacts](https://github.com/concourse/concourse/issues/3740). Concourse would require a managed image registry as a dependency. For each step, Concourse would generate a image config and manifest with all the relevant inputs modeled as image layers. 

### Pros
- Would have support for building an image in a step and it as the image for the subsequent step. This would require the image registry to be accessible by the CRI subsystem on a node
- Image registries are are critical to operating on K8s and as such there are plenty of options for leveraging managed IaaS based solutions such as GCR, ECR, ACR to on prem solutions like Harbor. Therefore, it would be a safe assumption that a Concourse on K8s user would already have a registry available for use.
- Could explore further de-coupling by exploring [csi-driver-image-populator](https://github.com/kubernetes-csi/csi-driver-image-populator) when using registries for storing artifacts. Listed as a sample driver in the CSI docs and README says it is not production ready. Last commit was Oct 2019
- Leverage performance enhancements to registries such as [pull through cache](https://docs.docker.com/registry/recipes/mirror/)
- Use a standardized and documented [OCI image-spec protocol](https://github.com/opencontainers/image-spec)
- LRU based local caching of image layers by the K8s CRI
- Simplified GC as registry would be a centralized store
- Established ways of securely pushing/pulling blobs from an image registry

### Cons
- Some registries such as GCR don't expose an API to delete layers directly
- **cache object** would have to have a fixed static path in the image file system to be able to reuse the same layer. This would require some additional handling on Concourse to support [input-mapping](https://concourse-ci.org/jobs.html#schema.step.task-step.input_mapping) and [output-mapping](https://concourse-ci.org/jobs.html#schema.step.task-step.output_mapping)
- Adds extra overhead to generate new image config & manifests to leverage **cache object** layers
- There isn't a well documented approach to setup an in-cluster secure registry. The setup requires exposing an in-cluster registry externally with traffic routed via an LB. [Prior spike](https://github.com/concourse/concourse/issues/3796)
- Potentially adds substantial load on registry, as Concourse would be creating 

## S3 Compatible Blobstore
## Description
Each **cache object** is stored in a blobstore. Concourse would require a mananaged blobstore as a dependency. For each step, Concourse would pull down the relevant blobs for inputs and push blobs for outputs. 

## Baggaeclaim as a CSI Driver
- [example HostPath CSI Driver example](https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/docs/deploy-1.17-and-later.md) ( It only uses K8s resources ).
- Pros:
  - Can use existing storage API's with our CSI backing it
  - Don't have to deal with [volume limits per node](https://kubernetes.io/docs/concepts/storage/storage-limits/#dynamic-volume-limits)
  - No performance concern with fetching artifacts, will be the same as the current setup, some lag when artifact streaming is required to send the artifact to another node
- Cons:
  - Nodes will need a lot of disk space like our workers currently need. Are k8s nodes usually configured to have a lot of local storage? Guessing no because when you need a lot of storage a pod will request a large PVC
  - Providing volume as an image for k8s to consume is not possible without uploading to an image registry first or configuring the CSI beforehand to pull from baggeclaim
  -  need to update baggeclaim to implement the CSI's gRPC interface: https://github.com/container-storage-interface/spec/blob/master/spec.md#rpc-interface

  
## Fuse
https://github.com/kubernetes/kubernetes/issues/7890

**Comment by xtreme-sameer-vohra** [comment]
The RFC that references the work done as part of this Spike is [074-k8s-storage](https://github.com/concourse/rfcs/tree/074-k8s-storage) and further developments should be captured in the RFC.

**Comment by xtreme-sameer-vohra** [comment]
SRED Time: 2 pair weeks
