### ISSUE TITLE
Containerd runtime errors with no user specified when `/etc/passwd` doesn't exist

### ISSUE THREAD

**Issue by aoldershaw** [concourse/concourse#6054]
## Summary

On images that don't have an `/etc/passwd` by default (e.g. `clearlinux`), our containerd runtime fails to run containers that don't specify a username.

## Steps to reproduce

```sh
$ docker-compose -f docker-compose.yml -f hack/overrides/containerd.yml up -d
$ cat task.yml
platform: linux
image_resource:
  type: registry-image
  source:
    repository: clearlinux
run:
  path: sh
  args:
  - -c
  - |
    ls -l .
$ fly -t dev execute -c task.yml
initializing
selected worker: 11bf5f0460fa
running sh -c ls -l /etc

Backend error: Exit status: 500, message: {"Type":"","Message":"lookup user: open /worker-state/volumes/live/9de26203-6908-4565-64d2-da4be5cc9859/volume/rootfs/etc/passwd: no such file or directory","Handle":"","ProcessID":"","Binary":""}

errored
```

Interestingly, we didn't even specify a `user` in the `run` config, so I don't know why it's even hitting the `LookupUser` code path:

https://github.com/concourse/concourse/blob/4b447f17787cb02d238c0652b86b13a54dc6342a/worker/runtime/container.go#L363-L368

Perhaps the `garden.ProcessSpec` gets a default user assigned somewhere?

## Expected results

Task runs successfully as the default user

## Actual results

Task errors

## Additional context

Seems to have been broken in #5704 

## Triaging info

* Concourse version: 6.5.1
* Did this used to work? Yep

**Comment by chenbh** [comment]
> Perhaps the garden.ProcessSpec gets a default user assigned somewhere?
https://github.com/concourse/concourse/blob/95f7540e0e6b34c5db8ecef2b77108b50e8cc0c7/atc/worker/container.go#L86-L90

Which overwrites the container spec at:
https://github.com/concourse/concourse/blob/95f7540e0e6b34c5db8ecef2b77108b50e8cc0c7/atc/worker/container.go#L107-L110

**Comment by chenbh** [comment]
Interestingly, the only reason this works on Guardian is because we don't specify a user and it defaults to root. If we specify any other user it'll also fail to lookup: https://github.com/cloudfoundry/guardian/blob/c54a8e3e96c18e4b87c851bf8fdc967ca4d8effb/rundmc/users/lookup_linux.go#L19-L22

To test this, we can use any other user specified in clearlinux's passwd file:
```bash
$ docker run clearlinux getent passwd 
$ # alternatively we can do:
$ docker run clearlinux cat /usr/share/defaults/etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1::/:/usr/bin/nologin
...
$ cat task.yml
platform: linux
image_resource:
  type: registry-image
  source:
    repository: clearlinux
run:
  user: bin
  path: sh
  args:
  - -c
  - |
    ls -l .
$ fly -t dev e -c task.yml
executing build 4 at http://localhost:8080/builds/4
initializing
selected worker: f6323c18b20d
running sh -c ls -l .

Backend error: Exit status: 500, message: {"Type":"","Message":"unable to find user bin: no matching entries in passwd file","Handle":"","ProcessID":"","Binary":""}

errored
```

Going further, this seem to be a documented part of runC: 
https://github.com/opencontainers/runc/blob/46a304b5929fedfa4023f950fc0dab3f66883a97/libcontainer/user/user.go#L274-L280

And even docker doesn't properly support non root users
```bash
$ docker run clearlinux head -2 /usr/share/defaults/etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1::/:/usr/bin/nologin
$ docker run -it -u bin clearlinux
docker: Error response from daemon: unable to find user bin: no matching entries in passwd file.
```

**Comment by chenbh** [comment]
Just a side note that Aidan's example wouldn't fully work on Garden, it turns out the `ls .` command on clearlinux uses `statx` syscall, which is disallowed by [Guardian](https://github.com/cloudfoundry/guardian/blob/master/guardiancmd/seccomp.go) but allowed on Concourse's [containerd backend](https://github.com/concourse/concourse/blob/11e614d791c9562aa221171f4e2fa97941585d4b/worker/runtime/spec/seccomp.go#L304)

**Comment by analytically** [comment]
When using ClearLinux on Containerd I'm again seeing `lookup user: unable to find user root: no matching entries in passwd file` while this works fine using Guardian in 7.3.1.

**Comment by aoldershaw** [comment]
@analytically indeed it regressed 😞 looks like a38054a9fd58dba414e155ed763812e393894c4b is the culprit.
