### ISSUE TITLE
New builds don't trigger automatically when a pending build exists

### ISSUE THREAD

**Issue by akshaymankar** [concourse/concourse#6071]
## Summary

If a job has pending builds (for example, due to https://github.com/concourse/concourse/issues/5935), new builds don't get triggered automatically. But triggering the job manually works.

## Steps to reproduce

1. Create a job which has an unsatisfiable input and has `trigger: true` for at least one get. 
1. Trigger the job, watch it being pending forever.
1. Fix the unsatisfiable input
1. Trigger it manually, it will run.
1. Make new version of the trigger available, it will not trigger.

## Expected results

The job triggers a new build when a new version of the triggering input work.

## Actual results

The job doesn't trigger a new build.

## Additional context

We enabled jaeger tracing to see where it was failing. We could isolate the issue to [this SQL](https://github.com/concourse/concourse/blob/ea5c9b885894fe722ecd1febdc7b98d8b9a07394/atc/db/job.go#L687-L693). It fails to create a build when the job has _any_ pending builds.
This wouldn't have been a problem if we were able to cancel the old build (I see that, that issue is fixed in master), but this would still show up if a retrigger of an old build happens exactly at the same time as a new build is supposed to be triggered.

## Triaging info

* Concourse version: v6.5.1
* Browser (if applicable): N/A
* Did this used to work?: Don't know.

Pairing with @flokli

**Comment by jamieklassen** [comment]
tl;dr - this seems to really be "no builds get automatically created when a job has a stuck pending build"

Hmm, this really seems like a second-order effect of #5935, which is already a failure mode -- in theory, if a pending build exists there should never be a need to automatically trigger a new one. This is because pending builds do not yet have their inputs determined (more specifically they do not yet have a "plan"), so any pending build should automatically get the latest versions of any inputs by the time it goes into the "started" state. Does this make sense?
