### ISSUE TITLE
`.rb` executables are reported "not found" if used as `run.path`

### ISSUE THREAD

**Issue by cjcjameson** [concourse/concourse#620]
Within task config, if run.path refers to a file:
 - that ends in `.rb`
 - that is executable

And we run this task yaml in a `fly execute`, mounting in the source code with `-i`

We get an error message:
```
running gpdb_src/ci/concourse/scripts/generate_signed_s3_url.rb
exec failed: no such file or directory
```

We can work around this by:
1. Renaming the executable ruby file to not have the `.rb` extension
2. setting `run.path` to be `ruby` and having the file with `.rb` as the argument
3. writing a bash wrapper around this... we have executable files with `.bash` extensions in many of our task yml's and they don't have this issue

We don't know if this behavior manifests itself in the context of a pipeline; we're only `fly execute`ing right now

**Comment by xoebus** [comment]
What's the shebang line in the file?

**Comment by cjcjameson** [comment]
Darn, you know what: we had an issue with the shebang line and changed it some time today, but I don't remember what happened first. But if you're suspecting that:
`#!/usr/bin/ruby` would cause an issue
whereas
`#!/usr/bin/env ruby` would resolve it
Then I think you're probably right.

Again, I forget if that was the fix for us, in the heat of the moment. Glad to do a fuller repro if you need more information

**Comment by vito** [comment]
Yeah, I don't think this has to do with `.rb` - file extensions don't actually do anything themselves. It was likely the shebang line or lack thereof. Or it could be that the shebang line pointed to an executable that was busted (i.e. missing dynamic libraries).

The error emitted could mean one of many things, and is the same message you'd get when running the executable on your local machine (given the same conditions). Wrapping it feels weird since it may suggest things that aren't actually the problem, and would introduce some platform-specific messaging.

That being said, I'd accept a PR for a better message so long as it doesn't hide the original error. This just isn't a priority for us at the moment.
