### ISSUE TITLE
Build rerun should fail when required version no longer avaible

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#6215]
## Summary

See the screen shot:

![pending-rerun-build](https://user-images.githubusercontent.com/18585861/97267383-08015280-1865-11eb-9711-0e232ad53ba9.png)

The rerun build `1.13` is pending forever because the require version (git commit) is no longer available because the user did a git force push.

## Steps to reproduce

1. Create a pipeline that use a git resource.
2. Trigger a build.
3. Make a git force push to delete the commit that just triggered the last build.
4. Run the last build.

## Expected results

The rerun should fail as the require version is no longer available.

## Actual results

The rerun stays in "pending" state forever.

## Additional context

IMO, build rerun should assume all required version are there. Unavailable version should cause rerun to fail immediately.

## Triaging info

* Concourse version: 6.4.0
* Browser (if applicable): Doesn't matter
* Did this used to work? Not sure

**Comment by vito** [comment]
Yeah I just ran into this the other day. It's really confusing for jobs with a serial group / max in flight since the preparation shows up on the most recent build too, but really it's talking about the older rerun build which may be way offscreen.

**Comment by xtremerui** [comment]
@vito Trying to determine what status the build should be ended up with.

Normally, when we talking build `failed`, it means a build is started and it is finished with failed state. In this case, since the build preparation is never done and the build is in pending state (i.e. build never started), should it be considered `failed`?

Another option is `errored`. Do we consider a missing version of rerun build input an error?

I think `aborted` might fit here since we know the satifaction will never met so we will abort the build as soon as we can.

**Comment by mvdkleijn** [comment]
I agree `aborted` seems to fit best. The combination of `aborted` and a textual message stating the version is `no longer available` should be enough for people to understand what's going on.

**Comment by chenbh** [comment]
Closing as #6265 has been merged in
