### ISSUE TITLE
task check image hangs for long time

### ISSUE THREAD

**Issue by evanchaoli** [concourse/concourse#6217]
## Summary

During my debugging of some issue, workers were under heavy load, very slow, then on the GUI, I saw task's check image just hang for long time:

![task-check-image-hang](https://user-images.githubusercontent.com/18585861/97278122-50743c80-1874-11eb-8ab0-6c30d538ddc6.png)

@vito  PR #6153 is trying to show what is going on during image fetching, but in this case, there still didn't show any message, moreover, I couldn't abort the build.

My task just used `busybox` image that is tiny, and the image had been cached to an internal registry, thus DockerHub rate limit should not matter at all in my test.

One more confusion is, as I used a timer to trigger builds, and my tests used only `busybox` image, thus all workers should already cached the image, so that image fetching supposed to be skipped or quickly finished, why `check` still hang up here?

## Triaging info

* Concourse version: based on master branch
* Browser (if applicable):
* Did this used to work?

**Comment by evanchaoli** [comment]
After adding some debug log, I realized that image check hang at https://github.com/concourse/concourse/blob/master/atc/exec/check_step.go#L144. And it should check `ctx.Done` at https://github.com/concourse/concourse/blob/master/atc/engine/check_delegate.go#L97, so that build can be aborted.

With #6153, tasks that use same image will only be triggered in serial due to their image-checks need to acquire the same lock. I don't think Concourse used to behave so. As task `image_source` usually defines only image uri and tag, it's very possible many tasks of different pipelines use same image, then those task can only be triggered in serial, which sounds like a big regression.

**Comment by vito** [comment]
This is definitely worth optimizing in the next release or two. I noticed the same issue. These `check` containers were recently changed (https://github.com/concourse/concourse/commit/7b680b70fae9525ae85f1a6631a899eb99a0255e) to be build-owned rather than check-session-owned so we can skip the locking npw that there's no risk of concurrent access to the same container.

I wouldn't block v6.7 on this though - shipping before Nov 1 is more important, and this can be addressed shortly after.

> The problem is, all workers have cached `busybox` image, should image-fetching be skipped?

The workers have cached a particular *version* of `busybox` - so the `check` still needs to run to know if that's the version we want to use. This is the same as it was before.

We could add a flag like `--image-resource-check-interval` to check less often. That would be really easy to add; just need to pass the flag value to the `TaskStep` where it can set `Interval` in the `CheckPlan` it runs. We could even have a higher default like 10 minutes, since images don't really change *that* often and if the user wants to force a check they can just manually trigger the build.

> After adding some debug log, I realized that image check hang at https://github.com/concourse/concourse/blob/master/atc/exec/check_step.go#L144. And it should check `ctx.Done` at https://github.com/concourse/concourse/blob/master/atc/engine/check_delegate.go#L97, so that build can be aborted.

Good catch! This could definitely use a fix.

**Comment by evanchaoli** [comment]
@vito Is it possible to revert #6153 for 6.7? Otherwise I don’t think we can use 6.7 because of this issue.

**Comment by vito** [comment]
@evanchaoli we're gonna ship 6.7 without it - so just the cluster wide defaults + newer resource type versions.
