### ISSUE TITLE
Ensure correct migration ordering when merging from 6.7.2 into master

### ISSUE THREAD

**Issue by muntac** [concourse/concourse#6277]
## Summary

Currently `master` contains 38b12fa85e7269f0318271a250a5a70268862ad8. As 6.7.2 is the next LTS release, this commit was cherry-picked on to that branch as well. 

When the changes in 6.7.2 are merged back into `master` the migration ordering should be double checked to ensure that they work as intended.

From a rough merge I did locally this seemed to cause no issues in ordering. But further testing is advisable.

**Comment by vito** [comment]
We're gonna have to bump all the migrations that were on `master` and not shipped prior to v6.7.0 being released:

```
1599922285_add_instancevars_to_pipelines
1601752213_add_resource_id_to_builds
1601752214_drop_checks
1601752215_add_last_referenced_to_resource_configs
1601752216_alter_id_on_builds_bigint
```

Because `ci.concourse-ci.org` has already run these migrations, we'll need to figure out how to prevent it from running them again.

One way to do this could be to fake the timestamps so that they're newer than v6.7.2 (`1601993582_add_successful_build_outputs_rerun_of_index`) but older than the last migration that it ran (`1603405319_prepare_build_events_for_bigint_migration`).
