### ISSUE TITLE
Submit Concourse v6.7.3 for OSM Approval

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#6308]
## Background
As part of our commercial release of Concourse v6.7.2 we will need to submit the release for OSM legal review

## Summary

- [ ] Follow the steps outlined in the [OSM Document](https://onevmw-my.sharepoint.com/:w:/r/personal/yvikram_vmware_com/_layouts/15/Doc.aspx?sourcedoc=%7BC62CC711-3EC9-4F96-A6F9-3EBA0ACF2F2F%7D&file=concourse-osl-instructions.docx&wdLOR=c63A4CE53-385B-184E-AE0C-A226B0A86B00&action=default&mobileredirect=true) that @xtreme-vikram-yadav wrote.

**Comment by vito** [comment]
* Cloned `p-concourse Latest`.
* Assigned @chenbh as the release manager for `p-concourse 6.7.2`
* I don't see a `p-concourse-bosh-deployment` (referenced from the OSM Document) anywhere - not sure if that's still a thing, or if I just don't have access to it.
* Just waiting on approval at this point I suppose.

**Comment by chenbh** [comment]
The OSM config for `p-concourse-bosh-release` is pointing to the `master` branch, this resulted it in it only picking up the `+dev` builds instead of the `+rc` builds we use for releases: https://osm.eng.vmware.com/oss/#/release/20002/packages. This is likely a result of us cloning from `latest` and might affect more all the products, I'm going to try and figure out if we can change the base branch anywhere.

**Comment by muntac** [comment]
Created ODP files for all 4 releases using the instructions [here](https://onevmw-my.sharepoint.com/:w:/r/personal/yvikram_vmware_com/_layouts/15/doc2.aspx?sourcedoc=%7BC62CC711-3EC9-4F96-A6F9-3EBA0ACF2F2F%7D&file=concourse-osl-instructions.docx&wdLOR=c63A4CE53-385B-184E-AE0C-A226B0A86B00&action=default&mobileredirect=true&cid=ea93df33-2614-4660-a645-f308fbd1b7b1), and the package IDs listed in the LFR tickets. Sent them to ODP support for validation.

**Comment by muntac** [comment]
ODP has been structurally validated. Next step would be to post the link to the ODP tar file in the corresponding LFR ticket. Not sure if we wait for ticket to be closed before we can release on Tanzu Net.

**Comment by muntac** [comment]
Had to go through OSL and ODP steps again to ship 6.7.3 instead of 6.7.2. Needed to setup a new Norsk pipeline to upload packages off the release/6.7.x branch.

Next steps:

- [ ] Upload each release to Tanzu Net along with OSL and ODP
- [ ] Put the link to the Tanzu Net release on the ticket as the final step
