### ISSUE TITLE
Pull Windows worker terraform config into Greenpeace

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6316]
I set this up as a one-off for now, but it should be pulled into Greenpeace:

https://github.com/concourse/ci/tree/master/deployments/windows-worker

We'll probably want to parameterize the URL of the `concourse.zip` that it downloads and figure out when it should be deployed/updated. Maybe every time we ship? Maybe we should have a job to ship from `master` too, for when the worker version bumps?

note: @xtremerui noticed that if you ever RDP into the machine, Chocolatey stops working. So watch out for that. :laugh:

**Comment by aoldershaw** [comment]
@xtremerui and I migrated the windows and darwin workers over to Greenpeace.

We haven't actually redeployed the darwin worker, but it should be pretty much good to go when we're ready (just need to uncomment https://github.com/concourse/greenpeace/blob/10ee141673f04b69b3e423b7cd33960b0b567061/terraform/production/ci.tf#L119-L134). We're holding off because the terraform module doesn't actually create a new VM - it just reconfigures the MacStadium machine. If we were to redeploy now, we'd end up breaking darwin builds on CI (since it'd point to ci-test.concourse-ci.org). We will deploy it when we are ready to switch CI over to greenpeace.
