### ISSUE TITLE
Check put-only resources as long as they are erroring

### ISSUE THREAD

**Issue by vito** [concourse/concourse#6342]
With upgrading prod to a dev image that had `registry-image` v1.0.0, various resource checks failed because their workers had not been upgraded to the new version and did not understand the `tag` field that is now present in versions.

So these resources all errored, but then they were never checked again. They're all fixed by manually going around and clicking 'check' once the workers are ugpraded, but it'd be nice if I didn't have to do that.

Can we instead skip only successfully-checked put-only resources? I think this can be done with a tweak to the query.

**Comment by taylorsilva** [comment]
@vito Aidan and I were about to pick this up but we can't understand what the problem is exactly or how to reproduce it. Can more details be added please?

**Comment by vito** [comment]
@taylorsilva np!

So, now that we don't check `put`-only resources, if a `put`-only resource errors during a `check` nothing will ever `check` it again, so it'll just be errored until someone comes by and triggers a check manually.

This issue proposes that we amend the query...:

https://github.com/concourse/concourse/blob/9515586bd7a9153b1a52f5939f914f969c006cb2/atc/db/check_factory.go#L144-L148

...to include resources whose build has errored. It's a pretty minor quality-of-life improvement but it's nice to not have to go around all the pipelines triggering checks to make the errors go away. 🙂

**Comment by taylorsilva** [comment]
Sample pipeline with a put-only resource. Please note that this specific pipeline is NOT a good example of what would happen in the real world. It does allow us to test the problem for this issue though.
```yaml
resources:
- name: put-only
  type: mock
  source:
    check_failure: "error!!!!"

jobs:
- name: job1
  plan:
  - put: put-only
    params:
      version: "1.1.1"
```

The job will succeed. Checks for the resource are configured to always fail. Concourse will not check put-only resource so this fine overall. If we force a check (`fly check-resource`) then it will error and our pipeline will forever look like this:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/4583837/104211204-cadb4400-5401-11eb-8ece-f347f9d818c5.png">

In the real world, the put-only resource may have errored for some real reason (not because it's configured it haha) and therefore should be auto-checked to clear the error. Currently it will never be checked so our pipeline will have this errored resource until someone hits check-resource again for it.
