### ISSUE TITLE
missing worker name on error

### ISSUE THREAD

**Issue by drahnr** [concourse/concourse#6346]
## Summary

When an error occurs on a worker, the name is not printed, i.e.

![image](https://user-images.githubusercontent.com/667047/101281800-96a4b000-37d1-11eb-94cd-74409b697c13.png)

## Steps to reproduce

start a native concourse instance with 

1. `rm -rf /var/gdn` (which is normally recreated, but not when used with external garden server0 
1. `concourse worker --external-garden=http://127.0.0.1:7777 --tag=foo ...`
2. try to launch a job tagged with `foo`
3. observer

## Expected results

Error including the worker that had the issue.

## Actual results

Just a error message.

## Triaging info

* Concourse version: 6.7.2
* Browser (if applicable): firefox
* Did this used to work? I don't think so.

**Comment by chenbh** [comment]
This will be fixed in 7.0.0, due to a combination of https://github.com/concourse/concourse/pull/6022 and https://github.com/concourse/concourse/pull/5846. Since checks are now run as builds, they now print out the `selected-worker` build event

![Screen Shot 2020-12-07 at 3 52 09 PM](https://user-images.githubusercontent.com/17577073/101404191-4c403380-38a4-11eb-8328-4ae36ee6e528.png)
