### ISSUE TITLE
pq: nextval: reached maximum value of sequence "resource_config_versions_id_seq"

### ISSUE THREAD

**Issue by AndrewNeudegg** [concourse/concourse#6354]
## Summary

Concourse was unable to check for any new resources, no pipelines were able to run. Displaying the error:

```
run check step: save versions: pq: nextval: reached maximum value of squence "resource_config_versions_id_seq" (2147483647)
```

Although we only had `141431` entries:

```
concourse=> SELECT count(*) FROM resource_config_versions;
 count
--------
 141431
(1 row)
```

The data:

```
concourse=> select * from resource_config_versions order by resource_config_versions desc limit 10;
     id     |                   version                    |           version_md5            | metadata | check_order | resource_config_scope_id | span_context
------------+----------------------------------------------+----------------------------------+----------+-------------+--------------------------+--------------
 2147286180 | {"time": "2020-12-10T05:19:14.134465595Z"}   | 4d0d977d2d300856c4ba8914b1d646fb | []       |       27167 |                     1484 | {}
 2147216221 | {"time": "2020-12-10T05:12:23.072239534Z"}   | d85659bb1965d9b03ad2ab46e4ed8394 | []       |        1747 |                     2322 | {}
...
```

## Steps to reproduce

```
concourse=> \d+ resource_config_versions_id_seq
          Sequence "public.resource_config_versions_id_seq"
  Type   | Start | Minimum |  Maximum   | Increment | Cycles? | Cache
---------+-------+---------+------------+-----------+---------+-------
 integer |     1 |       1 | 2147483647 |         1 | no      |     1
Owned by: public.resource_config_versions.id
```

`resource_config_versions_id_seq` is an int, although `id` is a bigint:

```
concourse=> \d+ resource_config_versions
                                                         Table "public.resource_config_versions"
          Column          |  Type   | Collation | Nullable |                       Default                        | Storage  | Stats target | Description
--------------------------+---------+-----------+----------+------------------------------------------------------+----------+--------------+-------------
 id                       | bigint  |           | not null | nextval('resource_config_versions_id_seq'::regclass) | plain    |              |
 version                  | jsonb   |           | not null |                                                      | extended |              |
 version_md5              | text    |           | not null |                                                      | extended |              |
 metadata                 | jsonb   |           | not null | 'null'::jsonb                                        | extended |              |
 check_order              | integer |           | not null | 0                                                    | plain    |              |
 resource_config_scope_id | integer |           | not null |                                                      | plain    |              |
 span_context             | jsonb   |           |          |                                                      | extended |              |
 old_id                   | bigint  |           |          |                                                      | plain    |              |
 compacted_id             | bigint  |           |          |                                                      | plain    |              |
Indexes:
    "resource_config_versions_pkey" PRIMARY KEY, btree (id)
    "resource_config_scope_id_and_version_md5_unique" UNIQUE CONSTRAINT, btree (resource_config_scope_id, version_md5)
    "resource_config_versions_check_order_idx" btree (resource_config_scope_id, check_order DESC)
    "resource_config_versions_version" gin (version jsonb_path_ops) WITH (fastupdate='false')
Foreign-key constraints:
    "resource_config_versions_resource_config_scope_id_fkey" FOREIGN KEY (resource_config_scope_id) REFERENCES resource_config_scopes(id) ON DELETE CASCADE
Access method: heap
```

We added `old_id` and `compacted_id` while investigating.

## Expected results

- No error message.
- `resource_config_versions` `resource_config_versions_id_seq` does not grow in an unbounded way

## Additional context

Upon resolving the issue the id column in resource_config_versions began to skip entries immediately:
<img width="814" alt="Screenshot 2020-12-10 at 11 12 18" src="https://user-images.githubusercontent.com/12610365/101765240-f56f6f80-3ad8-11eb-8066-262963d4600e.png">

We resolved the issue by:

```
BEGIN;  
  -- create a temporary sequence to compact the ids
  CREATE SEQUENCE temp_resource_config_versions_id_seq;
  LOCK TABLE resource_config_versions IN EXCLUSIVE MODE;
  -- bump all ids above the sequence value
  UPDATE resource_config_versions SET id = id + CURRVAL('resource_config_versions_id_seq');
  -- update the main id column 
  UPDATE resource_config_versions SET id = NEXTVAL('temp_resource_config_versions_id_seq');
  -- reset the main sequence to be the next value
  ALTER SEQUENCE resource_config_versions_id_seq RESTART WITH NEXTVAL('temp_resource_config_versions_id_seq');
  DROP SEQUENCE temp_resource_config_versions_id_seq;
COMMIT;
```

This allowed us to continue using Concourse but we are unaware of the long term consequences.

- `enableGlobalResources: false`

## Triaging info

- Seems similar to https://github.com/concourse/concourse/issues/5667, but this issue relates to `resource_config_versions_id_seq` not `resource_config_versions_id`. 

* Concourse version: v6.6.0
* Browser (if applicable): N/A
* Did this used to work? N/A

**Comment by agurney** [comment]
Hi, I saw this because I'd previously written up #5667 (where another user had run into the maximum value, and my team had previously done some preventative maintenance to avoid it). I think this is the same issue, with the twist that it's manifesting slightly differently after the migration in https://github.com/concourse/concourse/pull/6016. That patch added
```sql
ALTER TABLE resource_config_versions ALTER COLUMN id TYPE bigint;
```

which, as seen here, _doesn't_ change the type of the associated sequence. In PostgreSQL, `bigserial` and the like when creating a table are just sugar for creating a sequence at the same time as a column that wants to use it. But it looks like `ALTER TABLE ... ALTER COLUMN` does not reach to also changing the type of the sequence, so there should be another migration to do
```sql
ALTER SEQUENCE resource_config_versions_id_seq AS bigint;
```

(I think this should also update the maximum value appropriately.)

By the by, I think the behavior with "skipped" values is due to the way that `nextval` works in the case of conflicts. For performance reasons, it doesn't try to do any fiddly synchronization, but just atomically increments until everyone who wants a value out of the sequence can get their own distinct value. Since there can be lots of resources all trying to get new versions at about the same time, there will tend to be conflicts of this kind. So it's basically expected, with the main implication being that the ID space is getting used up faster than one might thing from an initial back-of-the-envelope estimate of how frequently resource versions are created.

Comparing your SQL fix to mine in the linked issue, I'd suggest you check whether you should also update values in any other tables which make use of resource config version IDs. It should not matter for new versions created after the fix, but there may be some weird behaviors if the `next_build_inputs` (etc.) refer to version ids that don't exist or are for entirely different resources. I don't know enough about the build scheduling logic to make predictions here, but just have a sense that it is safest to update data in all of the places where it's used.

**Comment by odormond** [comment]
Hello,

We got bitten by this same issue today and altering the sequence type as suggested by @agurney fixed it properly as the maximum of the sequence is automatically updated.

Please consider adding a migration with it in the next release.
