### ISSUE TITLE
Documentation should include a conceptual diagram

### ISSUE THREAD

**Issue by sushiandbeer** [concourse/concourse#653]
The Concourse documentation should include a high-level conceptual diagram to help users understand the big picture.  While surely not 100% correct, perhaps something like this:

![concourse](https://cloud.githubusercontent.com/assets/9683151/18642617/37cd8c98-7e56-11e6-9927-f8c2b286183c.png)

**Comment by jama-pivotal** [comment]
@sushiandbeer we finally did it! uploaded the architecture diagram that was pin'ed on slack to the main Concourse docs here: http://concourse.ci/architecture.html 

Its a small update and we're going to need to add a lot more of these diagrams, but I'm going to close this issue for now since it technically solves the original request 😏
