### ISSUE TITLE
Create flag to config either local or LDAP credentials

### ISSUE THREAD

**Issue by scottietremendous** [concourse/concourse#6627]
## Summary

Currently, Concourse does not allow for users to login using `fly` if they have LDAP configured and login only works with local credentials. Implementing this type of workflow would be non-trivial. It also goes against the design decision to not directly handle any credentials that dex manages. 

However, perhaps we could add a flag to config using either LDAP or local credentials. 

This flag would need to be configured on both BOSH and Helm.

## Context

* Prior discussion: #6050

**Comment by xtremerui** [comment]
Another thing we could do is update [concourse dex password template](https://github.com/concourse/concourse/blob/master/skymarshal/web/templates/password.html) to the upstream one. 

With that the lable of `Username` could be dynamiclly rendered based on the dex password connector username prompt configure value.

**Comment by xtremerui** [comment]
Right now there are 3 connectors in upstream dex that supports username/password login (could be more in the future if certain connector starts to implement the [password connector interface](https://github.com/dexidp/dex/blob/f7d1405cfd91528a95ccfe9476c9fd9b6a991c2f/connector/connector.go#L45)):

atlassiancrowd
ldap
keystone

where in Concourse we only ported in ldap connector atm. For forward compatibility, instead of configuring LDAP or local, the flag could be an enum that allows concourse ops to choose the connector to use username/password to login with.
