### ISSUE TITLE
check-docker-mounts job failing on CI

### ISSUE THREAD

**Issue by taylorsilva** [concourse/concourse#6637]
## Summary

The check-docker-mounts job is failing likely due to a new Docker [release](https://github.com/moby/moby/releases/tag/v20.10.5).
## Steps to reproduce

Rerun the [job](https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/check-docker-mounts/builds/57.1). 

## Expected results
Job passes.

## Actual results

Fails with:
```
+ diff -Ebw docker-mounts expected_docker_mounts

5a6

> cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,name=systemd)

17d17

< none on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,name=systemd)

32a33

> tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,size=65536k,mode=755)
```

**Comment by aoldershaw** [comment]
Doesn't look like it's related to the new docker version - we reran the last successful build (using `Docker version 20.10.3, build 48d30b5`) and it still failed: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/check-docker-mounts/builds/55.1

**Comment by aoldershaw** [comment]
It started failing because we our workers were (accidentally) running using the Guardian runtime, whereas the expected mounts were produced on a container running the containerd runtime. Not sure what the differences are that caused the discrepancy, but given that this job is to help us detect changes in Docker to evaluate whether we need to make changes, this can be closed
