### ISSUE TITLE
Web nodes are not resilient to DB restart

### ISSUE THREAD

**Issue by g-fusion** [concourse/concourse#6726]
## Summary

Current Setup:
- Concourse v6.5.1
- Bosh deployment
- Bosh VMs are running Ubuntu 16.04
- Azure PostgresDB v11
- Enabled TLS for PostgresDB

When PostgresDB get restarted (due to standard maintenance window for example), Concourse web nodes cannot recover afterwards and service just stop and in traces we can see errors like: "write: connection reset by peer"

## Steps to reproduce

Restart IaaS provided PostgresDB

**NB**: The issue not reproducible with docker and external Azure PostgresDB 

## Expected results
Concourse Web nodes to auto recover (be resilient) against PostgresDB restart/unavailability

## Actual results
Concourse Web nodes got stuck i.e connections to PostgresDB are not evicted from connection pool

## Additional context
Similar [Issue](https://github.com/lib/pq/issues/1028) addressed in pq 

## Triaging info

* PQ Driver: Local build of Concourse 6.5.1 with pq driver 1.10.0 
* Did this used to work? Yes.

## Question 
* Can pq driver 1.10.0 be backported to 6.5?

**Comment by taylorsilva** [comment]
Hey, thanks for reporting this! We only make patches for the current release (usually security related) and for specific versions that we consider LTS for our enterprise customers. 6.7.x is currently an LTS branch. 

A customer ran into this issue on 6.7.3 and we applied the fix in the latest patch, 6.7.6: https://github.com/concourse/concourse/releases/tag/v6.7.6

We won't be patching 6.5.x, we don't even have the release pipeline for it anymore.

I am going to close this issue since it is already fixed in the latest release of Concourse and now also in 6.7.6.
