### ISSUE TITLE
Performance testing metrics for v7.x

### ISSUE THREAD

**Issue by navdeep-pama** [concourse/concourse#6735]
**Summary**:
Evaluate the metrics that we can track over releases to measure the change in Concourse's performance. This should help us determine the releases that are candidate for commercial releases. As well as give us indicators around the growth or degradation of Concourses baseline performance.

**Comment by clarafu** [comment]
Starting on this epic, the first thing I ran into was a problem with the greenpeace deployment where the vault ca certificate had expired. It took me a few days to figure out because I was unfamiliar with the infrastructure of greenpeace but the problem turned out to be solved by re-terraforming the vault module. This is automated by greenpeace already, but the job was not able to run because of a separate terraform bug that was unrelated. By manually running the job that terraforms the dispatcher, it recreated the vault ca certificate because it noticed that it had expired. After doing so, the problem was still persisting with things erroring with `x509: certificate has expired or is not yet valid`. The reason for this turned out to be that terraforming the dispatcher did not actually restart the vault pod so I had to do so manually by running `kubectl delete pod` within the container for the job `initialize-vault`.

**Comment by clarafu** [comment]
Here are some of my notes for the PRs that I'm going to try to stress test

- check containers = https://github.com/concourse/concourse/pull/7208 + https://github.com/concourse/concourse/pull/6022
- custom resource types = https://github.com/concourse/concourse/pull/7176 + https://github.com/concourse/concourse/pull/6153
- https://github.com/concourse/concourse/pull/6597
- streamed volumes = https://github.com/concourse/concourse/pull/6660

**Comment by clarafu** [comment]
I am starting my first stress test with a smaller number of workers, ATCs, pipelines and resources. I want to start off with a smaller deployment in order to get an idea of if the size of deployment matters when the deployment is under heavy load. These are the total starting stats for each small deployment (1 deployment using 6.7.8 called **baseline** and 1 deployment using 7.7.0 called **stress**), which I might end up tweaking:
- 80 pipelines
- 1000 unique resources
- 120 shared resources
- 200 unique resource types
- 80 shared resource types
- 440 jobs
- 2 ATCs (cpu: 1500m, memory: 1Gi)
- 12 workers (disk: 50Gi, cpu: 3000m, memory: 8Gi)

These are the initial metrics that I have observed after running these pipelines for a few days. Metrics that are horizontal: Left is stress env and right is baseline env. Metrics that are vertical: Top is stress env and bottom is baseline env.

![Screen Shot 2022-02-17 at 10 07 58 AM](https://user-images.githubusercontent.com/19290703/154510418-fa194682-bcda-4541-a255-65af26b0f3e4.png)

![image](https://user-images.githubusercontent.com/19290703/154510624-c8bcf7a2-f905-4c61-a9df-54bea56d786b.png)

![image](https://user-images.githubusercontent.com/19290703/154511062-38803c0a-0dbf-4573-ad2e-cf4eca8aff38.png)![image](https://user-images.githubusercontent.com/19290703/154511101-a5129a0b-4f47-495e-9a4c-9960be982c33.png)

![image](https://user-images.githubusercontent.com/19290703/154511226-0adb3942-540f-4ec1-bcf9-3651e2b70fe7.png)![image](https://user-images.githubusercontent.com/19290703/154511250-c5d03370-0d83-460a-8439-1a3396218a45.png)

![image](https://user-images.githubusercontent.com/19290703/154511305-9baffffa-1dcb-453a-b15d-389d8ab09a96.png)![image](https://user-images.githubusercontent.com/19290703/154511353-94bb12cd-fe30-4129-94a6-dc2427eb12db.png)

![image](https://user-images.githubusercontent.com/19290703/154511398-cafc7153-d7a7-456b-ba97-6dd5bef41ecc.png)![image](https://user-images.githubusercontent.com/19290703/154511427-eb26668a-7254-4480-a7b8-90a3fc318711.png)

![image](https://user-images.githubusercontent.com/19290703/154511539-f1f23ec3-a658-4b2e-a0cc-da8fda376ead.png)
![image](https://user-images.githubusercontent.com/19290703/154511562-992c9f92-db0f-42e3-a24e-d0a249092019.png)

![image](https://user-images.githubusercontent.com/19290703/154511933-d313bba4-a769-498b-8495-978f6567b4b4.png)![image](https://user-images.githubusercontent.com/19290703/154511974-9a1755ae-d570-4b0b-8cb4-c629fcf6c275.png)

![image](https://user-images.githubusercontent.com/19290703/154512082-6f528e66-4af9-432c-bc32-f9152465fd0f.png)![image](https://user-images.githubusercontent.com/19290703/154512055-dc2ac010-4884-4376-bea7-54d2fe7cc1f6.png)

![image](https://user-images.githubusercontent.com/19290703/154512212-dc86cf95-0a10-44ca-92db-86d0335d96e6.png)
![image](https://user-images.githubusercontent.com/19290703/154512251-aa2f6c88-70f9-4b65-9474-e48c374c9f0c.png)

<img src="https://user-images.githubusercontent.com/19290703/154513308-0562266d-bd48-44cb-82ee-5662c1252ad1.png" width="380" height="220"><img src="https://user-images.githubusercontent.com/19290703/154513365-15e4d7d5-cf1f-41ad-91b3-27b4a19951bf.png" width="380" height="220">

<img src="https://user-images.githubusercontent.com/19290703/154530213-433fd170-2f78-4028-a34c-4b5484dc780f.png" width="380" height="220"><img src="https://user-images.githubusercontent.com/19290703/154530242-6ea9731c-cc63-4af5-bdab-b1729aeac445.png" width="380" height="220">

<img src="https://user-images.githubusercontent.com/19290703/154530410-0175977a-d35f-41f5-ac55-92be4af68d85.png" width="380" height="200"><img src="https://user-images.githubusercontent.com/19290703/154530535-0e7cfe08-d194-4865-89c4-11d05b7c196c.png" width="380" height="200">

<img src="https://user-images.githubusercontent.com/19290703/154530438-c4f704d5-0a86-4fc1-b541-426f6f08bc8d.png" width="380" height="200"><img src="https://user-images.githubusercontent.com/19290703/154530571-e3e76585-88c4-4b12-8834-303771fdfc98.png" width="380" height="200">

![image](https://user-images.githubusercontent.com/19290703/154532475-83e17835-54de-4889-ba12-b9afe89ad747.png)
![image](https://user-images.githubusercontent.com/19290703/154532501-5884dad0-a1d3-4a00-ab29-e30edaabe9e2.png)

I wasn't able to get the worker metrics all in one graph so the following metrics are the ones for a single worker pod:
![image](https://user-images.githubusercontent.com/19290703/154533129-706859ad-8e86-42e8-a9e8-e3ac79cf8f19.png)![image](https://user-images.githubusercontent.com/19290703/154533162-205dc85b-3563-4179-9792-747ac23898f5.png)

Overall, I find that the baseline env is more performant than the stress env in a lot of the different metrics. Also when I take a look at the number of builds being scheduled for each job, it looks like the jobs in baseline has more builds scheduled/finished than the jobs in stress. All the checks seem to be run quickly for both deployments, I haven't seen a check that has not run within the check interval of a minute. There seems to be a few flaky container errors coming from both deployment, the baseline env seems to have a bit more than the stress env. These are the errors coming from baseline

```
run check step: run check step: check: Backend error: Exit status: 500, message: {"Type":"","Message":"runc exec: exit status 1: exec failed: container_linux.go:367: starting container process caused: read init-p: connection reset by peer","Handle":"","ProcessID":"","Binary":""}
```

And these are the errors coming from stress

```
ERRO[0011] checking origin concourse/git-resource failed: initialize transport: Get "https://index.docker.io/v2/": net/http: TLS handshake timeout 
```

**Comment by evanchaoli** [comment]
@clarafu Looks like your test result is quite different from my load tests result. With my load test, master branch + my in-review PRs, is much more performant than 6.7.8.

- Have you turned on `EnableCacheStreamedVolumes`?
- Have you turned on p2p streaming?
- Can you share your pipelines so that I can run your test model in my environment?

**Comment by clarafu** [comment]
@evanchaoli I have not turned on enable cache streamed volumes or p2p streaming because I wanted to keep the deployment as barebones as possible first since that is typically the configuration that our current large customers/users have set. I might try turning them on later as a test?

This is the setup pipelines that I am using https://github.com/concourse/drills/tree/master/longevity/7.x-test

**Comment by clarafu** [comment]
Just a quick update on the stress testing so far, my baseline environment (6.7.8) is running quite smoothly with a few flakey errors, approx 5% error builds, of the worker disconnecting during a build run. 
![image](https://user-images.githubusercontent.com/19290703/159507438-4f360243-23ff-4c3f-a25e-9a07e2cc1fcc.png)

My stress environment (7.6.0) is not doing so well with a lot of errors and build failures, approx 60% errors/fail builds, and they mostly all seem to be caused by heavily loaded workers.
![image](https://user-images.githubusercontent.com/19290703/159507392-6f364a2d-335b-450c-b3ea-107f2e86362c.png)

The workers seem to be filling up in disk space and some of them end up with heavy CPU load and high memory, which I think might be caused by the filling up of disk. I created some issues from the stress test investigations, but I will continue to look into the workers a bit more to see if there is anything else
1. https://github.com/concourse/concourse/issues/8159
2. https://github.com/concourse/concourse/issues/8160

**Comment by clarafu** [comment]
One thing that I have seen from the stress environment is some builds taking hours to complete. For example, the build shown below usually takes only a few seconds to finish.

![image](https://user-images.githubusercontent.com/19290703/159508744-0e769bda-50de-43cd-b666-2b142b449bb7.png)

After investigating a little, it seems like the reason is coming from waiting for the resource lock.

![image](https://user-images.githubusercontent.com/19290703/159508936-4d683649-9bc6-47ac-ab5c-91c0806cd66c.png)

It takes so long to wait for the resource lock because there are multiple other resources in other pipelines waiting for the same lock, and it can't get it when another resource currently has the lock and is taking a very long time to run it's get because of the workers being overloaded.

**Comment by clarafu** [comment]
I did some digging into what could be causing the increase in memory spikes that lead to the worker disk filling up, and I wasn't able to find any bug within the code that could be causing it. When I took heap dumps from the workers, the biggest usage of memory was `ssh.readPacket` which does not tell me much because when the worker is talking over an ssh connection that will cause the `ssh.readPacket` to increase in memory usage. 

![image](https://user-images.githubusercontent.com/19290703/161776762-b944dbfe-1f3a-4cad-8dd7-30c5c3853a6f.png)

Also, the amount of memory from the heap dump is a fraction of the memory usage that I see in the metrics. So I dug into the worker vm itself and it looked like there were a lot of get processes running, and the number of those get processes seemed to be increasing along with the worker memory. Maybe there is just a lot of work that is needed to be done and the worker vm was not able to keep up with all of it. And maybe there was some dependency bump between v6->v7 that made the workers run the processes a little slower or maybe something is causing it to schedule more gets onto select workers? 

In any case, I decided to increase the disk type from standard to ssd which will help with the processing of the gets. After switching to ssds, everything seemed to stabilize and the workers were able to keep up with the work. I'm going to change the disk type for the baseline workers and after that, I think I will up the workload to stress the environments more.
