### ISSUE TITLE
Instanced pipelines break build history

### ISSUE THREAD

**Issue by mvdkleijn** [concourse/concourse#6833]
## Summary

The build history of instanced pipelines is lost when variable values change due to the fact that those are considered "new" pipelines.

## Steps to reproduce

Create an instanced pipeline with var=A
Run pipeline
Change var=B
Witness previous build's history is gone

## Expected results

Instanced pipeline can be assigned an ID so the build history is retained.

## Actual results

Build history bye bye.

## Additional context

-

## Triaging info

* Concourse version: 7.1.0
* Browser (if applicable): -
* Did this used to work?

**Comment by taylorsilva** [comment]
Hey, so the pipelines are now identified by their "group" name and all their vars. This is how it was described in the RFC https://github.com/concourse/rfcs/blob/master/034-instanced-pipelines/proposal.md
and explained in the docs https://concourse-ci.org/instanced-pipelines.html

I'm guessing you got hit by the automatic archiving and were using the `set_pipeline` step to set you instance pipelines?
https://github.com/concourse/rfcs/blob/master/033-archiving-pipelines/proposal.md

I think a workaround for you right now would be to add to the list of pipelines you're setting with `set_pipeline` instead of updating the vars for the pipeline. Then the "old" pipeline won't be archived and it's build history will be viewable still.

**Comment by mvdkleijn** [comment]
Hey there @taylorsilva thanks for the reply. I actually hadn't realized that there is automatic archiving going on. This might indeed explain it, I'll have to check that tomorrow.

What we're doing is building Docker containers with specific versions of apps inside them. The version is used as a variable in the pipeline instance. This would mean there are only a few builds in each instance and potentially lots of pipelines in the scenario that you describe. Not an ideal case.

I quite liked the idea of having instanced pipelines with the version variable shown in the UI... it would allow us to see the versions of the various apps in once glance. However, if this is impossible, I guess I could try a sub-optimal route and dig the version out of a file or hardcode it in the Dockerfile or something.

**Comment by taylorsilva** [comment]
Yes, I see how that would get noisy really fast. I would probably try and add whatever app(s) version you're tracking as resources to your pipeline instead. That feels like the more concourse way to interact with the app versions as inputs to your pipelines. Then build history would persist.
