### ISSUE TITLE
Across step errors don't show an orange outline in the builds page UI

### ISSUE THREAD

**Issue by clarafu** [concourse/concourse#6846]
## Summary

It looks like when there is an error within one of the across steps, it doesn't wrap the box with an orange line like it does when any other step errors. This is what I expect it to look like (but with a orange line)

![Screen Shot 2021-04-08 at 4 35 36 PM](https://user-images.githubusercontent.com/19290703/114092929-77558680-9888-11eb-8f96-0c91c3853c4f.png)

And this is what it looks like

![Screen Shot 2021-04-08 at 4 33 08 PM](https://user-images.githubusercontent.com/19290703/114092945-7d4b6780-9888-11eb-9d67-e6f7dd74f40d.png)

## Steps to reproduce

Create a job that uses an across step and have one of the steps error.

## Triaging info

* Concourse version: 7.1.0
* Browser (if applicable):
* Did this used to work? Not sure?

**Comment by aoldershaw** [comment]
Looks like this is because we render the step header using the `step.state`:

https://github.com/concourse/concourse/blob/e9357da9881f7d20db0bbfa6bcfc4af682cac874/web/elm/src/Build/StepTree/StepTree.elm#L772

However, for the `across` step, this may not be representative of the status of the substeps. Unlike concrete steps like `task`/`get`/`set_pipeline`, the state of the across step should be derived from the substeps. Each subheader (i.e. the header that shows the variable combinations) derives its state here:

https://github.com/concourse/concourse/blob/e9357da9881f7d20db0bbfa6bcfc4af682cac874/web/elm/src/Build/StepTree/StepTree.elm#L617-L618

We should do the same for the top-level header

**Comment by taylorsilva** [comment]
@chenbh and I dug into this a bit more and figured out that the atc is not sending a finished event for the across step when the build errors.

events from a failed build, matching Clara's first screenshot:
```
id: 27
event: event
data: {"data":{"origin":{"id":"606de39e"},"time":1617823460},"event":"initialize","version":"1.0","event_id":"27"}

id: 28
event: event
data: {"data":{"time":1617823460,"origin":{"id":"606de39e","source":"stderr"},"payload":"\u001b[1;33mWARNING: the across step is experimental and subject to change!\u001b[0m\n"},"event":"log","version":"5.1","event_id":"28"}

id: 29
event: event
data: {"data":{"time":1617823460,"origin":{"id":"606de39e","source":"stderr"},"payload":"\n"},"event":"log","version":"5.1","event_id":"29"}

id: 30
event: event
data: {"data":{"time":1617823460,"origin":{"id":"606de39e","source":"stderr"},"payload":"\u001b[33mfollow RFC #29 for updates: https://github.com/concourse/rfcs/pull/29\u001b[0m\n"},"event":"log","version":"5.1","event_id":"30"}

id: 31
event: event
data: {"data":{"time":1617823460,"origin":{"id":"606de39e","source":"stderr"},"payload":"\n"},"event":"log","version":"5.1","event_id":"31"}

id: 32
event: event
data: {"data":{"origin":{"id":"606de39e"},"time":1617823461},"event":"start","version":"1.0","event_id":"32"}

....

id: 3876
event: event
data: {"data":{"origin":{"id":"606de39e"},"time":1617824700,"succeeded":false},"event":"finish","version":"1.0","event_id":"3876"}
```

Events from an errored build, matching the second screenshot:
```
data: {"data":{"origin":{"id":"60a3b8e0"},"time":1621433938},"event":"initialize","version":"1.0","event_id":"31"}

id: 32
event: event
data: {"data":{"time":1621433938,"origin":{"id":"60a3b8e0","source":"stderr"},"payload":"\u001b[1;33mWARNING: the across step is experimental and subject to change!\u001b[0m\n"},"event":"log","version":"5.1","event_id":"32"}

id: 33
event: event
data: {"data":{"time":1621433938,"origin":{"id":"60a3b8e0","source":"stderr"},"payload":"\n"},"event":"log","version":"5.1","event_id":"33"}

id: 34
event: event
data: {"data":{"time":1621433938,"origin":{"id":"60a3b8e0","source":"stderr"},"payload":"\u001b[33mfollow RFC #29 for updates: https://github.com/concourse/rfcs/pull/29\u001b[0m\n"},"event":"log","version":"5.1","event_id":"34"}

id: 35
event: event
data: {"data":{"time":1621433938,"origin":{"id":"60a3b8e0","source":"stderr"},"payload":"\n"},"event":"log","version":"5.1","event_id":"35"}

id: 36
event: event
data: {"data":{"origin":{"id":"60a3b8e0"},"time":1621433939},"event":"start","version":"1.0","event_id":"36"}

# finish event is missing
```

Because the finish event is never sent the step defaults to "interrupted"
<img width="759" alt="image" src="https://user-images.githubusercontent.com/4583837/119689920-410f9e80-be17-11eb-91a2-d83aaa2ba341.png">
