### ISSUE TITLE
Group URLs are not consistently updated when switching between pipelines.

### ISSUE THREAD

**Issue by charlieoleary** [concourse/concourse#702]
In 2.3.1, the links to groups will not have their URLs consistently updated as you switch between pipelines.  In our case, all pipelines have the same group names available to them (develop and release).

Flow:

1. Start out at one pipeline, viewing the develop group (/team/main/pipelines/pipeline1).
2. Select pipeline2 from the hamburger menu.
3. Click on pipeline2's release group.
4. You will occasionally end up at /team/main/pipelines/pipeline1?groups=release instead of pipeline2?groups=release.

Here is how you can reproduce:

1. Create two pipelines with at least two groups.
2. Open the default pipeline then open the hamburger menu.
3. Select the pipeline you are currently NOT viewing.
4. Click on the group you are currently NOT viewing.

**Comment by DylanGriffith** [comment]
Hi @charlieoleary do you think it's possible this is a timing issue? Are you clicking the pipeline then quickly clicking the "release" group? I think we can reproduce the issue when we add some latency so it is probably what you're describing. We're just wondering since if it happens even if you're clicking links slowly then it may actually be a different issue to what we think.

**Comment by charlieoleary** [comment]
Hey @DylanGriffith  -- even when clicking slowly (waiting 10s+) it still ends up at the wrong link.
