### ISSUE TITLE
load proc: no running process found: process does not exist task: not found

### ISSUE THREAD

**Issue by reynico** [concourse/concourse#7056]
## Summary
A very small set of pipeline runs fails after 3-5 minutes with the following error:

```
backend error: Exit status: 500, message: {"Type":"","Message":"load proc: no running process found: process does not exist task: not found","Handle":"","ProcessID":"","Binary":""}
```

## Steps to reproduce

We trigger a fixed set of pipelines with [bors](https://github.com/bors-ng/bors-ng). 1/50 pipelines hangs after 3-5 minutes with the error "load proc: no running process found: process does not exist task: not found" in the same Concourse worker. Retrying the pipeline is enough to get the job done.

## Triaging info

* Concourse version: v7.2.0
* Did this used to work? yes, on v6.5.0
* Workers are EC2 machines with:

```
Linux ip-10-10-1-76 5.4.0-1047-aws #49-Ubuntu SMP Wed Apr 28 22:47:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

This is pretty similar to https://github.com/concourse/concourse/issues/6632

**Comment by chenbh** [comment]
I have some questions to see if it's caused by the same bug as #6632 

1. Is there any stdout output before the container errored? A key indicator was that none of the containers on the worker generated any output during the worker drain timeout (`CONCOURSE_CONNECTION_DRAIN_TIMEOUT` which defaults to 1h)
1. Are the erroring containers scheduled onto the same worker? If a worker experiences this problem, then all running containers on that worker will error
1. If the error repeats, do they roughly repeat in the same interval? If it's caused by worker rebalancing like the other issue, you might be able to see a pattern of it erroring every 5 hours.

In the meantime you can try waiting for [7.3.0](https://github.com/concourse/concourse/issues/7032) which contains the fix for #6632

**Comment by reynico** [comment]
Hi!

1. Yes, the normal stdout for the pipeline. 
2. Different workers (we run 4 workers).
3. Mmm no, not so repeatable


Right now I'm building a new AMI for Concourse v7.3.0, I think we can close this for now. What ya think?

**Comment by pratikbalar** [comment]
Facing this same issue sometime… it's like worker become slow and, then suddenly it gets this error and fail all running jobs in that worker
```
backend error: Exit status: 500, message: {"Type":"","Message":"load proc: no running process found: process does not exist task: not found","Handle":"","ProcessID":"","Binary":""}
```

Worker running on Ubuntu 20.04 server.

**Comment by chriseaton** [comment]
I am still see this in 7.6.0.
```
{"timestamp":"2021-12-29T01:11:21.530728647Z","level":"error","source":"worker","message":"worker.garden.garden-server.attach.failed","data":{"error":"load proc: no running process found: process does not exist task: not found","handle":"f7808240-4c24-4171-4d3c-02908dbb84d9","session":"1.4.12249"}}
```

**Comment by pratikbalar** [comment]
> Facing this same issue sometime… it's like worker become slow and, then suddenly returns this error and fail all running jobs in that worker
> ```
> backend error: Exit status: 500, message: {"Type":"","Message":"load proc: no running process found: process does not exist task: not found","Handle":"","ProcessID":"","Binary":""}
> ```
> 1. Yes, stdout as usual
> 2. tag tasks, resources, get steps with that worker for one specific pipeline
> 3. I can't see any pattern
> 
> Worker running on Ubuntu 20.04 server.

Not updated concourse to 7.6.x yet, will update in this one.
