### ISSUE TITLE
Disable the action re-run in the UI by ACL

### ISSUE THREAD

**Issue by aladjadj** [concourse/concourse#7204]
**challenge**
Currently when a user has not the permission to perform the re-run action, the button is not disabled, and the call is emitted with http-code 403 in return without information ( eg: popup )

**what would make this better**

- Disable the button in the UI
- Open a popup or a tooltip to inform the user about his rights

**Comment by chenbh** [comment]
The best way I can think of to implement is by looking at the role of the user and making the assumption that if they have the `viewer` role, then the shouldn't be able to trigger new builds, or rerun old ones.

If we want to get fancy (since [RBAC](https://concourse-ci.org/user-roles.html#action-matrix) allows you to assign individual actions to different roles), there probably needs to be some way to fetch the actions a user/role can do, and then add logic in the build page to disable if they don't have permission to perform such action.

A third way is to disable the button if the CreateJobBuild or RerunJobBuild API call returns 403. This should be easy to implement, but it does require the user clicking on the button before they get any feedback.

Either way, this isn't very high on our priorities list, but we would welcome any community PRs.
