### ISSUE TITLE
Global Resources build check spikes

### ISSUE THREAD

**Issue by taylorshaulis** [concourse/concourse#7350]
## Summary

Enabling Global Resources causes check spikes ~~and occasionally duplicate checks running at the same time~~.

Disabling Global Resources will cause all checks to always run but they will normalize how many checks are running at a given time

## Steps to reproduce

Use docker compose to spin up concourse
https://github.com/concourse/concourse/blob/master/CONTRIBUTING.md#running-concourse

Add the environment variable CONCOURSE_ENABLE_GLOBAL_RESOURCES: "true" to the web.environment portion of the docker-compose.yml file.

Start up 30 of the same hello world pipelines. I have attached the hello-world-pipeline and the mass create/destroy script.

[hello-world-pipeline.yml.txt](https://github.com/concourse/concourse/files/6895711/hello-world-pipeline.yml.txt)
[mass.sh.txt](https://github.com/concourse/concourse/files/6895715/mass.sh.txt)

Watch the build status using fly
watch -n5 "fly -t test bs -c 100 | grep started | grep repository"

## Expected results

1 repository/check given the resource is the exact same across all 30 pipelines.

## Actual results

30 repository/checks

~~Sometimes duplicate checks of the same resource run resulting in 50-60 checks during the current interval.~~

## Additional context

We can actually force the expected behavior of global resource checks by constantly checking one of the pipelines repository resource.  Including a script that will constantly check the repository resource for the first pipeline.
[checkloop.sh.txt](https://github.com/concourse/concourse/files/6895791/checkloop.sh.txt)

With the check loop running we only ever have 1 repository/check running at a time.

Also if we redo the setup without global resources enabled and not using the check loop all 30 pipelines will always check however after running for a couple minutes the checks will normalize out and no longer be spikes.  Only 5-10 checks will be running at any given time.

## Triaging info

* Concourse version: 7.3.2
* Browser (if applicable): NA
* Did this used to work? No clue. Just recently discovered this

**Comment by taylorshaulis** [comment]
Retested with concourse version 7.4.0

No longer getting duplicate checks.

The expected result of 1 check across all pipelines vs actual result of 30 checks is still happening.  
Running the check loop script is still able to force the expected result.

**Comment by clarafu** [comment]
@taylorshaulis Curious as to how are you determining that 30 checks have run for the resource? With global resources, your time resource will still check individually for each pipeline because time resources never share versions. For your git resource that should only result in one check for all the pipelines. Each pipeline will run a check step for the resource but only one of those check steps will actually execute a full check and the others will not (they will wait for the lock and grab the resulting version from the check step that ran). I just want to make sure that you are seeing 30 checks happening from the logs in the check build because that is the easiest way to see if the check step actually ran. For example, you should see some build logs if a check actually ran.
![Screen Shot 2021-08-23 at 10 31 46 AM](https://user-images.githubusercontent.com/19290703/130465431-00b419fd-f83f-4278-b128-1348e805ce40.png)

**Comment by taylorshaulis** [comment]
I tested with concourse 7.6.0 and I am no longer able to reproduce this issue.
I believe this is now resolved

**Comment by taylorshaulis** [comment]
To clarify this did not resolve the problem. The 7.6.0 update removed the ability to reproduce the problem using the fly cli.

I am going to leave this closed and push for Jenkins.
