### ISSUE TITLE
Enumerated State Resource Type (as opposed to versioned)

### ISSUE THREAD

**Issue by danger-ranger** [concourse/concourse#739]
## A Modest Proposal

Some types of automation work can be very awkward to implement using versioned resources.

One such use case is  triggering jobs based on the state of a PCF installation to keep its tiles up to date.

I would like to propose an alternative to the existing resource api - enumerated state resources.

The check script would return an integer corresponding to a predefined set of states.
The get script could maybe return some additional state metadata, but I don't know why this would be necessary
The put script would be more of a confirmation - I made a change that should be reflected in a change to a new state.

P.S. All of this is presupposing that Concourse wants to be a flexible automation tool, not just an opinionated CI tool. Restricting users from using concourse for CI antipatterns may well outweigh the usefulness of supporting more maintenance-oriented automation work.

**Comment by vito** [comment]
Not sure how to tackle this. Could you provide more background on what kind of workflow you're trying to achieve? (Or just close it if you don't remember - it's been a while. 😄 )

**Comment by xtreme-gavin-enns** [comment]
So this might just be that we were trying to tackle a problem in a non-concoursey way, or that it's not really an appropriate problem for concourse.

Two workflows that we found awkward to implement in concourse were:
1) Running a cleanup job for every environment lock in a "dirty" pool. This problem seems to mostly go away if you have a pipeline for each environment instead of on shared pipeline. 
2) The other had to do with having a pipeline to automatically apply tile updates to a single foundation. I can't recall what the difficulties were, but it probably had to do with the difficulty of idempotence when using an incomplete API (this was a while ago when ops manager made a lot less of it's state visible).

If you're interested I can spend some time to flesh these ideas out more, but I'm not working on this type of problem anymore so I don't mind if you just want to close this.

**Comment by vito** [comment]
This feels like something that could be accomplished with concourse/rfcs#1, so I'll just close as it's been pretty inactive otherwise.
