### ISSUE TITLE
[Feature Request] Filtering pipelines in the main view

### ISSUE THREAD

**Issue by tushar-dadlani** [concourse/concourse#754]
# Feature Request

## What challenge are you facing?

We have a large number of pipelines maintained by our team. The scrollbar for the pipelines is great. We are facing a challenge of filtering the list of pipelines based on a search string. We currently use the Find feature of our browser but believe it would be great if we could do this filtering from the concourse UI itself. 

## A Modest Proposal

Filter box, which allows us to filter pipelines that we can currently see within our view.

**Comment by jraqula** [comment]
+1 to this. Furthermore, it would be nice to have a few extra criteria for search than just pipeline name -- for example, search by full or partial job name and see pipelines that have a job that matches.

**Comment by jama-pivotal** [comment]
We finally did it! ...kind of. The new dashboard in Concourse v3.5.0 and v3.6.0 supports filtering on the dashboard page. Here's a list of the basic commands we implemented: 

Search by pipeline name #1682
Search by pipeline status #1703
Search by team name #1684

We're moving towards a world where the dashboard is the new landing page, and becomes a new method of navigation to other teams and pipelines. 

Closing this issue for now, since it is unlikely for us to implement filtering on the existing sidebar with all the work that's happening on the dashboard and new pipeline views! Feel free to reopen if you really really want that sidebar search though.
