### ISSUE TITLE
Scrolling is broken of Brave Browser and Chrome 

### ISSUE THREAD

**Issue by Eulerizeit** [concourse/concourse#782]
When I try and scroll with a long output I can't get off the bottom of the screen. 

https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/gpdb_master/jobs/icg_gporca_codegen_centos6/builds/183

# Bug Report

Bug reports are pretty free-form; just replace this with whatever. If applicable, though, please include steps to reproduce. Help us help you!

The following can also be handy:

* Concourse version: 2.4.0 and 2.5.0
* Deployment type BOSH
* Browser: brave	0.12.9 AND Chrome Version 54.0.2840.98 (64-bit)

**Comment by rosenhouse** [comment]
We're seeing the same thing.  There are two weird bits:

1. The list of builds seems to be centered, sort of, instead of left-aligned:
<img width="683" alt="build-bar-shifted" src="https://cloud.githubusercontent.com/assets/4128521/20765392/f14c909c-b6e6-11e6-8350-b3cd5a8b79b9.png">


2. We can't scroll up: https://drive.google.com/file/d/0Bx9k3GiR0tm6bjlWNW1qS3N2aUk/view

**Comment by pdelagrave** [comment]
Having the same scrolling issues as @rosenhouse with Firefox 49.0.2 and Version 54.0.2840.98 (64-bit) both on OSX 10.11.6, on Concourse 2.5.0.

**Comment by stepanstipl** [comment]
I had similar problem with chrome ` 54.0.2840.71` and looks like updating to `56.0.2924.76` solved this issue for me & scrolling is working as expected.

**Comment by inercia** [comment]
Same with Version 54.0.2840.100 (64-bit) on OpenSUSE

**Comment by vito** [comment]
Consolidating into https://github.com/concourse/concourse/issues/1930
