### ISSUE TITLE
Downgrade to 7.4.0 database (1625844436) fails

### ISSUE THREAD

**Issue by Eeems** [concourse/concourse#7857]
## Summary

When attempting to downgrade the database to 7.4.0 as instructed in the 7.4.3 release notes it fails.

## Steps to reproduce

Run `concourse migrate --migrate-db-to-version=1625844436` on a 7.4.2 database.

## Expected results

The migration should work and allow us to upgrade to 7.4.3.

## Actual results

```
error: could not migrate to version: 1625844436 Reason: migration '1625844437_drop_build_event_id_seq.down.sql' failed and was rolled back: pq: invalid input syntax for type integer: "select max(event_id) from pipeline_build_events_"
```

## Triaging info

* Concourse version: 7.4.2
* Did this used to work? No idea.

**Comment by clarafu** [comment]
Thanks for reporting this issue, there is a bug in the downgrade script 

https://github.com/concourse/concourse/blob/a421efde8fd9e572f6084188039aca213347ef28/atc/db/migration/migrations/1625844437_drop_build_event_id_seq.down.sql#L17

it is missing the second `|` in that line after `pipeline_build_events_'`.

Really sorry for the inconvenience, it seems like our upgrade/downgrade tests did not properly test out this downgrade script.

**Comment by Eeems** [comment]
Is there anything I can do to work around this, or will I have to wait for a new version to fix it?

**Comment by clarafu** [comment]
I think I'm going to create a script that you can run against your database that will fix it and then you will be able to downgrade back to 7.4.0!

**Comment by Eeems** [comment]
It would probably be a good idea for someone to update the release notes with a reference to this just in case others are planning to downgrade.

**Comment by Berber31** [comment]
@clarafu
> I think I'm going to create a script that you can run against your database that will fix it and then you will be able to downgrade back to 7.4.0!

Where the *.sql are located in the concourse docker image ? in didn't found them with a `find / -name *.sql` in the docker image

**Comment by Berber31** [comment]
@clarafu 
> I think I'm going to create a script that you can run against your database that will fix it and then you will be able to downgrade back to 7.4.0!

Do you plan to provide a 7.4.4 with a migrate binary fixed to downgrade database to 7.4.0 ?

cause we face off the same issue with our production environnement.

Thanks

**Comment by AndoniLarz** [comment]
> @clarafu
> 
> > I think I'm going to create a script that you can run against your database that will fix it and then you will be able to downgrade back to 7.4.0!
> 
> Do you plan to provide a 7.4.4 with a migrate binary fixed to downgrade database to 7.4.0 ?
> 
> cause we face off the same issue with our production environnement.
> 
> Thanks

Hi, I'm interested too in knowing when there will be a fix on this.

**Comment by jamesmealing** [comment]
Hi, any idea when 7.4.4 with the database downgrade fix will be released?

**Comment by clarafu** [comment]
I've been sick the past week so I am now working on the script and releasing 7.4.4

**Comment by jamesmealing** [comment]
Sorry to hear you've been unwell! 😕 But glad to hear 7.4.4 is coming soon. 😊

**Comment by clarafu** [comment]
I've created a script that contains

```
#!/bin/bash

set -ex

PGPASSWORD=$CONCOURSE_POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 --username=$CONCOURSE_POSTGRES_USER --host=$CONCOURSE_POSTGRES_HOST --dbname=$CONCOURSE_POSTGRES_DATABASE --port=$CONCOURSE_POSTGRES_PORT <<EOF
do \$$
declare
    b record;
    startValue int;
begin
    for b in
        select id, name, pipeline_id, team_id from builds where status = 'started' and completed = false
    loop
        raise notice 'dropping sequence build_event_id_seq_% ...', b.id;
        execute 'drop sequence if exists build_event_id_seq_' || b.id;

        if b.name = 'check' then
            execute 'select max(event_id) from check_build_events where build_id=' || b.id into startValue;
        elsif b.pipeline_id is null or b.pipeline_id = 0 then
            execute 'select max(event_id) from team_build_events_' || b.team_id || ' where build_id=' || b.id into startValue;
        else
            execute 'select max(event_id) from pipeline_build_events_' || b.pipeline_id || ' where build_id=' || b.id into startValue;
        end if;

        if startValue is null then
            startValue := 0;
        else
            startValue := startValue + 1;
        end if;

        raise notice 'creating sequence build_event_id_seq_% ...', b.id;
        execute 'create sequence build_event_id_seq_' || b.id || ' minvalue 0 start with ' || startValue;
    end loop;
end \$$;

DELETE FROM migrations_history WHERE version = 1627322257;
EOF
```

And done some manual testing and it seems to work. Basically what this script does is run the down migrations necessary for downgrading from 7.4.1 or 7.4.2 and also **removes** the history that the up migration that was included in 7.4.1 or 7.4.2. This is a little different from what a proper downgrade does to your database but I needed to do it this way because of a little unfortunate situation (if you want to know more I explain it in more detail here https://github.com/concourse/concourse/issues/7884)

**So for users that are currently on 7.4.1 or 7.4.2, if you run the script that I pasted above you will be able to upgrade to 7.4.3, 7.5.0 or 7.6.0. Or if you want you can also downgrade back to 7.4.0 (you will NOT need to run any `concourse migrate` commands anymore to downgrade to 7.4.0 if you run the script).** 

The script requires you to have the `psql`, access to your postgres database and also the following environment variables that you should already have from starting concourse `$CONCOURSE_POSTGRES_PASSWORD`, `$CONCOURSE_POSTGRES_USER`,  `$CONCOURSE_POSTGRES_HOST`, `$CONCOURSE_POSTGRES_DATABASE`, `$CONCOURSE_POSTGRES_PORT`.

**Comment by jamesmealing** [comment]
Thanks, @clarafu. Just to confirm, if I am already on 7.4.0, having downgraded from 7.4.2 but without having run `concourse migrate` at any point, am I okay to run the above script as-is on 7.4.0 and I am then back to "normal", ready to upgrade to a later version (7.4.3, 7.5.0 or 7.6.0)?

**Comment by clarafu** [comment]
@jamesmealing I'm just curious, after you downgraded back to 7.4.0 without running `concourse migrate`, is everything running smoothly? Do you see any errors in your web logs or any builds that are started and are stuck and cannot finish? But to answer your question, yes you are correct that you can run the script above and then be able to upgrade to any later version (7.4.3, 7.5.0, 7.6.0).

**Comment by jamesmealing** [comment]
@clarafu I'm not convinced they are, to be honest, but it's difficult to say for sure. We have Concourse deployed in AWS and use auto-scaling for certain worker pools and, since all of this kicked off with the 7.4.* upgrade path, we have seen a notable increase in workers getting stuck `retiring` when EC2 instances are terminated. We have also seen a slight increase in the number of stuck builds, however, not significant I don't think.

Our web logs have quite a lot of the following type of error:

> "pq: relation \"build_event_id_seq_15848821\" does not exist"

Is this likely to be related, do you think?

Thanks for the confirmation on running the downgrade script.

**Comment by clarafu** [comment]
Yes that error message is definitely related. If you run the script it should fix those build event seq does not exist errors.

**Comment by jamesmealing** [comment]
Awesome, thanks, @clarafu. I'll aim to give this a try soon. 👍

**Comment by AndoniLarz** [comment]
Hi ! Just to say I tested the script on a preprod instance and it seems it worked fine. I just had to adapt the env vars names according to those I have and it ran smoothly. I checked the `migrations_history` table and it's correct . Thank you for this quick fix !

**Comment by AndoniLarz** [comment]
I executed the script on the production instance. It worked fine for most of the cases since we saw a massive decrease in SQL related errors but one remained.
The error was on a job that had 3 builds :
- the first 2 were cancelled
- the third one was in a `pending` status, with `aborted` being `true`

The `select max(event_id) from pipeline_build_events_3711 where build_id=71038653;` request gave a `null` result, so I manually created the sequence with this request :
`create sequence build_event_id_seq_71038653 minvalue 0 start with 0;`

This one helped to deal with this last edge case.

**Comment by igor-nikiforov** [comment]
@clarafu thank you so much! Script worked as expected, successfully upgraded to 7.4.3 from 7.4.2.

**Comment by Eeems** [comment]
Finally got around to running this and it seems to have worked. Thanks again!

**Comment by clarafu** [comment]
@AndoniLarz Thanks so much for the information, that's actually very useful because that pending build was not fixed by my script. I'll update the script and the migration with this, thanks!!
