### ISSUE TITLE
Access metadata from task

### ISSUE THREAD

**Issue by mastertinner** [concourse/concourse#790]
## What challenge are you facing?

It would be nice to access the environment variables (e.g. `$BUILD_PIPELINE_NAME`) that we have in resources also in tasks. Is there a way to do that? If not, this is a feature request ;-)

These are the variables I'm talking about: https://concourse.ci/implementing-resources.html#resource-metadata

**Comment by databus23** [comment]
The are not exposed to task deliberately. Quoting the [docs](https://concourse.ci/implementing-resources.html#resource-metadata):
> They should not be used to emulate versioning (e.g. by using the increasing build number). They are not provided to task steps to avoid this anti-pattern.

That being set there are ways to workaround it: https://github.com/vito/build-metadata-resource

**Comment by mastertinner** [comment]
Cool. Thanks for the quick reply, @databus23!

**Comment by mwmahlberg** [comment]
I would like to reopen the discussion. While it is true that build numbers should not be used to emulate versioning, one might very well want to keep track of builds themselves in external tools. Case in point: [Artifactory's build integration](https://www.jfrog.com/confluence/display/JFROG/Build+Integration). The jfrog CLI needs a build number and name during at _compile time_ to be able to collect all necessary metadata, for some package types even at the time of dependency resolving (think `npm install`).

The current "solution" would be to have a custom resource type that collects those build informations during an additional `get` step and save them in a file. Since this course of action would lever out the precaution of not having build information available during the build anyway, I think it would make sense to provide the build information.

One could argue that it would be rather easy to use a `semver` file for the build number and a fixed string for the build name. However, due to the nature of pipelines, one code version might be compiled multiple times against different dependencies with the same qualifier: Say the base image for a Spring application changes: You might want to have the 1.0.0 version of your spring application be tested on the newsiest bugfix release of the `openjdk:8` image. Without build numbers, the build report generated could only overwrite the existing one. That is a less than ideal situation, especially in some compliance contexts.

**Comment by jmhwang7** [comment]
> I would like to reopen the discussion. While it is true that build numbers should not be used to emulate versioning, one might very well want to keep track of builds themselves in external tools. Case in point: [Artifactory's build integration](https://www.jfrog.com/confluence/display/JFROG/Build+Integration). The jfrog CLI needs a build number and name during at _compile time_ to be able to collect all necessary metadata, for some package types even at the time of dependency resolving (think `npm install`).
> 
> The current "solution" would be to have a custom resource type that collects those build informations during an additional `get` step and save them in a file. Since this course of action would lever out the precaution of not having build information available during the build anyway, I think it would make sense to provide the build information.
> 
> One could argue that it would be rather easy to use a `semver` file for the build number and a fixed string for the build name. However, due to the nature of pipelines, one code version might be compiled multiple times against different dependencies with the same qualifier: Say the base image for a Spring application changes: You might want to have the 1.0.0 version of your spring application be tested on the newsiest bugfix release of the `openjdk:8` image. Without build numbers, the build report generated could only overwrite the existing one. That is a less than ideal situation, especially in some compliance contexts.

We have a similar use case where we're sending test results from concourse to Datadog and want that metadata information to allow users to go from the Datadog UI to the associated build in the Concourse UI. The datadog results are sent during the task step, and I haven't found a way of providing metadata to the task. Trying to use a resource (ex. https://github.com/SWCE/metadata-resource/issues/8 ) to retrieve metadata during the get step to inject it to the task is not reliable, because Concourse caches resources and doesn't allow you to run the `check` step every time the resource is used.

**Comment by evanchaoli** [comment]
@jmhwang7 Please change to use https://github.com/olhtbr/metadata-resource, which is a proper implementation. To avoid the cache problem, metadata should be fetched by a `put` step.
