### ISSUE TITLE
Question - Updating Concourse with Concourse itself

### ISSUE THREAD

**Issue by mvdkleijn** [concourse/concourse#797]
Hi there!

We're running Concourse on Openstack using Bosh (which works well by the way) and today I thought I'd setup a simple pipeline to automatically update Concourse's stemcells and release. I've set this up using the standard bosh concourse resources.

This worked up to the point where Bosh started actually deploying stuff. Then the output cut out and the build seems to have been timed out / errored. The build log ends at:

```
     Done compiling packages > guardian/acbf14a4f6a062ff197f13e07247d2aab9c507ef (00:00:52)
     Done compiling packages > atc/af364fc230bbeda0295171c2fd48fb42375402e1 (00:00:34)
     Done compiling packages > postgresql_9.3/f8b7a26f105b921843fa5565818b50cc45ace6af (00:02:40)
     Done compiling packages (00:05:34)
```

Logically speaking I'm not that surprised. The worker starts the bosh deployment and eventually gets killed off whilst the bosh deployment happily keeps running on the director. Eventually the deployment is finished and concourse seems to be updated fine.

However, I was wondering if there's a better / advised way to do it? Are you doing this yourselves? Are you using two concourse installs for example?

Sorry if this is an obvious question, I'm fairly new to Concourse.

**Comment by vito** [comment]
You pretty much covered all of it. Self-deploying works, the build just doesn't tend to go green, either because the VM running it gets torn down, or we fail to re-attach (Guardian still needs some tuning for this to work properly).

We're adding draining real soon though, which will kinda break this since Concourse will wait on its own job to finish. We'll probably add an `interruptible` attribute or something to builds to hint that the draining process shouldn't wait. We have this problem ourselves as the `bosh-deploy` job at https://ci.concourse.ci deploys over itself.
