### ISSUE TITLE
All pipelines set with `set_pipeline` step archived after upgrade to 7.7.0

### ISSUE THREAD

**Issue by mymasse** [concourse/concourse#8167]
## Summary

We have setup our Concourse to follow the gitops for setting pipelines (https://blog.concourse-ci.org/gitops-for-pipelines/) and have a pipeline which makes use of the `set_pipeline` step to manage all our pipelines. After the upgrade from 7.6.0 to 7.7.0 at the first run of the master pipeline all child pipelines were archived.

## Steps to reproduce

- Follow blog mentioned above to create self updating pipelines with Concourse 7.6.0.
- Upgrade to 7.7.0
- Run the self-updating pipeline

## Expected results

Pipelines are updated (if required)

## Actual results

All pipelines were archived

## Additional context

Wondering if related to #8102 

## Triaging info

* Concourse version: 7.7.0
* Browser (if applicable):
* Did this used to work? Yes

**Comment by mymasse** [comment]
We downgraded our concourse back to 7.6.0 and re-ran our master pipeline and the all came back.

**Comment by evanchaoli** [comment]
@mymasse Can you describe more details on how that happened? Did your first run succeed or fail? Why do you consider the problem is caused by #8137?

**Comment by xtremerui** [comment]
pinning @clarafu just in case.

**Comment by clarafu** [comment]
@mymasse Do you know if the parent job that is responsible for all the `set_pipeline` steps for the child pipeline had a failed/errored build as the latest build when you saw all the child pipelines get archived?

**Comment by clarafu** [comment]
Oh btw https://github.com/concourse/concourse/pull/8137 never made it into 7.7, so I think that pr is supposed to fix what you saw happen here.

**Comment by gid0** [comment]
We're also impacted by this issue, self-updating pipelines were archived the first time they ran after the 7.6.0 to 7.7.0 upgrade.
The pipelines use set_pipeline: self.

**Comment by gid0** [comment]
Re. the fix here: https://github.com/concourse/concourse/commit/79cbc87931e08ab00f17e7fa3daa4f78b8406866
And its description:

> If the last build of the parent pipeline was a failed/errored build that
> did not get to the set_pipeline step for the child pipelines...

I'm not sure the fix will be enough. In the following screenshot we can see the previous build (87) was **successful**. The one that archived the pipeline was 88 (first build after 7.6.0 to 7.7.0 upgrade). The build was triggered, the `set_pipeline: self` task updated and archived the pipeline, then the following task failed because the pipeline was archived ("action not allowed for an archived pipeline" error in the task).

![Screenshot from 2022-03-23 18-31-43](https://user-images.githubusercontent.com/18396223/159761054-99ab947f-265c-4e48-9149-94690ae64910.png)

**Comment by gid0** [comment]
Ok so our self-updating pipeline archives itself at every single run, it's not a one-time issue because of the migration path now, it's just completely breaking the self-updating pipelines. Please reconsider the 7.8.0 milestone as 7.7.1 would be more appropriate.

**Comment by gid0** [comment]
It seems to happen after "set_pipeline: self" is executed twice in a row *with a change*.
When I execute "fly set-pipeline" and then trigger the self-update job, everything's fine. After another execution of "set-pipeline: true" with a change in the pipeline, it archives the pipeline. When there is no change during the second execution, the pipeline is not archived.

**Comment by evanchaoli** [comment]
@clarafu For @gid0 's case, as `set_pipeline` step should never archive pipeline, I guess the logic is, `set_pipeline` step that changed `self` that led `check-resources` to fail, then `build.Finish()` archived the pipeline:

https://github.com/concourse/concourse/blob/7c7a1e029b4b51c0a8744accf86831b8442707e4/atc/db/build.go#L748-L772 

@gid0 can you please show what error task `check-resources` hit?

**Comment by divyamudundi** [comment]
Team,
We upgraded concourse couple of days back from 7.6.0 to 7.7.0. And yesterday we noticed that our pipeline got archived after the set_pipeline: self step ran. So we set the pipeline again. But looks like this is not a one time issue. Appreciate if this can be fixed quickly. As cannot downgrade.

**Comment by gid0** [comment]
@evanchaoli sure, here's the screenshot, but the error saying that the pipeline was archived was also in my previous post. This task does a "fly check-resource". It only proves the pipeline was archived by the set_pipeline step because this one completed with no issue.

![Screenshot from 2022-03-24 14-00-57](https://user-images.githubusercontent.com/18396223/159922202-05bf8061-1264-44ea-a06e-de3e92f9f66f.png)

**Comment by divyamudundi** [comment]
We also have same issue
<img width="779" alt="Screen Shot 2022-03-24 at 6 37 13 PM" src="https://user-images.githubusercontent.com/36238259/159922838-fefd38ba-2efa-4337-8884-f72241df59bf.png">
:

**Comment by chbiel** [comment]
we also have a similar problem but we don't use `set_pipeline: self` but always reference the actual name of the pipeline like

```
- set_pipeline: the-pipeline-name
   file: git/pipeline.yaml
```

We also don't see any correlations between failing builds and the "removed pipelines".
And we also don't see any errors or log messages like the ones in the other comments above.

In our case the pipelines get removed more or less randomly. In one night 3 of 10 pipelines got removed (or archived, we could not find that out clearly).

**Comment by gid0** [comment]
This issue really impacts us and we can't run our pipelines any more.

My question is: if I spend some time creating a test-case pipeline with which you can reproduce the issue 100%, will a developer be available to fix the issue and will there be a Concourse 7.7.1 release ASAP?

We can't wait for the next minor version so if the answer to the previous question is no, then we'll just save some time not implementing a test-case and working on a workaround on our side that will allow us to run our pipelines.

**Comment by gid0** [comment]
That is awesome. Can we do something to help @clarafu? I was talking about writing a test pipeline to demonstrate the issue, would that still be useful?

**Comment by clarafu** [comment]
Thanks for the offer! :) I just have to wait on a pipeline to run through and I'll be able to ship a patch version.

Also, I actually decided to remove the line that introduced the bug in https://github.com/concourse/concourse/pull/7895 because I'm worried about missed edge cases. The purpose of that line was to help with cleaning up child pipelines that are no longer set by the parent job, but we have a query that runs after a build finishes that should help do that for us (the one below)

https://github.com/concourse/concourse/blob/4f3bb8fb4916cf8ff8cc918ed81580f84e418420/atc/db/build.go#L751-L762

**Comment by clarafu** [comment]
It's taking a bit of time because the production pipelines were failing with some changes to go 1.18 with darwin workers. Just got that fixed so it should be going through the pipeline now.

It is after my work hours so latest I will have the patch release is on Monday. If this is really a blocker, you can actually build concourse using the fixed code in the 7.7.x branch https://github.com/concourse/concourse/tree/release/7.7.x and use that image in your deployment.

**Comment by clarafu** [comment]
7.7.1 is out! https://github.com/concourse/concourse/releases/tag/v7.7.1

**Comment by gid0** [comment]
@clarafu I just deployed it and confirm it fixes the pipeline archiving bug for us. Thank you so much!

**Comment by mymasse** [comment]
@clarafu I can also confirm this is now working correctly with 7.7.1.
