### ISSUE TITLE
Latest linux package is 1.4gb

### ISSUE THREAD

**Issue by raggi** [concourse/concourse#8491]
It includes a whole bunch of large rootfs.gz files

![image](https://user-images.githubusercontent.com/348/180341381-602d2acd-5bfb-41aa-95e7-d33f8555e3fe.png)

**Comment by pn-santos** [comment]
The linux package includes a bunch of resource types (e.g. `registry-image`, `git`, `docker-image`) that's why it's so large.

**Comment by lrstanley** [comment]
Yeah, believe this is a non-issue. The release has been relatively large for quite some time, and there isn't really much that can be done about it. All of the included artifacts are correct, and the larger ones can't really be made smaller, due to their dependencies on items like the `git` package and similar.

```console
$ du -hx --max-depth 3 | sort -rhk 1
1.7G    .
1.2G    ./resource-types
354M    ./bin
276M    ./resource-types/pool
223M    ./resource-types/semver
211M    ./resource-types/tracker
147M    ./resource-types/hg
134M    ./resource-types/git
96M     ./resource-types/docker-image
83M     ./fly-assets
25M     ./resource-types/registry-image
23M     ./resource-types/s3
19M     ./resource-types/github-release
19M     ./resource-types/cf
14M     ./resource-types/bosh-io-stemcell
12M     ./resource-types/mock
11M     ./resource-types/time
7.4M    ./resource-types/bosh-io-release
```

The Windows/Darwin variants only include what's necessary to run worker variants of Concourse.
