### ISSUE TITLE
Need Access to Host Directories in Worker

### ISSUE THREAD

**Issue by idcmp** [concourse/concourse#857]
# Feature Request

## What challenge are you facing?

I work in an environment where certificates, credentials, license keys, keystores, etc are all kept on a central server accessed via SOAP. When a user wants access to an item on that server, they first provide their username/password in a SOAP call and the server returns an "access token". Further SOAP calls supply the "access token". 

Hosts can also be authenticated. This is done by giving a set of files in a specific directory to a command line tool. These files are specific per host. The result of running this tool is an "access token".

I have tasks running in containers that require access to license keystores, credentials, etc and require an access token to obtain these items.

## A Modest Proposal

I'm no Jonathan Swift, but Concourse workers could have named volumes available to them. (Garden supports adding BindMounts to the ContainerSpec). I could then ideally define the volume as a resource (workers that don't have a volume with the same name would be ignored).

**Comment by vito** [comment]
I say this not to necessarily dismiss your use case but more to provide the viewpoint from Concourse's principles.

Configuration and authentication living on the workers is the path to darkness. Workers are supposed to be stateless homogeneous VMs blindly running container workloads. The moment we add an outlet for folks to reach state on the host is when things start to break down. For example, you can no longer safely run pull requests, because your containers can reach your credentials. I imagine some folks would also think they need to install dependencies on the host VM, too, which is a big no-no (and part of the reason for using containers).

We've got a story and a plan for improving credential handling (#291) - do you see a path forward from there by chance?

**Comment by idcmp** [comment]
I appreciate that the host of workers should be stateless and interchangeable, but I sense that as Concourse grows people will start to find ways around this. 

#291 falls short in a few aspects.  First, we already have a secret management system in place. It's been audited, hardened and despite it shortcomings, serves us well. More importantly, it has good traction from dev teams who are actively storing credentials/keystores/etc in it. Switching to Vault, or even introducing a level of indirection would be a non-starter for us. :-(

Second, the contents of the files I'm looking to use are different per host. 

I'm not suggesting the entire host filesystem be arbitrarily exposed, just the subdirectory needed.

I'd also be open to having a pre-exec for certain tasks which provide environment variables into the container; not sure if that helps or not? In this scenario I would run the CLI tool on the host machine and ship the "access token" into the container to be used.

Thoughts?

**Comment by farcaller** [comment]
Bump with a similar use case: I want to set up a chain of trust from kubernetes cluster concourse workers are running on into the pipeline workload. Kubernetes will mount a service account token within the worker's container, but there's no way to mount that further into the pipeline at the moment.

**Comment by jama-pivotal** [comment]
Would ya'll be able to take advantage of the work done in #1027 with distributed certificates management on workers? probably doesn't help your full breadth of use cases

**Comment by cloud-rocket** [comment]
I think this is sometimes mandatory feature when drivers on host are needed to be accessed (i.e. Nvidia GPU enabled containers) - https://github.com/concourse/concourse/issues/2353

**Comment by makslevental** [comment]
i need to be able to do this in order to run tests against real live data that's too big to stick somewhere else (hundreds of GB). is there really no way to do this?

**Comment by vito** [comment]
@makslevental Nope - not right now.

I could see an argument being made for a worker-side configuration of directories to expose to all tasks that run on it. :thinking: We obviously want to prohibit access to the host machine's filesystem by default, but if we make it an operator-level decision then it would probably be fine.

Would read-only access be sufficient? Or is read-write necessary? I'm thinking read-only should be good enough for accessing drivers (@cloud-rocket) and data that's only used as an input for processing. Allowing read-write would be very tricky to coordinate.

This would also probably require the task to be privileged, because otherwise the file permissions for the directory mounted in won't align with the task's user namespace.

So, I guess my proposal then is to allow a worker to configure a map of host-side directories to bind-mount read-only into privileged tasks?

We probably won't get to this ourselves, but if we can agree on a starting point this seems like something that could be PR'd.

**Comment by makslevental** [comment]
for me read only would be fine. right now what are my options? to get this done though? i'm thinking sshfs with the host? is that possible or are there network permissions things i'm not anticipating

**Comment by vito** [comment]
@makslevental Never tried it, but something like that would probably work. Bear in mind you won't be able to ssh to `127.0.0.1` since that'll just access the container's own network, not the host VM. Your container would probably need to SSH to the private IP of the worker. I'm not sure how much that'll buy you though, since it'll end up going over the local network anyway.

At that point it might be comparable to just putting it in a locally deployed blobstore or GCS and using a resource (i.e. gcs) to fetch it. The artifact will be cached on the worker, so it would only be downloaded once. Transfer speeds to/from GCS are very very fast within the same infrastructure. I'm not sure what infrastructure you're on, though.

**Comment by makslevental** [comment]
@makslevental i'm on prem so that's not possible for me

**Comment by makslevental** [comment]
@vito i guess sshfs isn't possible either? https://stackoverflow.com/a/55765064

**Comment by idcmp** [comment]
Closing as it has been 2.5 years and I've long since moved away from looking at Concourse. 

If someone needs this feature, please open a new ticket and reference this one.
