### ISSUE TITLE
Any docker directory named dev is empty

### ISSUE THREAD

**Issue by beano** [concourse/concourse#904]
# Bug Report

* Concourse version: 2.6.0
* Deployment type (BOSH/Docker/binary): binary
* Infrastructure/IaaS: Ubuntu 16.04
* Did this used to work? Don't know

It seems that  any regular directory named "dev" is empty when a task is executed inside a docker container. See the following Dockerfile for a repro. 

- This issue does not appear when  docker is invoked directly. 
- Once the  task starts executing it is possible to create and populate new directories named "dev"
- This appears to be a problem if the directory is created in the Dockerfile only

I suspect that this is due to some code that  assumes directories named "dev" are device directories. I've not attempted to confirm this however.

```
FROM ubuntu:latest

RUN mkdir -p /test_dir/dev
RUN mkdir -p /test_dir/dev2

RUN echo "hello1" > /test_dir/dev/hello1
RUN echo "hello2" > /test_dir/dev/hello2

RUN echo "hello1" > /test_dir/dev2/hello1
RUN echo "hello2" > /test_dir/dev2/hello2
```

```
root@6393b89d-f836-4c75-5df4-ce1a10a5e233:/test_dir# ls -l dev
total 0
root@6393b89d-f836-4c75-5df4-ce1a10a5e233:/test_dir# ls -l dev2/
total 8
-rw-r--r-- 1 root root 7 Feb  1 00:59 hello1
-rw-r--r-- 1 root root 7 Feb  1 00:59 hello2
root@6393b89d-f836-4c75-5df4-ce1a10a5e233:/test_dir# 
```

**Comment by williamhaley** [comment]
I can confirm this same issue. I was torn on whether or not it was caused by concourse, but after some additional testing I'm positive it is. 

Below is a contrived/trivial example. However, I was seeing this on a real system at work and, unfortunately, it was super frustrating to debug. I had a `node_module` with a `dev` subdirectory, and I was pulling my hair out trying to figure out why it was empty. I thought it was an `npm` or a `yarn` problem, but it's clear to me now that, somehow, concourse is deleting the contents of that directory.

```
FROM alpine

RUN mkdir -p /test/dev
RUN touch /test/dev/1.txt
RUN touch /test/dev/2.txt
```

```
docker build --tag williamhaley/test-concourse-issue .
docker run --name test-concourse-issue -it williamhaley/test-concourse-issue sh
```

```
# find /test
/test
/test/dev
/test/dev/2.txt
/test/dev/1.txt
```

The contents are there, as you'd expect.

However, if I run that same image in concourse, the `dev` directory is empty.

```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: williamhaley/test-concourse-issue
    tag: latest

inputs:
- name: scripts

run:
  path: scripts/test-concourse-issue.sh
```

```
#!/bin/sh
set -e -x

find /test
```

```
fly -t lite execute --config $HOME/test-concourse-issue.yml --input scripts=$HOME/scripts
```

```
initializing
running scripts/test-concourse-issue.sh
+ find /test
/test
/test/dev
succeeded
```

The files under `dev` are gone. All contents deleted when run with concourse.

This issue only seems to affect directories named `dev` that are baked into the image. Not directories named `dev` created at run-time. So my workaround is to ensure that any file tree containing a `dev` dir cannot be baked into the image. It must be added at run-time.

**Comment by vito** [comment]
https://github.com/concourse/docker-image-resource/commit/6a9153480c64f776a5305b3553d9c301ccc8e4e9

**Comment by williamhaley** [comment]
This issue still exists. I can't use concourse with my node build environment because directories named `dev` aren't respected. I completely forgot about this and it bit me again today.

Unfortunately, I have no simple way to handle this since it is a vendor directory in a subtree named `dev`
