### ISSUE TITLE
flight-school doc does not work, gives ""

### ISSUE THREAD

**Issue by yngvark** [concourse/concourse#934]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Bug report

## What challenge are you facing?

The example in http://concourse.ci/flight-school.html doesn't work. 

Below the text `Ok, let's save that in build.yml and run our command again.` the command is `fly -t ci execute -c build.yml`

This yields `error: missing required input `flight-school``.

I have run the previous steps successfully. The `build.yml` file is in a directory one level up from `flight-school`.

Side note: I'm new to Concourse. The docs does not describe what an input actually _is_. It just says "Required. The expected set of inputs for the task." 

* Concourse version: 2.7.0

edit: missed a word

**Comment by ClaraFuPivotal** [comment]
You need to run `fly -t ci execute -c build.yml` within the `flight-school` directory because `fly execute` takes the working directory as the input. You can read about that in the second paragraph here : http://concourse.ci/fly-execute.html

I'm not sure why your build.yml file would be in a directory one level up from `flight-school` because in the docs it specifies "so we need a file called build.yml. Let's create it under the flight-school directory" and there was also a previous step before this to `cd flight-school`. Maybe you might've `cd`ed to another directory while you were pasting the commands or you can show me the commands you ran so that I can understand if there's anything we can improve in our docs? 

I totally agree with your opinion on how the docs do not describe inputs correctly, we will definitely need to do some work on that part of the docs. Thanks for your input!

**Comment by perfumister** [comment]
I'm also new to Concourse and experienced the same issue as _yngvark_.

I think the problem might be that we both may have been confused by the `path` in the `run` section, which (somewhat confusingly) implies that the build file would need to be in the folder containing the flight-school input.

After re-reading the instructions, it's not until after the file is created that we encounter the following clarification:

* The final run section describes how Concourse should run the task. By default Concourse will run your script with a current working directory containing all of your inputs as subdirectories.

Maybe just a little more up-front clarity might also be helpful.

**Comment by jama-pivotal** [comment]
Hi @perfumister and @yngvark I'm going to close this issue for now. The tutorial is written using a Socaratic approach and does have a flaw of creating intentional failures from you to learn from. That might not be so helpful for folks who are doing this tutorial in a rush. I think there would be value in creating a more direct tutorial for those who just want to dive right into it. That said, If you have any suggestions on where to include the clarification I'd be more than happy to pull it in.
