### ISSUE TITLE
 $TERM not set

### ISSUE THREAD

**Issue by mbhave** [concourse/concourse#94]
We are running our tests on the concourse pipeline using ```./gradlew run```. This seems to work fine on our docker image locally and also on gocd, where we do a docker run. It fails on our concourse pipeline with ```Could not open terminal for stdout: $TERM not set```.

**Comment by xoebus** [comment]
@mbhave Thanks for reporting this! The current workaround is to set `TERM` yourself in your script before you run `./gradlew`. See [here](https://github.com/seadowg/windsock-android/blob/09bad7fb671e7c58d57105943f9b1ab52f0d3389/concourse/test) for an example. We'll see what the best course of action is here to match the Docker behavior.

@goonzoid @julz It looks like Docker sets the `TERM` environment variable when you run `docker run -t ...`. How do you think this should be reflected in Garden?

**Comment by julz** [comment]
At first pass this seems like something the client needs to tell us: why not pass TERM as an env var in the process spec? Our general policy has been (with some historic exceptions) that garden should be unopinionated and defer to clients about things like this. We spin up a container exactly how you ask, you tell us if you want to add TERM etc. Does setting the env var on the spec work for this use case?

Sent from my iPhone

> On 3 Aug 2015, at 18:51, Chris Brown <notifications@github.com> wrote:
> 
> @mbhave Thanks for reporting this! The current workaround is to set TERM yourself in your script before you run ./gradlew. See here for an example. We'll see what the best course of action is here to match the Docker behavior.
> 
> @goonzoid @julz It looks like Docker sets the TERM environment variable when you run docker run -t .... How do you think this should be reflected in Garden?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

**Comment by xoebus** [comment]
@julz Yep, that works. It's more of a question of whether or not we should match Docker semantics ~***magically***~ than how we'd accomplish the same thing in Garden.

**Comment by julz** [comment]
Yeah magic is what I'd like to avoid. Better to let the client decide explicitly when we can, I think. Garden is more like runC (soon, even more so ;) than docker.

Sent from my iPhone

> On 3 Aug 2015, at 19:49, Chris Brown <notifications@github.com> wrote:
> 
> @julz Yep, that works. It's more of a question of whether or not we should match Docker semantics ~magically~ than how we'd accomplish the same thing in Garden.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU

**Comment by xoebus** [comment]
@julz Ok, makes sense - thanks!

@goonzoid Sound good to you?

**Comment by goonzoid** [comment]
Yeah, I agree with @julz here.

**Comment by xoebus** [comment]
@goonzoid Ok, thanks.

@mbhave Looks like that workaround above is the recommended way to actually do this. We're slightly different from Docker in this respect. I'm going to close this for now but please feel free to re-open if something comes up.

**Comment by mbhave** [comment]
ok we'll do that. thanks everyone!
