### ISSUE TITLE
Control of the limits of the task container

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#954]
# Feature Request

## What challenge are you facing?

I have a set of tests that require more file handlers than the default setup of 1024 that currently the concourse containers run with.

## A Modest Proposal

No idea - whatever way that I can control this value.

**Comment by clarafu** [comment]
We don't configure any limit, so it may just be inheriting the system default. Can you increase it with `ulimit`?

**Comment by ggeorgiev** [comment]
I cannot increase it inside the container. If I understand correctly from the system you mean the worker? - if so the container does not inherit the limit from the system.

**Comment by kmacoskey** [comment]
## A big  +1  for this feature request. 


Our need is slightly different, and we have dug into the issue a bit.

### Background

Specifically, we want to have the ability to change the core file size kernel limit. We are interested in this because our developers want the ability to hijack a container and core dump processes with a large memory footprint. In addition the product that they are developing already emits very large core dump files when it encounters an error, and those files are currently getting truncated.

### Technical bits

In our digging we know that the task processes are inheriting it from the garden process which in turn eventually gets it inherited from the VM's init process, which gets the defaults from the kernel.  This means that we have to lean on setting those params with garden, which it can do. 

For any non-login process the kernel has hard coded [defaults](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/asm-generic/resource.h?id=0ac1ee0bfec2a4ad118f907ce586d0dfd8db7641#n78). These limits are set for the init process and can be viewed with `cat /proc/1/limits`.  Every other process inherits its limits from its parent unless it makes a call to the os to modify its own limits with `setrlimit()`.  This means that if no intervention is taken, core file size will set the container to have soft limit 0 and hard limit unlimited.  Garden does have the ability to take a `json` [struct](https://github.com/cloudfoundry/garden/blob/66dfda27625680cbe8c9d864392426f452aa0cf6/container.go#L333) to modify these limits for the containers it spawns, but Concourse does not take advantage of that when [spinning up containers](https://github.com/concourse/atc/blob/fbcb0a46d5ee6b5a5cb2f9138afba680a85dfe1a/exec/task_step.go#L206).

### Proposed Feature

The feature could look like a field when specifying the configuration of the image for a task that is a string of the json structure that can be passed down into garden's `Limits` [defined here](https://github.com/cloudfoundry/garden/blob/66dfda27625680cbe8c9d864392426f452aa0cf6/container.go#L333) and used [here](https://github.com/cloudfoundry/garden/blob/66dfda27625680cbe8c9d864392426f452aa0cf6/container.go#L156). As far as we know, this is where in concourse the values should be passed (there is even a blank line for it that is begging for this feature :wink:): 

https://github.com/concourse/atc/blob/fbcb0a46d5ee6b5a5cb2f9138afba680a85dfe1a/exec/task_step.go#L206

We think it could make sense to just make this a field of the `image_resource` kinda like this:

```
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.1'
  resource_limits: '{... 'core' : '-1' ... }'
```

Such that the value passed to `resource_limits` is just the json struct that should be threaded through to Garden. This is a very low level feature and it probably doesn't need to be cleaner than json sitting in a yaml file (oh the humanity). We would even be happy if this is a hidden feature for advanced use. 

In absence of this feature there are other options that we want to call out for reference:

### Options for others fellow Ops folks in the same boat

1) This line at the top of any task script that runs a process that will need a core dump in a concourse container. 

```
# Set to unlimited
ulimit -c unlimited
# Verify core file size
ulimit -c
# Verify all limits
ulimit -a
 ```
Note that this assumes the base OS doesn't have some hard limits in place, which currently the bosh stemcells do not but that could always change. This is the standard Linux OS sysadmin limits caveat.

2) Set limits for the container in the necessary places of `/etc/security/limits.conf` and usually `/etc/security/limits.d/[something above 20-nproc from PAM]` as well. Then in a task script switch user to any user. It doesn't matter what user, you just need to create a login shell with `su foo`.

For reference a test that shows the difference in the behavior (run this from a hijacked container or in a task script)

If you have made the suggested changes from above to an image, the below *should* show those changes taking effect.

```
echo "ulimit for core file size as seen by concourse task: $(ulimit -c)"
echo "ulimit for core file size if we force a login: $(sudo -u root bash -c "ulimit -c")"
```

### ~~Bad~~ Fun things can be done:

1) Use `prlimit` (userland tool that wraps `getrlimit()`/`setrlimit()` which is done with the kernel function `prlimit()` ) to modify running processes (garden and the containers that inherits its limits) - Note: this can possibly require an upgrade of the bosh stemcells used, because some stemcells (depending on the Ubuntu version) don't come with `linux-utils >2.21` that provides `prlimit`. [Refer to this](https://packages.ubuntu.com/search?keywords=util-linux)

2) Use gdb like [this](https://superuser.com/questions/404239/setting-ulimit-on-a-running-process) to modify the parent process of all containers on the workers. This is untested because our GDB foo is weak.

3) Patch the [kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/asm-generic/resource.h?id=0ac1ee0bfec2a4ad118f907ce586d0dfd8db7641#n78). Very untested, but the coolest option, right???

**Comment by pivotal-topher-bullock** [comment]
@kmacoskey 👍 

I could see this being part of the task config, where there is an additional map for `garden_resource_limits` ( or some other key that `rootfs_uri` could be shoehorned under to keep them in "you sure you know what you're doing with these" group of settings.)

Might need to investigate what the side-effects passing those values to the Garden client with various backends would be.. probably just passed through by the Garden client and up to the backend to decide ( hence my suggestion to lump these and `rootfs_uri` together somehow )

```
---
platform: linux

garden_resource_limits:
  cpu: 3600 
  fsize: 1024
  #etc

image_resource:
  type: docker-image
  source:
...
```

**Comment by andrewedstrom** [comment]
Noting that this issue and #1284 seem related, as both address wanting to be able to increase/decrease resource limits. This story is about wanting to tweak resource limits for a task container, while the other is about wanting to impose limits for an entire team.

**Comment by andrewedstrom** [comment]
Closing this issue because it is encapsulated by #787, but I will add a note in that issue looping back to the discussion here.

**Comment by kmacoskey** [comment]
Bumping (because the topic came up today).

@topherbullock 

This issue was never actually solved with https://github.com/concourse/concourse/issues/787

We still have a desire to pass more kernel params through to garden. Everything laid out in https://github.com/concourse/concourse/issues/954#issuecomment-306848524 may still be valid.

**Comment by kmacoskey** [comment]
Bumping (because the topic came up today).

Can this be re-opened? It has not been solved yet.

**Comment by topherbullock** [comment]
@kmacoskey this should work in a task config:
```
container_limits:
  cpu: 256
  memory: 200mb
```

**Comment by vito** [comment]
@kmacoskey Please re-open a new issue for the specific limits you're requesting, rather than bumping this one.

**Comment by kmacoskey** [comment]
@topherbullock @vito I'll open a new issue.

cpu, and memory limits are great but that implementation didn't address these old issues. This pain point does still come up often for our teams using concourse.

A little bit of context is that the original issue was based on the file handle limits and I expanded it to ulimits in a more generic sense of: you can pass any of these kernel limits through to garden. That context is fairly old, but it looks to still be possible looking at https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go

**Comment by kmacoskey** [comment]
New issue opened up here: https://github.com/concourse/concourse/issues/3616
