### ISSUE TITLE
Hide meaningless output resources from the pipeline UI

### ISSUE THREAD

**Issue by ggeorgiev** [concourse/concourse#957]
# Feature Request

## What challenge are you facing?

Not every output resource is meaningful for the pipeline. For example, the slack notification that is based on put task in the job. I would like to be able to hide such resources from the pipeline UI.

## A Modest Proposal

Define special category or simply add an option on the put command that allows for resources to be hidden from the UI.

**Comment by cwinkler** [comment]
+1, my slack notifications are cluttering the pipeline view

**Comment by olhtbr** [comment]
+1

**Comment by clarafu** [comment]
Your concern definitely sounds reasonable! @vito and I took a look at the root of this issue and we created a separate issue (linked below) that involves abstracting away resources that augment the pipeline (slack notification resource) instead of influencing the pipeline. The reason why we wouldn't want to add an option for allowing resources to be hidden is explained by the [knobs anti-pattern](https://github.com/concourse/concourse/wiki/Anti-Patterns#knobs). It would be helpful to have your opinions on the direction of this feature!

https://github.com/concourse/concourse/issues/1052
