### ISSUE TITLE
Discussion: Sharing pipelines between teams

### ISSUE THREAD

**Issue by ryanmattcollins** [concourse/concourse#970]
# Feature Request

## What challenge are you facing?

We are part of a licensing team that scans other groups' repositories. The licensing team currently owns the scanning pipelines for all other groups. We're trying to figure out how to share these pipelines with their respective groups, or get the groups themselves to own the pipelines. But how will we help them troubleshoot these pipelines? We cannot share those pipelines using the 'teams' feature since the pipeline configurations have credentials (which can be grabbed using `fly get-pipeline`).

## A Modest Proposal

There are a few features that would make what we are trying to do possible:

- Hidden credentials in `fly get-pipeline`
- Disable`fly get-pipeline` for a specific pipeline
- Separate permissions for setting pipelines and seeing the logs for that pipeline

**Comment by vito** [comment]
Could you expand a bit on what you mean by 'troubleshooting'? Does this mean hijacking (i.e. write access in some form), or just being able to see the output?

If so, is it required that the output is *only* visible to individual teams, or would it be OK if it were public? (i.e. `expose-pipeline` and setting `public: true` on the jobs).

**Comment by chendrix** [comment]
of note to concourse/concourse#1209

**Comment by pms1969** [comment]
I was just thinking of a similar requirement.  I could really do with being able to share the same pipeline across 2 or more teams, with the output being available to authorized teams, but not public.

We've got a couple of teams at present, 1 front end, 1 api, and I'd like to be able to provide a "product" pipeline, that had all the output from both teams, and have them both see how the pipeline is hanging together.  They also need their own pipelines in order to identify problems with PR's and any plain messing around they want to do, but I'm not sure we want to make that available/visible across teams.  This also allows us to bring in external contractors and have them contribute without the need to poke around inside the workings of the other side of the fence.

The pipeline would need to be owned by 1 team, thus restricting update access, and it wouldn't even need to be capable of hijacking/interception to anyone who didn't have the requisite ownership

Cheers,
Paul

**Comment by ryanmattcollins** [comment]
So today I was asked to give another team access to one of our pipelines so they could see how it was implemented and monitor it's progress since it is a cross-team project. Temporarily, I added their GitHub team to our concourse team.

But that felt unsatisfactory because, although we only have one pipeline in our team, I just wanted to share the pipeline, not the whole team. So I decided to see if there was anything new in Concourse that enabled this...

So here I am a year later giving kudos to my own post. 👍 

Glad to see progress being made on it!
