### ISSUE TITLE
 unsupported protocol scheme "" using --input

### ISSUE THREAD

**Issue by dillera** [concourse/concourse#971]
Hi there!

Please pick the appropriate section (Feature Request or Bug Report) and delete the rest of this. Note that "missing support for X" is a feature request, not a bug!

# Bug Report

##  unsupported protocol scheme ""

Trying to go thru the tutorial, but this happens trying to use any --input

```
$ fly --target tutorial execute --config inputs_required.yml  --input some-important-input=.
executing build 13
upload request failed: Put /api/v1/pipes/78d0614a-e530-4c44-46e3-9c8f51945e71: unsupported protocol scheme ""
curl: (3) <url> malformed
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
```

* Docker version/latest as of Monday - on Ubuntu 16.04 w/ latest Docker (1.12.6)
* Fly version v2.7.0 (on OSX and Linux)

I thought it may be  some issue with the version of Go, but the fly binary 2.7.0 should work on your latest docker images?

If not what versions should I be using to get --input working.

**Comment by dillera** [comment]
My .flyrc has proper APi: values for my target.

**Comment by vito** [comment]
You need to configure the `web` node's external URL. There should be validations for this but it looks like it didn't work for some reason.

**Comment by dillera** [comment]
Setting the EXTERNAL_URL and still have this issue.

```

$ env |grep CON
CONCOURSE_EXTERNAL_URL=http://192.168.100.100:8080

$ fly --target main execute --config inputs_required.yml  --input some-important-input=.
executing build 15
upload request failed: Put /api/v1/pipes/d656895c-0bcf-499a-5077-c4cd80dd6b0f: unsupported protocol scheme ""
curl: (3) <url> malformed
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
exit status 2
failed
```

**Comment by dillera** [comment]
Solved:

Ubuntu wants root to run docker-compose, and so using sudo means that the root env didn't have the CONCOURSE_EXTERNAL_URL set as per the Documentation.

So either hardcode in the CONCOURSE_EXTERNAL_URL within the docker-compose.yml or ensure that the root env has that env seeded before starting docker.

Then --inputs work as expected.


Suggestion:  Update docs section "Docker Repository" to remind people to seed root's env with the 
export CONCOURSE_EXTERNAL_URL=http://192.168.99.100:8080
command as well as the local non-root env.

**Comment by EugenMayer** [comment]
Especially when using concourse-ci using the docker-compose setup, things can get a bit more complicated with docker for mac - obviously this is a test setup but still, maybe this helps.

You neither can use http://localhost:8080 as CONCOURSE_EXTERNAL_URL nor use any external ip as in docker toolbox ways, since d4m runs on the localhost network stack.

You need to define a alias on the localhost interface on you mac, e.g. 172.31.31.254 in my case. 

    sudo ifconfig lo0 alias 172.31.31.254 255.255.255.0

Then you use this for your concourse-ci external url

    CONCOURSE_EXTERNAL_URL=http://172.31.31.254:8080

This alias concept does work for several issues, e.g. for xdebug (remote_ip) and a lot more, You want to do this in general under d4m using e.g. boxen on every dev box.
